### ISSUE TITLE
RT 5.7 crashes upon attempt to open Fuji GFX50R file shot in 35mm mode

### ISSUE THREAD

**Issue by CharlesRT2** [Beep6581/RawTherapee#5571] opened 2019-12-19 18:33 UTC
The Fuji GFX50R "medium format" camera has a 35mm mode for use when the user mounts an adapted "full frame" lens. RT then records data only from the central portion of the sensor, which produces .raf files about half the usual size.

When I open RT and attempt to open such files, RT immediately closes without message. A sample .raf file is available for a week at
https://filebin.net/njjktod0rkg219c7/DGSF1332.RAF?t=pez33ilr

Version: 5.7
Branch: releases
Commit: f335efe6a
Commit date: 2019-09-10
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.1
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

Windows 10 at update 1903, 16 GB RAM, i5-3450 CPU, AMD Radeon HD7700 GPU.

**Comment by heckflosse** [comment] 2019-12-19 18:46
Bug confirmed.

**Comment by heckflosse** [comment] 2019-12-19 19:06
@CharlesRT2 Can you provide another file of this kind in the filebin link? Two are better than one to check for the reason of the crash.

**Comment by CharlesRT2** [comment] 2019-12-19 19:26
> > @CharlesRT2 Can you provide another file of this kind in the filebin link? Two are better than one to check for the reason of the crash.

Yes, I have put a second example in https://filebin.net/njjktod0rkg219c7 .

**Comment by Floessie** [comment] 2019-12-20 08:12
@heckflosse Regardless of what you'll find out, we should prevent RT from crashing:

```patch
diff --git a/rtengine/dcraw.cc b/rtengine/dcraw.cc
index d5348286c..812f122b3 100644
--- a/rtengine/dcraw.cc
+++ b/rtengine/dcraw.cc
@@ -4433,6 +4433,10 @@ void CLASS foveon_interpolate()
 
 void CLASS crop_masked_pixels()
 {
+  if (data_error) {
+    return;
+  }
+
   int row, col;
   unsigned r, c, m, mblack[8], zero, val;
 
```

**Comment by heckflosse** [comment] 2019-12-20 11:17
@Floessie :+1:  for your patch. Please commit.
Support for these files will take a while. I think we should open a new issue for that and close this one when your fix is committed.

**Closed as completed** 2019-12-20 12:37 UTC
Labels: type: bug

**Comment by Floessie** [comment] 2019-12-20 12:41
@heckflosse Ingo, you can open a new issue now.

**Comment by heckflosse** [comment] 2019-12-20 12:47
@Floessie Done
