### ISSUE TITLE
LA: Changing Spot method between Normal and Excluding resets shape outlines

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#6082] opened 2021-01-31 09:28 UTC
This is with current master 6b1e5d.

To reproduce:
Enable Local Adjustments, Add a spot, change the shape points (e.g. make the area larger), then change from "normal" to "excluding" - the shape gets reset.
Unfortunately the changes aren't recorded in the history so one has to manually adjust the shape again.

**Comment by Desmis** [comment] 2021-01-31 10:19
@ff2000 
Hello

Thank you fo testing :)

it is the "normal" behavior.... Sorry, very difficult to change

Jacques

**Comment by ff2000** [comment] 2021-01-31 10:22
But AFAIR this hasn't been the behaviour until recently, probably since addition of "full image" method. (I'll checkk ASAP)
Update: Yes, went back to commit d36545 and changing the method does not alter the shape outlines.

**Comment by Desmis** [comment] 2021-01-31 10:40
It s due to the 3 choices "normal" "excluding" , and "full image"...This last mode "auto" for "full image" leeds to this behavior...

I don't know how to to do otherwise :)

jacques

**Comment by ff2000** [comment] 2021-02-02 06:02
If it's hard to keep the outline at least register the change properly so that going back in history restores the previously (carefully crafted ;)) shape.

Where in the code do you handle the mode change? I could have a look if I have an idea (likely not... but at least I want to try to help :))

**Comment by Desmis** [comment] 2021-02-02 09:02
@ff2000 
The code is only GUI....And I am not at all a specialist
The main code is in "controlspotpanel.cc", (spotMethod_) but also to save / restore with pp3 , locallab.cc, procparams.cc, paramedited.cc and of course for "events" in procevents.h and refreshmap.cc

The problem is for me the same as for others variables when you change "basic" / "standard" / "advanced"...reset are "default"

The system cannot know what you want to do, and (I think) cannot keep en memory more than the last change.
For example, if no reset to 'default',  if you choose "Full image"...and after "excluding"....Excluding spot will have a very very big size....3000*3000 totaly unusable...

But, if you have a solution, I take

jacques

**Comment by Pandagrapher** [comment] 2021-02-02 16:22
@ff2000 @Desmis 
The problem is due to a bug in `ControlSpotPanel::spotMethodChanged()` method. I will provide a patch this WE.

Pierre

**Comment by Pandagrapher** [comment] 2021-02-04 16:06
Fixed with pull request #6093

**Closed as completed by Pandagrapher** 2021-02-04 16:06 UTC
