### ISSUE TITLE
SIGSEGV in rtengine::DFManager::addFileInfo on Alpine Linux

### ISSUE THREAD

**Issue by rnalrd** [Beep6581/RawTherapee#4412] opened 2018-02-27 08:31 UTC
While opening a NEF file, when is at 90% of loading, it crashes.

The NEF file can be found here: http://bit.ly/2EYhXZc

[log.txt](https://github.com/Beep6581/RawTherapee/files/1761786/log.txt)

Version: 5.3-r0 (v3.7.0-2252-gd7e7c692ba) from Alpine Linux repository
OS: Alpine Linux 3.7
RAM: 16GB
CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

**Comment by Floessie** [comment] 2018-02-27 09:07
What's the full path of the file on your system?

What's the full path of your dark-frames directory?

What's your system locale?

Could you try to [compile](http://rawpedia.rawtherapee.com/Linux) the latest `dev` branch and reproduce the problem with it?

NEF loads fine here.

Best,
Flössie

**Comment by rnalrd** [comment] 2018-02-27 10:10
> What's the full path of the file on your system?

/home/larena/Downloads/NEVE

_Downloads_ is a simlink. Loading NEF from /home/larena does not help.

> What's the full path of your dark-frames directory?

I'm not sure about this: I'm new to RawTherapee. I've just opened the program and attempted to load the file.

> What's your system locale?

"C.UTF-8". There are fundamental differences between glibc and musl (which Alpine uses). I'm not really into it but further info on differences about locale can be found [here](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Character-sets-and-locale)

> Could you try to compile the latest dev branch and reproduce the problem with it?

I'll do.

Thanks!

**Comment by Beep6581** [comment] 2018-02-27 10:37
@rnalrd could you upload the options file please? It will tell us the full path to your dark frames folder. You will find it most likely in `~/.config/RawTherapee-dev/options`
More info here: http://rawpedia.rawtherapee.com/File_Paths#Config

**Comment by rnalrd** [comment] 2018-02-27 10:59
Added suffix ".txt" otherwise could not upload it

[options.txt](https://github.com/Beep6581/RawTherapee/files/1762303/options.txt)

**Comment by rnalrd** [comment] 2018-02-27 11:30
Built from latest snapshot, getting same crash:

[log.txt](https://github.com/Beep6581/RawTherapee/files/1762386/log.txt)

**Comment by Beep6581** [comment] 2018-02-27 11:43
@rnalrd can you post the contents of AboutThisBuild.txt?

**Comment by heckflosse** [comment] 2018-02-27 12:24
@rnalrd Please delete your options file and try again. There is some stuff in your options file which looks like it's from an old installation. For example:

```
Version=v3.7.0-2252-gd7e7c692ba
```

and 
```
EDdetec=3
EDdetecStr=1.3
EDLow=15
EDLipinfl=0.80000000000000004
EDLipampl=1.1000000000000001
```

**Comment by rnalrd** [comment] 2018-02-27 12:40
> @rnalrd can you post the contents of AboutThisBuild.txt?

Version: v3.7.0-2252-gd7e7c692ba
Branch: master
Commit: d7e7c692ba
Commit date: 2018-02-26
Compiler: gcc 6.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Debug
Build flags: -Os -fomit-frame-pointer -g -std=c++11 -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g -ftree-vectorize
Link flags: -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

**Comment by rnalrd** [comment] 2018-02-27 12:52
> @rnalrd Please delete your options file and try again. There is some stuff in your options file which looks like it's from an old installation

That did trick. It now opens with the latest snapshot. With v5.3, after removing the options file it still crashes with same error.

So it must be fixed by a commit after 5.3. I see that 5.4 is close to be released, so I think I'll just update the package to 5.4-rc2.

Thanks for the support!

**Comment by Beep6581** [comment] 2018-02-27 12:54
There is no version `v3.7.0`, there is no commit `d7e7c692ba`, and our `master` branch has been dead for a long time. It looks like your distribution has been meddling with the code, and you should report that on your distribution's bug tracker so that they don't do the same with 5.4: https://bugs.alpinelinux.org/projects/alpine/issues

**Comment by Floessie** [comment] 2018-02-27 13:12
:disappointed_relieved: My Alpine VM is just compiling RT, and now you solved it by a simple file removal...

Anyway, now I got into touch with Alpine for the first time. It was relatively hassle-free, but needed more manual intervention than I'm used to. Any tip on `apk add` auto-completion, @rnalrd?

**Comment by rnalrd** [comment] 2018-02-27 13:14
@Beep6581 AL does nothing to source:
https://git.alpinelinux.org/cgit/aports/tree/community/rawtherapee/APKBUILD

But indeed during build process it detects:

<pre>
-- Build files have been written to: /home/larena/aports/community/rawtherapee/src/RawTherapee-5.4-rc2/build
Scanning dependencies of target UpdateInfo
[  0%] Creating AboutThisBuild.txt and other version-dependent files
-- git command found: /usr/bin/git
-- Git checkout information:
-- 	Commit description:	v3.7.0-2252-gd7e7c692ba
-- 	Branch:			master
-- 	Commit:			d7e7c692ba
-- 	Commit date:		2018-02-26
-- 	Commits since tag:	2252
-- 	Commits since branch:	2252
-- 	Version (unreliable):	v3.7.0.2252
</pre>

I'm checking why...

**Comment by Beep6581** [comment] 2018-02-27 13:24
@rnalrd  here's the problem:
https://git.alpinelinux.org/cgit/aports/tree/community/rawtherapee/APKBUILD#n17
I updated our release notes:
https://github.com/Beep6581/RawTherapee/blob/dev/RELEASE_NOTES.txt#L34

**Comment by Floessie** [comment] 2018-02-27 13:28
I can confirm, that `AboutThisBuild.txt` is sane with the cloned `dev`. RT release build segfaults on startup, but runs (albeit with many CSS errors) in GDB. Strange...

**Comment by rnalrd** [comment] 2018-02-27 13:28
@Floessie AL isn't really desktop-oriented :smile: 
You do `apk add PACKAGE` and search a package with `apk search STRING`
Is this what you were looking for? There's no auto-completion for `apk add` command...

**Comment by Beep6581** [comment] 2018-02-27 13:31
@Floessie I couldn't find any info on Alpine's packages from my usual one-stop source: https://distrowatch.com/table.php?distribution=alpine
What is the latest version of GCC and GTK+ Alpine provides?

I emailed GitHub to find out whether we can disable the automated tarball generation.

**Comment by Beep6581** [comment] 2018-02-27 13:33
Ah, found it:
https://pkgs.alpinelinux.org/packages?name=gtk%2B*&branch=edge&arch=x86_64

**Comment by Floessie** [comment] 2018-02-27 13:35
@rnalrd 
> You do apk add PACKAGE and search a package with apk search STRING
Is this what you were looking for? There's no auto-completion for apk add command...

That's how I intuitively did it. But it was... tedious.

BTW: Whenever I start RT **the first** time after reboot, it segfaults, but starts fine after that.

**Comment by rnalrd** [comment] 2018-02-27 13:46
ok, I've built 5.4-rc2 and now the About page shows the right version.

@Floessie got the crash the first time too. May be it's related to PaX?

<pre>
Starting program: /usr/bin/rawtherapee 
warning: Cannot call inferior functions, Linux kernel PaX protection forbids return to non-executable pages!
</pre>

If it's related to PaX this isn't a big issue, since grsecurity no longer available, AL is switching to "vanilla" kernel.

I'm going to bump the official package to 5.4-rc2 correcting the source.

Thanks!

**Comment by heckflosse** [comment] 2018-04-14 22:18
Can we close this issue?

**Comment by rnalrd** [comment] 2018-04-15 00:19
No objection for me, thanks

Il sab 14 apr 2018, 18:18 Ingo Weyrich <notifications@github.com> ha
scritto:

**Closed as completed** 2018-04-15 11:28 UTC
Labels: type: bug
