### ISSUE TITLE
Context menu spacing issue with TooWa* themes

### ISSUE THREAD

**Issue by casta** [Beep6581/RawTherapee#4968] opened 2018-11-10 18:02 UTC
Currently using current master ( b488e20 ), but this occurs since some time.
Menu and sub-menu have incorrect spacing between them when using TooWa* themes. This does not occur with default RT theme.

See the screenshot, this is self explanatory.
![toowagrey-bug](https://user-images.githubusercontent.com/835444/48304539-2efcd780-e51b-11e8-8533-0e4954ceb572.png)

**Comment by TooWaBoo** [comment] 2018-11-10 18:27
I guess this issue is GTK or system related. I can not control the position of menus in the theme. As far as I can see you are using Linux and your dpi setting is higher than 96dpi. The TooWa* theme increases the gui depending on font size and dpi.
Can you provide more information about your system, GTK version, RT version (Preferences->About->Version) and RT font size, please.

Did you do the screenshot after a restart of RT? When you change a theme, font or font size you must restart RT.

**Comment by casta** [comment] 2018-11-10 18:37
DPI is 96 indeed, and font size is a classic 10 (font in the screenshot is “Ubuntu”):
```
$ xdpyinfo | grep dot
  resolution:    96x96 dots per inch
```


GTK is 3.24.1, the system theme is Zukitre, but this also occurs if I set the system theme to the default Adwaita. This did not occur some weeks ago, and is not an issue with RT default theme, so I think it has todo with your theme ;) (for me average surround is a must have, other themes are too dark !)
```
Version: nightly-932-gb488e207
Branch: dev
Commit: b488e207
Commit date: 2018-11-10
Compiler: x86_64-pc-linux-gnu-gcc 8.2.0
Processor: Intel(R)\ Core(TM)\ i5-4690\ CPU\ @\ 3.50GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Gentoo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11  -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -ftree-vectorize
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common  -flto
OpenMP support: yes
MMAP support: ON
```

I’m quite short in time to take the time to bisect, but if it’s really needed, I may try.

**Comment by TooWaBoo** [comment] 2018-11-10 19:04
I can't reproduce this on Windows. Could be a problem of GTK+ 3.24. On Windows we do have a some issues with the tooltips which appear under the mouse pointer and other stuff. The different between the RT- and the TWB- theme is that the RT theme is designd in `Pixel` and the TWB them in `em`
Could it be that this problem occurs after update to GTK+ 3.24?

Can you try with font size 9, please?

Windows 10, GTK+ 3.24
![unbenannt](https://user-images.githubusercontent.com/13800920/48304981-5eafdd80-e523-11e8-80ef-3f17f746cab5.png)

**Comment by Beep6581** [comment] 2018-11-10 19:35
Sabayon, KDE, gtk+-3.22.30
`resolution:    96x96 dots per inch`
![screenshot_20181110_203321](https://user-images.githubusercontent.com/5844619/48305284-12b36780-e528-11e8-8444-92ef4b0b03ef.png)

**Comment by casta** [comment] 2018-11-10 19:42
I tried to downgrade to gtk+-3.22.30, same issue for me.

I don’t know what could be different on my computer…

**Comment by Thanatomanic** [comment] 2018-11-29 19:37
I just managed to have this issue too:
![image](https://user-images.githubusercontent.com/6567747/49247017-899c9b80-f416-11e8-8b36-1cbbcc462c77.png)

I think it happened after I switched themes, but I'll check.

**Comment by TooWaBoo** [comment] 2018-11-29 19:58
You always need to restart RT when you switch the themes.

**Comment by Thanatomanic** [comment] 2018-11-29 20:03
Getting slightly off-topic here, but that's not mentioned in the Preferences and there's only a very small mention in [RawPedia](http://rawpedia.rawtherapee.com/Preferences#Theme). If switching theme's is such an iffy thing, why not make a restart compulsory?

**Comment by Beep6581** [comment] 2018-11-29 20:05
@Thanatomanic http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
;)

**Comment by Thanatomanic** [comment] 2018-11-29 20:15
@Beep6581 I now have a way to properly reproduce:

1. Enable RawTherapee theme, close RT
2. Start RT
3. Right click an image in the File Browser and navigate through several levels of menu's (e.g. Processing profile operations).
4. Switch to the TooWaBlue - Dark theme
5. Repeat step 3, but now there is extra spacing.

AboutThisBuild.txt
```
Version: 5.4-1277-g15c18325c
Branch: dev
Commit: 15c18325c
Commit date: 2018-11-28
Compiler: gcc 8.2.0
Processor: corei7
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -Wno-parentheses -std=c++11 -march=corei7 -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=corei7
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment] 2018-11-29 20:24
@Thanatomanic you didn't restart in your steps, the GUI clearly says "restart required" :laughing:

**Comment by Thanatomanic** [comment] 2018-11-29 20:25
Where exactly?
![image](https://user-images.githubusercontent.com/6567747/49249721-4c87d780-f41d-11e8-81ab-b60a07de4c2b.png)

**Comment by Beep6581** [comment] 2018-11-29 20:28
@Thanatomanic my commit should be mentioned just above there:

![imgur-2018_11_29-21 26 13](https://user-images.githubusercontent.com/5844619/49249801-7c36df80-f41d-11e8-811f-34a7135f0170.png)

**Comment by Thanatomanic** [comment] 2018-11-29 20:29
Sorry, completely missed that! That means we can actually close this issue, right?

**Comment by casta** [comment] 2018-11-29 20:33
No ;)
I have the issue since some time with toowa themes, even after restart. The issue does not occur with default theme. I get this on 3 different computers but with exactly the same libraries versions (same distro)

**Comment by TooWaBoo** [comment] 2018-11-30 04:22
@casta 
I don't know what's wrong. The theme has no control over the positions of menus. They are calculated by Gtk and/or the OS.

**Comment by casta** [comment] 2018-12-04 12:36
After digging into the toowablue css, I achieved to fix the issue by adjusting this box-shadow property.
I still do not know why I’m the only who is affected.

**Comment by TooWaBoo** [comment] 2018-12-04 15:45
@casta 
Hmmm, looks like your system doesn't support client-side-decoration and doesn't handle this well.
The box-shadow adds a shadow to the menus and it shouldn't be shown if the system doesn't support it.

![grafik](https://user-images.githubusercontent.com/13800920/49453206-f59a4d80-f7e2-11e8-8826-7b0a10809a7a.png)

Instead of removing the shadow add `.csd` in front of `.popup`. Tell me if that works, please.

```
.csd.popup > decoration {
    background-image: none;
    border-radius: 0;
    border: none;
    padding: 0;
    margin: 0;
    box-shadow: 0 0.25em 0.75em 0.083333333333333333em rgba(0, 0, 0, 0.50), 0 0 0 0.083333333333333333em @bg-dark-grey;
}
```

**Comment by casta** [comment] 2018-12-04 16:44
Yes indeed, I have CSD disabled (using archlinux patches: https://github.com/TomaszGasior/gtk3-mushrooms/blob/master/csd__disabled-by-default.patch). So that is the difference. But what is the point to use CSD css classes on an application that do not handle CSD? (just a question, no offense)

Anyway, your proposal is working correctly!

**Comment by TooWaBoo** [comment] 2018-12-04 16:50
Ok, I'll fix it.
CSD is handled well on Windwos. :-)
Some Linux system doesn't support native windows, they only support CSD. Thats why the theme contains styles for client-side-decoration.

PS: Can you close your PR, please.

**Comment by Beep6581** [comment] 2018-12-04 17:06
"Some Linux system" > Wayland/Weston.

**Comment by gaaned92** [comment] 2018-12-04 18:26
@TooWaBoo 
`CSD is handled well on Windwos. :-)
`

If you use CSD on Windows, you break the snap feature.  So CSD is by default disabled in MSYS2 from 3.22.24 and @aferrero2707 disabled it for the windows automatic build.
see [Continuous integration of Win64 builds ](https://github.com/Beep6581/RawTherapee/issues/5000) 

[](url)

**Comment by TooWaBoo** [comment] 2018-12-04 19:04
@gaaned92
Misunderstanding :-)
Windows is using the native window but objects can have a decoration e.g. menus or the inspector has a csd window.
![grafik](https://user-images.githubusercontent.com/13800920/49466249-d9f17000-f7ff-11e8-82ac-8b7abfad91ff.png)

**Closed as completed** 2019-05-08 08:21 UTC
