### ISSUE TITLE
WinXP 32-bit crash on startup

### ISSUE THREAD

**Issue by Merlineintheworld** [Beep6581/RawTherapee#3015] opened 2015-12-08 16:33 UTC
I work with Vista, in 32bits.
I installed the last version of RT since a few weeks (RT 4.2.447 for Windows XP or newer 32-bit).
It was always crashing during the save but working after re-opening.
But since yesterday, I can't open anymore RT. 
I try to reinstall RT, I delate the file created with the pictures. But I still can't open.

I test with the older version (RT 4.1 for Windows XP or newer 32-bit ), and it was working. But I prefere the lastest for the with the Retinex).

I have as error this message:
"Microsoft Visual C++ Runtime Library
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

Thank you for your help!

**Comment by Beep6581** [comment] 2015-12-08 16:58
The crashing while saving was probably caused by running out of RAM, that's the most likely thing to happen on 32-bit XP. To find out what's causing the new crash on startup, you need to provide more info and try some things for yourself. See:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
http://rawpedia.rawtherapee.com/How_to_fix_crashes_on_startup
I asked sguyander if he could provide you with a debug build, keep an eye on http://rawtherapee.com/forum/viewtopic.php?f=1&t=1910&start=5000

**Comment by sguyader** [comment] 2015-12-08 17:38
Hmmm... I don't know why, but I can't semm to make a debug build, it fails in improcfun.cc with these errors:
```
[ 12%] Building CXX object rtengine/CMakeFiles/rtengine.dir/improcfun.cc.obj
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc: In member function 'void rtengine::ImProcFunctions::chromiLuminanceCurve(rtengine::EditBuffer*, int, rtengine::LabImage*, rtengine::LabImage*, LUT<float>&, LUT<float>&, LUT<float>&, LUT<float>&, LUT<float>&, LUT<float>&, bool, bool, bool, bool, bool, bool, LUT<unsigned int>&, LUT<unsigned int>&, LUT<unsigned int>&, LUT<unsigned int>&)':
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'gamutLch'
is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'protectRedH' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'protectRed' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'LCredsk' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'avoidColorShift' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'rstprotection' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'bwToning' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'chromaticity' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'clut' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'ccut' is predetermined 'shared' for 'firstprivate'
C:\Rawtherapee-sources\rtrepo\rtengine\improcfun.cc:5827:225: error: 'highlight' is predetermined 'shared' for 'firstprivate'
mingw32-make.exe[2]: *** [rtengine/CMakeFiles/rtengine.dir/improcfun.cc.obj] Error 1
mingw32-make.exe[1]: *** [rtengine/CMakeFiles/rtengine.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
```
It works when making a 32-bit Release build (and the Release build doesn't crash on my system), and works also when making a 64-bit Debug or Release build.

**Comment by heckflosse** [comment] 2015-12-08 17:43
@sguyader : I'll take a look at the improcfun.cc stuff

**Comment by sguyader** [comment] 2015-12-08 18:00
@Merlineintheworld have you tried my latest build? (get it here: https://drive.google.com/folderview?id=0B_AvPFlUj8t5SUdodURGOFdOems&usp=drive_web#list)

**Comment by heckflosse** [comment] 2015-12-08 18:02
I pushed a fix. But there maybe additional bugs of this kind. I can't test because gcc 4.9.2 doesn't spit out this errors.

Ingo

**Comment by Merlineintheworld** [comment] 2015-12-08 18:07
@sguyader, I just try your latest build, but have the same problem. 
I had as indicated in this page (http://50.87.144.65/~rt/w/index.php?title=How_to_write_useful_bug_reports) install TDM-GCC, but I don't arrived to run the GDB package (that I have dowlowd).
Which informations can be useful for you in more? I can try to find this.

**Comment by sguyader** [comment] 2015-12-08 18:36
@heckflosse I found again the same kind of bug in rtengine\ipvibrance.cc at line 191, I fixed it myself as you did for the first case:
```
rtengine/ipvibrance.cc
@@ -191 +191 @@
-    #pragma omp parallel default(shared) firstprivate(lab, width, height, chromaPastel, chromaSatur, highlight, limitpastelsatur, transitionweighting, protectskins, avoidcolorshift, MunsDebugInfo) reduction(+: negat, moreRGB, negsat, moresat) if (multiThread)
+    #pragma omp parallel default(shared) firstprivate(lab, MunsDebugInfo) reduction(+: negat, moreRGB, negsat, moresat) if (multiThread)
```

@Merlineintheworld I made a new Debug build that you can dowload here: https://drive.google.com/open?id=0B_AvPFlUj8t5a1h4X0tFdS1mbGM
Install it, then:
1/ open a console into the install folder containg the executable rawtherapee.exe
2/ type ```gdb rawtherapee```
3/ when you see the (gdb) pormpt, type ```run```
This will start RT in debug mode, copy and paste here any message that should appear in the console related with a crash.

**Comment by Merlineintheworld** [comment] 2015-12-08 19:00
I am not shure what is your point 1)
When I try to open your new Debug, I have this text in the console which opened in the same time:

<rawtherapee.exe:1228>: Glib-CRITICAL **/ g_utf16_to_utf8: assertion 'str != NULL' failed
terminate called after throwing an instance of 'Glib::KeyFileError'

**Comment by sguyader** [comment] 2015-12-08 19:03
In 1/, I mean run cmd.exe to open a command prompt.

**Comment by Merlineintheworld** [comment] 2015-12-08 19:49
ok, 
I have this text in the console: 

C:\Program Files\RawTherapee-4.2.511>gdb32 rawtherapee
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rawtherapee...done.
(gdb) run
Starting program: C:\Program Files\RawTherapee-4.2.511\rawtherapee.exe
[New Thread 3064.0x5b0]
[New Thread 3064.0xd64]
[New Thread 3064.0x608]
[New Thread 3064.0x5ac]

(rawtherapee.exe:3064): GLib-CRITICAL **: g_utf16_to_utf8: assertion `str != NUL
L' failed
[New Thread 3064.0x9b4]
[New Thread 3064.0xecc]
[Thread 3064.0x5ac exited with code 0]
[New Thread 3064.0xca0]
[New Thread 3064.0x9d8]
[Thread 3064.0xecc exited with code 0]
[Thread 3064.0x9d8 exited with code 0]
[New Thread 3064.0x2cc]
[New Thread 3064.0xb4c]
terminate called after throwing an instance of 'Glib::KeyFileError'

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[Thread 3064.0xd64 exited with code 3]
[Thread 3064.0x608 exited with code 3]
[Thread 3064.0xb4c exited with code 3]
[Thread 3064.0xca0 exited with code 3]
[Thread 3064.0x9b4 exited with code 3]
[Thread 3064.0x2cc exited with code 3]
[Inferior 1 (process 3064) exited with code 03]
(gdb)

**Comment by Beep6581** [comment] 2015-12-08 21:06
Merlineintheworld see my first link on what to write once you run GDB.

**Comment by heckflosse** [comment] 2015-12-09 00:38
I would try this with or without gdb:
md c:\beep6581
rawtherapee c:\beep6581

If that works, you most likely have a corrupt file in the last folder you opened in rt

If that doesn't work you can try to delete your options file(s) and start rt again

Ingo

**Comment by Merlineintheworld** [comment] 2015-12-09 08:53
@heckflosse I try your suggestion, and have the code below with gdb
This doesn't work, rawtherapee didno't have the time to open, and crash directly (as last time).
I think RT start to crash when I try to developp three RAW, I have delete these before to restart, but doesn't change anything.

The options file(s) are in RT? Or have I to change this in another place?

Thanks a lot


[code]
C:\Program Files\RawTherapee-4.2.511>md c:\marine

C:\Program Files\RawTherapee-4.2.511>rawtherapee c:\marine

(rawtherapee.exe:3888): GLib-CRITICAL **: g_utf16_to_utf8: assertion `str != NULL' failed
terminate called after throwing an instance of 'Glib::KeyFileError'

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[code]

**Comment by Beep6581** [comment] 2015-12-09 09:00
Merline: run the debug build in GDB again and follow step 3 onwards:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

**Comment by Merlineintheworld** [comment] 2015-12-09 11:19
@Beep6581 I try to follow the step. I think I did the thing well.
I obtain this code:

[code]
Setting up environment for using MinGW with GCC from C:\Program Files\RawTherape
e-4.2.511\.

C:\Program Files\RawTherapee-4.2.511>gdb32 rawtherapee-DEBUG.exe
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This GDB was configured as "mingw32".

Reading symbols from rawtherapee-DEBUG.exe...done.
(gdb) run
Starting program: C:\Program Files\RawTherapee-4.2.511\rawtherapee-DEBUG.exe
[New Thread 2616.0x9f4]
[New Thread 2616.0x5b0]
[New Thread 2616.0xa34]
[New Thread 2616.0xf4c]

(rawtherapee-DEBUG.exe:2616): GLib-CRITICAL **: g_utf16_to_utf8: assertion `str
!= NULL' failed
[New Thread 2616.0xd40]
[New Thread 2616.0xe78]
[Thread 2616.0xf4c exited with code 0]
terminate called after throwing an instance of 'Glib::KeyFileError'

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[Thread 2616.0x5b0 exited with code 3]
[Thread 2616.0xd40 exited with code 3]
[Thread 2616.0xa34 exited with code 3]
[Thread 2616.0xe78 exited with code 3]
[Inferior 1 (process 2616) exited with code 03]
(gdb) bt full
No stack.
(gdb)
[code]

**Comment by heckflosse** [comment] 2015-12-09 11:25
There are two options files. One is in the same folder as rawtherapee.exe, the other one on my system is in C:\Users\{username}\AppData\Local\RawTherapee\options

Rename both to options123 and start rt. If that works, please upload the renamed files to filebin.net and post the link here.

Ingo

**Comment by gaaned92** [comment] 2015-12-09 13:13
When I run Sguyader debug build on WXP, I get a crash at the end of processing a file
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 4116.0xcc0]
__chkstk_ms ()
    at ../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm:173
173     ../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm: No such
file or directory.
        in ../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm

(gdb) bt
#0  __chkstk_ms ()
    at ../../../../src/gcc-4.6.1/libgcc/../gcc/config/i386/cygwin.asm:173
#1  0x00aae8f5 in rtengine::ImProcFunctions::ip_wavelet ()
    at C:\Rawtherapee-sources\rtrepo\rtengine\ipwavelet.cc:1098
#2  0x00aa2aab in rtengine::ImProcFunctions::ip_wavelet (this=0xa0fb3e8,
    lab=0xa7c8c80, dst=0xa7c8c80, kall=0, waparams=..., wavCLVCcurve=...,
    waOpacityCurveRG=..., waOpacityCurveBY=..., waOpacityCurveW=...,
    waOpacityCurveWL=..., wavclCurve=..., wavcontlutili=false, skip=8)
    at C:\Rawtherapee-sources\rtrepo\rtengine\ipwavelet.cc:714
#3  0x00a71e19 in rtengine::ImProcCoordinator::updatePreviewImage (
    this=0xa0fb378, todo=2047, cropCall=0x0)
    at C:\Rawtherapee-sources\rtrepo\rtengine\improccoordinator.cc:680
#4  0x00a75e9f in rtengine::ImProcCoordinator::process (this=0xa0fb378)
    at C:\Rawtherapee-sources\rtrepo\rtengine\improccoordinator.cc:1296
#5  0x00d17660 in sigc::bound_mem_functor0<void, rtengine::ImProcCoordinator>::o
perator() (this=0xa7ce1a4)
    at P:/Transfert/MinGW32/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
#6  0x00d14b0c in sigc::adaptor_functor<sigc::bound_mem_functor0<void, rtengine:
:ImProcCoordinator> >::operator() (this=0xa7ce1a0)
    at P:/Transfert/MinGW32/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:2
56
#7  0x00bf7f5a in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, rten
gine::ImProcCoordinator>, void>::call_it (rep=0xa7ce188)
    at P:/Transfert/MinGW32/include/sigc++-2.0/sigc++/functors/slot.h:103
#8  0x664f312a in libglibmm-2!_ZNK4sigc5slot0IvEclEv ()
   from c:\rawtherapee-4.2.511\libglibmm-2.4-1.dll
#9  0x664ce5c5 in libglibmm-2!_ZN4Glib10SpawnError10throw_funcEP7_GError ()
   from c:\rawtherapee-4.2.511\libglibmm-2.4-1.dll
#10 0x686173d7 in libglib-2!g_static_mutex_get_mutex_impl ()
   from c:\rawtherapee-4.2.511\libglib-2.0-0.dll
#11 0x65c42128 in ?? () from c:\rawtherapee-4.2.511\libgthread-2.0-0.dll
#12 0x77c0a3b0 in msvcrt!_endthreadex () from C:\WINDOWS\system32\msvcrt.dll
#13 0x7c80b729 in KERNEL32!GetModuleFileNameA ()
   from C:\WINDOWS\system32\kernel32.dll
#14 0x00000000 in ?? ()
(gdb)

When I run an homemade debug build, it is ok with same option file and same file
Branch: master
Version: 4.2.512
Changeset: 031c41af60469314ccceef649c0683bf04a5205b
Compiler: gcc 4.6.1
Processor: generic x86
System: Windows
Bit depth: 32 bits
Gtkmm: V2.22.0
Build type: debug
Build flags:  -m32  -mthreads -mstackrealign  -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O1 -g2
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -mtune=generic -O1
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment] 2015-12-09 13:41
Maybe caused by missing -mstackrealign switch?

**Comment by sguyader** [comment] 2015-12-09 14:04
The -mstackrealign switch is used for my Release builds, so this is not the cause of @Merlineintheworld 's initial crash report.
Is it safe to add this switch also for Debug builds?

**Comment by Merlineintheworld** [comment] 2015-12-09 14:04
After changing the name of the option files, it was not working more. But I uninstall RT again and delete all the cache from RT (that I never did before because I did not seen the folder). After reinstall RT (4.2.510) it works again.

RT still crash when I send an picture to process if I work with biger file (from EOS M), but work well with file from 350D.

**Comment by Beep6581** [comment] 2015-12-09 14:23
"After changing the name of the option files, it was not working more."
Please upload this old options file to http://filebin.net/

**Comment by heckflosse** [comment] 2015-12-09 14:29
@sguyader : It should be safe to add this switch to Debug builds too. But the best solution would be to not use this switch anymore, because it slows down rt a bit. The switch was needed some time ago to get rt running correctly on Win32 with optimized code, but meanwhile I made a lot of changes targeting to avoid usage of this switch. So I would prefer If someone could make a Release build without this switch for Win32. If then some new bugs occur, I can try to fix them.

Ingo

**Comment by sguyader** [comment] 2015-12-09 14:57
Ok, I'll do that from now on.

**Comment by heckflosse** [comment] 2015-12-09 15:10
@Merlineintheworld : http://50.87.144.65/~rt/w/index.php?title=The_Floating_Point_Engine

**Comment by Merlineintheworld** [comment] 2015-12-09 15:15
thank you @heckflosse , I try to be careful and respect these "rules". I have less problem with my last camera. So next step will be to change computer and have 64bits... But not now.
Thank you a lot for all your help!

**Comment by Beep6581** [comment] 2018-12-11 09:33
WinXP 32-bit is unsupported - closing.

**Closed by Beep6581** 2018-12-11 09:33 UTC
