### ISSUE TITLE
Broken blue slider inside BW section

### ISSUE THREAD

**Issue by luisfl** [Beep6581/RawTherapee#4600] opened 2018-06-10 14:53 UTC
Inside the Color tab, the Black-and-White section seems to have a problem: While red and green sliders for gamma correction work normally, the blue slider does nothing, regardless of the method.

RawTherapee 5.4 in Fedora 28.

**Comment by heckflosse** [comment] 2018-06-10 15:07
Duplicate of #4188

**Closed as completed by heckflosse** 2018-06-10 15:07 UTC
