### ISSUE TITLE
Themes missing in 4.1.699 64 bits on Windows 10

### ISSUE THREAD

**Issue by TheHibou** [Beep6581/RawTherapee#3200] opened 2016-03-07 08:21 UTC
Hello,

I was running version 4.2.1 64 bits on a Win 10 machine, no issue.

I tried to update to version 4.2.699 64 bits, everything seems OK but I can't change the theme - nothing appears in the scrolldow menu.

Can I fix that ? 

Best Regards,
Herve

**Comment by TooWaBoo** [comment] 2016-03-07 16:55
No, you can't fix it.
The new Gtk3-GUI is still under development.
If you want to try another theme, checkout this:
https://discuss.pixls.us/t/final-custom-theme-toowabooblue-1-07-update-28-feb-2016-gtk3/772

**Comment by Beep6581** [comment] 2016-03-07 17:02
Closing this as duplicate of #2980

**Closed by Beep6581** 2016-03-07 17:02 UTC

**Comment by TheHibou** [comment] 2016-03-07 22:54
Thanks Beep6581.

At least now I know, and will survive :) until the problem is fixed.

Best Regards,

TheHibou

 

De : TooWaBoo [mailto:notifications@github.com] 
Envoyé : lundi 7 mars 2016 17:56
À : Beep6581/RawTherapee <RawTherapee@noreply.github.com>
Cc : TheHibou <herve.chappe@laposte.net>
Objet : Re: [RawTherapee] Themes missing in 4.1.699 64 bits on Windows 10 (#3200)

 

No, you can't fix it.
The new Gtk3-GUI is still under development.
If you want to try another theme, checkout this:
https://discuss.pixls.us/t/final-custom-theme-toowabooblue-1-07-update-28-feb-2016-gtk3/772
