### ISSUE TITLE
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL)

### ISSUE THREAD

**Issue by Kildor** [Beep6581/RawTherapee#4246] opened 2017-12-21 16:03 UTC
I'm downloading Win64 nightlies from Gaaned92 gdrive. And last several builds do not load. Last working for me was RawTherapee_dev_5.3-277-gb99babb8_WinVista_64.zip.
Debug version shows this error:
```
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Program Files\RawTherapee\share\icons\Adwaita\24x24/status\image-missing.png: Error opening file C:\Program Files\RawTherapee\share\icons\Adwaita\24x24\status\image-missing.png: No such file or directory (g-io-error-quark, 1)
```

If I create such file the RT starts to load fine. 

AboutThisBuild.txt from current build which has the error.

Version: 5.3-339-g62585bc4
Branch: dev
Commit: 62585bc4
Commit date: 2017-12-20
Compiler: gcc 7.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment] 2017-12-21 16:42
Ping @gaaned92

Could it be related to the forward-slash?
`/status\`

**Comment by Kildor** [comment] 2017-12-21 17:01
there is not 24x24 folder in "C:\Program Files\RawTherapee\share\icons\Adwaita" at all. Nor RawTherapee_dev_5.3-339-g62585bc4_WinVista_64, nor RawTherapee_dev_5.3-277-gb99babb8_WinVista_64 do not contain this folder.
May be there is some other icon which is missed so RT tries to handle this?

**Comment by gaaned92** [comment] 2017-12-21 20:55
@Kildor 

The 24x24 folder was never included in the windows builds.  So there should be an other problem.
Recently I updated all the share/icons/adwaita data with the last MSYS2 versions. It is perhaps the culprit.

To test here,  I reinstalled RT version dev_5.3-339-g62585bc4 on my W10PC  in C:\Program files\Rawtherapee. 
Normal version runs ok. Furthermore, with debug version and in verbose mode I get no warning in console.
So I cannot reproduce here.

I am thus going to build with old dependencies. It will be available in my google drive in a few minutes.
I will edit this post when ready.

RawTherapee_dev_5.3-339-g62585bc4_WinVista_64.zip uploaded on https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8
please test and report.

**Comment by Kildor** [comment] 2017-12-23 05:58
I'd downloaded RawTherapee_dev_5.3-339-g62585bc4_WinVista_64 with pgp

iQEcBAABCAAGBQJaPCBDAAoJEAArvnMO8uhgYvYH/RWR9yhl7n9/fnQ4UU9EQxvW
Bx3l8mRnEib7ZAc+L3Y2bHBHZKw88wVWbhzWPCI+AWKLPvVBr4kmlUrRtPU+o10h
TCiM0O+3GlBMvcGLIptMB9Kzoyhju/K8z/kifkmNKfFchgUEwKBC+Bt94QYbihKp
6BL+ro+u3WSMfClal/oxzm5zqsEccj2fYLygb4tOowvTf2HDINGBXOC2boUqajd/
ECeDzb2Iy8HQFBsr5sRXCZ1CvVNUW1VoZBq5bClXGGzHRPld9LXc9P38iIbUaTuv
QO1s/A9VONNbgshrKMvuXNFvxkZYAZXH6wp3lRfQAHLHaYEE9ZrnI4kLP+V9J3E=
=kdXY
and had the same problem with 24x24 icon.

**Comment by gaaned92** [comment] 2017-12-23 08:59
@Kildor  thanks for testing

- As the above build was made with exactly same process as 277, I think the build process itself is not the culprit.

To permit developpers to understand what is happening, could you do the following:

- go to your config folder located at" %LOCALAPPDATA%\rawtherapee5-dev". Edit the option file. change "verbose=false" to" verbose =true" (located in beginning of option file). Save.
- in windows console,  run rawtherapee-debug.exe under gdb
- when it crashes, type "bt full"
- copy   all generated text and either directly paste it here or if huge, paste in a file and attach file here.

**Comment by Kildor** [comment] 2017-12-23 15:18
Here it is.

[gdb.log](https://github.com/Beep6581/RawTherapee/files/1584203/gdb.log)

**Comment by gaaned92** [comment] 2017-12-23 15:58
@heckflosse @agriggio @Floessie 
Can you understand what is happening?

The same 339-g62585bc4 build runs ok here. Of course, I took MSY2 out of  %PATH%.

@Kildor  In the meantime, I will add the Adwaita\24x24\status\image-missing.png to the builds.

**Comment by heckflosse** [comment] 2017-12-23 16:14
@gaaned92 I can only guess that a png file is missing and then gtk tries to access the `image-missing.png` to show that a png is missing, but `image-missing.png` is also missing.

**Comment by gaaned92** [comment] 2017-12-23 17:10
@Kildor 
I added image-missing.png to the build RawTherapee_dev_5.3-346-ga2bf6081_WinVista_64.zip
uploaded at
https://drive.google.com/open?id=0B2q9OrgyDEfPS2FpdDAtMVI1RG8

- can you test as above please?
- Can you now  identify what PNG is missing through all warnings given in console?
- Do you have specific HW (display...) that could explain the different behaviour on your PC?

@heckflosse @Floessie Is it possible that due to display definition or some system setting, higher icons definitions could be required? (e.g. 24x24 icons)

**Comment by Kildor** [comment] 2017-12-23 17:35
I've installed the build. It doesn't crash. Also there is nothing about missed images in gdb.

About display -- I don't know. I have 1920x1080 display without any specific preferences (like scaling or DPI).

**Comment by gaaned92** [comment] 2017-12-23 17:46
@Kildor 
Could you send the log file as above, copying all text in the console from the gdb/ run command until display of the rawtherapee window.

**Comment by Beep6581** [comment] 2017-12-23 21:44
![image-missing](https://user-images.githubusercontent.com/5844619/34322846-0db859ea-e833-11e7-908b-94b619599d85.png)

@Kildor do you see this image anywhere in the interface in the new build? If so, where?
And is there anything in the console about missing images/icons?

**Comment by Kildor** [comment] 2017-12-24 03:17
> do you see this image anywhere in the interface in the new build? If so, where?

It will be so easy) No, I've never seen this or my image in RT interface. I've compare installed RawTherapee_dev_5.3-277-gb99babb8_WinVista_64.zip and RawTherapee_dev_5.3-346-ga2bf6081_WinVista_64.zip, both compiled and source. There are no difference about icons.

**Comment by heckflosse** [comment] 2017-12-24 14:56
@agriggio I guess you closed this issue by accident.

**Comment by agriggio** [comment] 2017-12-24 14:58
@heckflosse absolutely! I meant #4252, sorry

**Comment by Thanatomanic** [comment] 2018-10-23 08:04
@Kildor There have been newer builds now, does the problem still persists?

**Closed as completed** 2018-11-23 19:39 UTC
Labels: type: bug
