### ISSUE TITLE
Photos in portrait mode with green border in the vertical side on the right after enabling avoid color shift with chromatic aberration auto-correction selected

### ISSUE THREAD

**Issue by abelrsousa** [Beep6581/RawTherapee#6770] opened 2023-06-13 15:25 UTC
Greetings!

My name is Abel and I'm from Portugal.

First, I would like to thank you for making this awesome software.
The problem that I encountered is in the description below.

I apologise in advance for my poor English.

Best regards!

**Short description**

**Steps to reproduce**
<In photos that I've taken in vertical orientation, I noticed a green border in the vertical side on the right after enabling avoid color shift with chromatic aberration auto-correction selected>

**Expected behavior**

**Additional information**
<I currently run rawtherapee 5.9 in windows 11 pro - version 22H2.

![green border](https://github.com/Beep6581/RawTherapee/assets/136480192/2d0fb81b-a98f-400e-9fe2-337685f01d41)>

**Comment by Lawrence37** [comment] 2023-06-17 22:53
Unable to reproduce the issue. Could you please supply a sample file and associated pp3 that show the issue?

**Comment by abelrsousa** [comment] 2023-06-18 11:25
Yes, I can.
I notice this only occurs with my canon 7D mark II.
I also have a canon 500D which doesn't have this problem.
In DPP, the image appears to be fine.

Thank you for your attention.

Best regards,
Abel

[X][https://res.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]2023-06-13_0153.CR2<https://1drv.ms/i/s!AkfrjhUVGqP2qjgPtUmEAu5NDhxO>
________________________________

**Comment by Lawrence37** [comment] 2023-06-18 18:52
GitHub doesn't accept email attachments. You'll have to use a file sharing service such as filebin.net or if the image is small enough, upload it directly on GitHub as a ZIP.

**Comment by abelrsousa** [comment] 2023-06-18 19:13
Understood.

Here is the link:

Filebin | myez9n7qli2cn7y1<https://filebin.net/myez9n7qli2cn7y1>
Filebin | myez9n7qli2cn7y1<https://filebin.net/myez9n7qli2cn7y1>
Convenient file sharing. Think of it as Pastebin for files. Registration is not required. Large files are supported.
filebin.net
Best regards,

Abel
________________________________

**Comment by Lawrence37** [comment] 2023-06-21 05:04
Thanks. That image has one column of bad pixels which can be fixed by correcting the raw crop. The avoid color shift function could be improved by ignoring the pixels removed by the border defined in Raw tab > Sensor with Bayer Matrix > Demosaicing. I will start with the raw crop because it is a quick fix.

**Closed as completed** 2023-08-06 21:48 UTC
Labels: type: bug
