### ISSUE TITLE
Decoration thingy getting stuck

### ISSUE THREAD

**Issue by BSLprints** [Beep6581/RawTherapee#6398] opened 2022-01-04 02:54 UTC
**Short description**
When using the LAB adjustments, the decoration thingy at the bottom of the panel sometimes gets stuck over or under (z-order wise)  the controls.

**Steps to reproduce**
Open an image using a profile that doesn't have LAB adjustments by default
Turn on a channel adjustment as parametric
Issue sometimes happens, sometimes not, sometimes jumps around.

**Expected behavior**
Decoration should always be at the bottom of the column in vertical direction and not over or under controls in z-order direction

**Additional information**
- Version of RawTherapee: built from source
- Version of your operating system - Windows 10.0.19041
- If you built from source, the contents of the `AboutThisBuild.txt` file in the installation folder
Version: 5.8-3064-g690fab3d0
Branch: dev
Commit: 690fab3d0
Commit date: 2021-12-21
Compiler: cc 10.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-19041 3.2.0-340.x86_64 x86_64
Build date: Tue, 04 Jan 2022 01:14:52 +0000 UTC
Build epoch: 1641258892
Build UUID: 528b3843-4bbc-4a52-841e-31b551867d21

Other useful information:
Video showing this issue: https://youtu.be/8jjnRUVxRIM

**Comment by Lawrence37** [comment] 2022-01-04 04:09
Duplicate of #3525. Other curve editors are affected too, but we don't know what's going on.

**Closed as completed by Lawrence37** 2022-01-04 04:09 UTC
