### ISSUE TITLE
Panning red square in Navigator does not follow mouse

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3773] opened 2017-03-21 17:39 UTC
When I zoom the Editor preview to 100% and drag the red square in the Navigator, the square and preview do not follow the mouse.

The behavior is strange:
* If I click in the top-left corner https://i.imgur.com/wp7RIrI.png and drag the red square down it moves diagonally down-right https://i.imgur.com/6GmMogF.jpg If I now try to move it up, it moves diagonally up-right.
* If I click in the top-left corner and pan right, it moves diagonally right-down. If I click in the top-right corner and pan left, it moves diagonally left-down.
* The main preview always correctly follows the red square.

The square will drift all the way to the right or to the bottom if I move it up-down/left-right a few times.

Maybe related to #3772 ?

**Comment by TooWaBoo** [comment] 2017-03-21 18:47
I'm using the latest version from @agriggio branch: add-more-zoom-levels and can't reproduce this bug.

Gtk: 3.22.9, Win 10 x64

**Comment by heckflosse** [comment] 2017-03-21 20:38
Can't reproduce

**Comment by heckflosse** [comment] 2017-05-05 20:29
@Beep6581 Still valid?

**Comment by Beep6581** [comment] 2017-05-06 18:06
Yes.
```
Version: 5.0-r1-gtk3-497-g14e3f0e8
Branch: dev
Commit: 14e3f0e8
Commit date: 2017-05-05
Compiler: cc 4.9.3
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```
GTK+ 3.22.12 now.

**Comment by orava0** [comment] 2017-07-31 07:41
I am also confirming that this bug exists. It is happening when using mouse, but I am primarily using a Wacom Bamboo MTE-450 drawing tablet instead of mouse and with this tablet the panning offset is impossible to manage.

I took a screen capture to show the behaviour with the Bamboo tablet:
https://imgur.com/a/hkmr7

My configuration:

> Version: 5.2-4-gf12ee8a
> Branch: dev
> Commit: f12ee8a
> Commit date: 2017-07-25
> Compiler: cc 5.4.0
> Processor: x86_64
> System: Linux
> Bit depth: 64 bits
> Gtkmm: V3.18.0
> Build type: release
> Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
> Link flags:  -march=native
> OpenMP support: ON
> MMAP support: ON

**Comment by Beep6581** [comment] 2017-07-31 10:07
I still confirm the bug in latest dev, and it's exactly as @orava0 's gif shows. The red square is willing to go in any direction as long as that direction is down and right.

**Comment by Hombre57** [comment] 2017-07-31 22:16
I can't reproduce and never experienced this as far as I remember. Must be linux specific ?

```
Version: 5.2-8-ga1e957d5
Branch: dev
Commit: a1e957d5
Commit date: 2017-07-31
Compiler: gcc 7.1.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: Debug
Build flags: -mthreads -mwin32 -m64 -msse2 -mfpmath=sse -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O0 -g2 -Wall -fno-omit-frame-pointer
Link flags: -mthreads -march=native -O0 -fno-omit-frame-pointer
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment] 2017-08-01 14:29
I tested RawTherapee `5.0-r1-gtk2`, `5.0-r1-gtk3`, `5.1` and `5.2` in Windows 10. I could not reproduce the problem in any of them.

We don't know whether it's Linux-specific yet, but it doesn't appear on Windows (10 - @Hombre57 which version did you test in?).

**Comment by Hombre57** [comment] 2017-08-01 22:47
@Beep6581 

> We don't know whether it's Linux-specific yet, but it doesn't appear on Windows (10 - @Hombre57 which version did you test in?).

Win7

**Comment by Beep6581** [comment] 2017-08-01 23:45
Ok, @Benitoite can you reproduce this in macOS?

**Comment by Benitoite** [comment] 2017-08-02 00:26
@Beep6581 Red box panning normally at any zoom level on MacOS.

**Comment by orava0** [comment] 2017-08-02 05:45
For your information, this problem was not in the older version of Rawtherapee. This came along with version 5 as I recall. 

To confirm this, I just tested this with Rawtherapee version 4.2.1227 and did not experience this problem. I had this version previously installed and it was easy to revert to this version so that is why I tested with that exact version:
> Branch: master
Version: 4.2.1227
Changeset: 6f33c1af74158a73bf14f8924ad44c08d6cb7856
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON


I also tried to track the problem in version 5.2 by using different file types (jpg, cr2, orf, tif) and with different settings in the preferences window, but the problem was there with all the cases I tested. Clearing of thumbnail cache didn't help either.

Thanks for your efforts!

**Comment by Hombre57** [comment] 2017-08-02 23:47
Just tested in Linux Mint 18.1, all works fine.

```
Version: 5.2-13-g9a3ac4e
Branch: dev
Commit: 9a3ac4e
Commit date: 2017-08-02
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: Debug
Build flags: -m64 -msse2 -mfpmath=sse -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O0 -g2 -Wall -fno-omit-frame-pointer
Link flags:  -march=native -O0 -fno-omit-frame-pointer
OpenMP support: ON
MMAP support: ON
```

Could this be related to the Window Manager ???

**Comment by orava0** [comment] 2017-08-03 06:49
I am using Linux Mint 18.1 with Cinnamon desktop environment. Command wmctrl -m reports the window manager as default, i.e. Mutter (Muffin).  My kernel is 4.4.0-53-generic if that matters. 

RT version in the repositories is 4.2-4 and it works fine. I have compiled RT from source to get the latest version and that is where to problem with navigator window arises. I don't know if it matters, but I remember that apparently the compilation required another version of gcc packages and I had to follow instructions from this thread to get the correct gcc:  https://askubuntu.com/questions/26498/choose-gcc-and-g-version  I pasted my gcc versions here: https://pastebin.com/2qjfLZHm


Please let me know what kind of testing I could do with my setup if applicable. (I am not too familiar with different branches etc but I'll do my best :-)

**Comment by Beep6581** [comment] 2017-08-03 11:06
@orava0 the issue seems to be with the GTK3 version. 4.2 uses GTK2 IIRC.

**Comment by Hombre57** [comment] 2017-08-06 09:37
@orava0 @Beep6581 A patch has been committed to `dev` (7a7e9d3), could you test ?

**Comment by Beep6581** [comment] 2017-08-06 11:35
@Hombre57  Tested, unfortunately it does not solve the issue.
https://filebin.net/sdvd51qd8w69vust/rt_3773.mp4

**Comment by orava0** [comment] 2017-08-06 12:08
Thanks for the patch. I tested it as well and it didn't solve the issue yet, but to me it seems that the effect is less now than earlier, so it seems that you are certainly touching the right code 

https://filebin.net/wn8fhbas3t62lbg1/Kazam_screencast_00000.mp4

**Comment by Hombre57** [comment] 2017-08-06 23:18
@orava0 Your mp4 file is corrupted, I can't read it.

Could you check your toolchain, i.e. are you sure that the includes of Gtk(mm) are the same version than the library used ? Just guessing, as I don't understand where it could come from since @orava0 and I are using Linux Mint18.1, with different behavior.

**Comment by orava0** [comment] 2017-08-07 04:18
@Hombre57 Sorry for the corrupted file. I'll upload it again later today. Could you help on how to easily check if the gtk versions are correct? Probably a list of installed packages (i.e. a command in the terminal)...?

**Comment by Floessie** [comment] 2017-08-07 06:00
FWIW, I cannot reproduce this in Debian 9.1 with XFCE.

```
Version: 5.2-14-g7a7e9d32
Branch: dev
Commit: 7a7e9d32
Commit date: 2017-08-05
Compiler: cc 6.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment] 2017-08-07 06:21
Here's my `ldd` output on `rawtherapee`: https://paste2.org/CdN923ym
IIRC I had this problem in Gentoo and now I still have it in Sabayon.

**Comment by Floessie** [comment] 2017-08-07 06:48
@Beep6581 
> The red square is willing to go in any direction as long as that direction is down and right.

And this is also true for the crop in main image area, or is it the red square only?

**Comment by Hombre57** [comment] 2017-08-07 07:59
@Beep6581 @Floessie Is it theoretically possible to have an _includes_ mismatch regarding the version used ?

**Comment by Beep6581** [comment] 2017-08-07 08:27
@Floessie the main preview follows the red square correctly, and panning the main preview by clicking within it and dragging works correctly, but panning the navigator by clicking in it and dragging makes the red square jump to a spot and move in a direction which is not in sync with the mouse cursor.

@Hombre57 I don't know, but I don't think this is likely the issue, considering how Gentoo/Sabayon are built. I reproduced the problem using my self-compiled builds as well as using the RawTherapee build shipped in the package manager.

**Comment by Floessie** [comment] 2017-08-07 08:38
@Hombre57 
> Is it theoretically possible to have an includes mismatch regarding the version used ?

It's not impossible, but would be the result of a badly written CMake module.

As to the error we're after: @Beep6581 Could you check `event->x` and `event->y` in `PreviewWindow::on_motion_notify_event()` with some `printf` debugging? It should be negative sometimes.

**Comment by orava0** [comment] 2017-08-07 13:47
@Hombre57 here is a new try uploading the screen capture of the behaviour with Development 5.2-14-g7a7e9d3:  https://filebin.net/ywzk4exj3ighc4lv/output.gif

I also took an ldd list: https://paste2.org/bYGyONey

I also used command `dpkg --get-selections | grep gtk`   to get a list of all the packages that have gtk in their names:  https://paste2.org/Vz3dEOv4     I just noticed that I seem to have all packages for both i386 and amd64 installed. I'm not too familiar with this area, but it feels weird so could that be causing some problem?

**Comment by Hombre57** [comment] 2017-08-09 22:19
Thanks @orava0 , however I still have no clue of what's going on.

**Comment by Floessie** [comment] 2017-08-10 08:02
Quoting myself:
> It should be negative sometimes.

That was rubbish. It's relative to the window.

@Beep6581 If you find the time, could you test this patch?
```patch
diff --git a/rtgui/previewwindow.cc b/rtgui/previewwindow.cc
index 015c30d4..9393aed6 100644
--- a/rtgui/previewwindow.cc
+++ b/rtgui/previewwindow.cc
@@ -216,6 +216,28 @@ bool PreviewWindow::on_motion_notify_event (GdkEventMotion* event)
         CursorShape newType = cursor_type;
 
         if (isMoving) {
+            printf(
+                "---\n"
+                "press_x = %lf\n"
+                "press_y = %lf\n"
+                "zoom = %lf\n"
+                "event->x = %lf\n"
+                "event->y = %lf\n"
+                "event->axes = %p (%lf,%lf)\n",
+                static_cast<double>(press_x),
+                static_cast<double>(press_y),
+                zoom,
+                event->x,
+                event->y,
+                event->axes,
+                event->axes
+                    ? event->axes[0]
+                    : 0.0,
+                event->axes
+                    ? event->axes[1]
+                    : 0.0
+            );
+
             mainCropWin->remoteMove ((int)((event->x - (double)press_x) / zoom), (int)((event->y - (double)press_y) / zoom));
             press_x = event->x;
             press_y = event->y;
```

Can you post an excerpt of the output when the direction was wrong?

HTH,
Flössie

**Comment by Beep6581** [comment] 2017-08-10 14:28
Here you go @Floessie 
https://filebin.net/u0o5wjp7ncpercpu/rt_3773_log.txt

When testing, I would click "f" then "z", then I would click in one part of the navigator window and pan in one direction. Then I would click "f" and "z" again, and click and pan in another part and direction.
I described where I clicked and where I panned in the log file if you look for comment lines by searching for "GREPME".

**Comment by Floessie** [comment] 2017-08-10 16:46
@Beep6581 @Hombre57 The output looks reasonable to me. Is this a race or handlers called in an unexpected order?

**Comment by Floessie** [comment] 2017-08-11 09:22
@Beep6581 Are you running Sabayon KDE edition 17.07?

**Comment by Beep6581** [comment] 2017-08-11 09:44
I'm using Sabayon and KDE Plasma 5.9.5, KDE Frameworks 5.36.0 and KDE Apps 17.04.3.

Here is a new recording including log output: https://filebin.net/94taq8cxd2ew0x3q/rt_3773_2.mp4

**Comment by Floessie** [comment] 2017-08-11 11:29
@Beep6581 
> I'm using Sabayon and KDE Plasma 5.9.5, KDE Frameworks 5.36.0 and KDE Apps 17.04.3.

Same here in the Live ISO. Unfortunately I can't install to the virtual HD, as `liveinst` fails with `ImportError: No module named _selinux`. 😞 Although I've no experience with Sabayon, I tried to install the missing `sys-apps/selinux-python`, but it's not found. Any hint?

**Comment by Beep6581** [comment] 2017-08-11 14:38
@Floessie sounds like a bug, it shouldn't be using selinux. Have you tried a different ISO?
Stable: https://www.sabayon.org/desktop/
Daily: http://ftp.portlane.com/pub/os/linux/sabayon/iso/daily/daily.html

They are helpful on IRC (freenode, #sabayon)

I will be away in Tiveden until Monday. Have a good weekend everyone.

**Comment by Floessie** [comment] 2017-08-11 15:01
@Beep6581 Yes, it's a bug. The daily image from yesterday works. I will continue with it on Monday. Have fun and take some nice photos in Tiveden!

**Comment by Floessie** [comment] 2017-08-14 06:34
I managed to set a Sabayon VM up and installed the packaged RT 5.1. Still, I cannot reproduce the problem. 😞

**Comment by Floessie** [comment] 2017-08-14 09:37
@Beep6581 Could you try this patch (w/o the previous patch applied)? I'm only interested in moving top left (the bad case).

```patch
diff --git a/rtgui/crophandler.cc b/rtgui/crophandler.cc
index f6ff83a7..c4cc477e 100644
--- a/rtgui/crophandler.cc
+++ b/rtgui/crophandler.cc
@@ -637,6 +637,16 @@ void CropHandler::compDim ()
         imgY = 0;
     }
 
+    printf(
+        "CropHandler::compDim(): cropX = %d, cax = %d, wwImgSpace = %d, cropY = %d, cay = %d, whImgSpace = %d\n",
+        cropX,
+        cax,
+        wwImgSpace,
+        cropY,
+        cay,
+        whImgSpace
+    );
+
     cropX = cax - (wwImgSpace/2);
     cropY = cay - (whImgSpace/2);
     cropW = wwImgSpace;
@@ -671,4 +681,6 @@ void CropHandler::compDim ()
     }
 
     displayHandler->setDisplayPosition(imgX, imgY);
+
+    printf("CropHandler::compDim(): cropX = %d, cropY = %d\n", cropX, cropY);
 }
diff --git a/rtgui/cropwindow.cc b/rtgui/cropwindow.cc
index 8af0541f..523279f0 100644
--- a/rtgui/cropwindow.cc
+++ b/rtgui/cropwindow.cc
@@ -2557,10 +2557,12 @@ void CropWindow::setDisplayPosition (int x, int y) {
 
 void CropWindow::remoteMove (int deltaX, int deltaY)
 {
+    printf("CropWindow::remoteMove(deltaX = %d, deltaY = %d)\n", deltaX, deltaY);
 
     state = SCropImgMove;
     cropHandler.moveAnchor(deltaX, deltaY, false);
 
+
     for (auto listener : listeners) {
         listener->cropPositionChanged (this);
     }
diff --git a/rtgui/previewwindow.cc b/rtgui/previewwindow.cc
index 015c30d4..68825f66 100644
--- a/rtgui/previewwindow.cc
+++ b/rtgui/previewwindow.cc
@@ -48,6 +48,17 @@ void PreviewWindow::getObservedFrameArea (int& x, int& y, int& w, int& h)
         y = imgY + round(cropY * zoom);
         w = round(cropW * zoom);
         h = round(cropH * zoom);
+
+        printf(
+            "PreviewWindow::getObservedFrameArea(): x = %d, imgX = %d, cropX = %d, zoom = %lf, y = %d, imgY = %d, cropY = %d\n",
+            x,
+            imgX,
+            cropX,
+            zoom,
+            y,
+            imgY,
+            cropY
+        );
     }
 }
 
```

**Comment by Beep6581** [comment] 2017-08-14 11:54
The behavior is weird... sometimes while panning the red square seems to "click into" misbehaving in one way, e.g. for every change in input-x do the change in output-y, and then at some point while dragging it snaps to a different behavior, e.g. for every change in input-x do twice the change in output-y... The speed with which I drag also seems to play a role. And I get the feeling that it behaves a little differently in maximized window mode than it does when the window is not maximized (as in the screencast), though it's difficult to notice a real pattern if the behavior is buggy and feels random to begin with.
https://filebin.net/bpckic3kqu9s2xcq/rt_3773_3.mp4

**Comment by Floessie** [comment] 2017-08-14 12:16
@Beep6581 What I see in your video is that you move the right and the red sqare moves right *and down*. Is that the problem you're facing ATM? Seems, that is due to `press_(x|y)` is `int`. Could you give me a text file with comments on what you expected and what you experienced when is was wrong?

**Comment by Floessie** [comment] 2017-08-14 12:51
@Beep6581 Here's a patch, that gives me consistent behavior:

```patch
diff --git a/rtgui/previewwindow.cc b/rtgui/previewwindow.cc
index 015c30d4..cd4e0c75 100644
--- a/rtgui/previewwindow.cc
+++ b/rtgui/previewwindow.cc
@@ -216,7 +216,7 @@ bool PreviewWindow::on_motion_notify_event (GdkEventMotion* event)
         CursorShape newType = cursor_type;
 
         if (isMoving) {
-            mainCropWin->remoteMove ((int)((event->x - (double)press_x) / zoom), (int)((event->y - (double)press_y) / zoom));
+            mainCropWin->remoteMove ((event->x - press_x) / zoom, (event->y - press_y) / zoom);
             press_x = event->x;
             press_y = event->y;
         } else if (inside) {
diff --git a/rtgui/previewwindow.h b/rtgui/previewwindow.h
index a7b28620..f5041117 100644
--- a/rtgui/previewwindow.h
+++ b/rtgui/previewwindow.h
@@ -36,7 +36,7 @@ private:
     ImageArea* imageArea;
     int imgX, imgY, imgW, imgH;
     double zoom;
-    int press_x, press_y;
+    double press_x, press_y;
     bool isMoving;
     bool needsUpdate;
     CursorShape cursor_type;
```

HTH,
Flössie

**Comment by Beep6581** [comment] 2017-08-14 16:42
@Floessie here is a list of issues I observe:
- I move the red square left, it moves left but lags behind - initially the cursor is in the center of the square, but it ends up leaving the square (`00:00:03 - 00:00:05`).
- I move the square up, but it moves up and left (`00:00:05 - 00:00:08`).
- I move the red square to the right, it moves right but accelerated faster than I'm moving the cursor - it accelerates away from the cursor (`00:00:08 - 00:00:11`).
- I move the red square down, it moves down and right (`00:00:15 - 00:00:20`).
- When I zoomed to 200% and moved the red square left, it moved left and down (`00:00:33 - 00:00:35`, visible even better at `00:01:22 - 00:01:27`).
- 200%, I moved the square right, it moved right and down and much faster than I was moving it (`00:00:35 - 00:00:40`).
- 200%, when I move it up-left it lagged behind barely moving, and suddenly shots up when my cursor left the Navigator image and moved over the Navigator frame widget (`00:00:49 - 00:00:53`).

**Comment by Beep6581** [comment] 2017-08-14 16:45
@Floessie the last patch fixes it! Thank you, +1 for commit :)

Why is it that @orava0 and I were the only ones able to reproduce that?

**Comment by orava0** [comment] 2017-08-14 18:11
@Floessie I can also confirm that your patch fixed the problem. I am very grateful to all of you who took effort on this!

**Closed as completed** 2017-08-14 19:53 UTC
Labels: type: bug

**Comment by Floessie** [comment] 2017-08-14 19:58
@Beep6581 
> Why is it that @orava0 and I were the only ones able to reproduce that?

Actually, I could see it here, too (not so dramatically, though). But I was focused too much on that sentence of yours:

>The red square is willing to go in any direction as long as that direction is down and right.

With the debug patch, one could see, that there's a delta even when the mouse didn't move in that direction, and this was due to rounding `press_(x|y)` down to `int`s.

@orava0 @Beep6581 Thanks for your help catching this one! 👍 

Best,
Flössie
