### ISSUE TITLE
Non-raw images not shown in File Browser if folder name contains ß

### ISSUE THREAD

**Issue by FelixJongleur42** [Beep6581/RawTherapee#3598] opened 2017-01-07 12:27 UTC
Tried 4.2.1 x64 on Windows
I have the following Folders:
1. D:\Pictures\Astronomie\Objekte\Milchstraße\2015-08-13\Serie1\1-input\ containing .CR2 - **works**
2. D:\Pictures\Astronomie\Objekte\Milchstraße\2015-08-13\Serie1\2-work\ containing RT readable TIFF and PNG but the files are all filtered out

Renaming the parent folder "Milchstraße" to "Milchstrasse" makes the folder "2-work" work again.
As the analysis initiated by https://github.com/Beep6581/RawTherapee/issues/3583 shows - it's probably both of the routines involved with TIFF or PNG that "break" the folder since the folder with CR2 works.

The test files from https://filebin.net/tqb000qgtcz8skc4 (which reside under "2-work")
1. I put png only in "2-work" - broken
2. I put tiff only in "2-work" - broken

**Comment by Beep6581** [comment] 2017-01-07 12:37
I tried with ~/photos/teßt_images/amßterdam.pef and all photos in that folder show up in master and gtk3. Cannot reproduce.

**Comment by Beep6581** [comment] 2017-01-07 12:42
I tried again with your folder structure and with non-raw files, now I can reproduce.

With verbose mode, the console shows:
```
CacheImageData::load / Error code 4 while reading values from "/home/morgan/.cache/RawTherapee4/data/dss.png.e1a6e2f27399e2f3fc27228c8bfe6d9f.txt":
No such file or directory
CacheImageData::load / Error code 4 while reading values from "/home/morgan/.cache/RawTherapee4/data/dss.tif.2014346c50dd05a9b832bbada6f65c2e.txt":
No such file or directory
CacheImageData::load / Error code 4 while reading values from "/home/morgan/.cache/RawTherapee4/data/dss-stripped.tif.e8640eaf0a6ad046606d8573ca3ddf59.txt":
No such file or directory
CacheImageData::load / Error code 4 while reading values from "/home/morgan/.cache/RawTherapee4/data/dss8.tif.6bfae2356c06a4413783d081fda3964c.txt":
No such file or directory
CacheImageData::load / Error code 4 while reading values from "/home/morgan/.cache/RawTherapee4/data/dss8-small.tif.1c39c7b4fb28eca329b21976424b9849.txt":
No such file or directory
```

**Comment by FelixJongleur42** [comment] 2017-01-07 13:06
If you want I can look into the source in order to pin down the problem.

**Comment by Beep6581** [comment] 2017-01-07 13:14
You're most welcome to :)

**Comment by FelixJongleur42** [comment] 2017-01-07 13:55
Ok, compiling for Windows just now (gtk3 branch).

**Comment by FelixJongleur42** [comment] 2017-01-08 00:37
Isolated the problem that Glib::ustring::casefold() is used a couple of times in order to do case insensitive comparison of file extensions. The method casefold() may change length of the original string (with ß) such that the "dot" position is no longer correct on the result of casefold().
Starts off that StdImageSource::getSampleFormat() cannot determine the file type.
I grepped the code for casefold() and I figured the code could be improved by providing utility function to determine file name extension and if necessary file type by extension.

Turns out there may be more potential problems with such folder names, e.g. in profilestore.cc

To give an idea how callers would be changed:
```
diff --git a/rtengine/stdimagesource.cc b/rtengine/stdimagesource.cc
index 6017a1c..7125baa 100644
--- a/rtengine/stdimagesource.cc
+++ b/rtengine/stdimagesource.cc
@@ -74,27 +74,19 @@ void StdImageSource::getSampleFormat (const Glib::ustring &fname, IIOSampleForma
     sFormat = IIOSF_UNKNOWN;
     sArrangement = IIOSA_UNKNOWN;

-    size_t lastdot = fname.find_last_of ('.');
-
-    if( Glib::ustring::npos == lastdot ) {
-        return;
-    }
-
-    if (!fname.casefold().compare (lastdot, 4, ".jpg") ||
-            !fname.casefold().compare (lastdot, 5, ".jpeg")) {
+    if (isJPEG(fname)) {
         // For now, png and jpeg files are converted to unsigned short by the loader itself,
         // but there should be functions that read the sample format first, like the TIFF case below
         sFormat = IIOSF_UNSIGNED_CHAR;
         sArrangement = IIOSA_CHUNKY;
         return;
-    } else if (!fname.casefold().compare (lastdot, 4, ".png")) {
+    } else if (isPNG(fname)) {
         int result = ImageIO::getPNGSampleFormat (fname, sFormat, sArrangement);

         if (result == IMIO_SUCCESS) {
             return;
         }
-    } else if (!fname.casefold().compare (lastdot, 4, ".tif") ||
-               !fname.casefold().compare (lastdot, 5, ".tiff")) {
+    } else if (isTIFF(fname)) {
         int result = ImageIO::getTIFFSampleFormat (fname, sFormat, sArrangement);

         if (result == IMIO_SUCCESS) {
```

Utils functions currently look like:
```
/**
 * Return lower case extension without the "." or "" if the given name contains no "."
 */
Glib::ustring getFileExtension(const Glib::ustring &fname) {
    // issue 3598 do not use casefold() to compare ignoring case - it seems to mangle sharp-s character and length of string
    // simply get extension first, then use lowercase()
    size_t lastdot = fname.find_last_of ('.');
    if( Glib::ustring::npos == lastdot ) {
        return "";
    }
    return fname.substr(lastdot + 1).lowercase();
}

/**
 * Return true if file is a JPEG file (determined by file name extension)
 */
bool isJPEG(const Glib::ustring &fname) {
   const Glib::ustring extension = getFileExtension(fname);
   return ((extension == "jpg") || (extension == "jpeg"));
}

/**
 * Return true if file is a TIFF file (determined by file name extension)
 */
bool isTIFF(const Glib::ustring &fname) {
   const Glib::ustring extension = getFileExtension(fname);
   return ((extension == "tif") || (extension == "tiff"));
}

/**
 * Return true if file is a PNG file (determined by file name extension)
 */
bool isPNG(const Glib::ustring &fname) {
   const Glib::ustring extension = getFileExtension(fname);
   return (extension == "png");
}

```

Should I proceed?

**Comment by heckflosse** [comment] 2017-01-08 01:24
@FelixJongleur42 

> Should I proceed?

Of course. Any improvement is welcome :+1: 
Thanks for looking at this part of the code. I already opened [an issue about that](https://github.com/Beep6581/RawTherapee/issues/2289) more than 2 years ago.

**Comment by FelixJongleur42** [comment] 2017-01-08 01:51
Ok, how do I supply you with my changes?
Should I produce a patch file and if - how? I am not to familiar with git.
Anyway I am attaching the output of "git diff".

Please review the changes, especially the last one in rtgui/profilestore.cc - I was not sure how to run in that case (should be finding the pp3 next to the image?).

[issue-3598.patch.txt](https://github.com/Beep6581/RawTherapee/files/691834/issue-3598.patch.txt)

**Comment by Beep6581** [comment] 2017-01-08 14:35
@FelixJongleur42 you could either create your own fork and patch that and somehow link us to that (I'm not sure exactly how as I've never done that, but git is well documented with plenty of examples online) or you could just make your changes and output a patch "git diff > patch_3598.txt", then upload that file here. The fork way is probably better as it will have a more direct link to you, while the patch way is ok for small patches.

**Comment by Floessie** [comment] 2017-01-08 14:41
You can fork, commit on your fork, and create a Pull Request for us. See [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by Floessie** [comment] 2017-01-08 14:56
@FelixJongleur42 I really like your patch. These are just some minor things, I'd change:
- Rename `isPNG()` and friends to `hasPngExtension()`. Then you can omit the describing comments.
- Don't refer to #3598 everywhere. This can be recovered from git history.
- The type of `lastdot` should really be `Glib::ustring::size_type`. I know, this was also wrong before... You could also make it `const`, if you don't want to alter it later.
- Precedences are and were clear, so no need to add parentheses everywhere.

Good catch, btw. :+1: 

Best
Flössie

**Comment by Beep6581** [comment] 2017-01-18 10:37
Can we get this into RT5? @FelixJongleur42 @Floessie @heckflosse

**Comment by Floessie** [comment] 2017-01-18 17:36
@Beep6581 As said, I like the patch. If @FelixJongleur42 comes up with a cleaned up version, it should be merged for RT5.

**Comment by FelixJongleur42** [comment] 2017-01-18 18:48
Thanks for your feedback. I'll see to make the changes this week.

**Comment by FelixJongleur42** [comment] 2017-01-19 21:43
Added pull request #3616

**Comment by heckflosse** [comment] 2017-01-20 21:11
@Floessie @FelixJongleur42 Thanks :+1:

**Comment by Beep6581** [comment] 2017-01-21 22:13
Committed, closing.

**Closed by Beep6581** 2017-01-21 22:13 UTC
Labels: bug, patch
