### ISSUE TITLE
Exact preview render feature

### ISSUE THREAD

**Issue by vcrash** [Beep6581/RawTherapee#6310] opened 2021-07-20 10:08 UTC
It is known that some tools in RT require 1:1 zoom to be properly rendered in preview. And when some complex effects are in use such as a dynamic range compression, noise reduction or wavelets levels it is hard to control the overal image appearance.
It is always take a time to save the image, look at that and then return to RT to apply some changes. And then repeat all that again.
So what if to add Exact preview render button which will initialize accurate image rendering without saving it to the file. Rendered image can be appeared as preview with zooming and panning (hand tool) available. And when the user changes some settings, “exact preview mode” will be canceled and switched to the regular one.
Applying such a feature can also improve a perfomance of zooming and panning because of while image is prerendered there is no need to re-render complex effects during zooming and exploring.

**Comment by Thanatomanic** [comment] 2021-07-21 08:40
Duplicate of an old request: https://github.com/Beep6581/RawTherapee/issues/2900

**Closed as completed by Thanatomanic** 2021-07-21 08:40 UTC
