### ISSUE TITLE
LCP distortion correction not auto cropping black areas?

### ISSUE THREAD

**Issue by raceviper13** [Beep6581/RawTherapee#4159] opened 2017-10-25 14:15 UTC
I don't have the information with me now on the specific RT version I am using (5.3-???).  I will add that tonight when I have a chance.

With the change to the lens correction (lensfun I think), it seems that the LCP no longer auto crops out the black areas due to correcting the distortion to the image.  I am getting a lot of occurrences of this depending on lens focal length, and focus distance.

Can we get a check to see if that was changed with the lensfun?

**Comment by Beep6581** [comment] 2017-10-25 15:58
@raceviper13  please upload sample raw files + LCP files along with your version info. Unzipped, using https://filebin.net/

**Comment by raceviper13** [comment] 2017-10-25 21:09
OK, it looks like the problem is occurring when rendering the JPG because it looks like it is being cropped in the preview window properly.

Here is a single image that exhibits the problem.  If you need additional ones, please let me know.

https://filebin.net/q1iofpm73xjp8sc3

Version: 5.3
Branch: 5.3
Commit: ec0f7936
Commit date: 2017-09-30
Compiler: gcc 7.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads   -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by agriggio** [comment] 2017-10-25 21:52
@raceviper13 thanks, confirmed. It's a bad interaction between Distortion and Chromatic Aberrations correction. I'll fix it ASAP, but in the meantime you can work around it by de-selecting "Chromatic Aberration Correction" in "Profiled Lens Correction". Since you are already using RAW CA auto-correction, the setting would be useless anyway... (of course, this is just a workaround and we should fix the problem)

**Comment by agriggio** [comment] 2017-11-17 22:54
Fixed in d527e7ead2d649288cef0fea23c53df107a048c5

**Closed as completed by agriggio** 2017-11-17 22:54 UTC
