### ISSUE TITLE
locallab keyboard shortcuts issue

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#5265] opened 2019-04-04 18:42 UTC
Using shortcuts (e.g. z to zoom in) does not work because of this (whatever that is):
![grafik](https://user-images.githubusercontent.com/13733487/55580087-0e2b5d80-571a-11e9-8fda-18da340ea025.png)

**Comment by sguyader** [comment] 2019-04-04 19:44
@heckflosse I don't have this problem (fresh build, commit 2394e06)

**Comment by heckflosse** [comment] 2019-04-04 20:11
@sguyader I have the issue only when the locallab settings tool is opened.

**Comment by sguyader** [comment] 2019-04-04 20:21
@heckflosse yes tried also with the locallab settings open, but no issue here. However I use the Toowagrey theme, it's the only difference I see (besides the photograph of course).

**Comment by heckflosse** [comment] 2019-04-04 20:37
@sguyader I just checked again. With all themes I get the bug when the focus is on a spot in settings. I guess it's some automatism to select the spot by typing its name, but I dont get how it works (it doesn't seem to work)

**Comment by Beep6581** [comment] 2019-04-05 06:38
I get the popup too. Looks like a standard GtkTreeView search box, though it doesn't match anything I type.

**Comment by Beep6581** [comment] 2019-04-05 06:47
```diff
diff --git a/rtgui/controlspotpanel.cc b/rtgui/controlspotpanel.cc
index 0fecf9b54..37d93d4bd 100644
--- a/rtgui/controlspotpanel.cc
+++ b/rtgui/controlspotpanel.cc
@@ -98,6 +98,7 @@ ControlSpotPanel::ControlSpotPanel():
     buttonvisibilityconn_ = button_visibility_.signal_clicked().connect(
                                 sigc::mem_fun(*this, &ControlSpotPanel::on_button_visibility));
 
+    treeview_.set_enable_search(false); // Disable search to prevent hijacking keyboard shortcuts #5265
     treeview_.set_grid_lines(Gtk::TREE_VIEW_GRID_LINES_VERTICAL);
 
     scrolledwindow_.add(treeview_);
```

**Comment by sguyader** [comment] 2019-04-05 11:04
> @sguyader I just checked again. With all themes I get the bug when the focus is on a spot in settings. I guess it's some automatism to select the spot by typing its name, but I dont get how it works (it doesn't seem to work)

Ok, when a spot is focused in the list I get the same behaviour indeed.

**Comment by Pandagrapher** [comment] 2019-04-18 18:10
@Beep6581 
In fact, this patch doesn't completely deactivate `treeview` search. Pressing Ctrl+F the search popup reappears if `treeview` is focused, otherwise a Gtk-critical error is raised. I have introduced your patch then corrected the side effects with commit `853a6f0`

Pierre

**Comment by Pandagrapher** [comment] 2019-04-23 10:45
@heckflosse @Beep6581 
Is it ok to close this issue?
Pierre

**Comment by heckflosse** [comment] 2019-04-23 11:14
Ok from me. @Beep6581 ?

**Comment by Beep6581** [comment] 2019-04-23 11:43
Fix confirmed.

**Closed as completed** 2019-04-23 11:47 UTC
Labels: type: bug, patch provided, tool: selective editing
