### ISSUE TITLE
Custom curve shape affected by placing subsequent node

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#4851] opened 2018-10-04 19:10 UTC
To reproduce: Open a Raw and a Custom Curve. This could be within CIECAM, LAB or tone curves 1 or 2 in Exposure.  Place the first point.  Now position the mouse near but not quite on the curve. Press Ctrl. Click.  The curve alters, but it should not.  It has been a feature for quite some time that Ctrl clicking is the easy way to put a point exactly on the curve.  (This allows two points close together to be set up, thus isolating a section of curve from "whiplash" when a further point is moved)

Having done one Ctrl click, subsequent ones seem to work ok.  But if you reset the curve to a straight ine, you can repeat the issue.

This is version: 5.4-918-gae12a41, Branch: dev, Commit: ae12a41, Commit date: 2018-09-29.
Ubuntu.

**Comment by Beep6581** [comment] 2018-10-04 19:12
Cannot reproduce. Could you show a video?

**Comment by Beep6581** [comment] 2018-10-04 19:16
Ah, I see what you mean. The node seems to get placed exactly where it should be placed, but the new Catmull-Rom spline curve, introduced in #4701, results in the curve shape being affected by the new node.

**Comment by RawConvert** [comment] 2018-10-04 19:18
I think my title was better! - mentions the Ctrl bit!

**Comment by Beep6581** [comment] 2018-10-04 19:41
I don't think there's anything to be done about this because it behaves correctly, just differently than before, but we'll see what @agriggio and the others think.

**Comment by agriggio** [comment] 2018-10-04 20:25
Sorry, I don't understand what the issue is... I agree that a video would help

**Comment by agriggio** [comment] 2018-10-04 20:26
fwiw, I didn't touch the GUI at all when introducing the catmull-rom splines...

**Comment by RawConvert** [comment] 2018-10-05 10:08
I'll  hopefully come back to this over the weekend.  I don't think it behaves correctly because the first Ctrl Click point behaviour is different to subsequent Ctrl Clicks.  A bug!  @agriggio , the issue is about getting part of the curve just right, bit like the zone system I guess, then when you alter the next part of the curve, you don't want it to affect the bit you've just sorted out.  A number of users use this feature, I think I picked it up from @patdavid-test ages ago.

**Comment by Beep6581** [comment] 2018-10-05 11:29
@agriggio I think what @RawConvert means is that when placing a new node on the curve, in the old curve type you could do so without it affecting the shape of the curve, while now it does change the shape:
![screenshot_20181005_132740](https://user-images.githubusercontent.com/5844619/46532792-a6977100-c8a2-11e8-8276-f6dbf44e1c5c.png)
![screenshot_20181005_132756](https://user-images.githubusercontent.com/5844619/46532793-a6977100-c8a2-11e8-85f0-d2d080a878f1.png)
![screenshot_20181005_133013](https://user-images.githubusercontent.com/5844619/46532865-e4949500-c8a2-11e8-8d37-2eaa2c50ce04.png)

> the first Ctrl Click point behaviour is different to subsequent Ctrl Clicks

I haven't found that to be the case. If you have, please show a video.

**Comment by agriggio** [comment] 2018-10-05 12:05
ah ok, now I understand. yes, I guess it's not a bug then, just a change of behaviour. I'll have to think whether it's possible to have a workaround -- I'm not sure at the moment. anyway, placing another control point doesn't ensure that the curve won't change in the middle, I think this was never the case... if you want that behaviour, control cage curves are better imho

**Comment by RawConvert** [comment] 2018-10-08 10:52
@agriggio , hi, I think it is a bug because the first time you do it (when the curve jumps to the new point) it is different to subsequent times (when the point jumps to the curve).  Re. the curve changing in the middle, you suspect this was never the case, but I can assure you that previously, once you had two points fairly close together, moving a further point on say the left side of the pair resulted in no movement to the right of the pair (or at least such a small movement I can't see it).

Re. the GUI changing, someone has changed it because the icons are different!, as below, with old (mid-June) and recent RT.
![wiggles15jun](https://user-images.githubusercontent.com/16868433/46604315-b8208900-caed-11e8-8cff-848a116f5f1a.jpg)
![wiggles-30sep](https://user-images.githubusercontent.com/16868433/46604321-beaf0080-caed-11e8-8a2e-d69c3bea1134.jpg)
@Beep6581 referred to the upper of the 2 icons as a pipette.  I think this is a good description and the pipette icon (like white balance) might be a better choice.  However I'm wondering why this button is needed at all.  Why not have it enabled all the time and delete the button?  Then you'll always see the position being indicated in the histogtram (or equalizer), and as now, you do a CTRL Click to place the point.

The new spline curve is interesting.  It is less curvy then the previous one, with any segment between points being straighter than previously, it seems to me.  So an "S" curve is relatively linear along the middle section.  The new one has more symmetry - notice how with the old curve, the more vertical sections are pretty straight, while all the curving is done by the more horizontal segments.  The new one has curving equally, which seems natural given the points form a neutral pattern with respect to horizontal and vertical.

**Comment by Beep6581** [comment] 2018-10-08 11:19
> I think it is a bug because the first time you do it (when the curve jumps to the new point) it is different to subsequent times

Please show a video of what you mean.

**Comment by RawConvert** [comment] 2018-10-08 20:16
I don't know how to do a video! (and the time factor too).  I was just looking again at this, and I was wrong to say the curve jumps to the point, at least it's not just now.  The point goes to the curve I believe, but the curve alters. Previously the curve didn't alter.  Here are screen grabs... 1) a curve with 2 points   2) CTRL-Click add a third with mid-June RT - curve doesn't change  3) same but with new RT - curve changes (quite a lot).
![before](https://user-images.githubusercontent.com/16868433/46631216-b59a4f80-cb3e-11e8-8e6b-eb338c47aa9e.jpg)
2 -
![old-after](https://user-images.githubusercontent.com/16868433/46631242-c4810200-cb3e-11e8-9feb-da526e09fecd.jpg)
3 -
![new-after](https://user-images.githubusercontent.com/16868433/46631253-cc40a680-cb3e-11e8-91ba-9ee0dd1277cd.jpg)

**Comment by agriggio** [comment] 2018-10-08 22:02
Hi @RawConvert 

> Click add a third with mid-June RT - curve doesn't change

doesn't it? Look at the rightmost part: there's a visible difference between 1 and 2... or maybe I'm still misunderstanding what you mean?

**Comment by RawConvert** [comment] 2018-10-09 22:52
hi again, sorry, I thought I didn't need both the "before" images, so just posted one, but they are different due to the differing spline logic.  So... (1) and (3) above are correct images and you see quite an elbow appearing when the CTRL-Click point is added.  Here are the corresponding pair for mid-June RT -
![june-before](https://user-images.githubusercontent.com/16868433/46702661-e00e0a80-cc1b-11e8-873f-23a94fb52999.jpg)
![june-after](https://user-images.githubusercontent.com/16868433/46702671-e7351880-cc1b-11e8-89a2-f67c10b1ec42.jpg)
The point goes to the curve and the curve doesn't change.
I've noticed something else about the new curve - see this section with the window dragged large.  It's not that smooth, it seems to change direction more times than it needs or ought to perhaps?
![closeup](https://user-images.githubusercontent.com/16868433/46703231-2bc1b380-cc1e-11e8-9361-1bb61e45c685.png)

**Comment by agriggio** [comment] 2018-10-10 05:41
it's a different curve. the old splines are definitely smoother, but (*IMHO*) painful to edit, as moving a point has a global effect. the new curve is supposed to fix that, making editing easier. I'm not sure there's much that can be done, other than reverting to the previous implementation. if you'd like that, maybe open a separate issue where this can be discussed

**Comment by RawConvert** [comment] 2018-10-10 16:34
"painful to edit, as moving a point has a global effect"    This takes us back to the double-point / blocker "feature".  I may not be fully understanding "global effect" but I think you can and could isolate any section(s) of the curve using double points and so change the curve how you want without pain.  I think it would be worth getting others' opinions as these curves are surely a fundamental editing tool.

**Comment by agriggio** [comment] 2018-10-10 16:44
I am fine with restoring the old behaviour if there is consensus, but I think this should be discussed in a separate issue

**Comment by Beep6581** [comment] 2018-10-10 18:16
I wouldn't mind having the old mode added as an option to the combo, but I like the new curve mode and would like it to remain.

Closing this as it's not a bug.

**Closed as completed by Beep6581** 2018-10-10 18:16 UTC

**Comment by RawConvert** [comment] 2018-10-10 23:30
I think if it's possible to have the old algorithm available then that's really good.
As regards to closing because not a bug, perhaps you could address this! -
We are talking about fitting a curve to a set of points.  Assume you already have N points (N>=1) and a curve has been calculated.  You now add point N+1 **ON THE CURVE** (i.e. Ctrl+Click). Surely the curve remains as is; it should not change.  But it sometimes does with the new method (and didn't previously).

**Comment by agriggio** [comment] 2018-10-11 05:22
> Surely the curve remains as is;

I don't think that's necessarily true. currently the curve is recomputed every time the control points change, the code has no notion of "the old curve", that's purely a GUI thing. perhaps it's possible to tweak the code to reuse the old curve if it already fits, but I'm afraid that would require some nontrivial changes to how curves are computed, updated, and saved. *for me* it's not worth it, I understand you might disagree and that's perfectly fine, but the chances that I will do something about it are not very high, sorry.

**Comment by agriggio** [comment] 2018-10-11 12:03
@RawConvert just to illustrate what I mean by "global behaviour", and why I think your proposed solution of just using double points doesn't always work, here are two videos:

- old curve: https://filebin.net/bqlpiey4sj306cw2/old-spline.mp4?t=a4m4l1np

- new curve: https://filebin.net/bqlpiey4sj306cw2/new-curve.mp4?t=a4m4l1np

Does this help?

**Comment by RawConvert** [comment] 2018-10-12 16:29
Ok, well in this fairly extreme case, the curve does indeed go wild, though I'm wondering if you could have put the two blocker points closer together (might have helped, not certain).
