### ISSUE TITLE
Crash editing Nikon D70 raw files

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#4202] opened 2017-11-29 13:18 UTC
I'm editing some really old Nikon D70 raw files and for me, RT keeps crashing when I switch between photos. For instance, see the three shared NEFs below where the crash happens:
https://www.dropbox.com/sh/6hlvoiqx7aaksqb/AACtNFPYMgNb-ZNERV3OCh3Pa?dl=0

This is the output from a debug-build:
https://pastebin.com/QKahQr64

I'm on Ubuntu 17.10 using:
Version: 5.3-228-g56dc615b
Branch: dev
Commit: 56dc615b
Commit date: 2017-11-28
Compiler: cc 7.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

Thanks in advance! :-)

**Comment by agriggio** [comment] 2017-11-29 13:52
@mks9900 are you using multiple tabs or a single editor? How much RAM do you have?

**Comment by ghost** [comment] 2017-11-29 13:53
Hi! I'm using single editor and my system has 24 Gbyte of RAM.

**Comment by agriggio** [comment] 2017-11-29 13:54
ok, we ruled that out at least :-)

**Comment by agriggio** [comment] 2017-11-29 16:44
@mks9900 are you using RAW Auto-CA correction by any chance?

**Comment by agriggio** [comment] 2017-11-29 17:06
Anyway, I get a crash (consistently reproducible) if enabling RAW Auto-CA correction. There seems to be some memory corruption problem (probably an array out of bounds write). The crash is in `CA_correct_RT`. @heckflosse any idea?

**Comment by heckflosse** [comment] 2017-11-29 17:25
@agriggio Alberto, I thought I had all bugs in CA_correct_RT caused by odd image width (3031 in this case) fixed :( I will take a look.

**Comment by ghost** [comment] 2017-11-29 17:35
@agriggio: That seems to be the problem! Turning it off makes RT behave like normal again :-)
Now I have a workaround! :+1:

**Comment by agriggio** [comment] 2017-11-29 17:37
well I wasn't suggesting that as a workaround, I was rather looking for a confirmation that it was the culprit. now we can think of fixing the bug -- and thanks for reporting btw

**Comment by ghost** [comment] 2017-11-29 17:41
Oh, I understood that, but I was nevertheless glad to get around the bug :-)

**Comment by heckflosse** [comment] 2017-11-29 18:45
@agriggio This patch should fix the bug in ca_correct_rt and also two other bugs I found using adress sanitizer. Can you please test and review?

```patch
diff --git a/rtengine/CA_correct_RT.cc b/rtengine/CA_correct_RT.cc
index 59fd804f..bfd56cc0 100644
--- a/rtengine/CA_correct_RT.cc
+++ b/rtengine/CA_correct_RT.cc
@@ -218,18 +218,18 @@ void RawImageSource::CA_correct_RT(const bool autoCA, const double cared, const
             // Main algorithm: Tile loop calculating correction parameters per tile
             #pragma omp for collapse(2) schedule(dynamic) nowait
             for (int top = -border ; top < height; top += ts - border2)
-                for (int left = -border; left < width; left += ts - border2) {
+                for (int left = -border; left < width - (W & 1); left += ts - border2) {
                     memset(buffer, 0, buffersize);
                     const int vblock = ((top + border) / (ts - border2)) + 1;
                     const int hblock = ((left + border) / (ts - border2)) + 1;
                     const int bottom = min(top + ts, height + border);
-                    const int right  = min(left + ts, width + border);
+                    const int right  = min(left + ts, width - (W & 1) + border);
                     const int rr1 = bottom - top;
                     const int cc1 = right - left;
                     const int rrmin = top < 0 ? border : 0;
                     const int rrmax = bottom > height ? height - top : rr1;
                     const int ccmin = left < 0 ? border : 0;
-                    const int ccmax = right > width ? width - left : cc1;
+                    const int ccmax = (right > width - (W & 1)) ? width - (W & 1) - left : cc1;
 
                     // rgb from input CFA data
                     // rgb values should be floating point numbers between 0 and 1
@@ -755,20 +755,20 @@ void RawImageSource::CA_correct_RT(const bool autoCA, const double cared, const
             #pragma omp for schedule(dynamic) collapse(2) nowait
 
             for (int top = -border; top < height; top += ts - border2)
-                for (int left = -border; left < width; left += ts - border2) {
+                for (int left = -border; left < width - (W & 1); left += ts - border2) {
                     memset(buffer, 0, buffersize);
                     float lblockshifts[2][2];
                     const int vblock = ((top + border) / (ts - border2)) + 1;
                     const int hblock = ((left + border) / (ts - border2)) + 1;
                     const int bottom = min(top + ts, height + border);
-                    const int right  = min(left + ts, width + border);
+                    const int right  = min(left + ts, width - (W & 1) + border);
                     const int rr1 = bottom - top;
                     const int cc1 = right - left;
 
                     const int rrmin = top < 0 ? border : 0;
                     const int rrmax = bottom > height ? height - top : rr1;
                     const int ccmin = left < 0 ? border : 0;
-                    const int ccmax = right > width ? width - left : cc1;
+                    const int ccmax = (right > width - (W & 1)) ? width - (W & 1) - left : cc1;
 
                     // rgb from input CFA data
                     // rgb values should be floating point number between 0 and 1
@@ -1145,7 +1145,7 @@ void RawImageSource::CA_correct_RT(const bool autoCA, const double cared, const
                     STC2VFU(rawData[row][col], LVFU(RawDataTmp[indx]));
                 }
 #endif
-                for(; col < width; col += 2, indx++) {
+                for(; col < width - (W & 1); col += 2, indx++) {
                     rawData[row][col] = RawDataTmp[indx];
                 }
             }
diff --git a/rtengine/amaze_demosaic_RT.cc b/rtengine/amaze_demosaic_RT.cc
index 3cb0ee8d..fdd51d92 100644
--- a/rtengine/amaze_demosaic_RT.cc
+++ b/rtengine/amaze_demosaic_RT.cc
@@ -223,13 +223,19 @@ SSEFUNCTION void RawImageSource::amaze_demosaic_RT(int winx, int winy, int winw,
                 // fill inner part
                 for (int rr = rrmin; rr < rrmax; rr++) {
                     int row = rr + top;
-
-                    for (int cc = ccmin; cc < ccmax; cc += 4) {
+                    int cc = ccmin;
+                    for (; cc < ccmax - 3; cc += 4) {
                         int indx1 = rr * ts + cc;
                         vfloat tempv = LVFU(rawData[row][cc + left]) / c65535v;
                         STVF(cfa[indx1], tempv );
                         STVF(rgbgreen[indx1], tempv );
                     }
+                    for (; cc < ccmax; ++cc) {
+                        int indx1 = rr * ts + cc;
+                        float temp = rawData[row][cc + left] / 65535.f;
+                        cfa[indx1] = temp;
+                        rgbgreen[indx1] = temp;
+                    }
                 }
 
                 //fill lower border
diff --git a/rtengine/demosaic_algos.cc b/rtengine/demosaic_algos.cc
index 88d36996..1677b785 100644
--- a/rtengine/demosaic_algos.cc
+++ b/rtengine/demosaic_algos.cc
@@ -2029,7 +2029,8 @@ SSEFUNCTION void RawImageSource::igv_interpolate(int winw, int winh)
             for (; col < width; col++, indx += 2) {
                 dest1[indx >> 1] = CLIP(rawData[row][col]); //rawData = RT datas
                 col++;
-                dest2[indx >> 1] = CLIP(rawData[row][col]); //rawData = RT datas
+                if(col < width)
+                    dest2[indx >> 1] = CLIP(rawData[row][col]); //rawData = RT datas
             }
         }
 
```

**Comment by ghost** [comment] 2017-11-29 20:00
Great work, Ingo! It worked like a charm! :+1: :+1: 
Thank you so much for a quick resolution!

**Comment by heckflosse** [comment] 2017-11-29 20:06
Johan, thanks for testing. I hope it doesn't introduce artifacts in ca correction ;-)

**Comment by heckflosse** [comment] 2017-11-29 21:08
reopened because it's not yet committed

**Comment by ghost** [comment] 2017-11-29 21:09
Ah, sorry! :+1:

**Closed as completed** 2017-11-29 22:07 UTC
Labels: type: bug, priority: critical
