### ISSUE TITLE
Race when using same dcp profile with different settings

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3304] opened 2016-05-23 07:35 UTC
With the latest build I started seeing that thumbnails sometimes look undeveloped (settings not fully aplied) and/or have a clearly visible "box" inside them that looks like it uses different settings or is unprocessed.

![partial_thumbnails](https://cloud.githubusercontent.com/assets/10639257/15463297/afb72fde-20c8-11e6-907a-4bad0926ae47.jpg)

Opening up (in edit mode) the image with problematic thumbnail usually corrects it. This makes me think RT didn't have enough time to generate the thumbnail the first time. I didn't close the program (and it didn't crash) so that's not the reason for it.

All of my images had film simulation enabled.

Win 8.1, 64bit, 8GB ram
Fuji X-Pro1 X-trans files
 
Branch: master
Version: 4.2.862
Changeset: 023e7d36956a0fefa7a0d99fc9e1316468eff5f7

**Comment by Beep6581** [comment] 2016-05-23 08:15
I've seen these artifacts for months. They only affect the thumbs, I've never seen that in the main preview nor in the processed output.

```
x11-libs/cairo-1.14.2
dev-cpp/cairomm-1.12.0-r1
Branch: gtk3
Version: 4.2.1005
Changeset: 20fc105cf8494b58fcf55538f00d12707f5cd70d
Compiler: cc 5.3.0
Processor: Intel(R)\ Core(TM)\ i7\ CPU\ Q\ 820\ @\ 1.73GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Floessie** [comment] 2016-05-25 09:17
In #3154 I wrote:

> An anomaly I see here is when entering a directory with only the two RAFs from pi99y, whose thumbnails where not yet cached, and (quickly) selecting the second image, I have both thumbnails on top of the editor view, but the first one (with the window) has only half its width! Switching to filebrowser and back repairs that.

I had a look at it, and there is a race between `Thumbnail::_generateThumbnailImage()` and `Thumbnail::getThumbnailSize()`. The first sets `tw` to -1 while loading, the latter takes this into account in `w = tw_ * h / th_` which results in `w` returning as `0` (usually).

This little patch fixes it and adds a debug message for reproduction:
```patch
diff --git a/rtgui/thumbnail.cc b/rtgui/thumbnail.cc
index 673c49e..3f2345e 100644
--- a/rtgui/thumbnail.cc
+++ b/rtgui/thumbnail.cc
@@ -499,6 +499,8 @@ void Thumbnail::decreaseRef ()
 
 void Thumbnail::getThumbnailSize (int &w, int &h, const rtengine::procparams::ProcParams *pparams)
 {
+    MyMutex::MyLock lock(mutex);
+
     int tw_ = tw;
     int th_ = th;
     float imgRatio_ = imgRatio;
@@ -533,6 +535,17 @@ void Thumbnail::getThumbnailSize (int &w, int &h, const rtengine::procparams::Pr
     } else {
         w = tw_ * h / th_;
     }
+
+    printf(
+        "%s: pparams = %p, h = %d, tw = %d, th = %d, imgRatio = %f, w = %d\n",
+        fname.c_str(),
+        pparams,
+        h,
+        tw_,
+        th_,
+        imgRatio_,
+        w
+    );
 }
 
 void Thumbnail::getFinalSize (const rtengine::procparams::ProcParams& pparams, int& w, int& h)
```

This might or might not be related to @pi99y's problems, but may be a hint as to where things go wrong.

HTH,
Flössie

**Comment by Floessie** [comment] 2016-05-25 09:35
@Beep6581 While the `rtgui::Thumbnail` interface is mostly modeled after the [Monitor](https://en.wikipedia.org/wiki/Monitor_%28synchronization%29) pattern, a handfull of methods isn't. Some may have been considered to be too trivial for synchronization, some may have been forgotten in the header file. Fact is, there are concurrent accesses that need to be synchronized, even if they only return a `bool`.

**Comment by heckflosse** [comment] 2016-05-25 21:42
@Floessie @Beep6581 I never ran into this issue but the patch from Floessie and his explanation looks good. @Beep6581 Can you include it in your test of rgbcurvespeedup branch, please?

Ingo

**Comment by Beep6581** [comment] 2016-05-26 08:00
I will.

**Comment by heckflosse** [comment] 2016-06-04 12:23
@Floessie @Beep6581 
I just found the real reason for this behaviour. [Here](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/dcp.cc#L1763) we return a pointer to a dcpProfile.
And [here](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rtthumbnail.cc#L1049) we apply a state to this profile. That leads to conflicts in multithreaded processing when one thumb has for example dcp tone curve enabled and another thumb with same dcp profile has not.
I'll try to fix it.

Ingo

**Comment by Beep6581** [comment] 2016-06-04 12:49
@Floessie I discovered yesterday that DCP tone curves are no longer shown in the main preview, though they are shown in the thumbnails. Ingo and I spent some hours looking for the bug, but no luck yet.
Bisect lead me to this commit: https://github.com/Beep6581/RawTherapee/commit/5c14573be7cba3d191f759ed7042328ec0bf1273

I am guilty of not having tested the patch you provided above yet - I can do that now, but should I, or will there be a new patch?

**Comment by Floessie** [comment] 2016-06-04 13:17
Great, Ingo. Looking forward to your solution. Perhaps the Monitor pattern isn't needed anymore afterwards...

**Comment by heckflosse** [comment] 2016-06-04 13:30
[this patch](https://gist.github.com/heckflosse/7f28b73c50dd4c58a613a795e08a3a36) should fix the races.

**Comment by heckflosse** [comment] 2016-06-04 13:33
@Floessie Feel free to improve my fix. I made a quick and dirty one because this bug not only affects thumbs. It can also 'destroy' output of queue when queue is running in background while editing pictures or changing folder in file browser in foreground.

**Comment by Floessie** [comment] 2016-06-04 16:30
@heckflosse Oh my! Now I know, what to do this evening. ;) Your patch is fine, but `DCPStore` isn't. I'll style your patch a bit and introduce new bugs to `DCPStore` while I'm at it. :)

**Comment by heckflosse** [comment] 2016-06-04 17:21
@Floessie :+1:

**Comment by heckflosse** [comment] 2016-06-04 18:33
@Floessie There's also a speedup in the 35% to 40% range possible (without using SSE) for the dcp stuff. I'll open a new Issue for the speedup when the fix (which is more important) is pushed. Maybe we can make another optimizing fun session as with clut :)

Ingo

**Comment by Beep6581** [comment] 2016-06-04 19:27
I confirm that the bug is fixed in branch [fix-dcp-race-and-store](https://github.com/Beep6581/RawTherapee/compare/fix-dcp-race-and-store)

**Comment by heckflosse** [comment] 2016-06-04 20:45
@Beep6581 @Floessie I would prefer to merge [fix-dcp-race-and-store](https://github.com/Beep6581/RawTherapee/compare/fix-dcp-race-and-store) and then continue work because imho the bug (though undetected in code for long time) is critical. What do you think?

Ingo

**Comment by heckflosse** [comment] 2016-06-04 21:10
@Floessie Sorry, I didn't want to hurry. I just wanted to fix the bug during one week or so.
About the speedup: I'm really curious about the changes you detected vs. my detections. I guess together we can get more than 40% speedup for dcp, which is especially useful because dcp seems to get more important for good processing of raw files in rt.

Ingo

**Comment by Floessie** [comment] 2016-06-05 19:37
I'm approximately halfway through. Stay tuned (and please test, if something broke on the way)...

**Comment by heckflosse** [comment] 2016-06-05 20:59
@Floessie About the speedup: I almost reached double speed for DCPProfile::Apply
Now I'll start testing you branch

**Comment by heckflosse** [comment] 2016-06-05 23:02
@Floessie I tested: Seems to work fine :)

**Comment by Floessie** [comment] 2016-06-06 05:36
@heckflosse Thanks for testing, Ingo. It'll be a busy week for me, but I hope to be able to spend some time on the evenings cleaning `DCPProfile` up. Glad, you already made progress on the speedups. Those local functions (like `multiply3x3()` etc.) caught my eyes, but as long as I'm cleaning up, I won't waste a second on optimizations. :)

**Comment by Floessie** [comment] 2016-06-07 19:09
@heckflosse Now that I have my Eclipse Mars.2 up and running (that consumed yestereve, solution is [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=492071)), my refactoring gains speed. I'm not finished yet, but if you have the time, please check the lastest commit for regressions.

**Comment by heckflosse** [comment] 2016-06-08 21:02
@Floessie Didn't find the time today. I will check it tomorrow

**Comment by Floessie** [comment] 2016-06-09 17:18
@heckflosse Okay, that's as far as I'd go for the cleanup and moment. Let's merge (if all is okay on Windows and there are no regressions) and do the speedup in #3331.

**Comment by heckflosse** [comment] 2016-06-09 17:31
@Floessie Ok, I will build and test now

**Comment by heckflosse** [comment] 2016-06-09 17:45
@Floessie Builds fine and seems to work fine too. Also had a look at the code changes. Couldn't detect anything wrong (though it's a big diff, I could have missed some thing). Let's merge.
Should we keep the branch open to use it for the speedups too?

Ingo

**Comment by Beep6581** [comment] 2016-06-09 17:56
It would be cleaner to use one branch for bug fixes and then close it after merging, and have another branch for optimizations.

**Comment by heckflosse** [comment] 2016-06-09 18:04
@Beep6581 Ok

**Comment by Beep6581** [comment] 2016-06-09 18:19
I tested `fix-dcp-race-and-store`, the preview and saved images look fine. @Floessie could you merge into `master`? Then I'll merge `master` into `gtk3` and ask for new builds.

**Comment by Floessie** [comment] 2016-06-09 18:37
@Beep6581 It's done. Let's wait for the fallout. :)

@heckflosse Yeah, was a lot to change and even more could have been done if this wasn't tagged "Priority-Critical". I think, there will be more cleanups when we proceed with #3331.

**Closed** 2016-06-09 19:02 UTC
Labels: bug, Priority-Critical
