### ISSUE TITLE
Add screenshots to README.md

### ISSUE THREAD

**Issue by Korb** [Beep6581/RawTherapee#6642] opened 2022-12-12 11:23 UTC
It is very strange in the description of the application for working with graphics to not see anything but text.

**Comment by Entropy512** [comment] 2022-12-13 20:55
For the most part, the README of a git repo like this is intended for developers.

More importantly, it links to important resources that have plenty of screenshots, such as the main website at https://www.rawtherapee.com/ - which is also where most users are going to be starting.

Adding screenshots to the README just inflates the size of the git repo for developers.

**Comment by Korb** [comment] 2022-12-14 07:50
@Entropy512, I am a regular user, not a programmer. I found this app with the help of Google and from the description it looks like it might be what I need. There is a section with Releases where I can download the application itself. Why would I need to go somewhere else just to look at the screenshots? Why these complications? Just for a Github user to decide to save 10KB of space on their PC? Seriously? In 2022? When even on mobile devices, screenshots of all repositories connected to F-Droid are saved on the user's device. I do not understand. Or is this some kind of joke?

**Comment by Thanatomanic** [comment] 2022-12-14 10:14
@Korb Can you share a repository where you think the README is of excellent quality?

I also agree that a few kilobytes (megabytes) of images couldn't hurt.

**Comment by Entropy512** [comment] 2022-12-14 12:39
No, it is not a joke.

https://github.com/GNOME/gimp vs https://www.gimp.org/
https://gitlab.com/inkscape/inkscape vs https://inkscape.org/
https://github.com/KDE/kdenlive vs https://kdenlive.org/en/

It is common and standard practice for a github README to not be a duplicate of the website, and to merely redirect to the main website instead.

What does f-droid have to do with this?  And their github readme does not have screenshots either:
https://github.com/f-droid/fdroidclient vs https://f-droid.org/

A common app distributed on F-droid:
https://github.com/osmandapp/OsmAnd vs https://osmand.net/

You say you do not understand why there's a desire not to add unnecessary binaries to a repository:
https://vegeta2102.medium.com/why-you-should-not-push-binary-files-to-git-and-what-to-do-if-you-do-29f34692cef0
https://robinwinslow.uk/dont-ever-commit-binary-files-to-git

git sucks for binary file management, it's always considered bad practice to put binaries in git unless *absolutely* necessary.  It's not just about a few kilobytes of storage - it's about the long-term performance impacts binary blobs have on a repo.  If a screenshot is put into the repo - what happens when the software is updated and the screenshot is no longer representative of the software?  Check in another version?  Remember, the old image lives *forever* in the repository now unless dangerous/risky pruning and filtering operations are performed on the entire repository's history, so now you have the old screenshot AND the new one taking up disk storage, taking up network bandwidth and CPU on every clone operation, (potentially even the CI system, although a shallow clone may work around that), etc.

As far as getting here via Google - the repository is the third result from Google, rawtherapee.com is the first...

**Comment by Beep6581** [comment] 2022-12-18 00:05
I understand how @Korb feels about landing here from a search engine as a normal user and not seeing screenshots. I get annoyed by that as well, when I land on some project's GitHub page and it has no website nor a screenshot in GitHub, so I can't immediately judge by the screenshot whether it's for me. However, as pointed out above, it is in fact very unusual to have screenshots in GitHub, and we do have a lot of links right on our main GitHub page - to a website full of screenshots, to detailed documentation, and to a forum.

:-1: for bloating the repo with screenshots.

But I wouldn't be against embedding a screenshot via an external link - see PR #6648

**Comment by Lawrence37** [comment] 2022-12-21 05:36
Completed in #6648

**Closed as completed by Lawrence37** 2022-12-21 05:36 UTC
