### ISSUE TITLE
Film simulation dropdown is not working.

### ISSUE THREAD

**Issue by ror6ax** [Beep6581/RawTherapee#4516] opened 2018-04-21 21:02 UTC
Running Fedora 26 and RT 5.2.

Film simulation dropdown works once, I can choose the profile, if gets applied. 

After that clicking won't affect the dropdown. Rest of RT seems to work fine after that, I can disable the film simulation. But effectively it means a restart every film simulation preset change.

**Comment by heckflosse** [comment] 2018-04-21 21:08
@ror6ax 
Can't reproduce on current RT 5.4

**Comment by aferrero2707** [comment] 2018-04-22 07:59
@ror6ax an easy way to test the latest 5.4 release on your system might be to download and run the corresponding appimage package, available from [here](https://github.com/Beep6581/RawTherapee/releases/download/nightly/RawTherapee-releases-5.4.AppImage).

Here are the simple steps to follow for running the appimage from the terminal:
* `wget https://github.com/Beep6581/RawTherapee/releases/download/nightly/RawTherapee-releases-5.4.AppImage`
* `chmod +x ./RawTherapee-releases-5.4.AppImage`
* `./RawTherapee-releases-5.4.AppImage`

No need to install additional dependencies, so you do not risk to mess up with your base system...

**Comment by Floessie** [comment] 2018-04-22 08:35
Seems to be a duplicate of #3967.

**Closed as completed** 2018-04-23 09:23 UTC

**Comment by ror6ax** [comment] 2018-04-23 09:43
Can't repoduce in 5.4. appimage either.

I think updating the version in Fedora official repo might be in order in such case.

Anyway, thanks for help and your work on RT!
