### ISSUE TITLE
Disable Tool "log-encoding" in Local Adjustments Fails, When Masc (L) Is Applied And Activated

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6459] opened 2022-04-18 09:50 UTC
Using the tool "log-encoding" under local adjustments works fine, but trying to switch it off or disable the corresponding spot, doesnt show any action.
Switching off the local adjustments will do the job.

**Steps to reproduce**

1. Go to Tab LA
2. create a spot, define it to whole image, add the tool log-encoding, 
3. click enhanced
4. create a mask (L)
5. move some sliders, to see some obvious changes, created by this tool
6. Click on "disable spot" or switch off "log-encoding" 
7. The changes are still there
8. Finally switch off the "local adjustments" will show the pic without the log-encoded adjustments

**Expected behavior**
Clicking "disable spot" or/and switch on/off the single tool should be available without affecting other tools and adjustments.

**Additional information**
I am working on Version: 5.8-3089-g274c99e9b under windows.

Edit:
I also was able to reproduce this behaviour with the tool "color and light"

**Comment by Desmis** [comment] 2022-04-18 10:51
@marter001 

Thank you for testing :)

I confirme the bug :)

I think I have found....

I verify, and push a change

Thank you

Jacques

**Comment by Desmis** [comment] 2022-04-18 11:02
@marter001 

Done :)

jacques

**Comment by marter001** [comment] 2022-04-18 11:09
Such quickly, great and thanks a lot!

**Comment by Lawrence37** [comment] 2022-04-24 00:33
@marter001 Does the Color and Light tool work correctly now too? I was able to reproduce the issue with log encoding but not color and light.

**Comment by marter001** [comment] 2022-04-24 07:58
@Lawrence37 yes, now both are working fine. Thank you very much!

**Comment by marter001** [comment] 2022-04-24 08:15
@Lawrence37 i am sorry, to tell you, that LOG encoding now doesnt show any changes anymore. 
Whatever slider you move, there are no changes - but loading such a sidecar by a former version will show the changes very clearly.

**Comment by Desmis** [comment] 2022-04-24 10:46
@marter001 

Effectively when mask is disable, something is wrong....

the day I did this (a long time ago now) my mind must have been elsewhere

I will open a PR to be sure all is fine now :)

Jacques

**Comment by Desmis** [comment] 2022-04-27 06:25
https://discuss.pixls.us/t/latest-dev-branch-2022-04-24-log-encoding-not-doing-anything/30529/4
@marter001  @Lawrence37 

Jacques

**Comment by ghost** [comment] 2022-04-27 09:22
This seems to be fixed.

As already mentioned on pixls: Merged #6465 and tested it: All now works as expected.

**Comment by Desmis** [comment] 2022-04-27 09:33
@jade-nl 

Than you 


if nobody objects, I will merge the PR tomorrow :)

jacques

**Comment by Desmis** [comment] 2022-04-28 05:54
pull request merged :)

jacques

**Closed as completed** 2022-04-30 21:21 UTC
