### ISSUE TITLE
Exposure correction + Haze Removal results in wrong colours in dark images

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6532] opened 2022-07-23 13:16 UTC
**Short description**
Combining strong exposure correction and haze removal tool results in a strong colour shift in dark images

**Steps to reproduce**
1. Open an underexposed image (mine was a darkish room with a bright window. The camera adjusted itself to the bright window and not the dark interiour)
2. Increase the exposure correction (like +2-3 EV)
3. Haze Removal tool
4. Look at dark areas

**Observed behavior**
RT shifts the colour of dark areas
1) Default view in RT
![01](https://user-images.githubusercontent.com/10911084/180606547-76624dc9-f8db-4ea1-863b-f8e768c045cc.JPG)

2) +EV correction
![02 false](https://user-images.githubusercontent.com/10911084/180606532-e44ef754-8e03-498a-b487-500f47e90c68.JPG)

3) +Haze Removal
![03 true](https://user-images.githubusercontent.com/10911084/180606553-40b9894d-ec4f-4c7f-9315-3d9bb84210b2.JPG)

**Expected behavior**
RT does not shift the colours

**Additional information**
Since I use the haze removal for something it was (I guess) not designed to do I expect the error to be on my end here. Yet this behaviour will may also show up in a regular usecase.

Same results on my Windows and Linux machine.

Same results across different dev versions of RT

**Comment by chaimav** [comment] 2022-07-26 13:32
Haze removal is known to introduce a blue color cast under some conditions. 
Per [Rawpedia](http://rawpedia.rawtherapee.com/Haze_Removal) "Might remove color casts, but might also introduce a blue cast which can be corrected using other tools."
Slide the saturation slider to left to remove the color element of dehaze.

**Comment by Benitoite** [comment] 2022-07-26 21:23
It looks clipped on the low end... please post your RAW file per the instructions. 
- Exact Version of RT
- Name and Version of OS
- RAW Image file and PP3 sidecar

**Comment by gaaned92** [comment] 2022-07-27 10:38
As haze removal is a tool dedicated to fight the atmospheric haze, it is a surprising idea to try it on a tissue photo and after complain that it doesn't work! But perhaps it is a valid use case.

**Comment by rebio** [comment] 2022-08-14 09:06
> Haze removal is known to introduce a blue color cast under some conditions.

@chaimav If the tool can "introduce a blue cast" I wouldn't expect that it changes the very dark blues so much. I would rather expect a blue 'fog' over the entire image or the areas where the fog was present which could be changed using eg. the Color Toning tool.

> It looks clipped on the low end... please post your RAW file per the instructions.
> 
> * Exact Version of RT
> * Name and Version of OS
> * RAW Image file and PP3 sidecar

@Benitoite I can not post this RAW file here since it's an image taken at a wedding. I hope you understand why I will note share this photograph on the internet.
It should be rather simple to reproduce though. I just need a dark room, a bright window and something coloured dark blue. Once I have it I will share the image.

> As haze removal is a tool dedicated to fight the atmospheric haze, it is a surprising idea to try it on a tissue photo and after complain that it doesn't work! But perhaps it is a valid use case.

@gaaned92 Where do I "complain that it doesn't work". I opened this bug report since it could be one. If the devs think that it's not a bug they will close the report.

**Comment by Benitoite** [comment] 2022-11-23 08:09
@rebio No one has been convinced this is a bug.  Haze removal [(Dark Channel Prior)](https://projectsweb.cs.washington.edu/research/insects/CVPR2009/award/hazeremv_drkchnl.pdf) works well for haze removal in properly exposed images.

**Comment by Beep6581** [comment] 2022-11-23 14:18
No raw file provided and tool not used as intended so closing.

**Closed as completed by Beep6581** 2022-11-23 14:18 UTC
