### ISSUE TITLE
Perspective correction.

### ISSUE THREAD

**Issue by nmalykh** [Beep6581/RawTherapee#3516] opened 2016-11-27 17:26 UTC
When adjusting the perspective distortion, the picture moves in one direction and part of the picture is lost (it's easy to see when Auto-fill option is off). In my opinion this is not quite correct. Maybe there are possible adjustments on completion to perform a reverse shift for the restoration of the lost part of the picture?

**Comment by Beep6581** [comment] 2016-11-28 12:33
Duplicate of #198

**Closed by Beep6581** 2016-11-28 12:33 UTC
