### ISSUE TITLE
Debug message

### ISSUE THREAD

**Issue by DigitalReload** [Beep6581/RawTherapee#3217] opened 2016-03-14 03:14 UTC
(rawtherapee.exe:6040): Gtk-WARNING **: Failed to fetch network locations: Error opening directory 'C:\Program Files (x86)\RawTherapee-4.2.1\network:': No such file or directory

I have installed stable version and it failed to load. I then stalled the bug version and produced this report.

os Win 10

**Comment by Beep6581** [comment] 2016-03-14 18:34
It's just a warning, not an error and not a problem.
It's not caused by RawTherapee but by one of the programs RawTherapee uses, Gtk+ 3. Closing.

**Closed by Beep6581** 2016-03-14 18:34 UTC
