### ISSUE TITLE
Raw Therapee 5.0-r1 will not operate

### ISSUE THREAD

**Issue by mpeman** [Beep6581/RawTherapee#3850] opened 2017-04-29 19:20 UTC
My system is: Intel Pentium CPU 2020@2.90 GHZ-Installed Memory is 4.00 GB with 3.89 Usable-it is a 64-bit operating system, x64 based processor.

I have installed RT 5.0-r1-gtk3 and it will not run.  The 32-bit version will.  The 64-bit version of 4.2.1 works just fine.

RT 5 will open, but never operate.  I cannot click on anything, and nothing responds.  The window will not even close once clicked upon.  I have had this issue with all the latest releases of RT.  The newest one will not work, but the last prior release will!  I have always used the 64-bit version.  I ran the debug version of 5.0-r1  and all it stated was that it could not find the file "network".

I wish I could provide more info, but I simply do not have it.  Any help would be greatly appreciated.

**Comment by Beep6581** [comment] 2017-04-29 19:33
@mpeman which version of Windows?

1. Try disabling Drive A/Floppy/Legacy Drives in your BIOS, see #3450
2. Try waiting even 30 minutes - does RT become responsive after this time?

**Comment by mpeman** [comment] 2017-04-29 20:20
Yes.  I have left it on overnight, and it was still unresponsive.  My apologies...Windows 10.

**Comment by heckflosse** [comment] 2017-04-29 20:49
@mpeman Maybe good to post your issue [also here](https://discuss.pixls.us/c/software/rawtherapee)

**Comment by mpeman** [comment] 2017-04-29 20:51
Will do!

**Comment by Beep6581** [comment] 2017-04-29 23:00
@mpeman you could run RT and attach GDB to the running process. That should tell us what it's stuck doing.

**Comment by mpeman** [comment] 2017-04-29 23:14
Not being real heavy on computer knowledge I have no idea how to do that!  I also don't even know if I was looking for a floppy disc in the right place in my BIOS...if it even was my BIOS, I still don't know if I got into my BIOS correctly or at all.

**Comment by Beep6581** [comment] 2018-03-26 11:40
Closing due to lack of info and follow-ups, possibly duplicate of #3450 #3544

**Closed as completed** 2018-03-26 11:39 UTC
