### ISSUE TITLE
Zooming with zoom buttons problem (Gtk3)

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3225] opened 2016-03-18 19:12 UTC
RT4.2.880, Win 10 x64
Clicking on the zoom buttons (+/-) in the editor only shifts the image.
If you click into the image after zooming, it's jumping to the center and shows the correct size.
Also the other zoom buttons (fit to screen, 100%...) sometimes gives a strange result.

Sometimes, after zooming, the image looks pixellated.

**Comment by Beep6581** [comment] 2016-03-18 22:49
Duplicate of #3182

**Closed by Beep6581** 2016-03-18 22:49 UTC
