### ISSUE TITLE
Problem with Gtk3 3.20

### ISSUE THREAD

**Issue by GSib43** [Beep6581/RawTherapee#3251] opened 2016-04-10 15:11 UTC
I installed Msys2-64 on my new Win10-64 laptop to build RT as usually made on the old Win7-32.
The build went straightforward but at start RT was without the std Win10-style window and resize was impossible, the min/max button didn't work. The arrows of the folder tree were too large, the buttons over thumbnail too tall as the fields on the lateral areas, also not resizable in height. The version of S. Guyader runs without problem. The only difference I noted is that Guyader utilizes Gtk3 3.18 while I got, with the new install of Msys2, the version 3.20. I proved the substitution of my Gtk3 3.20 dlls with the ones of the Guyader's install file and my RT runs as ever save the arrows of the folder tree.
Can someone verify?
Thanks
Giorgio
[My AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/211813/My.AboutThisBuild.txt)
![cattura2_w](https://cloud.githubusercontent.com/assets/18380284/14411094/297ccd3e-ff3f-11e5-9b85-2c0665d7b07f.png)
![cattura4_w](https://cloud.githubusercontent.com/assets/18380284/14411103/4061c84c-ff3f-11e5-8c57-a224e4bd6d33.png)

**Comment by sguyader** [comment] 2016-04-10 17:11
@GSib43 I think the problem is simply that you didn't copy the required icons. I'm not at my computer and I don't remember which icons you need, but I think there's something about that on Rawpedia. Otherwise, simply install one of my windows builds, and copy the content of 'share/icons' into your RT installation directory.

**Comment by GSib43** [comment] 2016-04-10 18:52
As I made in win32, the icons are in the installation directory. And to find the difference I noted, I installed your last build from where I get the Gtk3 3.18 dlls to make my RT build run. I think there is something else!
Thank for your answer
Giorgio

**Comment by sguyader** [comment] 2016-04-10 19:00
So you have the ''Adwaita'' icons, and the ''Hicolor'' folder in ''{RT
installer directory}/share/icons''?

**Comment by GSib43** [comment] 2016-04-10 19:29
Yes, the icons are there!

**Comment by Hombre57** [comment] 2016-04-10 22:17
Gtk3.20 is a mess, it brokes everything ! It works fine with Gtk3.18.0, but is broken by 3.18.2 and above, as reported in issue #3250.

@Beep6581 What should we do ? Stick to Gtk3.18.0 or update everything to 3.20.0 ?

**Comment by Tilo15** [comment] 2016-04-11 04:38
As @Hombre57 suggested in #3250 I changed my RawTherapee theme to "RawTherapee" and it fixed my graph problems. Initially theme was set to nothing, the field was blank and I'm guessing the theme is never meant to be set to nothing. Changing this fixed the problem.

![screenshot from 2016-04-11 16-34-50](https://cloud.githubusercontent.com/assets/11801324/14416943/d314cb70-0003-11e6-8e9b-a9a8b0d049cc.png)
![screenshot from 2016-04-11 16-36-09](https://cloud.githubusercontent.com/assets/11801324/14416945/d768ccee-0003-11e6-8f9f-ba0e5024daaf.png)

Perhaps the next task is to make that the default. rawtherapee-gtk might have picked up some settings from previously installed rawtherapee which uses a different theme set.

**Comment by Tilo15** [comment] 2016-04-11 05:00
Just had a look through some other issues, and it looks like my issue could have been avoided if something like what was mentioned in #3238 was implemented

**Comment by GSib43** [comment] 2016-04-11 16:06
I think Hombre is right!
With libgtk-3.0.dll (version 3.18.6.0) and libgtkmm-3.0-1.dll (version ?) from the install file of Guyader my build, made with the latest MSys2-64 that installs libgtk-3.0 version 3.20.1, runs with no problem save the arrows of the folder tree.
So if you think to stay with 3.18 it is important to make this well known [in RawPedia-Windows (only ?)] because if someone upgrade MSys2 and uses the new dlls will have my problems.
I hope that will be possible to get back the little arrows!
Giorgio

**Comment by Beep6581** [comment] 2016-04-14 14:28
Hello

@Hombre57 
> Gtk3.20 is a mess, it brokes everything ! It works fine with Gtk3.18.0, but is broken by 3.18.2 and above, as reported in issue #3250. @Beep6581 What should we do ? Stick to Gtk3.18.0 or update everything to 3.20.0 ?

I use 3.18.7 (it's the only 3.18 I ever used) and RT looks fine! But I was informed/warned by the GTK+ devs that 3.20 will break themes. I can't test 3.20 yet so I can't advise, but if your 3.18.2 looks broken then perhaps the issue lies elsewhere? If you post a screenshot of RT in 3.20.* I can ask the GTK+ devs for advice, though I will be away for the weekend.

**Comment by GSib43** [comment] 2016-04-15 13:46
Here some screenshots of RT in 3.20. I hope they will be useful.
![cattura_gtk3seb1w](https://cloud.githubusercontent.com/assets/18380284/14562801/21fa63bc-031f-11e6-9c00-4e6938226151.jpg)
Image 1

![cattura_gtk3new1aw](https://cloud.githubusercontent.com/assets/18380284/14562824/3feb09a8-031f-11e6-8b2d-b9ea88629000.jpg)
Image 2

These screenshots were made using the same RT_Gtk3 exe, built with the latest Msys2_64 with Gtk3-3.20.1, installed on april 04 2016, with the TooWaBlue css and the same options file.
In the first image RT runs “normal” with the two dlls (libgtk-3-0 and libgtkmm-3.0-1) that are in the  build of S. Guyader; in the second the same RT build runs with the dlls that are in the new Msys2-64.
The window is not the standard Win10 windows; the button (1) doesn’t work, the icons (2) are too tall compared to those of the version running with Gtk3-3.18 (first image); the fields on the right (4) are also too tall and unpleasant.
The arrows (3) are the same in my RT version built with the new Msys2-64 (with the new Gtk3-3.20 and here visible): they are too large compared to those of the RT build by S. Guyader with the Msys2-64 with Gtk3-3.18.


 
![cattura_gtk3new2aw](https://cloud.githubusercontent.com/assets/18380284/14562855/63aa0718-031f-11e6-9464-71ce67951c54.jpg)
Image 3

![cattura_gtk3seb2w](https://cloud.githubusercontent.com/assets/18380284/14562912/9ca1963a-031f-11e6-8a87-40c3e444cde6.jpg)
Image 4

![cattura_gtk3new3aw](https://cloud.githubusercontent.com/assets/18380284/14562933/ae8149b8-031f-11e6-9812-491c2c7fbab3.jpg)
Image 5

Also here you can see the empty space on the left (5), the icons (6), the diagramm to tall (7), the behavior (?) of the curve in 8 and the dimension in height of the fields on the right (9) compared to those in image 4. Other example of the strange behavior on picture 6.

![cattura_gtk3new4aw](https://cloud.githubusercontent.com/assets/18380284/14562956/cfecc1ae-031f-11e6-9dff-1bf6ade1800d.jpg)
Image 6

If necessary I can send other images.
Buon lavoro e grazie
Giorgio

**Comment by Beep6581** [comment] 2016-04-17 21:06
It's clear that the problematic screenshots are not using our theme at all, so they are not demonstrating RT theme issues when using GTK+ 3.20.

**Comment by GSib43** [comment] 2016-04-18 12:17
Here the images made using RawTherapee.css: they presents almost the same problems.
All the images were made using the same RT_Gtk3 exe compiled with MSys2-64 with Gtk3-3.20 (see attached AboutThisBuild.txt).
In images 1,3 and 6 RT_Gtk3 runs with the Gtk3 (Gtk3-3.18) and Gtkmm libraries from the build of Guyader without problems save the arrows of the folder tree.
In images 2,4,5 and 7 RT_Gtk3 runs with the Gtk3 (Gtk3-3.20.1) and Gtkmm libraries from the mingw64\bin folder of MSys2_64 installation.
Buon lavoro
Giorgio
[AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/223708/AboutThisBuild.txt)
![cattura_gtk3seb14aw](https://cloud.githubusercontent.com/assets/18380284/14603596/f583135e-056e-11e6-8c9e-0ce52f108cfa.jpg)
Image 1
![cattura_gtk3new13aw](https://cloud.githubusercontent.com/assets/18380284/14603649/46feb120-056f-11e6-8fb6-8aabb4186940.jpg)
Image 2
![cattura_gtk3seb15aw](https://cloud.githubusercontent.com/assets/18380284/14603687/75d8867e-056f-11e6-9a42-13e3a7263e49.jpg)
Image 3
![cattura_gtk3new10aw](https://cloud.githubusercontent.com/assets/18380284/14603701/8cd2cf74-056f-11e6-93f4-b4abc8c6e185.jpg)
Image 4
![cattura_gtk3new12aw](https://cloud.githubusercontent.com/assets/18380284/14603790/152984c6-0570-11e6-9241-5b858791e3fc.jpg)
Image 5
![cattura_gtk3seb16aw](https://cloud.githubusercontent.com/assets/18380284/14603721/b497a6a6-056f-11e6-8a6d-5bef9d7135eb.jpg)
Image 6
![cattura_gtk3new11aw](https://cloud.githubusercontent.com/assets/18380284/14603734/c3bd5de2-056f-11e6-8688-ded390d73468.jpg)
Image 7

**Comment by GSib43** [comment] 2016-04-18 12:19
Closed accidentally

**Comment by Beep6581** [comment] 2016-04-18 12:47
@GSib43 these images (e.g. https://cloud.githubusercontent.com/assets/18380284/14603649/46feb120-056f-11e6-8fb6-8aabb4186940.jpg ) are not using our CSS file at all, so uploading them is pointless. We know about GTK+ 3.20, we will add good support for it once we can install it on our machines (I cannot do that yet), so no point uploading more irrelevant screenshots, just wait.

**Comment by GSib43** [comment] 2016-04-18 13:53
If I open the "preferences" I read "RawTherapee" for the theme!
But .. no problem, I wait
Giorgio

**Comment by TooWaBoo** [comment] 2016-04-21 09:46
@GSib43 
Can you upload (e.g. http://filebin.net/upload/) your compiled RT version with Gtk 3.20, so I can make some tests with my theme?

**Comment by GSib43** [comment] 2016-04-21 11:54
With pleasure!
http://filebin.net/cl1uue7vaj
In the zip the libgtk*.dllSeb are the dll, that I got from the Guyader's build and make my build (almost) normal running.
I hope you can find a solution
Giorgio

**Comment by TooWaBoo** [comment] 2016-04-21 11:57
@GSib43 

Thanks, but the link doesn't work.

**Comment by GSib43** [comment] 2016-04-21 12:10
I proved 30 seconds ago and all was ok

**Comment by TooWaBoo** [comment] 2016-04-21 12:23
It works now. I was using the Google DNS server. After switching back to my provider DNS server, I could connect to filebin.

**Comment by TooWaBoo** [comment] 2016-04-21 12:38
@GSib43 
I've downloaded the RT, but it won't runn. It quits immediately.

**Comment by GSib43** [comment] 2016-04-21 13:23
As you see from the images an my pc (Lenovo P50 Intel Xeon E3-1505M v5) runs with problems but runs...
I made the zip with 7Zip, perhaps it is better I make a 7z file. Uploaded:
http://filebin.net/cl1uue7vaj

**Comment by TooWaBoo** [comment] 2016-04-21 13:42
@GSib43 
No difference. I'm using a Gigabyte MB, CPU Intel I3 530 and Win 10 Home

**Comment by GSib43** [comment] 2016-04-21 14:10
I try to make a build with the generic processor target and then upload it.

**Comment by GSib43** [comment] 2016-04-21 14:31
Uploaded with the same name but with the new RT4.2.927Gtk3_G.exe.
http://filebin.net/cl1uue7vaj

**Comment by TooWaBoo** [comment] 2016-04-21 14:41
@GSib43 
Thanks, this version works.

**Comment by GSib43** [comment] 2016-04-24 20:32
Nothing interesting fronte tour testa?

**Comment by GSib43** [comment] 2016-04-24 20:34
Nothing interesting from your tests?

**Comment by TooWaBoo** [comment] 2016-04-24 21:01
I did some tests and it's crazy, everything has changed in Gtk 3.20. I have to build the theme from scratch. I will do this, when the developers make the decision to switch to Gtk3.20.
There are a lot of things, where I don't know right now how to adapt it to Gtk3.20.
Here is the test theme, at which I'm playing around. Only for evaluating.
[TooWaBlueGtk3.20.css.txt](https://github.com/Beep6581/RawTherapee/files/233657/TooWaBlueGtk3.20.css.txt)

**Comment by GSib43** [comment] 2016-04-25 08:37
Good work, yours. Many problems solved.
If it is not possible to get Gtk3-3.18 when installing MSys2, I think necessary the switch.
Thanks
Giorgio

**Comment by sguyader** [comment] 2016-04-28 13:22
Gtk 3.20 is starting to roll into more Linux distros. Yesterday Manjaro published new updates, including Gtk 3.20.

**Comment by TooWaBoo** [comment] 2016-04-28 21:01
@sguyader 
Gtk3.20 has a lot of changes, which require more object IDs and classes in the rtgui files.
e.g right now, it's not possible to set a background color of curves, because an object ID for the GtkDrawingArea doesn't exist anymore.

It also has a combobox bug. In Gtk3.18 long text where overflowing the box, in Gtk3.20 the min. width of the combobox is the size of the longest text. This makes Gtk3.20 useless, because the toolpanel needs half of the screen.

**Comment by Beep6581** [comment] 2016-09-23 21:29
Summary:
Gtk+ 3.20 was intended to break a lot of things, as it did.
"GTK+ 3.22 shall be as rock-stable (and hence "boring") as GTK+ 2"
Closing this issue, as there is no need to keep it open. If someone feels like supplying a patch for Gtk+ 3.20, then by all means. Personally, I will try to add support for 3.22 (as soon as Gentoo ships 3.22 packages), not sooner.

Also see https://blogs.gnome.org/desrt/2016/06/13/gtk-4-0-is-not-gtk-4/

**Closed by Beep6581** 2016-09-23 21:29 UTC
