### ISSUE TITLE
OM system (Olympus) OM-1 raw file support.

### ISSUE THREAD

**Issue by lucmparis** [Beep6581/RawTherapee#7024] opened 2024-04-01 21:32 UTC
Not a bug but....

**Comment by kmilos** [comment] 2024-04-02 05:26
...but duplicate of https://github.com/Beep6581/RawTherapee/issues/6620?

**Comment by Lawrence37** [comment] 2024-04-05 06:09
Hi @lucmparis, there is basic support for the OM-1 as of 5.10. If you want specific improvements, please let us know what kind.

**Closed as not planned by Lawrence37** 2024-04-05 06:09 UTC
Labels: scope: file format
