### ISSUE TITLE
raw therapee Mac problem CTRL click not working

### ISSUE THREAD

**Issue by blankester** [Beep6581/RawTherapee#4258] opened 2017-12-26 17:27 UTC
Hi there new user here, this looks like a great program.  I am pulling in hundreds of images for timelapse photography and I managed to save a picture profile I like but when I go to file browser and CTRL A to select all (fine) I then CTRL click to right click and use this profile on all the images to send to batch nothing happens on right click. I tried downloading vsn 5.3 more recent to see if this was fixed but still not working. Would sb be able to tell me if there is any way of 'right clicking' on a mac or if there is a way of me doing the same function without needing to right click? Any help much appreciated.

**Comment by Beep6581** [comment] 2017-12-26 17:50
Duplicate of #3510

@blankester please seek help in that issue.

**Closed as completed by Beep6581** 2017-12-26 17:50 UTC
