### ISSUE TITLE
JPEG XR (*.jxr) file format support

### ISSUE THREAD

**Issue by mrwonko** [Beep6581/RawTherapee#6612] opened 2022-11-20 10:42 UTC
When I play games in HDR and take screenshots using the GeForce overlay, they get saved as HDR .jxr files. I would like to convert these "raw" files to SDR using RawTherapee.

Currently, the options for working with the file format are severely limited. The best I've found is [brion/hdrfix](https://github.com/brion/hdrfix), a command line tool for converting .jxr to .jpg. I'm attaching a before-and-after sample from it: [jxr-and-jpg-sample.zip](https://github.com/Beep6581/RawTherapee/files/10049400/jxr-and-jpg-sample.zip)

Since these images don't originate from a real camera, I can't provide images of different ISO levels or of a white frame, but let me know if you want additional screenshots.

**Comment by Beep6581** [comment] 2022-11-20 15:04
Workaround: convert JPEG XR to floating-point 16-bit or 32-bit TIFF or PNG.

**Comment by Entropy512** [comment] 2022-11-21 15:16
> Workaround: convert JPEG XR to floating-point 16-bit or 32-bit TIFF or PNG.

int16 might also work, especially if the files are nonlinearly encoded (for example, Rec2020+PQ 10-bit) - in which case the TIFF would ideally have a matching ICC profile

I'll try to take a look at these files after the Thanksgiving holiday here in the US to at least provide some additional details on an appropriate workaround (e.g. conversion to either linear float or properly ICC-tagged TIFF)

**Comment by ValZapod** [comment] 2022-11-28 20:31
>Currently, the options for working with the file format are severely limited

In fact there is only one HDR capable app:  https://github.com/13thsymphony/HDRImageViewer
https://www.microsoft.com/store/apps/9PGN3NWPBWL9

>command line tool for converting .jxr to .jpg

JPEG does not support HDR.

**Comment by Beep6581** [comment] 2022-11-28 20:39
ImageMagick can be used to perform the conversion.

**Comment by ValZapod** [comment] 2022-11-28 20:40
> ImageMagick can be used to perform the conversion.

Does it support HDR displays? Nope.

**Comment by Beep6581** [comment] 2022-11-28 21:01
Does a microwave oven support kitchens painted yellow?

Let's keep this issue focused on RT's support of JPEG XR.

**Comment by Entropy512** [comment] 2022-11-28 21:18
ImageMagick's convert tool does not support displays at all.  It just converts from one format to another - the hdrfix link states, for JXR files: "as taken with Nvidia's GeForce Experience game overlay capture utility which saves a JPEG XR in 32-bit float precision scRGB"

While it is in theory possible to combine float16 or float32 with a nonlinear transfer function such as PQ, this is *extremely* uncommon.  Converting float32 JXR to float32 TIF should work.  (Although I do recall that sometimes IM's internal pipeline is only int16 depending on how it is compiled???  That could be a problem...)

Due to the holiday in the US, I haven't had time to take a look at the samples.

@Beep6581 At least on Ubuntu 22.04, ImageMagick *cannot* convert these images:
```
adodd@censoredmachinename:~/Downloads/tmp$ identify Destiny\ 2\ Screenshot\ 2022.11.16\ -\ 20.30.59.86.jxr
*** ERROR: Unsupported format in JPEG XR ***
identify-im6.q16: unable to open image `/tmp/magick-jO0wM7zGEu-JD0WstHLy9CK4KSESQWcc': No such file or directory @ error/blob.c/OpenBlob/2924.
identify-im6.q16: unable to open file `/tmp/magick-jO0wM7zGEu-JD0WstHLy9CK4KSESQWcc': No such file or directory @ error/constitute.c/ReadImage/614.
```

A TIF converted with JxrDecApp kinda sorta works, but the white balance is kinda funky.  Way too much blue.  Even if I override the color profile with a rec2020 ICC profile generated with the ICC profile generator, color is way off.

@ValZapod can you take a screenshot in a saner location like the Tower courtyard or the Cosmodrome?  Colors are so screwy in all of the Eternity/Prophecy/Nine-themed locations I can't tell what's right or what's wrong.  Bonus if you equip Sweet Business because I know what that looks like.

**Comment by ValZapod** [comment] 2022-11-28 21:40
>this is extremely uncommon

Tell that to Camera Raw 15 on MacOS that added support for HDR part of RAW photos.

**Comment by Entropy512** [comment] 2022-11-28 21:44
> Tell that to Camera Raw 15 on MacOS that added support for HDR part of RAW photos.

That is completely irrelevant to combining float32 with a nonstandard transfer function.  And does not provide any proof that you've actually encountered an image that combined float32 with a nonlinear transfer function.  Have an example of a DNG that is float32 and has a LinearizationTable present???  I'm not even sure if DNG allows that!

After all, JXR files are not RAW images, and many would argue that int16 is enough to meet the requirements of HDR.  For those that would argue otherwise, I know from experience (as does @Beep6581 ) that RT supports float16, float24, and float32.

Anyway, it *looks* like this might be linear float32.  Fortunately for you, I play D2.  Unfortunately for you, your provided screenshot is from a location in the game I visit so rarely I don't know what it SHOULD look like.  I can get the file to load but it looks...  wrong...

**Comment by ValZapod** [comment] 2022-11-28 21:47
>Fortunately for you, I play D2. Unfortunately for you, your provided screenshot is from a location in the game I visit so rarely

Open wide-gamut.com, make sure DCI-P3 (D65 that is) or BT.2020 are available. After that use WCG images https://www.wide-gamut.com/images to test Alt-F1 of Alt-Z of Nvidia. You need HDR on in windows 11.

**Comment by Entropy512** [comment] 2022-11-28 23:13
You'll need to take the screenshots yourself, while I play D2 and know what it looks like on an HDR display, I don't play on Windows and PS5 screenshots are in a different format.  EDIT:  Oh wait, I didn't realize you're not even the dude who posted this issue and the example screenshots.  So you've just been obnoxiously useless here.

https://github.com/brion/hdrfix implies it is scRGB - https://en.wikipedia.org/wiki/ScRGB - Generating an ICC profile with a linear transfer function (gamma=1.0) and sRGB primaries appears to allow load properly after converting to float32 TIF using JxrDecApp (part of jxr-tools).  Input profile in color management needs to be set to Custom with an sRGB linear ICC profile.  (As a side note, @Beep6581 , on Linux the default output of the ICC creator tool is in $HOME/.config, which is really hard to navigate to from the "Custom" input profile selecter since .config is normally a hidden directory...)  The player in front of you seems a bit washed out which is unusual, but maybe it's just environmental snow in your location ingame, which is why I'd prefer a screenshot in a less funky environment.

![image](https://user-images.githubusercontent.com/193570/204400238-9bd3711f-14b9-44a8-82a8-0ad409b83c46.png)

**Comment by mrwonko** [comment] 2022-11-29 08:22
> can you take a screenshot in a saner location like the Tower courtyard or the Cosmodrome?

I'll get on that later today.

**Comment by Thanatomanic** [comment] 2022-11-29 08:33
A reminder to everyone to keep things civil _and_ on topic. Discussion about workarounds or other ways to process images are better suited to our support forum on Pixls.us.

**Comment by Entropy512** [comment] 2022-11-29 14:24
For some of the more niche file formats, it may be beneficial to document the workaround in rawpedia.

While in theory JXR support could be added directly to RT, it's such a niche use case that I'm not sure if it is worth the effort, especially since there are fairly simple workarounds (convert to TIFF).  I may spend a little time on a conversion tool that will be a little better than JxrDecApp as a side project - helps me learn to use the Python tifffile module and would allow generating a compressed TIFF with embedded ICC profile.

Although in futzing with this, I hit more examples where the ICC profile path handling UI could probably use some improvement, but that's a separate issue.

Edit:  Wow.  I'm unimpressed by JXR - zlib-compressed TIFF with the floating point predictor is SMALLER than the original image!

Edit 2:
```
#!/usr/bin/env python3

import imagecodecs
import tifffile
import sys
import os
import pyexiv2
import base64

#Base64 encoded linear (gamma=1.0) sRGB ICC profile generated by RT's ICC profile generator
#Anyone know of a decent way to create an ICC profile from Python?  Nearly everything I've seen is
#read-only
icc_profile = base64.b64decode('AAACsGxjbXMEMAAAbW50clJHQiBYWVogB+YACwAdAA4ALAAbYWNzcEFQUEwAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAMZGVzYwAAARQAAAA8Y3BydAAAAVAAAABad3RwdAAAAawAAAAUY2hh\
ZAAAAcAAAAAsclhZWgAAAewAAAAUYlhZWgAAAgAAAAAUZ1hZWgAAAhQAAAAUclRSQwAAAigAAAAQ\
Z1RSQwAAAjgAAAAQYlRSQwAAAkgAAAAQY2hybQAAAlgAAAAkZG1uZAAAAnwAAAAybWx1YwAAAAAA\
AAABAAAADGVuVVMAAAAgAAAAHABzAFIARwBCAEwAaQBuAGUAYQByAF8AZwA9ADEALgAwbWx1YwAA\
AAAAAAABAAAADGVuVVMAAAA+AAAAHABDAG8AcAB5AHIAaQBnAGgAdAAgAFIAYQB3AFQAaABlAHIA\
YQBwAGUAZQAgADIAMAAyADEALAAgAEMAQwAwAABYWVogAAAAAAAA9tYAAQAAAADTLXNmMzIAAAAA\
AAEMQgAABd7///MlAAAHkwAA/ZD///uh///9ogAAA9wAAMBuWFlaIAAAAAAAAG+gAAA49QAAA5BY\
WVogAAAAAAAAJJ8AAA+EAAC2w1hZWiAAAAAAAABilwAAt4cAABjZcGFyYQAAAAAAAAAAAAEAAHBh\
cmEAAAAAAAAAAAABAABwYXJhAAAAAAAAAAAAAQAAY2hybQAAAAAAAwAAAACj1wAAVHsAAEzNAACZ\
mgAAJmYAAA9cbWx1YwAAAAAAAAABAAAADGVuVVMAAAAWAAAAHABSAGEAdwBUAGgAZQByAGEAcABl\
AGUAAA==')

if len(sys.argv) < 2:
    print("Need to provide filename!")
    exit(0)

hdrimage = imagecodecs.imread(sys.argv[1])

#Discard alpha channel
hdrimage = hdrimage[:,:,0:3]

filebase = os.path.splitext(sys.argv[1])[0]
tifname = filebase + '.tif'

with tifffile.TiffWriter(tifname) as tif:
    tif.write(hdrimage,
            photometric='rgb',
            compression='zlib',
            predictor=True)

with pyexiv2.Image(tifname) as exiv_image:
    exiv_image.modify_icc(icc_profile)
```

**Comment by cgohlke** [comment] 2022-11-29 17:36
> Anyone know of a decent way to create an ICC profile from Python?

Did you try the [`imagecodecs.cms_profile`](https://github.com/cgohlke/imagecodecs/blob/f930e75cc559f41558d2503bf62055a82b6e5950/imagecodecs/_cms.pyx#L280) function? Not sure it is decent enough. Feedback is welcome.

> `exiv_image.modify_icc(icc_profile)`

Is this necessary? Tifffile does not directly support the ICC profile tag, but the [`extratags`](https://github.com/cgohlke/tifffile/blob/a73812e98f58b068a590de862ed547820fd332ad/tifffile/tifffile.py#L1769-L1781) argument should work, no?

**Comment by mrwonko** [comment] 2022-11-29 18:32
~Ah, the zlib compression explains why zipping the result does not compress it further.~ _(I misread that.)_ [Here](https://filebin.net/v0u8e8uiulgvwdhi) are some more screenshots.

**Comment by Entropy512** [comment] 2022-11-29 18:32
@cgohlke Thanks for the cms_profile pointer - will take a look.  (Edit 2:  Looks like it should do the trick.  Won't be able to futz with this until later in the week though.)

as far as extratags, I may have been misled by "IPTC, ICC, and XMP metadata are not implemented" - but from the sounds of it, adding a pre-cooked bytestream is possible?

Edit:  Yup, adding
`extratags=[(34675, tifffile.DATATYPE.BYTE, len(icc_profile), icc_profile)]`
did the trick

**Comment by Entropy512** [comment] 2022-11-30 01:36
@mrwonko unsurprisingly, anything already compressed (such as JXR) does not compress well - not just the zlib-compressed TIFs from my conversion script.  I'm actually quite surprised at how large the JXRs are compared to a TIF compressed with a more primitive lossless codec (although admittedly, the lossy JXR codec likely alters the entropy of the decoded image such that it compresses better with even radically different lossless approaches...)

You've confirmed that scRGB is indeed the colorspace, while the easiest location to test (tower courtyard) isn't there, you've got plenty of "neutral white/gray BRRRRRRRRRRRTTTTTTTT" in those screenshots including the EDZ loading zone, and I'm positive that my current script will preprocess/convert screenshots to work fairly well in RT (Due to the nature of HDR, you need some fairly aggressive tonemapping, such as activating the second tone curve and turning on DRC, for it to look decent on an SDR display).  The script depends on a few small tweaks to the dependency libraries, I've submitted PRs to @cgohlke 's modules for those tweaks.

![image](https://user-images.githubusercontent.com/193570/204686045-910ff135-ba5e-4d4b-aba8-9a4c9e312106.png)

**Comment by mrwonko** [comment] 2022-11-30 14:35
I had attempted to take a tower screenshot, but ran into unrelated technical difficulties (the screenshot key also opens the character screen, and in this case I ended up with a black screenshot, maybe because I was emoting at the time and that somehow lowers the delay before opening the character screen?) and hoped the remaining screenshots would be sufficient. Looks like I was right. :)

Can you link your PRs so I can keep track?

Thanks for the help!

**Comment by Entropy512** [comment] 2022-11-30 15:47
https://github.com/cgohlke/imagecodecs/pull/53 - as an interim, the script I published above should work for your purposes, by using a pregenerated linear sRGB ICC profile instead of generating it on the fly like the current version of the script.

**Comment by Entropy512** [comment] 2022-11-30 23:47
Per @Thanatomanic , discussion of workarounds/preprocessing should be on pixls, so:
https://discuss.pixls.us/t/python-image-conversion-scripts-intended-primarily-for-rawtherapee-input-but-useful-otherwise/33865

**Comment by ValZapod** [comment] 2022-12-14 17:43
Adobe just added HDR on windows 11 in Camera RAW 15.1. It works insanely well in SDR and HDR for RAW imaged. Nice. And it appears to have all the right features.

Will add screenshots of Draw SDR as greyscale.

**Comment by Entropy512** [comment] 2022-12-14 18:14
Camera RAW is offtopic here.  Especially since the HDR stuff is MacOS-only - RT is a cross platform application with three different operating systems to support.

HDR display support isn't going to happen until Wayland color management improves significantly, and likely never going to happen for legacy X.

**Comment by ValZapod** [comment] 2022-12-14 18:16
HDR stuff is now not MacOS only. It works on windows 11.

**Comment by Entropy512** [comment] 2022-12-14 18:50
Perhaps you should actually read what you linked.

For example: https://github.com/mpv-player/mpv/issues/8219 - "I know that (currently) wayland and Xorg do not have any support for HDR passthrough, so this issue is not about full HDR support on linux, just for DRM." - in short, fullscreen video playback only.  Support isn't even merged in MPV, so your assertion that it allows HDR output on Linux is a lie.  The issue in question is still open/unresolved, and related pull requests, such as https://github.com/mpv-player/mpv/pull/8456, https://github.com/mpv-player/mpv/pull/8648, or https://github.com/mpv-player/mpv/pull/10762 are not yet merged.

And why are you ranting about ICC?  I NEVER said anything about ICC support.  There's more to color management than ICC profiles, and the aspects of Wayland color management needed to support HDR *ARE NOT IMPLEMENTED YET* so there is no way for a GUI application to do anything HDR in any way, shape, or form.

It is also, AGAIN, completely and totally irrelevant and offtopic with respect to support for floating point JXL files.

**Comment by ValZapod** [comment] 2022-12-14 19:08
>open/unresolved, and related pull requests, such as https://github.com/mpv-player/mpv/pull/8456, https://github.com/mpv-player/mpv/pull/8648, or https://github.com/mpv-player/mpv/pull/10762 are not yet merged.

Those pull requests are about HDR10, as in static metadata, not HDR. HDR works already. https://github.com/mpv-player/mpv/pull/9421#issuecomment-962700737

See, DRM works. DRM is a linux thing, not windows.

**Comment by Thanatomanic** [comment] 2022-12-14 19:44
Okay, this is going off-topic yet again. I'm going to close and lock this issue.

While JXR support and support for working with HDR images could be very nice for RT's future, please remember that we are not a general purpose image editing (or tone-mapping) application. We primarily focus on the processing of photographic raw files (Bayered/X-Trans). Anything else will get less traction. And considering the low number of contributors to RT in general, here 'less' probably means 'nothing' in the foreseeable future. Sorry.

**Closed as not planned by Thanatomanic** 2022-12-14 19:44 UTC
Labels: scope: file format, type: feature
