### ISSUE TITLE
Edit window - calculate right panel width from right window border

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2683] opened 2015-08-11 20:39 UTC
Originally reported on Google Code with ID 2701

```
Branch: default
Version: 4.2.74
Changeset: 34f74fa6e787
Compiler: gcc 4.8.1
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.22.0
Build type: Release
Build flags: -m64 -mwin32 -mthreads -msse -msse2 -mtune=generic -fopenmp -Werror=unknown-pragmas
-mwindows -DNDEBUG -O3 -Wno-aggressive-loop-optimizations
Link flags: -mwin32 -mthreads -static-libgcc  -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

In short: Right panel width should be saved as distance from the right window border,
not from the left border. 

I am working in the "Multiple Editor Tabs In Own Window" (MEOW) Mode. I have two displays
with different resolutions (notebook w=768px, monitor w=1080px). Usually I have the
edit window open on the monitor and adjust the right panel width to a comfortable size.
But sometimes I just take the notebook somewhere. What happens: The right panel is
a thin line when I open the edit window on the notebook display as RT assumes there
a 322px more to work with, and I need to adjust the size. When I come back to the office,
the same thing in reverse: the panel takes up a huge portion of the monitor window
as the panel is now 322px too wide. RT should remember how wide the panel from the
right window border was.
```

Reported by `stephan.thuermer` on 2015-03-02 04:24:37

**Comment by Hombre57** [comment] 2017-07-15 14:23
Now a duplicate of issue #3957. Closing.

**Closed by Hombre57** 2017-07-15 14:23 UTC
Labels: enhancement
