### ISSUE TITLE
5.2 in macOS 10.11.6 issues - font too large, preferences not saved

### ISSUE THREAD

**Issue by FritzBo** [Beep6581/RawTherapee#3984] opened 2017-07-24 16:16 UTC
### Brief description

When starting a freshly installed RT 5.2 release for Mac OS from the website, the fonts are to much too large and cannot be changed.

### Description

The preference menu says that the font type is "none" with size 12. Changing the font size and type works. Changing only the size (leaving font type to be "none") results in a crash. With the applied changes, the app works, but the new preferences are not saved. Starting the app again I end up with the same much too large font.

The RT 5.1 release does not have this issue.

### Download location

http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.9_64_5.2.zip

### Exact steps to reproduce the error

Just start RawTherapee.

### Screenshot of the error

http://imgur.com/a/MeiUV

### Information regarding my OS

OS: Mac OS 10.11.6
CPU: 2,6 GHz Intel Core i5
Memory: 16 GB 1600 MHz DDR3

### Version information

Version: 5.2
Branch: 5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -O3 -mmacosx-version-min=10.9 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags: -arch x86_64 -mmacosx-version-min=10.9 -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment] 2017-07-24 16:39
@FritzBo thanks for the good report. Do you get any errors in the console (run RT from the console when testing) or popups when you click "Ok" to save Preferences?

**Comment by Benitoite** [comment] 2017-07-24 20:16
Works fine on my clean 10.11.6 installation. Not crashing when selecting font size and not failing to save options. @fritzBo thx for reporting the font error; you are not the first: https://github.com/Beep6581/RawTherapee/issues/3966#issuecomment-314979450

**Comment by Benitoite** [comment] 2017-07-25 07:19
Running a debug build (fresh run with cache and config dirs deleted):

```
lldb /applications/rawtherapee-debug.app/contents/macos/rawtherapee-bin
(lldb) target create "/applications/rawtherapee-debug.app/contents/macos/rawtherapee-bin"
Current executable set to '/applications/rawtherapee-debug.app/contents/macos/rawtherapee-bin' (x86_64).
(lldb) r
Process 21845 launched: '/applications/rawtherapee-debug.app/contents/macos/rawtherapee-bin' (x86_64)

(rawtherapee-bin:21845): GLib-GObject-WARNING **: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

(rawtherapee-bin:21845): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee-bin:21845): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee-bin:21845): Gtk-WARNING **: Could not find the icon 'inode-directory'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
Error: "<data>:1:17Expected a string."

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node marks owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node mark owner GtkScale)

(rawtherapee-bin:21845): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node indicator owner GtkScale)
Process 21845 exited with status = 0 (0x00000000) 
(lldb) bt
error: invalid thread
(lldb) q
```
 The `Error: "<data>:1:17Expected a string."` happened when I changed the font size and hit Select without selecting a font name. Did not crash RT however; I was able to exit normally.

```
Version: 5.2-12-gb4899f24
Branch: dev
Commit: b4899f24
Commit date: 2017-07-24
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.22.1
Build type: debug
Build flags: -arch x86_64 -O3 -mmacosx-version-min=10.9 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g
Link flags: -arch x86_64 -mmacosx-version-min=10.9 -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```

**Comment by Benitoite** [comment] 2017-07-26 07:51
After being in the state of font=None and changing only the font size (from 12 to 13) the config/options file shows:
```
FontFamily=.AppleSystemUIFont
FontSize=13
```

**Comment by Benitoite** [comment] 2017-07-26 09:09
I was trying to troubleshoot the font=None issue, and noticed different font syntax between the `repo-rt/tools/osx/options.osx `and the `˜/Library/Application Support/RawTherapee/config/options`
We may more explicitly set the font selectors like: 
```
diff --git a/rtdata/options/options.osx b/rtdata/options/options.osx
index 4d35255c..54beadb2 100644
--- a/rtdata/options/options.osx
+++ b/rtdata/options/options.osx
@@ -24,7 +24,8 @@ PathTemplate=%p1/converted/%f
 CustomProfileBuilder=
 
 [GUI]
-Font=Sans 12
+FontFamily=Arial Regular
+FontSize=12
 
 # Set here an absolute or relative path (to the rawtherapee.exe file) to the directory containing your own profiles.
 # If MultiUser=true, each user will have their own "options" file, and can set a common or different absolu path

```
As a result, the font did not show up as "None" on a fresh run.  No matter what I put in front of Font=, it never took. Once I separated the FontFamily and FontSize it seemed to take Arial Regular (a random font available in MacOS 10.9 and up). I'm curious what effect this would have on a high resolution screen. 

@FritzBo and/or @kapiliitr Can you try deleting your options file and trying this build?   

The options file is located within the hidden Library folder in your home directory.
Delete the options file in Terminal or go to it by typing Command-Shift G, then enter:
   /Users/_username_/Library/Application Support/RawTherapee/config
,  substituting your username where it says _username_.

**Comment by kapiliitr** [comment] 2017-07-27 04:56
By default, the Font was `Arial Regular` and Font size was 12 with the new build and deleting the options file. However that was too big I think.
<img width="1202" alt="screen shot 2017-07-26 at 9 53 16 pm" src="https://user-images.githubusercontent.com/1621360/28654975-3e43d9b0-724d-11e7-9007-5e2cf6f6c98e.png">

**Comment by Benitoite** [comment] 2017-07-27 06:17
Many thx @kapiliitr, it is as I expected. What is the size and resolution of your screen? 12 is a good size on my mac, but apparently not on every mac. Are you able to change to a suitable size to work with RT?

@Hombre57 wondering if you had any further thoughts on the _font-too-large-on-certain-macs_ issue.

**Comment by Benitoite** [comment] 2017-07-27 06:26
Might it be possible there is uncontrolled scaling going on. Is there a need to `export GDK_DPI_SCALE=0.5` or something like that if a Hi Dots Per Inch display is detected and the UI is scaled up per https://wiki.archlinux.org/index.php/HiDPI#GDK_3_.28GTK.2B_3.29

**Comment by kapiliitr** [comment] 2017-07-27 06:27
Font size 6 works well for me.

**Comment by kapiliitr** [comment] 2017-07-27 06:30
My mac has a 15.4 inch screen with 2880 x 1800 resolution which is the
default I think.

**Comment by Benitoite** [comment] 2017-07-27 07:00
@kapiliitr if that is the case, then I suspect 2x scaling is happening for your Retina display. 

It seems the quartz backend on mac gtk+3 does not accept the x11 environment variables like GDK_DPI_SCALE=0.5. from https://developer.gnome.org/gtk3/stable/gtk-x11.html
I tried setting these in the executable loader but they have no effect.

**Comment by Beep6581** [comment] 2017-07-27 13:22
> Font size was 12 with the new build and deleting the options file. However that was too big I think

There is no one-size-fits-all. The size on screen depends most importantly on the DPI value used by your OS (72, 96, 120, other), your screen's physical size, the resolution, and desktop scaling (`GDK_SCALE`, `GDK_DPI_SCALE`, other).

**Comment by kapiliitr** [comment] 2017-07-27 13:32
Sure, I understand that and I am not going to hold down on this issue.
However, when I first installed RT 5.1, the default font/font size were
perfect. However, the large font issue started happening with the newer
build I tried in
https://github.com/Beep6581/RawTherapee/issues/3966#issuecomment-314357754.
Could something have changed between 5.1 and that build that affected the
fonts? I don't have that build anymore and it has been removed from the
comment as well but I think it was 5.1-134.

**Comment by Beep6581** [comment] 2017-07-27 13:41
@Benitoite let me know if there is a need to update the macOS build on our website.

**Comment by Benitoite** [comment] 2017-07-27 15:02
@Beep6581 Is there a way to obtain the functionality of GDK_DPI_SCALE=0.5 for Quartz? 

@kapiliitr Occasionally the Frameworks libraries are upgraded in between builds. 
There was one particularly ancient library that was upgraded to something more modern, libomp --> libiomp5 (that does not seem a likely culprit.)
Gtkmm went from 3.16 to 3.22 right after making the current mac 5.2 release build, mainly to see if the default-font-too-big issue would magically resolve. Gtk+3 3.22 was a fairly recent upgrade, and that scaling became incompletely supported on mac retina is another possibility.

**Comment by Beep6581** [comment] 2017-07-27 15:14
@Benitoite I don't know anything about macOS. Have you tried using `GDK_SCALE` instead? In Linux one scales only the fonts while the other scales everything.

**Comment by Benitoite** [comment] 2017-07-27 15:20
@Beep6581 Tried all the combinations of GDK_SCALE and GDK_DPI_SCALE, with no effect. 

@kapiliitr  Here's an interesting detail from your screenshot comparing the resolution of the graphical elements and the resolution of the text, 
<img width="238" alt="28654975-3e43d9b0-724d-11e7-9007-5e2cf6f6c98e" src="https://user-images.githubusercontent.com/17919239/28677516-8912c5fa-72a2-11e7-9194-6f2f1203f611.png">
Can you also control font scaling with the OS control panel?

**Comment by kapiliitr** [comment] 2017-07-27 15:39
Not sure if this is what you wanted, but I tried scaling down the display resolution _System Preferences -> Displays -> Display_ Attached is the screenshot. Weirdly, this time the default font was None (I had deleted the options file)
<img width="1680" alt="screen shot 2017-07-27 at 8 38 02 am" src="https://user-images.githubusercontent.com/1621360/28679114-0cb97f76-72a7-11e7-9c53-9793e8ff8b80.png">

**Comment by Benitoite** [comment] 2017-07-27 16:02
Thanks @kapiliitr what I had in mind was not adjustment of screen resolution but the font scaling.

**Comment by Benitoite** [comment] 2017-07-27 16:05
@kapiliitr http://cdn.osxdaily.com/wp-content/uploads/2016/02/change-mac-system-font-size-display-resolution.png

**Comment by Benitoite** [comment] 2017-07-27 16:07
@kapiliitr Which of these settings have you tried. Could you try one of the in-between modes with rawtherapee.
With regards to the font being None, are you still using RawTherapee_OSX_10.9_64_5.2-16-gb84a027d.zip

**Comment by kapiliitr** [comment] 2017-07-27 16:40
No, I was using RT 5.2 published on the website. I'll try your suggestion
out later today.

**Comment by Hombre57** [comment] 2017-07-27 20:27
@Benitoite Here is a patch that will let you set see the current font resolution and set a new hardcoded one. You'll have to set `verbose=true` in options.

```patch
diff --git a/rtdata/options/options.osx b/rtdata/options/options.osx
index 4d35255..e9daccb 100644
--- a/rtdata/options/options.osx
+++ b/rtdata/options/options.osx
@@ -23,9 +23,6 @@
 # Parameters: <Path to raw/JPG> <Path to default profile> <fNumber> <expose in seconds> <focal length in mm> <ISO> <Lens> <Camera>
 CustomProfileBuilder=
 
-[GUI]
-Font=Sans 12
-
 # Set here an absolute or relative path (to the rawtherapee.exe file) to the directory containing your own profiles.
 # If MultiUser=true, each user will have their own "options" file, and can set a common or different absolu path
 #Directory=profiles
@@ -39,3 +36,7 @@
 
 # Default profile name (without extension) to use for standard (8bits) images
 #ImgDefault=Neutral
+
+[GUI]
+FontFamily=Arial Regular
+CPFontFamily=Arial Regular
diff --git a/rtgui/main.cc b/rtgui/main.cc
index 099751f..5a03229 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -254,6 +254,15 @@
         Gtk::Settings::get_for_screen(screen)->property_gtk_theme_name() = "Adwaita";
         Gtk::Settings::get_for_screen(screen)->property_gtk_application_prefer_dark_theme() = true;
 
+#if defined(__APPLE__)
+        double resolution = screen->get_resolution ();
+        printf("Screen resolution is %.1f", (float)resolution);
+
+        // This will force screen resolution regarding font, but I don't think it's compliant with Gtk guidelines...
+        // Do not confuse with screen scaling, where everything is scaled up !
+        screen->set_resolution (96.);
+#endif
+
         Glib::RefPtr<Glib::Regex> regex = Glib::Regex::create(THEMEREGEXSTR, Glib::RegexCompileFlags::REGEX_CASELESS);
         Glib::ustring filename = Glib::build_filename(argv0, "themes", options.theme + ".css");
         if (!regex->match(options.theme + ".css") || !Glib::file_test(filename, Glib::FILE_TEST_EXISTS)) {
```

**Comment by Benitoite** [comment] 2017-07-27 23:58
@Hombre57 That seems to look normal on my mac. 

![screen shot 2017-07-27 at 3 08 42 pm](https://user-images.githubusercontent.com/17919239/28696634-93dbcf74-72eb-11e7-8def-a5ed047d6abd.jpg)

@kapiliitr Can you let us know if this looks right on your display:
https://filebin.net/u5cujuba4mwperg2/RawTherapee_OSX_10.9_64_5.2.1-2-gb5e76836.zip

**Comment by Hombre57** [comment] 2017-07-28 14:01
@Benitoite Looks bold to me. Is there any thinner _sans_ font ?

**Comment by kapiliitr** [comment] 2017-07-28 14:39
@Benitoite Looks good to me !

**Comment by Benitoite** [comment] 2017-07-28 15:13
There's a subtle difference between Arial Regular (left) and Helvetica (right).
![screen shot 2017-07-28 at 8 01 08 am](https://user-images.githubusercontent.com/17919239/28723685-625978e4-736c-11e7-90d1-7f3e46b220a2.jpg)
Helvetica is slightly narrower.

**Comment by Benitoite** [comment] 2017-08-04 13:05
Thanks to @Hombre57 for merging fixes https://github.com/Beep6581/RawTherapee/pull/3992

**Comment by Beep6581** [comment] 2017-08-04 14:18
@Benitoite would you advertise it in the forum and paste a link to your post here?

**Comment by Benitoite** [comment] 2017-08-04 15:51
@Beep6581 https://discuss.pixls.us/t/macos-rawtherapee-retina-font-performance-develeopements/4777

**Comment by sjmudd** [comment] 2017-08-05 18:23
For what it's worth I've had the same problem on a MacBook Pro (Retina, 13-inch, Late 2013) and the corrected binary also fixes the problem for me. So thanks for taking the time to resolve this. It took me a while to find this issue on github, partly as this was my first install of RawTherapee so I'm trying out the software for the first time, and thus I guess for newcomers such as myself we may not see the post in the forum at least initially.  Might it be better to update the downloads page to reflect this and provide the link for those people who have experienced this problem?

**Comment by Benitoite** [comment] 2017-08-05 19:05
As far as rawtherapee dot com releases, I think v2.5.1 is coming rather soon. 
There is also a central page for development series builds: https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924

**Comment by Beep6581** [comment] 2017-08-05 19:13
Yes, this will be part of 5.2.1.

So the issue is fixed and the fix is confirmed - @Hombre57 ok to close?

**Comment by Hombre57** [comment] 2017-08-06 12:31
If everyone is happy, then yes, closing.

**Closed as completed by Hombre57** 2017-08-06 12:31 UTC
Labels: type: bug, os: macOS
