### ISSUE TITLE
Demosaic and Fuji Finepix F770EXR RAFs

### ISSUE THREAD

**Issue by seadra** [Beep6581/RawTherapee#5178] opened 2019-02-16 03:58 UTC
Demosaicing pattern look totally incorrect with RAF files, zooming in reveals pattern glitches.
I can provide RAFs along with JPGs if necessary. 

In the RAW table, only "Sensor with Bayer Matrix" is accessible. Is there a way to force-switch to "Sensor with X-Trans Matrix" mode?

**Comment by heckflosse** [comment] 2019-02-16 09:01
Works fine here. F770EXR has Bayer cfa.
![grafik](https://user-images.githubusercontent.com/13733487/52897174-c4220300-31d1-11e9-854b-26cee22533ee.png)

**Comment by heckflosse** [comment] 2019-02-16 09:40
Well, it's not real bayer pattern, it's two combined bayer patterns.
You can select the individual frames here
![grafik](https://user-images.githubusercontent.com/13733487/52897656-46f98c80-31d7-11e9-836b-cc5bed94207b.png)

**Comment by seadra** [comment] 2019-02-16 21:16
Here's a comparison of the RAF and the JPG generated by the camera. I zoomed in 200%, but even at half zoom level, the demosaic artifacts are distinctly visible (photo of a signboard with white background).

![demosaic](https://user-images.githubusercontent.com/9574367/52905237-69a29a00-3205-11e9-9bdc-c3ee47ab83db.png)

So far F770EXR RAFs don't look look when opened with RawTherapee, unless I'm missing something (they looked fine in Lightroom 5 though).

I may be wrong about the cause here, of course; I'm not sure what you think of these colorful artifacts, patches of areas that are tinted either greed, red or blue, which cover all the images when opened in RawTherapee.

By the way, there is a sub-image in SN priority mode RAFs, although I'm not sure if it's full utilized, per #4830. I did try changing the sub-image with such RAFs but it just gives different artifact patterns.

**Comment by heckflosse** [comment] 2019-02-17 11:40
@seadra Currently the sub-image selector does what its label suggests: It allows you to open one of the two sub-images. With the patch from #4830 which was never committed I changed the behaviour: Selecting sub-image 1 then gives the average of both sub-images, selecting sub-image 2 gives just sub-image 2.

Averaging both sub-images reduces the noise as you can see here:
Left is sub-image 2, right is 1 and 2 averaged
![grafik](https://user-images.githubusercontent.com/13733487/52912271-767bc800-32af-11e9-9f27-80bc88d2ebed.png)

**Comment by heckflosse** [comment] 2019-02-17 11:48
@seadra Here's a before/after:
It's from an ISO1600 EXR file
Left is just opened in RT using auto-matched curve ISO low
Right is averaged sub-images, demosaic changed to Amaze+VNG4 contrast threshold 20, Noise Reduction enabled, Impulse Noise reduction enabled

![grafik](https://user-images.githubusercontent.com/13733487/52912454-1175a180-32b2-11e9-9ac9-11f133e51631.png)

**Comment by heckflosse** [comment] 2019-02-21 21:22
Ok to close this? https://github.com/Beep6581/RawTherapee/commit/b37f5453911cac58b2f57889655315ea6885130d

**Comment by Beep6581** [comment] 2019-02-21 21:39
@heckflosse yes, but @seadra don't forget to submit sample raw files to [RPU](https://raw.pixls.us/) as per https://github.com/Beep6581/RawTherapee/issues/4830#issuecomment-440938344

**Comment by seadra** [comment] 2019-03-03 22:40
@Beep6581 

He's asking for two raws of the same scene, and suggested using a tripod [in the comment](https://github.com/Beep6581/RawTherapee/issues/4830#issuecomment-464424277), which I don't have. I can upload single RAF file (along with the JPG generated by the camera) if that'd be useful.

**Comment by seadra** [comment] 2019-03-03 22:53
I don't think b37f545 fixes this issue, because this happens with non-SN images as well (for example, the image in my [comment above](https://github.com/Beep6581/RawTherapee/issues/5178#issuecomment-464386349) doesn't have any additional sub-images)

**Comment by Beep6581** [comment] 2019-03-03 23:18
> which I don't have

@seadra take photos of a scene for each mode your camera has (normal raw + SN + whatever other mode it may have) and upload to RPU. Don't worry about the tripod if you don't have one.

**Comment by heckflosse** [comment] 2019-03-03 23:58
Closed

**Comment by seadra** [comment] 2019-03-04 00:01
@Beep6581 OK, I will do that.

@heckflosse Why did you close this issue? It is not about SN.

**Comment by heckflosse** [comment] 2019-03-04 19:54
@seadra 
> (for example, the image in my comment above doesn't have any additional sub-images)

Can you provide such a RAF please?

**Comment by seadra** [comment] 2019-03-09 16:28
Sure thing, I attached the RAF and the JPG from that comment: 
[dscf.zip](https://github.com/Beep6581/RawTherapee/files/2948585/dscf.zip)

**Comment by heckflosse** [comment] 2019-03-16 23:33
@seadra Sorry for the late answer.

What you call `Demosaicing pattern` simply is noise caused by shooting at ISO 1600. In the jpeg the camera software `cleaned` the noise. RT does not do that by default. You have to enable the `Noise reduction` tool and adjust its settings to clean the noise.

Still wondering why you raf has only one frame. I thought all fuji exr raf files have two frames.

**Comment by seadra** [comment] 2019-03-17 05:23
Noise reduction was one the first things I tried. It does soften those colorful patterns, but they're still visible. Camera's JPEG doesn't have such colorful patterns.

Again, I'm not sure if it's related to demosaicing pattern, but it does resemble that.

> I thought all fuji exr raf files have two frames.

This is true only in certain modes.

**Comment by Beep6581** [comment] 2019-03-17 13:01
@seadra http://rawpedia.rawtherapee.com/Getting_Started#Edit_your_first_image

@seadra you still have not uploaded the photo(s) to RPU.

**Closed as completed by Beep6581** 2019-03-17 13:01 UTC

**Comment by seadra** [comment] 2019-03-18 01:18
No idea why you linked "Edit your first image" or closed this issue.

I know, I am busy these days.
