### ISSUE TITLE
Rawtherapee Crash on Start up

### ISSUE THREAD

**Issue by ex-ee** [Beep6581/RawTherapee#3310] opened 2016-05-25 17:18 UTC
This problem has been persistent at least since upgrading to OSX 10.11.

Rawtherapee crashes immediately on opening every time whether am opening a raw file or simply the program itself. I have tried all recent OSX versions from the site.  Any ideas?? I really love the program and the integration with GIMP is a lifesaver, but this issue seems persistent on my machine for the last few versions of 4.2.

Downloaded from here: http://rawtherapee.com/releases_head/mac/RawTherapee_OSX_10.11_64_4.2-753_master.zip

2.6Ghz Intel Core i7; 8GB of RAM

About Build File:
Branch: master
Version: 4.2.753
Changeset: 0e0f5dd80dea08c05dc102d1b2325d133790ec2c
Compiler: clang-mp-3 3.7.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -w -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON

Exceptions:
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000011a491000
Exception Note:        EXC_CORPSE_NOTIFY

Crashed Thread:
Thread 24 Crashed:: pool
0   libsystem_platform.dylib      	0x00007fff9db2d625 _platform_memmove$VARIANT$Nehalem + 197
1   rawtherapee-bin               	0x0000000100480c5b rtengine::ImageIO::loadPPMFromMemory(char const*, int, int, bool, int) + 315
2   rawtherapee-bin               	0x0000000100578e90 rtengine::Thumbnail::loadQuickFromRaw(Glib::ustring const&, rtengine::RawMetaDataLocation&, int&, int&, int, bool, bool) + 384
3   rawtherapee-bin               	0x000000010031b6c6 Thumbnail::_generateThumbnailImage() + 582
4   rawtherapee-bin               	0x000000010031b354 Thumbnail::Thumbnail(CacheManager*, Glib::ustring const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 260
5   rawtherapee-bin               	0x000000010016fb73 CacheManager::getEntry(Glib::ustring const&) + 579
6   rawtherapee-bin               	0x000000010024b17b PreviewLoader::Impl::processNextJob() + 299
7   libglibmm-2.4.1.dylib         	0x0000000100de16fe (anonymous namespace)::call_thread_entry_slot(void*, void*) + 52
8   libglib-2.0.0.dylib           	0x0000000100cfdd35 g_thread_pool_thread_proxy + 37
9   libglib-2.0.0.dylib           	0x0000000100cfd091 g_thread_proxy + 90
10  libsystem_pthread.dylib       	0x00007fff9678599d _pthread_body + 131
11  libsystem_pthread.dylib       	0x00007fff9678591a _pthread_start + 168
12  libsystem_pthread.dylib       	0x00007fff96783351 thread_start + 13

**Comment by NextTherapist** [comment] 2016-06-01 15:13
Try to use the newest builds which you can find here (but for Windows): https://discuss.pixls.us/t/new-windows-builds/615
Older builds had among other things this bug: https://github.com/Beep6581/RawTherapee/issues/3084
They crashed with only one image file without exif metadata in the folder - and ciecam settings enabled.
I do not know if this is the reason for your crash, but they really do a lot of bug correction every week...

**Comment by ex-ee** [comment] 2016-06-01 15:22
Are there any links to new OSX builds? Windows is no help to me.

Thanks,

-E

**Comment by Beep6581** [comment] 2016-06-01 16:23
Thank you for the report. Unfortunately our OS X builds are now outdated. I will try asking the people who made those to make new ones. As for this issue, I will close it, because much has changed since the version you ran and the problem may have been fixed. When new OS X builds appear, please try those, and provide a [stack backtrace with raw+PP3](rawpedia.rawtherapee.com/How_to_write_useful_bug_reports) if you can reproduce a crash.

**Closed by Beep6581** 2016-06-01 16:23 UTC
