### ISSUE TITLE
Save As - Wrong file suffix when clicking on existing file then changing file format

### ISSUE THREAD

**Issue by blitzgneisserin** [Beep6581/RawTherapee#4446] opened 2018-03-19 23:27 UTC
Hi, basically this bug works like this: I export a photo directy to JPEG or TIFF, and right after that I do another direct export and change the file type. Result is the same file type, but if it is a JPEG it is as big as the TIFF. E.g. first I export to JPEG. Then I switch file type to TIFF and export again. Result is a JPEG with usually more than 50 MB. I do not know what that file is. It is called JPEG but how can it be this big? I can open it and view it but I have no idea what it actually is.
I tried this with 5.3 (portable) from portableapps and 5.4. rc-3 (https://gaaned92.keybase.pub/RTW64NightlyBuilds/RawTherapee_5.4-rc3_WinVista_64.zip?dl=1).
OS is Win 10. When using 5.4-rc3 I also got a strange screen:
![screenshot 103](https://user-images.githubusercontent.com/16564210/37627306-19daa432-2bd4-11e8-861b-80200a250297.png)
And here the strange file in the Windows Explorer:
![screenshot 104](https://user-images.githubusercontent.com/16564210/37627418-95093574-2bd4-11e8-9899-53d5405595a4.png)
I opened the file in Affinity and it appears to be a 16-bit-JPEG
![screenshot 105](https://user-images.githubusercontent.com/16564210/37627511-0c2e4810-2bd5-11e8-8b3e-61464cbd6f0e.png)
Here the data of my PC:
![screenshot 102](https://user-images.githubusercontent.com/16564210/37627706-f5667dfe-2bd5-11e8-9be5-b5ea082d36d8.png)
It must be a wrong file ending, right?

**Comment by Beep6581** [comment] 2018-03-20 00:55
Could not reproduce.

@blitzgneisserin please post the *exact* steps to reproduce, or even better a video screen recording.

**Comment by Floessie** [comment] 2018-03-20 07:35
Could not reproduce as well.

When I hit Ctrl+S on let's say "DSC_1234.NEF" the save dialog proposes "DSC_1234" in the top line. Selecting JPEG produces a JPEG. Even if I hit Ctrl+S again while saving, it still proposes "DSC_1234", and selecting TIFF yields a TIFF. The only way to create a TIFF file with a ".jpg" extension is to select the "DSC_1234.jpg" in the file selection and TIFF as output format. But that is expected.

**Comment by blitzgneisserin** [comment] 2018-03-20 07:47
open an ORF, strg + s, choose file type (e.g. jpeg), save
open ORF, strg + s, choose different file type (e.g. tiff), save

tried it again, with strg +s (although I usually use the button, not the keyboard), same result
I will try to make a screen recording later
![screenshot 106](https://user-images.githubusercontent.com/16564210/37641896-a83bab9e-2c1b-11e8-84a2-9c7115959a2f.png)
When I hit strg + s the second time, RT suggests tif as file ending (before I saved a tif), althogh tile type jpeg is selected

**Comment by cuniek** [comment] 2018-03-20 07:55
I guess it is the oldest trick in the book:

1) open image, and Ctrl-S
2) click on any JPG or TIFF file (the filename has a suffix like .jpg)
3) change filetype (the suffix stays the same)
4) OS like Windows will show filetype based on the suffix, so You have 50MB TIFF file with JPG suffix detected/shown as JPG.

Oh, @Floessie was first.

**Comment by Floessie** [comment] 2018-03-20 08:05
@blitzgneisserin What you're basically saying is, that "P8200086.tif" is proposed in the top line immediately after opening the save dialog without selecting anything actively in that dialog? Can anyone confirm this on Windows?

**Comment by gaaned92** [comment] 2018-03-20 08:52
W10 can reproduce
beginning with empty output dir
- open an image
- click "save current image", select "file format"=jpg, save : a file with jpg type is created
- click "save current image", select "file format"=tiff 16bits, save : a file with jpg type is created

no click on any file or other action. 

after that it works and the file suffix is ok

so if you have a look at the second file with exiftool, 

![screen-2018-03-20_09-43-06](https://user-images.githubusercontent.com/13785581/37644208-4f6e4820-2c23-11e8-9e1c-d18c12f49c59.jpg)
 

@Floessie on W10, when you open the save dialog, only the filename is proposed in the first line, for instance "blue-horse" here. the suffix is automatically appended by RT.

remarks: there is no problem to read the file. A work around is just to change the file suffix.

**Comment by cuniek** [comment] 2018-03-20 08:57
confirm on win7 - just as @gaaned92 wrote
By default only the filename is displayed in "Save as" dialogbox, and when you change the filtype the name stays and suffix is automatically added during the save process.

If filename was changed, then changing the filetype does not touch the suffix, so it may be wrong.

**Comment by Floessie** [comment] 2018-03-20 09:13
@gaaned92 @cuniek Thanks for testing. This explains @blitzgneisserin' woes. I still don't understand why this is different between Windows and Linux. Could you test this patch, which adds some printf debugging?

```patch
diff --git a/rtgui/editorpanel.cc b/rtgui/editorpanel.cc
index 278b14fe0..29e8fd248 100644
--- a/rtgui/editorpanel.cc
+++ b/rtgui/editorpanel.cc
@@ -1863,6 +1863,7 @@ void EditorPanel::saveAsPressed ()
     }
 
     saveAsDialog->set_default_size (options.saveAsDialogWidth, options.saveAsDialogHeight);
+    std::cout << "setInitialFileName(" << lastSaveAsFileName << ")" << std::endl;
     saveAsDialog->setInitialFileName (lastSaveAsFileName);
     saveAsDialog->setImagePath (fname);
 
@@ -1877,6 +1878,8 @@ void EditorPanel::saveAsPressed ()
         options.autoSuffix = saveAsDialog->getAutoSuffix ();
         options.saveMethodNum = saveAsDialog->getSaveMethodNum ();
         lastSaveAsFileName = Glib::path_get_basename (removeExtension (fnameOut));
+        std::cout << "fnameOut = '" << fnameOut << "'" << std::endl;
+        std::cout << "lastSaveAsFileName = '" << lastSaveAsFileName << "'" << std::endl;
         SaveFormat sf = saveAsDialog->getFormat ();
         options.saveFormat = sf;
         options.forceFormatOpts = saveAsDialog->getForceFormatOpts ();
```

Thanks,
Flössie

**Comment by blitzgneisserin** [comment] 2018-03-20 10:12
Everything works fine if you delete the suggested suffix with the help of the keyboard (in the "save"-dialogue), but that is a bit tricky too.

**Comment by gaaned92** [comment] 2018-03-20 11:29
@Floessie 

```
Load D:\PHOTOS\test\blue_horse.nef: 294187 usec
setscale before lock
setscale starts (611, 406)
freeall starts 0
setscale ends
setscale ends2
LENSFUN:
  camera: Nikon Corporation Nikon D700
  lens: ---
  correction: NONE
Nikon D700 2060204.badpixels not found
Nikon D700.badpixels not found
Preprocessing: 78864 usec
Demosaic Bayer image n.1 using method: amaze
Demosaicing Bayer data: amaze - 149879 usec
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (611, 406)
setscale ends
setscale ends2
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=1
setcropsizes before lock
setsizes starts (407, 284, -1, -1, 407, 284)
setsizes ends
setcropsizes before lock
setsizes starts (856, 568, 407, 284, 856, 568)
setsizes ends
setInitialFileName(blue_horse)
fnameOut = 'C:\Users\Andre\Pictures\blue_horse.jpg'
lastSaveAsFileName = 'blue_horse'
Nikon D700 2060204.badpixels not found
Nikon D700.badpixels not found
Preprocessing: 80278 usec
Demosaicing Bayer data: amaze - 134122 usec
Info denoise auto performed in 45141 usec:
RGB_denoise uses 1 main thread(s) and up to 8 nested thread(s) for each main thread
Denoise performed in 1028268 usec:
Output image / Auto B&W coefs:   R=-9000.00   G=0.00   B=0.00
Output profile_: "RT_sRGB"
Using "RT_sRGB" output profile
setInitialFileName(blue_horse)
fnameOut = 'C:\Users\Andre\Pictures\blue_horse.jpg'
lastSaveAsFileName = 'blue_horse'
Nikon D700 2060204.badpixels not found
Nikon D700.badpixels not found
Preprocessing: 69840 usec
Demosaicing Bayer data: amaze - 133471 usec
Info denoise auto performed in 43228 usec:
RGB_denoise uses 1 main thread(s) and up to 8 nested thread(s) for each main thread
Denoise performed in 1006346 usec:
Output image / Auto B&W coefs:   R=-9000.00   G=0.00   B=0.00
Output profile_: "RT_sRGB"
Using "RT_sRGB" output profile
freeallcrop starts 1
freeall starts 1
```

**Comment by Floessie** [comment] 2018-03-20 11:54
@gaaned92 André, thanks for testing. The outcome is the same as on Linux: We set the initial filename without extension in the save dialog. Still it shows "blue_horse.jpg" the second time you open the dialog?

**Comment by gaaned92** [comment] 2018-03-20 12:02
@Floessie 

Yes above, the second save was in tif format, nevertheless it shows blue_horse-1.jpg because there is already a jpg file.

I think the second time,
fnameOut = 'C:\Users\Andre\Pictures\blue_horse.jpg'
should be
fnameOut = 'C:\Users\Andre\Pictures\blue_horse.tif'

**Comment by Floessie** [comment] 2018-03-20 12:36
@gaaned92 
> Yes above, the second save was in tif format, nevertheless it shows blue_horse-1.jpg because there is already a jpg file.

This is the bottom line: It only happens (also on Linux) when "Automatically add suffix if the file already exists" is checked.

I'll try to fix that...

**Comment by blitzgneisserin** [comment] 2018-03-20 13:07
another issue appears to be related to this issue:
if I save a processing profile before the first export/save of a photo, when I save/export, RT  creates a file name like ****.pp3.***
![screenshot 107](https://user-images.githubusercontent.com/16564210/37656218-b8978310-2c47-11e8-9a9b-28eec37c988b.png)
At least, there is a "warning"
![screenshot 108](https://user-images.githubusercontent.com/16564210/37656232-c4516d56-2c47-11e8-8422-c43240513110.png)
I am not sure whether a new issue should be created

**Comment by Beep6581** [comment] 2018-09-11 12:35
I accidentally ran into this issue the other day using more or less `5.4-806-g0aa1158bc`. I ended up with a file with an incorrect extension - examining it with `hexdump` and `identify` showed that it was a TIFF file with a JPEG extension. There was no warning about a wrong extension.

Maybe I accidentally did what @cuniek [described](https://github.com/Beep6581/RawTherapee/issues/4446#issuecomment-374506507) - in fact I tried his steps now in `5.4-816-gea992fc91` and I could reproduce.

**Comment by Floessie** [comment] 2018-09-11 12:51
@Beep6581 Ah, thanks for reminding me about this one. I'm completely busy ATM and can't promise to have a second look at the issue this week, though...

**Comment by Floessie** [comment] 2018-10-05 07:03
Here's a patch with two countermeasures:

1. Fix the "double extension" warning I broke in b84e570f500a19fec0f6a35fe775061116be283b.
2. Change suffix on format change.

```patch
diff --git a/rtgui/batchqueuepanel.cc b/rtgui/batchqueuepanel.cc
index 1a9e08b94..b73fb2f6f 100644
--- a/rtgui/batchqueuepanel.cc
+++ b/rtgui/batchqueuepanel.cc
@@ -363,15 +363,12 @@ void BatchQueuePanel::pathFolderButtonPressed ()
 // since these settings are shared with editorpanel :
 void BatchQueuePanel::pathFolderChanged ()
 {
-
     options.savePathFolder = outdirFolder->get_filename();
 }
 
-void BatchQueuePanel::formatChanged (Glib::ustring f)
+void BatchQueuePanel::formatChanged(const Glib::ustring& format)
 {
-
-    options.saveFormatBatch = saveFormatPanel->getFormat ();
-
+    options.saveFormatBatch = saveFormatPanel->getFormat();
 }
 
 bool BatchQueuePanel::handleShortcutKey (GdkEventKey* event)
diff --git a/rtgui/batchqueuepanel.h b/rtgui/batchqueuepanel.h
index 497bc166e..d765e23dc 100644
--- a/rtgui/batchqueuepanel.h
+++ b/rtgui/batchqueuepanel.h
@@ -72,7 +72,7 @@ public:
     void saveOptions ();
     void pathFolderChanged ();
     void pathFolderButtonPressed ();
-    void formatChanged (Glib::ustring f);
+    void formatChanged(const Glib::ustring& format) override;
     void updateTab (int qsize, int forceOrientation = 0); // forceOrientation=0: base on options / 1: horizontal / 2: vertical
 
     bool handleShortcutKey (GdkEventKey* event);
diff --git a/rtgui/saveasdlg.cc b/rtgui/saveasdlg.cc
index 7067e8ed1..f2a7206b9 100644
--- a/rtgui/saveasdlg.cc
+++ b/rtgui/saveasdlg.cc
@@ -16,15 +16,36 @@
  *  You should have received a copy of the GNU General Public License
  *  along with RawTherapee.  If not, see <http://www.gnu.org/licenses/>.
  */
+#include <functional>
+
 #include "saveasdlg.h"
-#include "multilangmgr.h"
+
 #include "guiutils.h"
+#include "multilangmgr.h"
 #include "rtimage.h"
 
 #include "../rtengine/utils.h"
 
 extern Options options;
 
+namespace
+{
+
+Glib::ustring getCurrentFilename(const Gtk::FileChooserWidget* fchooser)
+{
+    Glib::ustring res = fchooser->get_filename();
+
+    // NB: There seem to be a bug in Gtkmm2.22 / FileChooserWidget : if you suppress the filename entry and
+    //     click on a folder in the list, the filename field is empty but get_filename will return the folder's path :/
+    if (Glib::file_test(res, Glib::FILE_TEST_IS_DIR)) {
+        res = fchooser->get_current_name();
+    }
+
+    return res;
+}
+
+}
+
 SaveAsDialog::SaveAsDialog (const Glib::ustring &initialDir, Gtk::Window* parent)
     : Gtk::Dialog (M("GENERAL_SAVE"), *parent)
 {
@@ -219,13 +240,7 @@ SaveFormat SaveAsDialog::getFormat ()
 
 void SaveAsDialog::okPressed ()
 {
-    fname = fchooser->get_filename();
-
-    // NB: There seem to be a bug in Gtkmm2.22 / FileChooserWidget : if you suppress the filename entry and
-    //     click on a folder in the list, the filename field is empty but get_filename will return the folder's path :/
-    if (Glib::file_test(fname, Glib::FILE_TEST_IS_DIR)) {
-        fname = fchooser->get_current_name();
-    }
+    fname = getCurrentFilename(fchooser);
 
     // Checking if the filename field is empty. The user have to click Cancel if he don't want to specify a filename
     if (fname.empty()) {
@@ -246,9 +261,18 @@ void SaveAsDialog::okPressed ()
         // Extension is either empty or unfamiliar
         fname += '.' + formatOpts->getFormat().format;
     } else if (
-        !rtengine::hasJpegExtension(fname)
-        && !rtengine::hasTiffExtension(fname)
-        && !rtengine::hasPngExtension(fname)
+        (
+            formatOpts->getFormat().format == "jpg"
+            && !rtengine::hasJpegExtension(fname)
+        )
+        || (
+            formatOpts->getFormat().format == "tif"
+            && !rtengine::hasTiffExtension(fname)
+        )
+        || (
+            formatOpts->getFormat().format == "png"
+            && !rtengine::hasPngExtension(fname)
+        )
     ) {
         // Create dialog to warn user that the filename may have two extensions on the end
         Gtk::MessageDialog msgd(
@@ -283,15 +307,42 @@ void SaveAsDialog::cancelPressed ()
     response (Gtk::RESPONSE_CANCEL);
 }
 
-void SaveAsDialog::formatChanged (Glib::ustring f)
+void SaveAsDialog::formatChanged(const Glib::ustring& format)
 {
+    const auto sanitize_suffix =
+        [this, format](const std::function<bool (const Glib::ustring&)>& has_suffix)
+        {
+            const Glib::ustring name = getCurrentFilename(fchooser);
+
+            if (!has_suffix(name)) {
+                fchooser->set_current_name(removeExtension(Glib::path_get_basename(name)) + '.' + format);
+            }
+        };
 
-    if (f == "jpg") {
+    if (format == "jpg") {
         fchooser->set_filter (filter_jpg);
-    } else if (f == "png") {
+        sanitize_suffix(
+            [](const Glib::ustring& filename)
+            {
+                return rtengine::hasJpegExtension(filename);
+            }
+        );
+    } else if (format == "png") {
         fchooser->set_filter (filter_png);
-    } else if (f == "tif") {
+        sanitize_suffix(
+            [](const Glib::ustring& filename)
+            {
+                return rtengine::hasPngExtension(filename);
+            }
+        );
+    } else if (format == "tif") {
         fchooser->set_filter (filter_tif);
+        sanitize_suffix(
+            [](const Glib::ustring& filename)
+            {
+                return rtengine::hasTiffExtension(filename);
+            }
+        );
     }
 }
 
diff --git a/rtgui/saveasdlg.h b/rtgui/saveasdlg.h
index 073be23f4..e02be340f 100644
--- a/rtgui/saveasdlg.h
+++ b/rtgui/saveasdlg.h
@@ -62,7 +62,7 @@ public:
 
     void okPressed ();
     void cancelPressed ();
-    void formatChanged (Glib::ustring f);
+    void formatChanged(const Glib::ustring& format) override;
     bool keyPressed (GdkEventKey* event);
 };
 
diff --git a/rtgui/saveformatpanel.h b/rtgui/saveformatpanel.h
index 47011be18..7c4dbf33f 100644
--- a/rtgui/saveformatpanel.h
+++ b/rtgui/saveformatpanel.h
@@ -28,8 +28,8 @@ class FormatChangeListener
 {
 
 public:
-    virtual ~FormatChangeListener () {}
-    virtual void formatChanged (Glib::ustring f) {}
+    virtual ~FormatChangeListener() = default;
+    virtual void formatChanged(const Glib::ustring& format) = 0;
 };
 
 class SaveFormatPanel : public Gtk::Grid, public AdjusterListener
```

HTH,
Flössie

**Comment by Floessie** [comment] 2018-10-09 07:23
#4854 merged. Closing.

**Closed as completed by Floessie** 2018-10-09 07:23 UTC
Labels: type: bug, patch provided
