### ISSUE TITLE
[Bug] HSV curves from latest file are being applied to new file

### ISSUE THREAD

**Issue by SaturnusDJ** [Beep6581/RawTherapee#4573] opened 2018-05-27 17:15 UTC
When opening a new NEF without copying any .pp3 or whatever link between the new and previous file, the curve of the HSV from previous file is being applied to the new file after enabling the HSV Equalizer.

Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

**Comment by TooWaBoo** [comment] 2018-05-27 18:23
It's not a bug, it's a feature and happens to all curves. :-)

**Comment by SaturnusDJ** [comment] 2018-05-27 18:28
Surprising. What is the reason to have it like that? Is there a preference to turn it off?

**Comment by TooWaBoo** [comment] 2018-05-27 18:48
No, you can't turn it off and I do not know why, but it works like that since I use RT.

**Comment by Hombre57** [comment] 2018-06-02 00:45
Each curve is a set of multiple curve editor. When switching to a new image, you often switch the curve type. By doing so, the old curve editor is hidden without being reset and the new one is shown.

Do we want to reset all curve editor when switching to a new image or keep its content ? It's debatable IMHO (I personally don't care). If you prefer letting the user chose, then the discussion will continue in issue #4575.

**Comment by Hombre57** [comment] 2018-06-02 00:45
Forgot to ping @SaturnusDJ @Beep6581

**Comment by Beep6581** [comment] 2018-06-02 09:50
@Hombre57 this issue is a bug report, and this is not a bug. There is a cleaner feature-request issue for this in #4575. We should preferably use that one, or close that one as a duplicate of this one.

> Do we want to reset all curve editor when switching to a new image

My opinion hovers somewhere between "no" and "don't-care". The way it currently is is useful when working on a series of shots, and the curve can be reset with a single click.

**Comment by SaturnusDJ** [comment] 2018-06-02 10:10
Yes it is useful when working on a series, even then though you need to enable HSV, then enable each of the 3 channels to fully copy from the previous file. And when resetting you need to enable HSV, then enable and reset each of the channels. 

Maybe an on/off button for starting from scratch and some kind of reload button to immediately enable from cache is an idea?

**Comment by Beep6581** [comment] 2018-06-02 10:31
> Yes it is useful when working on a series, even then though you need to enable HSV, then enable each of the 3 channels to fully copy from the previous file.

In that case you would copy the PP3 from one image to the next to avoid having to do that.

One is likely to end up using a very similar curve in a series of images. Having a new image's curve automatically show the last-used curve when enabling it allows you to quickly jump to that point with no effort, and make minor adjustments as necessary.

Imagine you're working on a series of images, some are ISO100 and some are ISO6400. Very different regarding required sharpening, noise reduction, demosaicing, etc. i.e. you would not copy the PP3 from one to the other because they are too different. But the required curves would look very similar, since curves are independent of ISO.

What benefit would removing this functionality bring?

> Maybe an on/off button for starting from scratch and some kind of reload button to immediately enable from cache is an idea?

-1, bloat. Either we keep this functionality, or we remove it, but let's not add bloat.

**Comment by SaturnusDJ** [comment] 2018-06-02 12:50
> -1, bloat. Either we keep this functionality, or we remove it, but let's not add bloat.

Yeah that's the way to kill idea's and creativity. Bravo.
One simple reload button would surely be bloat before even testing it.

I totally agree it's useful a.f. in a series and didn't really see that before opening the topic, but for people who don't do series it's just as annoying a.f. Series-people already have a super nice feature with the copy-paste curve buttons. Adding a reload last curves button above that totally is not bloat. Binding the last state of the channels to such a button would make it even quicker for series-people than current method of having to activate each channel individually.

**Comment by Beep6581** [comment] 2018-06-02 17:19
> Yeah that's the way to kill idea's and creativity. Bravo.
One simple reload button would surely be bloat before even testing it.
>
> I totally agree it's useful a.f. in a series and didn't really see that before opening the topic, but for people who don't do series it's just as annoying a.f. Series-people already have a super nice feature with the copy-paste curve buttons. Adding a reload last curves button above that totally is not bloat. Binding the last state of the channels to such a button would make it even quicker for series-people than current method of having to activate each channel individually.

1. Disagreeing with you does not warrant your retaliatory tone.
2. Tune down your swearing and sarcasm.

**Closed as completed** 2018-11-23 18:58 UTC
