### ISSUE TITLE
Make "crop guides" a global tool

### ISSUE THREAD

**Issue by ff2000** [Beep6581/RawTherapee#6090] opened 2021-02-02 05:54 UTC
Many transformations (like rotate, perspective, distortion) make it necessary to re-check if the subject still is positioned correctly according to the preferred composition rule. Having to move to the "crop" tool feels a little bit weird therefor.
I suggest to add a button to the quick operation icons (or even a keyboard shortcut) to quickly show/hide the guides. Long press on that button would open a popup menu to select the preferred crop guide.

**Comment by Thanatomanic** [comment] 2021-02-02 08:13
Duplicate of https://github.com/Beep6581/RawTherapee/issues/504

**Closed as completed by Thanatomanic** 2021-02-02 08:13 UTC
