### ISSUE TITLE
CIECAM02 - initial preview darker than subsequent preview or saved image

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3380] opened 2016-07-10 16:38 UTC
-- update 2016-08-18
See  [this later comment](https://github.com/Beep6581/RawTherapee/issues/3380#issuecomment-240696767) for easier steps to reproduce

--

Found a bug that was baffling me. Traced it down to the crop affecting the CIECAM02 tool.

1. Apply neutral to a photo, open it.
2. Drag a crop area which does not cover the full frame (or which does not cover the brightest areas), enable CIECAM02, take a screenshot.
https://i.imgur.com/3stZ1TV.jpg
3. Zoom in to 100%, zoom out, take another screenshot.
https://i.imgur.com/sM2OlPO.jpg

This example is not the most clear, but in some real-life photos I saw a huge difference between the first preview and saved image or subsequent zoom-in-zoom0-out previews. Using other tools can amplify this difference.

**Comment by heckflosse** [comment] 2016-07-10 16:54
Could this be related to https://github.com/Beep6581/RawTherapee/issues/2708 ?

**Comment by Beep6581** [comment] 2016-07-10 17:10
As far as I can see nothing points to that, as that issue (despite still being valid) does not use the crop tool, while reproducing this bug seems to rely on it.

**Comment by heckflosse** [comment] 2016-07-10 17:22
My guess is, that 2. shows the wrong result...

**Comment by Beep6581** [comment] 2016-07-10 17:29
I don't know which is correct, but the second one matches the saved image, and that's all that matters to me, since I use CIECAM02 for aesthetic reasons.

Another two examples:
http://i.imgur.com/qGlM9B3.jpg
http://i.imgur.com/S5oeHd2.jpg

As the zoom-in-zoom-out thing needs to be redone after every tool change (I tried changing only CIECAM02 Tone Curve 1), this makes using CIECAM02 almost guaranteed to render results inconsistent with the preview, therefore broken. For that reason it's a serious issue.

**Comment by heckflosse** [comment] 2016-07-10 17:33
I agree this being a serious issue but it also is an old issue (noone did change this code since a long time)...

**Comment by NextTherapist** [comment] 2016-08-17 07:30
I installed 4.2.1000 from Master branch and see something which is perhaps the same effect. The thumbnails of some (CIECAM tuned) images look very coloured (quietschbunt, as we say in German). When I open them as a single image from there, the first look of the opened image has the same artificial colours for about one second, and then it switches to the right colours.

But this did not occur in previous versions. 927 did not have that.

**Comment by heckflosse** [comment] 2016-08-17 09:41
@NextTherapist Can you post the changeset of 927 please (it's in preferences/About/Version). I can try then to search for the culprit.

**Comment by NextTherapist** [comment] 2016-08-17 10:21
@heckflosse 
I'm sorry, it was 922 - and I already uninstalled it. This attached 

file is from the installation zip.
[AboutThisBuild.txt](https://github.com/Beep6581/RawTherapee/files/422317/AboutThisBuild.txt)

**Comment by heckflosse** [comment] 2016-08-17 11:06
@NextTherapist Thanks for AboutThisBuild.txt :+1:

**Comment by heckflosse** [comment] 2016-08-17 20:43
While searching for the reason of this issue I made some performance improvements to ciecam01 (using default values). Currently it's 10% faster than before at my machine without differences in output.
Still did not find the reason for this issue because I'm not able to reproduce it.

Ingo

**Comment by Beep6581** [comment] 2016-08-17 21:11
@NextTherapist sounds like the display profile kicking in. If that's the case, its not a bug, but I would like RT to not display the color-unmanaged preview if a monitor profile is used, and instead just compute the managed preview.

**Comment by NextTherapist** [comment] 2016-08-18 07:20
This is definitely right, I am using a monitor profile in RT.

**Comment by NextTherapist** [comment] 2016-08-18 08:52
No... it also happens with monitor profile "none" in RT settings.

**Comment by Beep6581** [comment] 2016-08-18 11:29
In some cases (when I discovered the bug) the difference was much larger, but I don't remember which photo I was working on and I didn't want to upload it as it was a private portrait.

Turns out you don't need to crop.

A way to reproduce without screenshots:
1. Open any photo (SETM)
2. Enable CIECAM02.
3. Press "z" (zoom to 100%) and "f" (zoom to fit). You might notice a difference already here, though its not easy to see because for a moment you get the blocky low-res preview.
4. Double-click on the thumbnail of the photo in the Filmstrip to reload it. This re-calculates the preview without going blocky, making the difference obvious.

**Comment by Beep6581** [comment] 2016-08-18 11:30
1. Opened image:
![imgur-2016_08_18-13 28 26](https://cloud.githubusercontent.com/assets/5844619/17772207/d8f37ac4-6547-11e6-8c5a-605636e59a4b.png)

2. Enabled CIECAM02
![imgur-2016_08_18-13 28 31](https://cloud.githubusercontent.com/assets/5844619/17772208/d8f6a514-6547-11e6-898f-0c6594814640.png)

3. z f
![imgur-2016_08_18-13 28 37](https://cloud.githubusercontent.com/assets/5844619/17772206/d8f3227c-6547-11e6-8e3d-c57b85bfda41.png)

**Comment by heckflosse** [comment] 2016-08-18 19:43
Oups, double # didn't close this.

**Closed by heckflosse** 2016-08-18 19:43 UTC
Labels: bug
