### ISSUE TITLE
Support for JPEG-compressed DNG files

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4285] opened 2018-01-08 16:41 UTC
Request from:
https://discuss.pixls.us/t/compressed-dng-support/6370

Raw file:
https://raw.pixls.us/getfile.php/2204/nice/Canon%20-%20EOS%205D%20Mark%20III%20-%2014bit%20(2.3471882640587).dng

The DNG file seems to come from Magic Lantern and uses JPEG compression.

```text
-TIFF:ExifByteOrder=Little-endian (Intel, II)
-TIFF-IFD0:BitsPerSample=14
-TIFF-IFD0:Compression=JPEG
-TIFF-IFD0:Make=Canon
-TIFF-IFD0:Model=Canon EOS 5D Mark III
-TIFF-IFD0:Software=MLV App
-TIFF-IFD0:DNGVersion=1.4.0.0
```

**Comment by jedypod** [comment] 2018-07-09 01:40
I would love to see support for LJ92 compressed "Cinema DNG" files in RawTherapee.

I have some more example files and some information which may help push this forward:

Compressed Cinema DNG are created by a few different cameras:
- Digital Bolex D16
- Canon DSLR Magic Lantern raw (converted to CinemaDNG/DNG)
- BlackMagic Cinema Cameras

When opening these DNG files in RawTherapee, it has problems decoding the file. See this screenshot:
![rt-lj92-dng](https://user-images.githubusercontent.com/3261432/42426597-1789c8be-82f7-11e8-870c-64394606a579.png)

There is some useful information on LJ92 DNG compression here:
https://thndl.com/how-dng-compresses-raw-data-with-lossless-jpeg92.html

That post mentions a lj92 compression library that is open sourced as part of the MLVRawViewer project:
https://bitbucket.org/baldand/mlrawviewer/src/master/liblj92/?at=master

I have also uploaded a few more example compressed cinema dng files, included below, as well as uploaded to https://raw.pixls.us/

[cinemadng.tar.gz](https://github.com/Beep6581/RawTherapee/files/2174350/cinemadng.tar.gz)

I hope this helps! Thank you for your consideration!

**Comment by nvki** [comment] 2018-08-02 10:11
I would like to +1 this request as I'm having the same issue opening .dng files from my Blackmagic Pocket Cinema Camera. In addition to jeypod's example files I can add a example file with a color checker: [bmpcc_cinemadng](https://drive.google.com/open?id=1eVqBzSsnyRiuP7tw9Tv3Rs0_bWKIPdUG)

**Comment by Waveluke** [comment] 2018-11-06 17:41
I am also seeking a resolution to this request, primarily for my Blackmagic Pocket Cinema Camera, and can volunteer to hunt for someone who can do it if I can get the info of: How much of a time commitment will this project be? What sort of specific expertises within the vast world of Computer Science/ Coding are needed? 

Take note that I do not have any computer coding knowledge aside from basic and shaky web html, but an advanced understanding of digital photography from the photography side, and multiple social networks that I could potentially tap for talent to solve this issue.

**Comment by Waveluke** [comment] 2018-11-06 18:42
Update: someone at Pixls gave me the skillset info needed to recruit someone to work on this, but I would like to know, besides Pixls and here at GitHub, would there be any other options for me to get the my recruit in contact with the developers?

**Comment by paperdigits** [comment] 2018-11-06 18:47
Yes, #pixlsus or #rawtherapee on Freenode, which is IRC, a chat application.

**Comment by heckflosse** [comment] 2018-11-07 19:49
I take this issue. I test with Blackmagic files atm.

For reference the version using adobe dng converter:

![grafik](https://user-images.githubusercontent.com/13733487/48156519-dab0e800-e2cd-11e8-917c-c0b658429754.png)

The original dng file has two tiles (onle left, one right).
Here's a screenshot of my current mockup where the left tile already is decoded correctly. Don't care about the colours (matrix, white level...) atm. Decoding has to be done correctly first:

![grafik](https://user-images.githubusercontent.com/13733487/48156773-5b6fe400-e2ce-11e8-8a83-8917a1e11d82.png)

**Comment by Waveluke** [comment] 2018-11-08 04:28
Thanks so much.

So excited for native support!

Thanks,
Waveluke.

**Comment by Waveluke** [comment] 2018-11-08 04:34
I have the Blackmagic Pocket Cinema Camera on hand if anything else is needed, in terms of files, camera tests or other things.

**Comment by heckflosse** [comment] 2018-11-08 10:57
Now the right tile is also decoded:
![grafik](https://user-images.githubusercontent.com/13733487/48194405-32daff00-e34d-11e8-9d2f-3bb39f26ef75.png)

**Comment by heckflosse** [comment] 2018-11-08 16:41
@Waveluke Can you provide files as described [here](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats)?
If you have access to a ColorChecker, please also provide shots as described [here](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles#Shooting_the_Color_Target).

**Comment by heckflosse** [comment] 2018-11-08 20:07
With last commit I get 1.5x speed for decoding of dng files with 2 tiles (blackmagic pocket...), and triple speed for decoding of dng files with 8 tiles (blackmagic 4k) measured on my 8-core (files loaded from SSD)

**Comment by heckflosse** [comment] 2018-11-09 11:12
I added support for the Magic Lantern files.
Screenshot shows the raw from first post:

![grafik](https://user-images.githubusercontent.com/13733487/48259561-9b42e280-e418-11e8-9caf-42576c73b662.png)

**Comment by heckflosse** [comment] 2018-11-09 11:59
@jedypod Can you provide files from `Digital Bolex D16` ?

**Comment by heckflosse** [comment] 2018-11-09 13:46
Using linearization table gives much better colors for blackmagic files:

![grafik](https://user-images.githubusercontent.com/13733487/48265939-309ca180-e42e-11e8-9a3f-be621b38f2d8.png)

**Comment by Thanatomanic** [comment] 2018-11-09 13:48
@heckflosse I can try to get you a colour chart file from the black magic compact cinema. Would it matter that it wasn't shot under any controlled lighting or perfect exposure?

**Comment by heckflosse** [comment] 2018-11-09 13:53
@Thanatomanic Don't know. @Beep6581 knows

**Comment by heckflosse** [comment] 2018-11-09 14:32
With last commit the camera model is shown in info-dialog instead of `Unknown` for blackmagic cameras

![grafik](https://user-images.githubusercontent.com/13733487/48268185-9c820880-e434-11e8-93c1-c8b3066de967.png)

**Comment by heckflosse** [comment] 2018-11-09 17:43
Short status report:

I tested the latest code with all Canon DNG files I have (from Magic Lantern, Adobe DNG converter, Adobe Lightroom) as well as with all Blackmagic DNG files I have (straight out of camera and also converted using Adobe DNG converter). All decode correctly. Imho this issue can be set to 5.5 Milestone.

**Comment by Beep6581** [comment] 2018-11-09 18:21
@Thanatomanic 

> I can try to get you a colour chart file from the black magic compact cinema. Would it matter that it wasn't shot under any controlled lighting or perfect exposure?

That would be good. There's a good chance that it would improve the situation. I can judge whether they're usable once I see the file.

**Comment by Thanatomanic** [comment] 2018-11-09 18:28
How about these two? https://filebin.net/qgfqlh62gjsbls8j

**Comment by iliasg** [comment] 2018-11-09 19:32
Ingo !!!

Nice .. only one problem .. when we convert the in_camera DNG to "AdobeDNG" with adobe dng converter .. RT does not recognize the colormatrix2 of the new file. The colors are as if no color matrix is used.
BTW I am uploading in the above filebin the adobe converted files and the dcps I extracted from both the original and converted files.
Looks like both the dng converted and dcp tool somehow change the color matrices .. and adobe's matrix gives more reasonable WB values than BlackMagic's ..

**Comment by heckflosse** [comment] 2018-11-09 19:53
@iliasg 

> only one problem .. when we convert the in_camera DNG to "AdobeDNG" with adobe dng converter .. RT does not recognize the colormatrix2 of the new file

I didn't change that. Should be no difference for this case before/after changes

**Comment by iliasg** [comment] 2018-11-09 20:05
Yes it's same (wrong) as before :)

**Comment by heckflosse** [comment] 2018-11-09 20:12
@iliasg Decoding of native Blackmagic DNG files (without using Adone DNG converter) gives good results now imho. Do you agree that it's ready for 5.5 release?

**Comment by iliasg** [comment] 2018-11-09 20:43
@heckflosse Ingo yes .. it's almost ready for release .. waiting for a proper dcp profile (I cannot build one from the avaible shots :( )

I was wrong for the "more reasonable WB values" coming from "adobe's matrix" I mentioned before .. the "more reasonable" WB values is the result of RT not detecting the colormatrix2 in the converted file ..

BTW I think the extracted dcp gives better colors when used (it's a mystery for me because it olny consists the matrices !!) .. should we bundle the above dcp also ?.

**Comment by heckflosse** [comment] 2018-11-09 20:46
@iliasg Ilias, let me explain a bit more:

Blackmagic DNG files need to be processed fast (as there are a lot of them for one video). For that reason, native processing (without need to use Adobe DNG converter) is preferable to reduce processing time and storage space. 

@Waveluke may correct me if my assumption is wrong

**Comment by Thanatomanic** [comment] 2018-11-09 20:46
> (I cannot build one from the avaible shots :( )

@iliasg Unfortunately, I don't have access to the camera anymore, and cannot help (producing better shots if needed).

**Comment by heckflosse** [comment] 2018-11-09 20:47
@iliasg ping @Beep6581 for the dcp and the matrices. Let's wait for @Waveluke . He offered to provide images.

**Comment by Beep6581** [comment] 2018-11-09 21:34
Since one of the shots was taken using fluorescent light, a good dual-illuminant D50/StdA profile is not possible. However, I made one just for testing. I uploaded both to the bin:
https://filebin.net/qgfqlh62gjsbls8j

**Comment by Waveluke** [comment] 2018-11-09 21:51
"Blackmagic DNG files need to be processed fast (as there are a lot of them for one video). For that reason, native processing (without need to use Adobe DNG converter) is preferable to reduce processing time and storage space."

You are correct with that, and I am just seeking native support for proper decoding of CDNG files from the Blackmagic Pocket Camera, in time for v. 5.5 release, and if the colors are inaccurate, then I can correct them myself, using RTs powerful color correcting tools until someone does a proper dual illuminant DCP.

I do not have a color checker, but I was considering buying one anyway.  In the short term all I have is the camera, but no way of producing a color checker image, though I do have the knowhow to create color checker samples if I were to have a color checker.

**Comment by Waveluke** [comment] 2018-11-09 21:52
Any other things besides color checker shots I can provide, however.

**Comment by iliasg** [comment] 2018-11-09 21:59
@heckflosse Ingo, another feature which the cinemaDNG users will ask is to automatically crop at the default size .. here 1920x1080 .. RT does no use of the default origin/crop DNG tags .. we can either use camconst.json for this or improve RT's tag recognition and use ... what do you think ?.

**Comment by heckflosse** [comment] 2018-11-09 22:00
@Waveluke Which OS are you using? In case you use Windows, I can ask for a build of the Blackmagic branch...

**Comment by heckflosse** [comment] 2018-11-09 22:01
@iliasg Just set the raw border to 16 will be fine :) No need to use camconst.json for this

**Comment by heckflosse** [comment] 2018-11-09 22:01
@iliasg will be fine for the blackmagic file I meant

**Comment by Waveluke** [comment] 2018-11-09 22:03
Windows is correct.  As to the concern about not autocropping to 1920 by 1080, I like having access to the extra pixels for a slight recompose.  If a user is bothered by it, they can set a custom crop and save as a Blackmagic BMPCC processing profile, and load it whenever setting parameters for a BMPCC chain of stills.

**Comment by Waveluke** [comment] 2018-11-09 22:07
Apparently there is also this raw border crop feature in the new Rawtherapee as well, I do not think I saw it in 5.4 stable release.

**Comment by Beep6581** [comment] 2018-11-09 22:12
Another solution would be to use dynamic profiles. Once RT ships with some built-in dynamic profiles (#4488), handling the crop origin/size for the Blackmagic Pocket Cinema Camera would be trivial.

**Comment by heckflosse** [comment] 2018-11-09 22:34
@Waveluke 

>Apparently there is also this raw border crop feature in the new Rawtherapee as well, I do not think I saw it in 5.4 stable release.

Yes, that's a new feature in > 5.4 builds. That's what I refered to mentioning the 16 pix raw border above.

**Comment by iliasg** [comment] 2018-11-09 22:36
> 
> 
> @iliasg Just set the raw border to 16 will be fine :) No need to use camconst.json for this

OK looks fine for the BM samples we have .. but .. 
- I am sure there are cases where the border is not symmetric or maybe even the 16pixels is not enough ..
- It's a little faster if you start with the correct crop ;)

**Comment by Thanatomanic** [comment] 2018-11-09 22:37
@Beep6581 See https://filebin.net/qgfqlh62gjsbls8j 
I've added jpegs of `amsterdam.pef` with your DCP applied in various ways, and also jpegs of the daylight color chart with camera default and DCP applied. Was that what you wanted?

**Comment by Waveluke** [comment] 2018-11-09 22:47
Oh and the proper border for 1080 output for the BMPCC is 12 pixels not 16, at least the according to the misdecoded native BMPCC files and the properly decoded Adobe DNG converter files.  For both instances I have seen a resolution of 1944 by 1104, and subtract 1920 by 1080 from both dimensions and you get 24 extra pixels of width, and 24 extra pixels of height.  since there are two borders per dimension, that means each border should be 12 pixels.

However, if Adobe and the magenta artifact misinterpreted RT decode are BOTH throwing away the same number of pixels, then I stand corrected.

**Comment by iliasg** [comment] 2018-11-09 22:50
> 
> 
> Since one of the shots was taken using fluorescent light, a good dual-illuminant D50/StdA profile is not possible. However, I made one just for testing. I uploaded both to the bin:
> https://filebin.net/qgfqlh62gjsbls8j

@Beep6581 Fine !! .. do you have the spyder24 reference values available .. just to check a bit ..

**Comment by Waveluke** [comment] 2018-11-09 22:51
And full pixel readout should always be an option, so that footage can be stabilized in the NLE of the users choice and require a less intense crop.   Although I will say, center crop 540 by 960 upscaled to 1080p BMPCC footage raw developed in RT can look as sharp or sharper than native DSLR h264 captured full 1080p!

**Comment by Waveluke** [comment] 2018-11-09 22:52
RT developed BMPCC 1080p has certainly put me in the 4k is overrated camp!

**Comment by iliasg** [comment] 2018-11-09 23:01
> 
> 
> Oh and the proper border for 1080 output for the BMPCC is 12 pixels not 16, at least the according to the misdecoded native BMPCC files and the properly decoded Adobe DNG converter files. For both instances I have seen a resolution of 1944 by 1104, 

It's 1944 x 1104 after  cropping of the default 4pix border .. it's 1952 x 1112 originally ;)

**Comment by heckflosse** [comment] 2018-11-09 23:29
@Waveluke 

![grafik](https://user-images.githubusercontent.com/13733487/48293419-47b7af80-e47f-11e8-813e-b3b43e04cf81.png)

![grafik](https://user-images.githubusercontent.com/13733487/48293467-80f01f80-e47f-11e8-85f0-f89c05cc1ac7.png)

**Comment by iliasg** [comment] 2018-11-09 23:35
@heckflosse Ingo, where can I download the samples you use for your screenshots ?.

**Comment by heckflosse** [comment] 2018-11-09 23:36
@iliasg raw.pixls.us

**Comment by Waveluke** [comment] 2018-11-09 23:57
As I figured I might, I stand corrected.  But that is good news, for video stabilization and extreme low light where using a marginally bigger sensor area trumps sharpness loss of resampling.

**Comment by Waveluke** [comment] 2018-11-10 00:02
32 pixels doesn't sound like much, but on a 1080p camera, using them means gaining 1/20 of a stop of low light performance.

**Comment by heckflosse** [comment] 2018-11-10 00:13
I just merged blackmagic support into dev branch...

**Comment by heckflosse** [comment] 2018-11-10 20:58
@Waveluke 
> 32 pixels doesn't sound like much, but on a 1080p camera, using them means gaining 1/20 of a stop of low light performance.

I disagree. It just means that some border pixels are cropped. Except you don't crop them and scale down to 1920x1080 which doesn't sound like a good idea to me

**Comment by Thanatomanic** [comment] 2018-11-11 15:02
> 32 pixels doesn't sound like much, but on a 1080p camera, using them means gaining 1/20 of a stop of low light performance.

@Waveluke I have no idea why you think that. It's equally dark in the cropped areas, no?

I tested a workflow using a BMPCC raw clip as input (so, a series of DNGs), do some basic RT processing, apply the DCP and then export to 16 bit TIFF. I believe this works great.
There's two downsides:
- You need to pay attention to the color science - and I'm no expert in that. Choosing your output profile and color space, should match your input color space in your favorite NLE.
- You will triple the number of files on your disk (1 DNG, 1 PP3 and 1 TIF), and likely increase the disk space needed by a factor of ten or more. For moderately to large clips this gets really annoying. But I guess that's the price to pay for not doing your processing directly in your NLE 🤷‍♂️

**Comment by Waveluke** [comment] 2018-11-12 10:10
Davinci Resolve has a transcode media feature that is really quick to convert 16 bit tiff sequences into 10bit compressed movie files, and after the export, all but one pp3 file can be deleted.  Obviously a more complicated workflow, but the IQ results warrant it for loose deadline/artistic video.  Mostly, I noticed RT demosaicing to be superior to Resolve, and processing engine overall tend to get a more filmic result.  

As far as border pixels in low light, think of how you tend to notice noise less when you are further away, or when you stitch a panorama, or switch from a smaller sensor to larger sensor with same pixel pitch and sensor tech.  So the cleaner image from zooming out by a factor of 1.016 would be not much, but that would be squared.  Also, I was thinking more along the lines of border pixel using resampling in circumstanses where the 1 pixel by 1 pixel level of detail is swamped with noise so resampling makes no difference.  

I guess the above is more a theoretical musing than anything.  But border pixels are useful more realistically for slight recomposes and post stabilization of footage.

**Comment by Waveluke** [comment] 2018-11-15 23:28
Here are some overexposure tests for white levels of the BMPCC, as well as some documentation of technical issues with the BMPCC that might complicate the issue (or might not, this is not my expertise as I am doing this at the directive of a developer).

Here are the the raw files for white point calibration, shot with a tungsten light source for smooth spectrum lightsource, filming while moving the light closer and further away to change exposure. I shined it in a way to make a slight gradient in light level across the white paper I was shooting for this test. The subject was out of focus, so that any fine detail could be attributable to camera sensor and image pipeline artifacts.

Although the request is for one 1-2 stop overexposed raw file, I decided to give you multiple, because I noticed a few issues that might complicate figuring out white points. First, I noticed a weird fixed pattern grain in highlights very close to or at clipping (not 100% shure as I don’t have Rawdigger, the most accurate way of assessing), and it is observable even when it is safe to say the files are being correctly decoded (camera original files pixel peeped in Davinci Resolve). Note this is not an issue that warrants trying to do lots of trouble shooting to fix, as it is only visible at 100% or more with excessive sharpening, and is likely pretty easy to fix in most pro NLE video editors. I also noticed that the rgb channel levels, according to the waveforms in Davinci Resolve (Again, disclaimer, this is not Raw Digger), seem to reach a pseudo-saturation point (Example file labeled 4 Saturation light.dng), with an observable variance of the levels, depending on the pixel. As the overexposure rises further, the flat lines of levels rise just a little bit, as well as getting just a little less variance in values (5 Saturation Heavy.dng).

Edit: Heckflosse confirmed that the raw file labeled "5 Saturation Heavy.dng" wasn't fully saturated, so I uploaded another shot directly into a 100 watt tungsten bulb labeled "7 Directly into the bulb.dng".  As the compressed raw file is only 274 kilobytes large, (for reference these files tend to be 1.6-2.2 megabytes depending on compression), I think it is safe to say that the file is fully clipped, (I have been proved wrong on saturation levels before and I don't have rawdigger, so take this with a grain of salt).  

https://drive.google.com/open?id=11gbxOLWAj7mMo5AXGX9VpcgFfGADXUM3

**Comment by iliasg** [comment] 2018-11-16 11:42
@heckflosse Ingo, with "none demosaic" we can read raw values at navigator .. are these values before WL (=51080) cutoff ? I read max = 51064 which comes from 51320-256 (51320 is the raw clipping value and 256 is the BlackLevel) .. 

@Waveluke can you show a screenshot of this "fixed pattern grain" you mentioned ?. Is it like 
![prnuorrollingshutter](https://user-images.githubusercontent.com/15012599/48619469-47e70c00-e9a5-11e8-83f5-642d5046abcf.jpg)

This looks like RollingShutter's interaction with flickering lights ..

**Comment by heckflosse** [comment] 2018-11-16 13:10
@iliasg Ilias, the values are after blacklevel subtraction. Would it be beter to show the values before bl subtraction?

**Comment by iliasg** [comment] 2018-11-16 15:14
@heckflosse Ingo, I think it's better as it is with the black level because we can read the negative values. So we have both the BL indication without clipping any values below black ..

I asked about the **WhiteLevel** where we read the raw values as if the "WhiteLevel" is innactive .. 
With the BMPCC overexposed files the white level is 51080 and after BL subtraction the max value that is used by RT is 50824 .. 

I am not sure if clipping the displayed value at WL is better than the currently displayed value .. I would prefer a solution where both the WL value and the values above it are clearly identified (still scratching my head to find a **compact** way of dispaying this ..)

If we also had a presentation in 0-1 range we could have the above WL values as at the >1.0 range so that the indication of the used WL is clear

**Comment by Waveluke** [comment] 2018-11-16 18:14
@iliasg I agree that the low frequency vertical pattern observed is a combination of rolling shutter and flicker, but the fixed pattern grain I was referring to occurs at the pixel by pixel level, and doesn't change between frames, and has been observed in natural light, as well as artificial, and doesn't vary between frames, like photon variance noise does, but only occurs near clipping whites.  Demo screenshots upcoming.

**Comment by nvki** [comment] 2018-11-25 18:14
@heckflosse How are you linearizing the BMDFilm log? I tried getting a description of their log space from BMD directly (for use in nuke) but they wouldnt give me anything.

**Comment by heckflosse** [comment] 2018-11-25 18:28
@nvki I just use the linearization table in the DNG file

**Comment by nvki** [comment] 2018-11-26 01:31
@heckflosse Did you use exiftool to extract it? I wanted to use it for videos shot with the camera, which dont have it embedded and I am unsure how to view that information in the dng.

**Comment by heckflosse** [comment] 2018-11-26 12:00
@nvki Fortunately dcraw code already read the linearization table. I just had to use it. The DNG files have the linearization table embedded:

https://raw.pixls.us/getfile.php/970/exif/Blackmagic%20URSA_1_1999-12-31_2153_C0003_000001.dng.exif.txt

https://raw.pixls.us/getfile.php/2433/exif/Blackmagic_Pocket_Cinema_Camera_1_2016-09-17_0053_C0022_000007.dng.exif.txt

**Comment by nvki** [comment] 2018-11-27 20:35
@heckflosse Thank you!

**Comment by heckflosse** [comment] 2018-11-27 20:52
@nvki @Waveluke @jedypod Ok to close this issue now?

**Closed as completed** 2018-11-29 17:29 UTC
Labels: type: enhancement, scope: file format
