### ISSUE TITLE
Visibility of Profile Names

### ISSUE THREAD

**Issue by Kakupakat** [Beep6581/RawTherapee#4104] opened 2017-09-25 18:18 UTC
The "Dynamic Profiles Rules" tool introduced by @agriggio is great and works fine. Unfortunately it gives no feedback that it did actually work. In the processing profiles dropdown you won't see the name of the profile it loaded. Instead it says "(Last saved)." Which I don't think is correct anyway. Last saved? I just opened RT and have never touched this raw image before... 
So, to make sure the correct profile was loaded, you have to check all the options you set in the profile you created for automatic loading. Sure, after a while you will know that the profile you wanted was loaded, but at the beginning, when you are setting up the profiles, it does get a bit confusing.
Please make the name of the profile, that was automatically loaded, appear in the processing profiles dropdown.

Similarly, in the Color tab, under Color Management, please show which camera profile was loaded when "Auto-matched camera profile" is used. It would be more reassuring.

**Comment by olhof** [comment] 2017-09-26 15:37
This is a very good idea. I made a special very "dark" profile while setting up the rules for selection of the dynamic profile so it was apparent if it worked as intended or not. When I was satisfied that it worked as intended I changed the profile in the rules. But this is not as elegant as your solution.....

**Comment by agriggio** [comment] 2017-09-26 16:41
the problem is that in general dynamic rules apply multiple partial profiles in sequence. that was the typical use case I had in mind when I implemented this, and in fact I typically have 5-6 partial profiles that get applied for each shot. in this case, there's no single name to display.
but I agree that having some form of feedback would be nice...

**Comment by Kakupakat** [comment] 2017-09-26 17:15
Ok, I think it is a rather complicated way of doing things, especially for your average user, but it is certainly valid and it gives you a lot of control.
Since "there's no single name to display," why not display all of them? This could be done in a separate information widget or maybe in the history. Now it only says "Photo loaded - (Last saved)" in the history. Could you possibly list all the applied (partial) profiles there? In the processing profiles dropdown it could state the name of the profile, if it is only one or something like "multiple profiles, see history" when several partial profiles are loaded.

**Comment by agriggio** [comment] 2017-09-26 20:57
@Kakupakat thanks for the suggestion, I'll have to think about how feasible that is. The "information widget" might be a reasonable way to go.

**Comment by agriggio** [comment] 2017-11-16 12:06
ok, but unlikely to happen anytime soon...

**Comment by Beep6581** [comment] 2017-11-16 12:19
> ok, 

@agriggio by assigning you I didn't mean to imply that you should do this nor that I even think doing this is a good idea, I only did that because this is nearest to your area of interest and indeed you already expressed interest. Up to you whether to keep this or close it.

**Comment by agriggio** [comment] 2017-11-16 12:24
it would be nice to have, but there are a lot of things that are way more interesting/useful...

**Comment by olhof** [comment] 2017-11-18 09:50
It is an interesting technique to use several  partial profiles. But how do I create a partial profile only containing say sharpening settings? “Processing Profile Selector” in Rawpedia doesn’t explain this.

And where do I find a list of the default positions?

**Comment by heckflosse** [comment] 2017-11-18 10:41
@olhof It is explained [here](http://rawpedia.rawtherapee.com/Creating_processing_profiles_for_general_use)

**Comment by olhof** [comment] 2017-11-23 19:49
Thank you.
I have reread the section “partial processing profiles”. 
Since I started using Rawtherapee this year the subject of partial profiles has been somewhat of a mystery to me.
Now I understand the concept of partial profiles as follows. 
When you open a new, never edited photo in the editor a full profile is always established. If the profile specified as the default in the “Preferences” is only partial then RT will replace the missing values with hard-coded defaults, so a full profile is established, no matter what the status of the “Processing profile fill mode” is. 
If you open a photo in the editor you can afterwards load a profile. If the profile you load is partial then the “Processing profile fill mode” controls, which values of the current profile that will be replaced by the profile you load. You can choose only to replace the values the profile you load contains or you can replace the current profile by a full new profile consisting of the partial profile you load and hardcoded defaults for the missing values. 
You can establish a partial profile by ctrl-click and select the values you wish to save when you save the current profile. When you exit RT a full profile is saved as a pp3-file belonging to the photo in question.  
Right?
This seems all very logical once you have learned how it works but it is less logical when you are new to RT and read the documentation for the first time...:o)!

**Comment by agriggio** [comment] 2017-11-24 09:34
@olhof that is all correct :+1: 
If you have suggestions for how to improve RawPedia, they are more than welcome!

**Comment by olhof** [comment] 2017-11-24 10:16
Hi' Alberto Griggio
I will try to write a suggestion to improve the RawPedia documentation regarding profiles/partial profiles. How should I forward it?

**Comment by Beep6581** [comment] 2017-11-24 12:28
Here is fine.

**Comment by olhof** [comment] 2017-11-29 08:54
I have written a new version of “Sidecar Files - Processing Profiles”. 

You can find it by following this link:
https://1drv.ms/w/s!Ag3mjK0RkQdnsk22-to-olX7E7G8

What do you think?
It may be obvious that I am Danish and not a native English speaking individual. I can have the text edited by an American relative so the text will be in perfect English if you want to use it.

**Comment by Beep6581** [comment] 2017-12-26 14:30
I made a major update to http://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles and related articles loosely based on @olhof's input.

**Closed as completed by Beep6581** 2017-12-26 14:30 UTC
Labels: type: enhancement, patch provided, external: RawPedia

**Comment by olhof** [comment] 2017-12-27 09:29
I have read the revised article on Sidecar-Files-Processing. Very good indeed, a big improvement to the Rawpedia text and much better than my draft (I also learned something new from reading the revised article). 
It has been a pleasure to work with you guys……:o)!
