### ISSUE TITLE
5.6 AppImage does not run in Ubuntu 14.04

### ISSUE THREAD

**Issue by gaudry-daniel** [Beep6581/RawTherapee#5299] opened 2019-04-23 15:44 UTC
Hi I used the 5.4 version with no problem but the newest one gives me this : any help is welcome

```
daniel@daniel-B85M-DS3H:/media/daniel/18437ae6-7090-43fe-ad0a-c91a3f64e582/rt5.6$ ./RawTherapee-releases-5.6-20190420.bin 
AILIBDIR=/tmp/tmp.aIn2wY3HJs
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.25"
Bundled stdc++ library version: "3.4.19"
Newest stdc++ library version: "3.4.25"
Using system stdc++ library
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0" (libfontconfig.so.1.8.0)
  system library version: 1.8.0
/tmp/.mount_RawTheKYGxTU/apprun-helper.sh: line 105: realpath: command not found
  ailib: ""
  bundled library version: 
  newest library version: "1.8.0"
Removing bundled "libfontconfig"
removed ‘/tmp/tmp.aIn2wY3HJs/libfontconfig.so.1’
removed ‘/tmp/tmp.aIn2wY3HJs/libfontconfig.so.1.11.1’
Checking versions of library "libfreetype"
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.11.1" (libfreetype.so.6.11.1)
  system library version: 6.11.1
/tmp/.mount_RawTheKYGxTU/apprun-helper.sh: line 105: realpath: command not found
  ailib: ""
  bundled library version: 
  newest library version: "6.11.1"
Removing bundled "libfreetype"
removed ‘/tmp/tmp.aIn2wY3HJs/libfreetype.so.6’
removed ‘/tmp/tmp.aIn2wY3HJs/libfreetype.so.6.14.0’
DO_UPDATE: 1
GTK_PATH=/tmp/.mount_RawTheKYGxTU/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_RawTheKYGxTU/usr/lib/gtk-2.0:/tmp/.mount_RawTheKYGxTU/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_RawTheKYGxTU/usr/lib
/tmp/.mount_RawTheKYGxTU/usr/bin/rawtherapee: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatk-bridge-2.0.so.0)
/tmp/.mount_RawTheKYGxTU/usr/bin/rawtherapee: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatspi.so.0)
        linux-vdso.so.1 =>  (0x00007ffc713fc000)
        libcanberra-gtk3.so.0 => /tmp/tmp.aIn2wY3HJs/libcanberra-gtk3.so.0 (0x00007f44b6998000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f44b6663000)
        libcanberra.so.0 => /tmp/tmp.aIn2wY3HJs/libcanberra.so.0 (0x00007f44b6452000)
        libgtk-3.so.0 => /tmp/tmp.aIn2wY3HJs/libgtk-3.so.0 (0x00007f44b5b3b000)
        libgdk-3.so.0 => /tmp/tmp.aIn2wY3HJs/libgdk-3.so.0 (0x00007f44b584d000)
        libatk-1.0.so.0 => /tmp/tmp.aIn2wY3HJs/libatk-1.0.so.0 (0x00007f44b5627000)                                                                                                                             
        libgio-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libgio-2.0.so.0 (0x00007f44b5288000)                                                                                                                             
        libpangocairo-1.0.so.0 => /tmp/tmp.aIn2wY3HJs/libpangocairo-1.0.so.0 (0x00007f44b507a000)                                                                                                               
        libgdk_pixbuf-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libgdk_pixbuf-2.0.so.0 (0x00007f44b4e52000)                                                                                                               
        libcairo-gobject.so.2 => /tmp/tmp.aIn2wY3HJs/libcairo-gobject.so.2 (0x00007f44b4c49000)                                                                                                                 
        libpango-1.0.so.0 => /tmp/tmp.aIn2wY3HJs/libpango-1.0.so.0 (0x00007f44b4a03000)                                                                                                                         
        libcairo.so.2 => /tmp/tmp.aIn2wY3HJs/libcairo.so.2 (0x00007f44b46cc000)                                                                                                                                 
        libgobject-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libgobject-2.0.so.0 (0x00007f44b447c000)                                                                                                                     
        libglib-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libglib-2.0.so.0 (0x00007f44b4166000)                                                                                                                           
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f44b3f3c000)                                                                                                                               
        libatomic.so.1 => /tmp/tmp.aIn2wY3HJs/libatomic.so.1 (0x00007f44b3d34000)                                                                                                                               
        libfftw3f.so.3 => /tmp/tmp.aIn2wY3HJs/libfftw3f.so.3 (0x00007f44b39bb000)                                                                                                                               
        libfftw3f_omp.so.3 => /tmp/tmp.aIn2wY3HJs/libfftw3f_omp.so.3 (0x00007f44b37b4000)                                                                                                                       
        libgiomm-2.4.so.1 => /tmp/tmp.aIn2wY3HJs/libgiomm-2.4.so.1 (0x00007f44b33f5000)                                                                                                                         
        libglibmm-2.4.so.1 => /tmp/tmp.aIn2wY3HJs/libglibmm-2.4.so.1 (0x00007f44b3173000)                                                                                                                       
        libsigc-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libsigc-2.0.so.0 (0x00007f44b2f6c000)
        libgthread-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libgthread-2.0.so.0 (0x00007f44b2d6a000)
        libgtkmm-3.0.so.1 => /tmp/tmp.aIn2wY3HJs/libgtkmm-3.0.so.1 (0x00007f44b25bc000)
        libatkmm-1.6.so.1 => /tmp/tmp.aIn2wY3HJs/libatkmm-1.6.so.1 (0x00007f44b236e000)
        libgdkmm-3.0.so.1 => /tmp/tmp.aIn2wY3HJs/libgdkmm-3.0.so.1 (0x00007f44b211a000)
        libpangomm-1.4.so.1 => /tmp/tmp.aIn2wY3HJs/libpangomm-1.4.so.1 (0x00007f44b1eec000)
        libcairomm-1.0.so.1 => /tmp/tmp.aIn2wY3HJs/libcairomm-1.0.so.1 (0x00007f44b1cc6000)
        libiptcdata.so.0 => /tmp/tmp.aIn2wY3HJs/libiptcdata.so.0 (0x00007f44b1aba000)
        libjpeg.so.62 => /tmp/tmp.aIn2wY3HJs/libjpeg.so.62 (0x00007f44b1865000)
        liblcms2.so.2 => /tmp/tmp.aIn2wY3HJs/liblcms2.so.2 (0x00007f44b160b000)
        libpng15.so.15 => /tmp/tmp.aIn2wY3HJs/libpng15.so.15 (0x00007f44b13e0000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f44b11c7000)
        libtiff.so.5 => /tmp/tmp.aIn2wY3HJs/libtiff.so.5 (0x00007f44b0f50000)
        liblensfun.so.1 => /tmp/tmp.aIn2wY3HJs/liblensfun.so.1 (0x00007f44b0d33000)
        librsvg-2.so.2 => /tmp/tmp.aIn2wY3HJs/librsvg-2.so.2 (0x00007f44b0afe000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f44b07f8000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f44b04e2000)
        libgomp.so.1 => /tmp/tmp.aIn2wY3HJs/libgomp.so.1 (0x00007f44b02bc000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f44b00a4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f44afe86000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44afabd000)
        libvorbisfile.so.3 => /tmp/tmp.aIn2wY3HJs/libvorbisfile.so.3 (0x00007f44af8b4000)
        libvorbis.so.0 => /tmp/tmp.aIn2wY3HJs/libvorbis.so.0 (0x00007f44af687000)
        libogg.so.0 => /tmp/tmp.aIn2wY3HJs/libogg.so.0 (0x00007f44af480000)
        libtdb.so.1 => /tmp/tmp.aIn2wY3HJs/libtdb.so.1 (0x00007f44af269000)
        libltdl.so.7 => /tmp/tmp.aIn2wY3HJs/libltdl.so.7 (0x00007f44af05f000)
        libxcb.so.1 => /tmp/tmp.aIn2wY3HJs/libxcb.so.1 (0x00007f44aee37000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44aec33000)
        libgmodule-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libgmodule-2.0.so.0 (0x00007f44aea2f000)
        libXi.so.6 => /tmp/tmp.aIn2wY3HJs/libXi.so.6 (0x00007f44ae81f000)
        libXfixes.so.3 => /tmp/tmp.aIn2wY3HJs/libXfixes.so.3 (0x00007f44ae619000)
        libatk-bridge-2.0.so.0 => /tmp/tmp.aIn2wY3HJs/libatk-bridge-2.0.so.0 (0x00007f44ae3ea000)
        libwayland-client.so.0 => /tmp/tmp.aIn2wY3HJs/libwayland-client.so.0 (0x00007f44ae1db000)
        libepoxy.so.0 => /tmp/tmp.aIn2wY3HJs/libepoxy.so.0 (0x00007f44adeaf000)
        libpangoft2-1.0.so.0 => /tmp/tmp.aIn2wY3HJs/libpangoft2-1.0.so.0 (0x00007f44adc99000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f44ada5d000)
        libXinerama.so.1 => /tmp/tmp.aIn2wY3HJs/libXinerama.so.1 (0x00007f44ad85a000)
        libXrandr.so.2 => /tmp/tmp.aIn2wY3HJs/libXrandr.so.2 (0x00007f44ad64f000)
        libXcursor.so.1 => /tmp/tmp.aIn2wY3HJs/libXcursor.so.1 (0x00007f44ad444000)
        libXcomposite.so.1 => /tmp/tmp.aIn2wY3HJs/libXcomposite.so.1 (0x00007f44ad241000)
        libXdamage.so.1 => /tmp/tmp.aIn2wY3HJs/libXdamage.so.1 (0x00007f44ad03e000)
        libxkbcommon.so.0 => /tmp/tmp.aIn2wY3HJs/libxkbcommon.so.0 (0x00007f44acdfe000)
        libwayland-cursor.so.0 => /tmp/tmp.aIn2wY3HJs/libwayland-cursor.so.0 (0x00007f44acbf6000)
        libwayland-egl.so.1 => /tmp/tmp.aIn2wY3HJs/libwayland-egl.so.1 (0x00007f44ac9f4000)
        libXext.so.6 => /tmp/tmp.aIn2wY3HJs/libXext.so.6 (0x00007f44ac7e2000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f44ac5da000)
        libffi.so.6 => /tmp/tmp.aIn2wY3HJs/libffi.so.6 (0x00007f44ac3d2000)
        libpcre.so.1 => /tmp/tmp.aIn2wY3HJs/libpcre.so.1 (0x00007f44ac170000)
        libselinux.so.1 => /tmp/tmp.aIn2wY3HJs/libselinux.so.1 (0x00007f44abf49000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f44abd2e000)
        libmount.so.1 => /tmp/tmp.aIn2wY3HJs/libmount.so.1 (0x00007f44abaeb000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f44ab848000)
        libpixman-1.so.0 => /tmp/tmp.aIn2wY3HJs/libpixman-1.so.0 (0x00007f44ab59f000)
        libEGL.so.1 => /tmp/tmp.aIn2wY3HJs/libEGL.so.1 (0x00007f44ab38b000)
        libxcb-shm.so.0 => /tmp/tmp.aIn2wY3HJs/libxcb-shm.so.0 (0x00007f44ab187000)
        libxcb-render.so.0 => /tmp/tmp.aIn2wY3HJs/libxcb-render.so.0 (0x00007f44aaf79000)
        libXrender.so.1 => /tmp/tmp.aIn2wY3HJs/libXrender.so.1 (0x00007f44aad6e000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f44aaade000)
        libthai.so.0 => /tmp/tmp.aIn2wY3HJs/libthai.so.0 (0x00007f44aa8d2000)
        libfribidi.so.0 => /tmp/tmp.aIn2wY3HJs/libfribidi.so.0 (0x00007f44aa6b6000)
        liblzma.so.5 => /tmp/tmp.aIn2wY3HJs/liblzma.so.5 (0x00007f44aa490000)
        libcroco-0.6.so.3 => /tmp/tmp.aIn2wY3HJs/libcroco-0.6.so.3 (0x00007f44aa255000)
        libxml2.so.2 => /tmp/tmp.aIn2wY3HJs/libxml2.so.2 (0x00007f44a9eeb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f44b6b9d000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f44a9cb2000)
        libXau.so.6 => /tmp/tmp.aIn2wY3HJs/libXau.so.6 (0x00007f44a9aae000)
        libatspi.so.0 => /tmp/tmp.aIn2wY3HJs/libatspi.so.0 (0x00007f44a987d000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f44a9638000)
        libharfbuzz.so.0 => /tmp/tmp.aIn2wY3HJs/libharfbuzz.so.0 (0x00007f44a939b000)
        libblkid.so.1 => /tmp/tmp.aIn2wY3HJs/libblkid.so.1 (0x00007f44a915b000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f44a8f56000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f44a8d30000)
        libGLdispatch.so.0 => /tmp/tmp.aIn2wY3HJs/libGLdispatch.so.0 (0x00007f44a8a7a000)
        libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f44a8851000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f44a864f000)
        libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f44a8438000)
        libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f44a8233000)
        libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f44a8030000)
        libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f44a7e2d000)
        libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f44a7c27000)
        libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f44a7a25000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f44a781f000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f44a7611000)
        libgraphite2.so.3 => /tmp/tmp.aIn2wY3HJs/libgraphite2.so.3 (0x00007f44a73e3000)

==========

LD_LIBRARY_PATH: /tmp/tmp.aIn2wY3HJs:/usr/lib::/tmp/.mount_RawTheKYGxTU/usr/lib/gdk-pixbuf-2.0/loaders
DIRNAME: /tmp/.mount_RawTheKYGxTU/usr/bin
DESKTOPFILE_NAME: rawtherapee.desktop
APP_FULL: RawTherapee
APP: RawTherapee
APP_FULL: RawTherapee
APP: RawTherapee
BIN: /tmp/.mount_RawTheKYGxTU/usr/bin/rawtherapee
DESKTOPINTEGRATION: 
HERE!!!
zenity: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatk-bridge-2.0.so.0)
zenity: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatspi.so.0)
zenity: symbol lookup error: /tmp/tmp.aIn2wY3HJs/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenTypeDouble
yesno finished
zenity: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatk-bridge-2.0.so.0)
zenity: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatspi.so.0)
zenity: symbol lookup error: /tmp/tmp.aIn2wY3HJs/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenTypeDouble
yesno finished
/tmp/.mount_RawTheKYGxTU/usr/bin/rawtherapee: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatk-bridge-2.0.so.0)
/tmp/.mount_RawTheKYGxTU/usr/bin/rawtherapee: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/tmp.aIn2wY3HJs/libatspi.so.0)
/tmp/.mount_RawTheKYGxTU/usr/bin/rawtherapee: symbol lookup error: /tmp/tmp.aIn2wY3HJs/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenTypeDouble
daniel@daniel-B85M-DS3H:/media/daniel/18437ae6-7090-43fe-ad0a-c91a3f64e582/rt5.6$ 
```

**Comment by Beep6581** [comment] 2019-04-23 16:56
What is `RawTherapee-releases-5.6-20190420.bin`? Where did you get it from? What is its hash (MD5, SHA1, whatever)? What distro and version are you running? What did you have for dinner? http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by gaudry-daniel** [comment] 2019-04-23 17:56
HI
Sorry
uname -r
3.16.0-77-generic
md5sum RawTherapee-releases-5.6-20190420.bin 
545181e4515d059fb532bb887e9c636d  RawTherapee-releases-5.6-20190420.bin
lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
Nothing to eat yet!

**Comment by Beep6581** [comment] 2019-04-23 21:53
So `RawTherapee-releases-5.6-20190420.bin` is https://github.com/Beep6581/RawTherapee/releases/download/nightly/RawTherapee-releases-5.6-20190420.AppImage

Ping @aferrero2707

**Comment by Beep6581** [comment] 2019-04-23 21:56
Confirmed that that AppImage does not run in a freshly installed 14.04.6. Worth noting that 14.04 is originally from 2015, so I'm not sure we need to bend over backwards to support it.

**Comment by aferrero2707** [comment] 2019-04-25 13:15
@gaudry-daniel @Beep6581 the root of the problem is here:
```
/tmp/.mount_RawTheKYGxTU/apprun-helper.sh: line 105: realpath: command not found
```
The `realpath` command is needed to determine the version of the bundled `fontconfig` library, and select it if it is newer than the one provided with the system.

This is exactly the case in 14.04, and generates the symbol lookup error:
```
symbol lookup error: /tmp/tmp.aIn2wY3HJs/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenTypeDouble
```
Installing the `realpath` command (`sudo apt-get install realpath`) should fix the problem, and allow you to run RT-5.6 on Ubuntu 14.04

**Comment by Beep6581** [comment] 2019-04-25 18:49
Fix confirmed.

@aferrero2707 ok to close?

**Comment by aferrero2707** [comment] 2019-04-26 08:18
Yes, we can close this. Meanwhile I will see if it is possible to get rid of `realpath` in the AppImage startup scripts...

**Closed as completed** 2019-04-26 12:54 UTC

**Comment by gaudry-daniel** [comment] 2019-04-26 15:40
Hi
So many thanks
Problem solved by realpath
Regards
