### ISSUE TITLE
Parametric curve clips at some positions

### ISSUE THREAD

**Issue by paulmatthijsse** [Beep6581/RawTherapee#6193] opened 2021-04-01 15:29 UTC
Hello, I noticed again (had been reported in 2015!) a clipping problem with the parametric curve in the exposure section. Set the Shadows slider to +1, drag the right control point under the curve to the right to position +1.00, the middle control point somewhere to the left and the curve clips, so the image. Clipping starts with the right point at 0.93. See attachment.

![rt_param_curve_clips](https://user-images.githubusercontent.com/14089212/113317329-9051bb00-930f-11eb-9985-f7dbe47f3807.jpg)

Version: 5.8-2833-ge98288ab3
Branch: dev

**Comment by arturoisilvia** [comment] 2021-04-01 17:41
@paulmatthijsse 
In 2015 and also here: https://github.com/Beep6581/RawTherapee/issues/5859
Greetings.

**Comment by paulmatthijsse** [comment] 2021-04-02 09:08
Hello @arturoisilvia, I have been searching for "parametric curve" but your ticket didn't show up for some reason. We are indeed talking about the same thing. 
Regards, Paul.

**Comment by Beep6581** [comment] 2021-04-03 08:33
Closing as duplicate of #5859

**Closed as completed by Beep6581** 2021-04-03 08:33 UTC
