### ISSUE TITLE
Preferences not displayed in latest Rawtherapee (5.7, FR) on Windows 10 (x64)

### ISSUE THREAD

**Issue by Vordalf** [Beep6581/RawTherapee#5597] opened 2020-01-04 15:32 UTC
Hello, the preferences are not displayed correctly in the latest Rawtherapee (5.7, in French language) on Windows 10 (x64). The top tabs of the "Preferences" window are displayed correctly, but clicking on any of them just displays one line below (nothing that can be set or clicked). I had Raw Therapee 4.2 previously on that PC.

**Comment by heckflosse** [comment] 2020-01-04 18:09
Can you post some screenshots please?

**Comment by Vordalf** [comment] 2020-01-04 20:39
![RawTherapee - preferences](https://user-images.githubusercontent.com/59508947/71771417-b638b600-2f3a-11ea-8f80-356c061ff0d1.jpg)

**Comment by Vordalf** [comment] 2020-01-04 20:40
Screenshot posted.

**Comment by Thanatomanic** [comment] 2020-01-06 20:07
@Vordalf I cannot reproduce when setting the language to French. 
But this window is resizable. Can you try to enlarge the preferences and see if that solves the issue?
![image](https://user-images.githubusercontent.com/6567747/71845400-8ae3d180-30c8-11ea-9698-f502b0cccc9d.png)

**Comment by Vordalf** [comment] 2020-01-06 20:28
Hello, thanks a lot for your help. Yes, resizing worked, and I can access all parameters. Now, that's still really a bug, because by default the window is so thin, that it looks like something is not working. The window should be larger (vertically) upon first display. I'll survive without a fix.

**Comment by Thanatomanic** [comment] 2020-01-08 19:22
Unless someone else experiences this, will close it for now.

**Closed as completed by Thanatomanic** 2020-01-08 19:22 UTC

**Comment by Beep6581** [comment] 2020-01-15 16:01
> Now, that's still really a bug, because by default the window is so thin

That is not the default behavior. Probably you had some left-over settings from your old version of RawTherapee, or Windows did some remembering of its own.

**Comment by Vordalf** [comment] 2020-01-15 16:17
I had RawTherapee 4 installed before the v5. As far as I remember, I uninstalled the v4, before installing the v5. I doubt I had hidden the parameters in the v4. But it is probably related to that v4 version indeed.
