### ISSUE TITLE
Icons in Gtk3 builds for Windows

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3046] opened 2015-12-29 23:00 UTC
Now I can run RT - Gtk3 in Windows. To remove most warnings regarding missing icons, I had to install icons from Adwaita and hicolor in the `/share/icons` folder in the RT install directory. But I still have a couple icons missing:
![Imgur](http://i.imgur.com/lHgIns9.jpg)

**Comment by sguyader** [comment] 2015-12-30 01:13
If I don't copy the `hicolor` icons in the RT /share/icons folder, I get this warning in the console:
```
(rawtherapee.exe:2264): Gtk-WARNING **: Could not find the icon 'pan-down-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
```
If I copy the icons, the warning disappears, but I don't see any difference. And in the `hicolor` folder I can't find any icon starting with `pan-down-symbolic`.

As the `Adwaita` icon set by itself takes at least 15MB of disk space, copying the hole set into the RT directory is not a great solution. Is there a way to select only the icons which are needed?

**Comment by sguyader** [comment] 2015-12-31 00:12
I put gtk3 builds for Windows 64 bits on my google drive (https://drive.google.com/folder/d/0B_AvPFlUj8t5SUdodURGOFdOems/edit) in the 'Win64_Gtk3' folder, for those who want to test.

**Comment by Beep6581** [comment] 2015-12-31 01:15
@sguyader in Linux, Ctrl+Shift+i or Ctrl+Shift+d would launch "Gtk+ Inspector", it comes bundled with Gtk3, and you could probably find out icon names from that. Does it work on Windows? Run the Gtk3 build of RawTherapee and at any moment press one of those shortcuts (whichever works), the window should magically appear.

**Comment by sguyader** [comment] 2015-12-31 02:11
@Beep6581 I did what you said, the shortcuts indeed work in Windows too. When I browse in the Visual tab of the inspector Window, I find references to some gtk icons (such as `gtk-edit.png`) but these are ot present in mingw64/share/icons.

**Comment by Beep6581** [comment] 2015-12-31 11:36
gtk-edit.png is shipped with RT, see /rtdata/images/Light/actions/ in the repo, or /images/Light/actions in the build dir.
Btw. You can click the little target icon in the top-left corner of the Gtk+ Inspector window and then click anywhere in the RT window to see info on that element.

**Comment by sguyader** [comment] 2015-12-31 17:37
Ah thanks for the tip, in fact in the Windows environment the icons of the Gtk inspector are not shown either, so I didn't see the target icon (even the close, decrease and raise window icons at the top right are showing missing image icon instead of the usual cross, low bar and square). But I found the target button, and when I select one of the missing icons, I don't get much information (or not anything I can understand.
For example, when selecting with the target the "down arrow head" at the right of the " Recent folders" drop-down menu, I get this information:
	Address				0000000005e73660
	Reference count		1
	State				dir-ltr
	Buildable ID
	Mnemonic Label
	Allocated size		18 x 23
	Clip area			18 x 26
	Tick callback
	Accessible role		icon
	Accessible name
	Accessible description
	Mapped				[missing image]
	Realized			[missing image]
	Is Toplevel
	Child Visible		[missing image]
The only name I see at the very top of the widow is GtkImage.
In MingW64 shell, when I do the same (with icons showing correctly), I get the same info, with no particular icon name. On the + or - icons, also missing in Windows, I get Gtkmm__GtkSpinButton.

**Comment by Beep6581** [comment] 2016-01-02 02:38
Gtk+ Inspector won't be of use on complex widgets which are composed of more than one other widgets, and that's the case with the adjuster. But I found out that they are called "list-add-symbolic" and "list-remove-symbolic". As for the missing icon in the tone curve type button, Gtk+ Inspector tells us the name: "pan-down-symbolic" ("Properties" menu).

On my system, I have:
```
/usr/share/icons/Adwaita/16x16/actions/list-add-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/actions/list-remove-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/actions/pan-down-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/actions/list-add-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/actions/list-remove-symbolic.symbolic.png
/usr/share/icons/Adwaita/24x24/actions/pan-down-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/actions/list-add-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/actions/list-remove-symbolic.symbolic.png
/usr/share/icons/Adwaita/32x32/actions/pan-down-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/actions/list-add-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/actions/list-remove-symbolic.symbolic.png
/usr/share/icons/Adwaita/48x48/actions/pan-down-symbolic.symbolic.png
/usr/share/icons/Adwaita/64x64/actions/list-add-symbolic.symbolic.png
/usr/share/icons/Adwaita/64x64/actions/list-remove-symbolic.symbolic.png
/usr/share/icons/Adwaita/64x64/actions/pan-down-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/actions/list-add-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/actions/list-remove-symbolic.symbolic.png
/usr/share/icons/Adwaita/96x96/actions/pan-down-symbolic.symbolic.png
/usr/share/icons/Adwaita/scalable/actions/list-add-symbolic.svg
/usr/share/icons/Adwaita/scalable/actions/list-remove-symbolic.svg
/usr/share/icons/Adwaita/scalable/actions/pan-down-symbolic.svg
```

Copying specific icons is not the way to go. There is a problem with your setup and we need to find it instead of copying single icons here and there.

0. Try this
On my system when I run
`gtk-update-icon-cache /usr/share/icons/Adwaita/ ; echo $?`
it returns nothing - no errors - and the echo prints "0". Is it the same on yours?

1. Remove everything
I assume that when @adamreichold compiled a Gtk3 build he did not have this missing icons problem. We should not document steps in the Windows compilation instructions in RawPedia which result from a broken toolchain or missing deps. It might be good if you removed MSYS/MSYS2/MinGW and anything else related to this, completely purged your system from any of these packages, made sure your environment variables are also clean, and then installed the toolchain as described in RawPedia on a clean system.

2. Check that all dependencies are correctly installed.
I read a post about MSYS2/pacman which said, "the original installation was incomplete because i had to set rules for a lot of program executions and internet accesses (firewall rules). some parts of the MSYS2 install script timed out too quick and therefor some packages were skipped".
To fix this, follow step III - Updating Packages: https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

3. Check that the Adwaita icon theme is installed.
`pacman -Ss adwaita`
Then install the icon theme:
`pacman -S mingw-w64-adwaita-icon-theme`
I also found references to two other Adwaita icon packages, you could check for these (but -Ss should have returned the correct names anyway): "mingw64/mingw-w64-x86_64-adwaita-icon-theme" and/or "mingw32/mingw-w64-i686-adwaita-icon-theme".

**Comment by sguyader** [comment] 2016-01-02 03:22
@Beep6581 
1. The command returns this on my system:
```
gtk-update-icon-cache.exe: No theme index file.
1
```
3. I don't think any packages were skipped during MSYS2 installation
4. I have already installed `adwaita-icon-theme`, and I even reinstalled it a couple times, in case I remove some files accidentally.

So it leaves only step 2. which I'm quite relunctant to do. I have to add that my PATH variable is cleaned from the old toolchain.

**Comment by adamreichold** [comment] 2016-01-02 08:57
@Beep6581 @sguyader If I understand this correctly, the problem is not running a Gtk+-version-3-based RT from the MinGW environment but rather produce a binary bundle that could be shipped to another machine? As for my experiences, I have only executed the produced binaries from the MinGW environment without any problems. But the manual for producing installation bundles on RawPedia is very much incomplete as of now.

@sguyader I can imagine two things about the setup: You have to recreate the theme index (using `gtk-update-icon-cache`) in the RT installation folder as well so that these icons are found. (Also copying a theme index is probably wrong, since it might contain invalid paths.) Concerning the 'symbolic' icons, at least on my Arch box, they are limited to the `scalable` variants and shipped as SVG files only.

**Comment by Beep6581** [comment] 2016-01-02 10:57
@sguyader the first point shows you don't have the Adwaita icon theme installed, in your system's opinion. That Adwaita folder should contain an `index.theme` file.

You could ask on IRC, specifically on #gtk+ on irc.gimp.org, about how one should go about making an installation bundle.

**Comment by sguyader** [comment] 2016-01-02 12:29
Well that's weird, because there are actually both `index.theme` and `index-theme.cache` in the Adwaita folder in mingw64. Despite that, the `gtk-update-icon-cache` command fails to find the index file. I ran the same command pointing to the `share\icons\Adwaita` forlder in the RT install folder, with the same result.

**Comment by Beep6581** [comment] 2016-01-02 15:46
I was told that EasyTAG uses Gtk3 and creates an installer for Windows, you could try asking its developers how they do it: https://wiki.gnome.org/Apps/EasyTAG

**Comment by sguyader** [comment] 2016-01-05 00:56
@Beep6581 I didn't need to contact the developers of EasyTAG, I found their latest Windows binary package, which contains Adwaita and hicolor icons, I copied them over RT folder and guess what, now the icons show up whenn I launch RT from Windows! I going to try figuring out what was missing earlier.

**Comment by sguyader** [comment] 2016-01-05 12:56
OK, so it looks like the problem of missing icons comes form the adwaita icon theme istalled from MSYS2. When I use this icon set, RT doesn't find some of the icons. But after installing the icons from a source package from ftp.gnome.org, and copying the installed icons to the RT `share/icons/` folder, all the icons are found by RT.
So in Rawpedia, for gtk3-specific compiling instructions I recommend to specify that Adwaita should be installed from the source package:
```
$ curl -LO http://ftp.gnome.org/pub/gnome/sources/adwaita-icon-theme/3.18/adwaita-icon-theme-3.18.0.tar.xz
$ tar xzf adwaita-icon-theme-3.18.0.tar.xz
$ cd adwaita-icon-theme-3.18.0
$ ./configure --prefix=/mingw64
$ make
$ make install
$ cd ..
```
You may see a whole bunch of `Can't load file: Unrecognized image file format` messages, but you can safely ignore them.

Then copy the `Adwaita` folder from `<MSYS2 installation folder>\mingw64\share\icons\` to `<Rawtherapee installation folder>\share\icons`.

I think Adwaita is installed by default as a dependency of `mingw-w64-x86_64-gtk2` and `mingw-w64-x86_64-gtk3`, so before installing it from source it is preferable (cleaner) to remove it with `pacman -R --nodeps --nodeps mingw-w64-x86_64-adwaita-icon-theme` as a first step (yes we need twice the `--no-deps` switch).

**Comment by Beep6581** [comment] 2016-01-05 13:31
Have you identified what it is about the ftp.gnome.org Adwaita package which is different from the MSYS2 one? It would be better to find this, then to let the MSYS2 folk know so they can fix it.

**Comment by sguyader** [comment] 2016-01-05 14:28
It looks like all the `*.symbolic.png` icons are missing from the MSYS2 package.

**Comment by Beep6581** [comment] 2016-01-05 15:17
Great!

**Comment by sguyader** [comment] 2016-01-05 15:31
Well, I was too quick... I resynchronized the MSYS2 repositories, and found an updated Adwaita package (v. 3.18.0-1). I installed it, and the symbolic icons are there.
However, the new package is quite big (5373 files, 45.1 MB) compared to the the one installed from the source package (5294 files, 17.3 MB). It's not very efficient, in my opinion, to generate Windows builds which will be 2 (at best) to 4 times (at worst) bigger just because of the icon set.

**Comment by adamreichold** [comment] 2016-01-05 17:24
@sguyader I would definitely prefer to keep the amount of manually compiled dependencies at a minimum and stay with the MSYS2-provided packages as much as possible.

Concerning the size of the Windows builds we distribute, I think what would be best here is a script that copies exactly the necessary files from the MSYS2 folders into a separate installation directory which can then be distributed. This way, we only need to copy those icons that we actually use, in those versions that we actually need. Personally, I would suggest opening a separate issue for the creation of such a Windows packaging (batch?) script?

**Comment by sguyader** [comment] 2016-01-05 17:26
I'm okay with that.

**Comment by adamreichold** [comment] 2016-01-05 17:30
I have created issue #3060 for the packaging script. Is this issue resolved by the update of the MSYS2 package of the Adwaita theme? Are any changes to the RawPedia article necessary?

**Comment by sguyader** [comment] 2016-01-05 17:44
Yes with the latest Adwaita theme provided by MSYS2, the issue is solved, I think we don't need to change Rawpedia for the moment.
For Windows installers, so far just by avoiding copying `cursors`, `scalable` and `scalable-up-to-32` folders we can save ~34 MB of non used icons.

**Closed** 2016-01-05 17:49 UTC
