### ISSUE TITLE
CLI version asks for X server

### ISSUE THREAD

**Issue by fliker09** [Beep6581/RawTherapee#3762] opened 2017-03-16 14:24 UTC
Ubuntu 16.04, RawTherapee 5.0-r1-gtk3

Error message:
"Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(rawtherapee:9404): Gtk-WARNING **: cannot open display: "

With 4.x there was no such problem. If additional information needed - ready to provide it!

**Comment by Beep6581** [comment] 2017-03-19 00:05
@fliker09 there is no version "5.0.1". Try to reproduce the problem using the latest dev. If you cannot reproduce it, close this issue. If you can still reproduce it, provide the correct version info:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Requirements_of_a_good_bug_report

**Comment by fliker09** [comment] 2017-03-20 09:56
Sorry, fixed the version in the first message. More info:

Version: 5.0-r1-gtk3
Branch: releases
Commit: 50114c1a
Commit date: 2017-02-01
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: Release
Build flags: -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:  -Wl,-Bsymbolic-functions -Wl,-z,relro
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment] 2017-03-20 12:21
@fliker09 thanks, that is the latest release and back then RT had no real CLI version. Hombre is working on one, so I will close this issue.

**Closed as completed by Beep6581** 2017-03-20 12:21 UTC

**Comment by fliker09** [comment] 2017-03-20 13:26
"back then RT had no real CLI version" - what do you mean? 4.x branch?

**Comment by Beep6581** [comment] 2017-03-20 13:55
5.0-r1

**Comment by fliker09** [comment] 2017-03-20 13:56
Ok, thanks for info! Waiting for true CLI!
