### ISSUE TITLE
Update: TooWaBlue-GTK3-20_.css v2.12

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3540] opened 2016-12-14 11:21 UTC
Rename the file extension from .txt to .css
The theme requires RT 4.2.1412 or higher.
[TooWaBlue-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/655120/TooWaBlue-GTK3-20_.txt)
[TooWaBlue-Dark-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/655121/TooWaBlue-Dark-GTK3-20_.txt)

**Comment by Beep6581** [comment] 2016-12-15 07:00
Will push a new version when the update mentioned in the forum is ready.
Hard-coding a font in the theme is not a good idea, the point was to let RT inherit the system-wide GTK+ theme (though no one yet explained how one should set a system-wide GTK+ theme in Windows and macOS).

**Comment by gaaned92** [comment] 2016-12-15 10:25
Excuse me but I don't really understand your position and I have some remarks:
1- font definition in a css theme is not really hardcoded. You can change it after installation.
2- What is the benefit of a system wide theme for application dev teams that generally want a specific presentation adapted to their app and  use cases? 
3- I don't see the utility to have the same font for all gtk3 apps .  What is good for an app will not be good for an another. Furthermore, good use of different fonts, sizes and colors can improve the clarity of a GUI (or a web page).
Surely I missed the point point and I would be thankful you correct me.

**Comment by TooWaBoo** [comment] 2016-12-15 12:46
@Beep6581 

I made a comparison between Arial and the default font (see screenshot). Both have font size 12px and the toolbox is set to its min. width. The screenhot explains erverything, there is nothing more to say.
On my computer isn't any application installed, which uses uses a font like this.

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21223974/472def62-c2ca-11e6-99d9-c00ec3eb01a2.png)

**Comment by Beep6581** [comment] 2016-12-15 13:52
Let me start off my saying that I am absolutely not against having a font selector as we did before.
The font selector was removed because the GTK2 one doesn't work for GTK3.

1- font definition in a css theme is not really hardcoded. You can change it after installation.
I see not being able to change the font in a user-friendly way as the next best thing to hard-coding.

> 2- What is the benefit of a system wide theme for application dev teams that generally want a specific presentation adapted to their app and use cases?

It's not up to some developer somewhere to decide how large the font on my screen should be, it's up to me, my eyesight, my screen size, my DPI, and my font style. You can feel the problem when visiting a website from the 90s where someone decided a tiny font was perfect for them.

Creating a consistent user experience for example through inheriting the font style and size is standard practice in the Linux world, it is not my opinion. The two biggest graphical toolkits, GTK+ and Qt, use very different themes, but on a modern Linux system the user can choose one theme, including font style and size, and all programs will (optionally) have a consistent look, unless one of the programs supports customization (good) or hard-codes something (bad). RT-GTK3 currently has its own color scheme but inherits the font and font size from the user's system, which means my RT looks the same as my web browser or my email client without any hacking. If I have poor eyesight, I set a large font once in my system settings and all programs use that. That is also the same way font size is handled on well written websites - they can use various fonts, but they should inherit the default font size from the web browser (which should inherit it from the system theme), and make larger or smaller fonts based off of the default size - that is why "em" and "%" are used, and setting font size in "px" is considered bad practice. That is the way things are, it is not my opinion, and I hope it answers your question.

There is another gotcha with DPI. How large a font looks is not just about the font size but also the DPI. My system uses a certain DPI value, lets say x. The font size I selected system-wide takes that into account. Now if some program ignores the system DPI and uses a hard-coded DPI value, such as 96 in Windows or 72 in macOS, the font will have the wrong size even if `font-size` is the same.
https://en.wikipedia.org/wiki/Dots_per_inch#Computer_monitor_DPI_standards

As I mentioned before and asked several times, I still don't know how a Windows or macOS user is supposed to set a font size. This is something we need to solve.
List of places where this was previously mentioned:
- https://github.com/Beep6581/RawTherapee/issues/3446#issuecomment-257043578
- https://github.com/Beep6581/RawTherapee/issues/3447#issuecomment-254354725
- https://github.com/Beep6581/RawTherapee/issues/3497#issuecomment-258636283
- https://github.com/Beep6581/RawTherapee/issues/3300#issuecomment-261031767
- https://discuss.pixls.us/t/osx-compiling-issue-from-git-pull/2602/26?u=morgan_hardwood

> Furthermore, good use of different fonts, sizes and colors can improve the clarity of a GUI (or a web page).

No doubt about that, but that is a non-sequitur. Even when RT had a font selector, it only allowed you to choose one font at one size. Now that one font and one size are inherited from the system theme. RT is still free to make smaller and larger versions of that.

@TooWaBoo I don't like Arial. Hard-coding a font is only good for people with the same taste, eyesight, screen size and DPI as the developer. 

Summary: we still need to find out how to set the font style and size in Windows and macOX, and/or we need a patch which adds a font selector that works in GTK3.

**Comment by Hombre57** [comment] 2016-12-15 14:12
I've found a link on where to put the gtk `.settings` file (or `.gtksettings` I don't remember), but it didn't worked here. One simple and elegant solution would be to let the user override the provided theme by creating a `user.css` file next to the options file (i.e. not in the app installation dir but in user's settings dir). We can provide a `sample_user.css` file as a template with a proposed font choice per OS (linux/win/mac).

That way any user will be able to override the font or the named colors. It would provide a greater experience for power users.

On a side note, I like the way that TooWaBoo's theme use named colors and can derive them, someone should do it for standard RT's theme too, in respect to the mechanism explained above.

@TooWaBoo Do you agree that we add your theme to RT now ? I don't know if it's finished yet, but it's already very clean and usable.

**Comment by Hombre57** [comment] 2016-12-15 14:15
@Beep6581 @TooWaBoo
> Summary: we still need to find out how to set the font style and size in Windows and macOS, and/or we need a patch which adds a font selector that works in GTK3.

The problem is that the font selector send you back a string that is directly usable with Pango and the Gtk2 `.gtkrc` file, but not for the CSS syntax. The font selector should provide a method to get the CSS formatted font description, but it's not there actually.

**Comment by Hombre57** [comment] 2016-12-15 14:21
Second side note : the `Zurücksetzen` button in the Exposure tool could be transformed to an icon, which would save some horizontal space and let us narrow the Tool Panel further. Or should we use the standard reset icon ?

**Comment by Hombre57** [comment] 2016-12-15 14:24
Third side note : the curve's buttons does actually expand, making the optional accompanying widget shrink. Should we change the expand/shrink policy and on which basis (automatic or programmed) ?

**Comment by Beep6581** [comment] 2016-12-15 14:25
@Hombre57 I assume you refereed to `Gtk::FontSelection`. Is what you wrote true for the new `Gtk::FontChooser` too?

**Comment by Hombre57** [comment] 2016-12-15 14:33
> Is what you wrote true for the new Gtk::FontChooser too?

I have to check that.

**Comment by Hombre57** [comment] 2016-12-15 14:34
> Third side note : the curve's buttons does actually expand, making the optional accompanying widget shrink. Should we change the expand/shrink policy and on which basis (automatic or programmed) ?

Sorry, already reported in issue #3531.

**Comment by TooWaBoo** [comment] 2016-12-15 14:55
@Beep6581 

> ...that is why "em" and "%" are used, and setting font size in "px" is considered bad practice...

I've tried "%" and "em" and got different font sizes everywhere.
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21228082/c3477dfe-c2dc-11e6-992b-160801e1ab29.png)

Please, can you post a screenshot how my theme looks like on Linus?
_____________________________________________________________________________________
@Hombre57 

> @TooWaBoo Do you agree that we add your theme to RT now ? I don't know if it's finished yet, but it's already very clean and usable.

I'll upload an update today and than you can add it to RT.

**Comment by Beep6581** [comment] 2016-12-15 15:02
> I've tried "%" and "em" and got different font sizes everywhere.

That sentence was about websites, GTK3 only conforms with CSS to some degree.

Sure, I'll post a screenshot when done compiling `gtk3-bugfix` on one core...

**Comment by Beep6581** [comment] 2016-12-15 15:21
@Hombre57 as I understand it, the `Gtk::FontChooser` should save the selected font info into `user.css` in `rtdir` for example, and then read that on startup.

**Comment by Hombre57** [comment] 2016-12-15 15:27
No, if we reintroduce the FontChooser then we'll save it in options as usual. Otherwise the user could edit a `user.css` file to set the font family and size, as well as other things if he wants to. If we reintroduce the FontChooser, no need to create the `user.css` as of now.

**Comment by TooWaBoo** [comment] 2016-12-15 15:34
@Hombre57 

Changed version 2.1 to 2.11 in the first post. Add a dark theme too.
Ready to add it to RT

**Comment by Beep6581** [comment] 2016-12-15 15:49
@TooWaBoo
- RawTherapee https://i.imgur.com/7SFdpL1.jpg https://i.imgur.com/hYforAi.png
- TooWaBlue v2.11 https://i.imgur.com/RKvm7fj.jpg https://i.imgur.com/Nf369CE.png
- TooWaBlue Dark v2.11 https://i.imgur.com/PFpcDOQ.jpg https://i.imgur.com/tKKV1Bs.png

Now I set DPI on my system to 120:
- RawTherapee https://i.imgur.com/8ziG0PR.jpg
- TooWaBlue v2.11 https://i.imgur.com/dhKI8Mz.jpg
- TooWaBlue Dark v2.11 https://i.imgur.com/iJe21He.jpg

Both TooWaBlue themes are wrong due to the reasons I stated in my previous post, and force the user either to change their system-wide DPI or to come to the forum looking for help and be told they have to hack CSS files.

**Comment by Beep6581** [comment] 2016-12-15 15:55
@TooWaBoo both v2.11 themes are missing `px` on line 659.

**Comment by TooWaBoo** [comment] 2016-12-15 16:03
> @TooWaBoo both v2.11 themes are missing px on line 659.
fixed and uploaded

Did you quit RT when you switched the themes? On the TooWaBoo themes screenshots, the window decoration is missing. If you switch on the fly, not all styles will be applied.

**Comment by Beep6581** [comment] 2016-12-15 16:08
@TooWaBoo yes I restarted RT before taking each screenshot.

**Comment by TooWaBoo** [comment] 2016-12-15 16:35
@Beep6581 
The DPI problem isn't really a problem for me. It only won't change the font size and when a fontchooser is implemented, I can remove the style from the .css.

A bigger problem is this:
It seems like KDE Plasma doesn't use a window decoration and is ignoring the styles in the TooWaBlue theme. That's why you can not reproduce this bug https://github.com/Beep6581/RawTherapee/issues/3532
But the Window decoration is an important part of my theme. I've to think about this.

**Comment by TooWaBoo** [comment] 2016-12-15 16:47
@Beep6581 
Where is the titlebar on your screenshots? It's part of the window decoration? Didn't you grab the whole window?

**Comment by Beep6581** [comment] 2016-12-15 16:50
@TooWaBoo 
> the Window decoration is an important part of my theme

What do you mean by important?

Here is a screenshot including the window decorations https://i.imgur.com/I09SJML.jpg

**Comment by TooWaBoo** [comment] 2016-12-15 17:21
> What do you mean by important?

I'm using the decoration to get a e.g. 5px border around the content and for a resize area, but it looks like on Linux, you are using a native window. On Window there is no resize area, no restore funktion. Most of the window control is missing. This has nothing to do with the themes, but when I add the resize area it will affect the theme, but only on non Linux OS.

Now I understand, why nobody act on my  post here https://github.com/Beep6581/RawTherapee/issues/3446

```
btw.
Because we are not using a native window, I think we have to do the whole window control.

These are the steps for the gui file

    Replace the Maximize button with a Restore button when maximezed
    Assign a class .maximized to the window when the window is maximized
    Remove the class .maximized when the window is not maximized
    Assign a class .fullcreen to the window when we are in fullscreen
    Remove the class .fullcreen when the window is not in fullscreen

With these modifications we can add or remove the decoration of the window in the theme file and the window resize problem is gone.
```

**Comment by TooWaBoo** [comment] 2016-12-15 18:17
On windows, the RawTherapee theme has no resize area. Either we use native windows on all OS or none.

**Comment by Beep6581** [comment] 2016-12-15 19:28
> the RawTherapee theme has no resize area 

What does that mean?

**Comment by TooWaBoo** [comment] 2016-12-15 19:33
I can't resize the window with the mouse. Switching of the decoration removes the whole resizing area.

**Comment by TooWaBoo** [comment] 2016-12-15 20:26
Let me explain in details:
This is what the RT theme is doing. I've shortend it to the relevant styles:
```
window > decoration {
    box-shadow: none;
    margin: 0px;
}
```
It removes the box shadow and margin = 0px; removes the resize area which is **outside** of the window. This is necessary for maximized and fullscreen state. This has no effect on Linux, 'cause of the native window.
The problem -> no resizing area

Im doing this in the TooWaBlue theme:
```
window > decoration {
    box-shadow: none;
    margin: 0px;
    border: 1px solid @winHeaderbar;
    padding: 5px;
}
```
padding: 5px and a border of 1px gives me a resizing area of 6px, but **inside** of the window. Because it's inside, it becomes part of the theme too. It's the border for the items which touches the window border.
The problem --> it's ignored by Linux,  'cause of the native window

I hope this makes the thing clearer

**Comment by Beep6581** [comment] 2016-12-15 20:55
Thank you for the clear explanation. I'm busy investigating whether the way it currently is in RT is the expected GTK3 way, or whether we do something wrong. Regardless, the RT window must be resizable using all bundled themes.

**Comment by TooWaBoo** [comment] 2016-12-16 05:50
I've made a test theme that should work on Linux. Can you check if it looks like the screenshots below with the exception of  the titlebar? It has only a 1 pixel resizing border. Thats not enough.
[TooWaBlue_no_decoration-GTK3-20_.txt](https://github.com/Beep6581/RawTherapee/files/656460/TooWaBlue_no_decoration-GTK3-20_.txt)
btw: Why isn't it possible to get a native window on all OS, like in Gtk 3.18?

![x2](https://cloud.githubusercontent.com/assets/13800920/21252966/365f037e-c35b-11e6-845e-96c854aaad35.PNG)
![x1](https://cloud.githubusercontent.com/assets/13800920/21252968/3eb4f696-c35b-11e6-8ba6-5fb732c4ad35.PNG)

**Comment by Beep6581** [comment] 2016-12-16 10:51
SETM-VT https://i.imgur.com/uC9UdYp.jpg
METM https://i.imgur.com/jG1E2uS.jpg

> The DPI problem isn't really a problem for me.
Exactly, no problem for the theme author, but a problem for people using the theme who have a different DPI, different font preference, etc. ;)

**Comment by TooWaBoo** [comment] 2016-12-16 12:25
> Exactly, no problem for the theme author

This is bullshit

The only thing what happens, when you set a different DPI, it changes the font size, but everything is defined in px and changing the DPI has no effect to them. I didn't spend so many hours to keep everthing in line, fighting with different image sizes and then any DPI setting can distroy this work.

To compare the result from your screenshot above, I've cut out a small part. Look at the items around the combobox. My layout is DPI save, your's not.

Left Standard DPI, Right 120 DPI

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/21262358/3a78556a-c391-11e6-856c-b5afaefdfc97.png)

**Comment by Beep6581** [comment] 2016-12-16 14:24
> when you set a different DPI, it changes the font size

That's supposed to happen when one changes the font DPI, but it does not in TooWaBlue. On my home laptop where the font is set to 128DPI (correct for that screen size and resolution), text size in TooWaBlue is wrong, while the rest of the system is consistent.

Same font size, changing only font DPI:
50DPI https://i.imgur.com/qSJu1zE.png
96DPI https://i.imgur.com/obpcYYm.png
150DPI https://i.imgur.com/GGlM20k.png

This is not the same thing http://i.imgur.com/QTpZPvN.jpg

https://msdn.microsoft.com/en-us/library/windows/desktop/ff684173(v=vs.85).aspx
http://askubuntu.com/a/272172

I will not be involved in this issue anymore. Have a good weekend.

**Comment by Hombre57** [comment] 2016-12-16 22:50
Theme added to gtk3-bugfix branch, thank you @TooWaBoo !

For the font problem, neither version respect the standard unfortunately : when changing system DPI, **everything** have to scale, not just font, so RT's theme doesn't conform to the standard and produce an awkward looking interface. TooWaBlue's theme doesn't scale anything, which doesn't conform to the standard neither, but it stay coherent with RT's interface.

So let's drop that font size problem, I'm trying to reintroduce the font chooser anyway.

**Comment by heckflosse** [comment] 2016-12-16 22:55
I also have no objections to add a theme which does not scale anything. I like the TooWaBlue theme, but no one is forced to use it as long as it's not the only theme.

**Comment by Floessie** [comment] 2016-12-17 08:16
@Hombre57 That's a Solomonic judgement! :+1: I'd also prefer an aesthetically pleasing theme over a readable one. :smile:

**Comment by Hombre57** [comment] 2016-12-17 18:47
I understand how use the FonButton now, and will be able to reintroduce the font button.

@TooWaBoo You're using `Arial` font in your theme, but are you sure that it exist on Linux and MacOS too ?

If a user want to change it's display DPI settings, there might be an obvious reason of readability and sight capability, so what should be the preferred way of changing font size :
- through a `user.css` file that will have to be edited by hand and saved to some obscure directory for most of the user which are photographs or casual user, but enables more control on the interface from a power user POV
- through a `FontButton` in Preference, enabled by a checkbox, which would override the theme's font. Easier for most users and would still remain optional, to let the user enjoy the bundled theme as designed by their author. However care must be taken to provide a suitable font by default for each system in the CSS file (we should then have 3 CSS file, which is not ideal in a maintainer POV)

Regarding icon size, I think it can be addressed easily and quickly, but I'll need the help of @Beep6581 for that, and we'll discuss it on IRC.

**Comment by TooWaBoo** [comment] 2016-12-17 19:00
> @TooWaBoo You're using Arial font in your theme, but are you sure that it exist on Linux and MacOS too ?
Arial is a standard font only on windows, If the font is not aviable, the default font is used. But if you add a font chooser, I will remove the the font and style from the theme and the user can set whatever he wants.
I've add it **only** to the theme, because the default font looks terrbile, the size is to big and the lack of a fontchooser.

**Comment by Hombre57** [comment] 2016-12-19 00:32
@TooWaBoo 
Patch committed, I've added the FonButton in Preferences and removed the font setting in your CSS files

**Comment by TooWaBoo** [comment] 2016-12-19 00:35
@Hombre57 

Perfect, thanks

**Closed** 2016-12-29 20:40 UTC
Labels: Component-UI, enhancement, gtk3, patch
