### ISSUE TITLE
RawTherapee does not show rank (stars) information coded in EXIF-data

### ISSUE THREAD

**Issue by ecuapac** [Beep6581/RawTherapee#4139] opened 2017-10-10 18:41 UTC
I have JPG images with the rank property (0 to 5 stars). The property shows up, e.g., in Windows Explorer and other Image software like those from Adobe.
![01_explorer](https://user-images.githubusercontent.com/6481070/31403572-ba4fd6de-adf9-11e7-963e-8f8e8b063947.png)

But it does not so in RawTherapee's file browser:
![02_rawtherapee](https://user-images.githubusercontent.com/6481070/31403573-ba704252-adf9-11e7-8ad4-9b803789ee50.png)

The information is stored into the EXIF information of the images. Example images are here:
[images.zip](https://github.com/Beep6581/RawTherapee/files/1372975/images.zip)

I think, the EXIF rank property is a standard way to provide the "star-rating" and I would be very grateful if RawTherapee also implemented this, as it is part of my basic workflow and probably of others.

Thanks for your awesome work,
  Ralph

Version: 5.3
Branch: 5.3
Commit: ec0f7936
Commit date: 2017-09-30
Compiler: gcc 7.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads   -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment] 2017-10-10 19:51
Duplicate of #3728

**Closed as completed by Beep6581** 2017-10-10 19:51 UTC
