### ISSUE TITLE
Local Adjustments: enabled Grain & Denoise Tool leads to wrong image rendering

### ISSUE THREAD

**Issue by rfaeseke** [Beep6581/RawTherapee#6159] opened 2021-03-06 23:08 UTC
**Short description**
When using the LA Grain&Denoise Tool and enable/disable the Local Contrast Tool several times the rendering of the current image gets wrong.

https://user-images.githubusercontent.com/5074899/110224098-feee5500-7ed8-11eb-9dc0-1f0ce2e42951.mp4

**Steps to reproduce**
see attached video

**Additional information**
Version: 5.8-2809-g47b180403
Branch: dev
Commit: 47b180403
Commit date: 2021-03-06
Compiler: cc 9.3.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.8.0-44-generic x86_64
Build date: Sat, 06 Mar 2021 21:49:54 +0000 UTC
Build epoch: 1615067394
Build UUID: 9e67ab06-8d1e-4ec6-ae10-586ce709071a

Linux xxxxxx 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 useful information:
- see attached video
- using current dev RT version

**Comment by Lawrence37** [comment] 2021-03-06 23:53
Thanks for the detailed bug report. This probably has the same underlying cause as #6132. I can reproduce this issue in `dev` branch but not in `laandlocalcontrast`. Closing as a duplicate of #6132.

**Closed as completed by Lawrence37** 2021-03-06 23:53 UTC
