### ISSUE TITLE
Usability improvement: Editor hotkeys

### ISSUE THREAD

**Issue by polezhaevdmi** [Beep6581/RawTherapee#3925] opened 2017-06-14 09:02 UTC
Target: RT 5 and above.
Goal: increase GUI usability for photographers.
Suggestions:

- Make the RT keyboard shortcuts editable and document the way to edit them. Or, at least, add in SETM the synonims for "Shift+F3"/"Shift+F4" keys as "RightArrow"/"LeftArrow". Just because the frequent use of F-keys in a multiimage workflow is extremely boring. The Shift/Alt/Ctrl+"RightArrow"/"LeftArrow" combinations also acceptable.
- The "Delete" key in Editor should put the active file into Trash AND automatically open NEXT available file, which is NOT marked as Trash. Now the Trash morking looses the focus in Filmstrip and makes the further movement impossible (seems, coupled with issue #3904 ). The Filmstrip "activity" mark should reflect the file, which is loaded in Editor.
- The Filmstrip should "predict" the Editor file opening sequence by giving more stip space to "movement" direction. For example, when the "RightArrow" is pressed, the current opened file should be placed at about 1/3th distance from left to right. Otherwise, when the "LeftArrow" is pressed, the "active" file should be at 1/3th from right to left. This will give much information about image sequence to operator.

Thank You!

**Comment by Beep6581** [comment] 2019-09-06 19:57
Duplicate of #1472, and point 3 was done in 5.6 or so. In the future, open 1 issue per issue.

**Closed as completed by Beep6581** 2019-09-06 19:57 UTC
Labels: type: enhancement
