### ISSUE TITLE
Raw Therapee 5.2 - EOS Rebel XS

### ISSUE THREAD

**Issue by magret2017** [Beep6581/RawTherapee#4002] opened 2017-08-05 11:07 UTC
Hello everyone,

I have installed Raw Therapee 5.2 on my computer through line command which is running under Lubuntu 16.10. All my pictures I've been taking by an Canon EOS Rebel XS which is supposed to be fully supported sinceversion 4.2. Indeed, I can see all my raw picture except those from one folder. Why? Here's a screen capture. 
![2017-08-05-125017_1024x768_scrot](https://user-images.githubusercontent.com/30749031/28995068-e1cfa490-79de-11e7-8c9e-eab7edf09487.png)
Please, can anyone help me?
Magret

**Comment by Beep6581** [comment] 2017-08-05 12:16
@magret2017 upload a sample photo using https://filebin.net/ and paste the resulting link here.

**Comment by Floessie** [comment] 2017-08-05 12:19
@magret2017 Your file looks corrupted. Can you open it with other programs, such as geeqie or darktable?

**Comment by Beep6581** [comment] 2017-08-05 12:27
@Floessie Geeqie only reads embedded JPEGs (at least on my system), so the result would be misleading.

I tried two raw files from the EOS Rebel XS / 1000D / Kiss F and they work fine in 5.2, indicating that your photos are corrupt as @Floessie suggested.

**Comment by Floessie** [comment] 2017-08-05 14:52
@Beep6581 
> Geeqie only reads embedded JPEGs (at least on my system), so the result would be misleading.

Of course, you are right. I just thought that the thumb is so damaged, that even the embedded preview is corrupt, too. But that must not necessarily be the case, right.

**Comment by magret2017** [comment] 2017-08-06 09:07
Hello Beep,
Here's the link for the file https://filebin.net/u08j0vbpdydhmdav.
Thanks for you help.

**Comment by Floessie** [comment] 2017-08-06 09:15
@magret2017 I don't even have to download the file: It's only 3.6MB, whereas an intact CR2 is usually bigger than 20MB. Something went wrong, when you copied it from you SD card. Maybe it was even stored that way (battery empty while shooting?). Sorry, but we can't help you with it. 😞

**Comment by magret2017** [comment] 2017-08-06 09:24
Hello Floessie,
I am unable to run Darktable on my computer for very long, it crashes all the time. Theses files were on a Mac then burn on a DVD support for storage & then copy back to my computer. Could that be the source of the problem?
Thanks for your help.

**Comment by Beep6581** [comment] 2017-08-06 10:24
Confirmed, that raw file is corrupt. Closing.

DVDs are a bad medium for backups due to most of the DVD writers and the discs themselves being low quality and user discipline while burning them being sloppy.

**Closed as completed by Beep6581** 2017-08-06 10:24 UTC
