### ISSUE TITLE
Version 5.0-r1 crashing during color temperature change

### ISSUE THREAD

**Issue by daurzada** [Beep6581/RawTherapee#3752] opened 2017-03-11 16:43 UTC
(I don't have a debug version compiled on my system).  
RawTherapee is crashing on color temperature changes. I can make one or two clicks of the +/- and then it will crash. It doesn't seem to matter if I use the default or my custom "baseline" profile.

attached is my default profile:
[baseline.pp3.txt](https://github.com/Beep6581/RawTherapee/files/835939/baseline.pp3.txt)

HW:
os: ubuntu 16.04 LTS
kernel: 4.4.0-66-generic #87-Ubuntu SMP
mem: 31.1 GB
proc: Intel i7-4790K
graphics: Intel Haswell Desktop  (integrated graphics)
os: 64-bit
disk: 24.2 TB

RawTherepee from repository ppa:dhor/myway
Version: 5.0-r1-gtk3
Branch: releases
Commit: 50114c1a
Commit date: 2017-02-01
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: Release
Build flags: -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:  -Wl,-Bsymbolic-functions -Wl,-z,relro
OpenMP support: ON
MMAP support: ON

**Comment by Floessie** [comment] 2017-03-11 16:50
@daurzada 
> (I don't have a debug version compiled on my system).

But you should install `gdb` and [provide us with a backtrace](http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports) anyway. We always need something to chew on. :wink:

**Comment by Beep6581** [comment] 2017-03-11 18:26
As @Floessie said. You can reply with your stack backtrace in issue #3650 which this is a duplicate of.

**Closed as completed by Beep6581** 2017-03-11 18:26 UTC
