### ISSUE TITLE
Re-selecting same curve mode of hidden curve - should the curve be shown?

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#4019] opened 2017-08-15 22:07 UTC
Suppose you are using Lab exposure and you define a custom L* curve.  You now use the Equaliser, say LH.  You now try to go back to the custom curve, but it won't display.  To see it or further adjust it, you have to select linear for L*, then select Custom.   This gets your curve back.  Preferably RT should display your curve as soon as you select Custom.

Ubuntu 16.10,   Version: 5.2-5-g10822f5,   Branch: dev,   Gtkmm: V3.20.1

**Comment by Beep6581** [comment] 2017-08-15 22:19
Cannot reproduce. Can you show a screencast?

**Comment by RawConvert** [comment] 2017-08-15 22:50
I take a raw with noPP3 present, and do a custom curve, giving this -
![q1](https://user-images.githubusercontent.com/16868433/29339798-d65d5d04-8213-11e7-8f53-8a1a0e77c800.png)
Then use Equaliser, giving this -
![q2](https://user-images.githubusercontent.com/16868433/29339861-3352855c-8214-11e7-9f74-fc210729ccd3.jpg)
I now click the L* dropdown and click Custom, but nothing changes.
Does this help?

**Comment by Beep6581** [comment] 2017-08-16 07:11
![curvemode](https://user-images.githubusercontent.com/5844619/29350932-d3219716-8260-11e7-95c5-22e0b1085944.png)

Now I see what you mean. If a curve, any curve, has a shape set but the curve is hidden (click on 1 to hide it), then when you click on the drop-down to select _the same curve mode_, the curve is not automatically shown, because it already uses that mode, so the show event is not fired.

The experienced user or programmer may wonder why you're pressing the wrong button (1 shows and hides the curve, 2 only does that when needed) and why you're setting a curve to a mode which it already has, though it seems no harm would be done if setting a curve to a mode it already has would also show it if its hidden.

**Comment by RawConvert** [comment] 2017-08-16 08:59
Morgan, the experienced user might wonder why this bit of the application is so complicated and un-intuitive!  I didn't know [1] was a button so haven't pressed it unless by accident.  It should perhaps be made more clear this is a button, e.g. it doesn't change appearance between on and off states, and the popup tool tip doesn't give any clue either.  Perhaps it is mentioned in rawpedia, I haven't read it all.  Having to use language like "setting a curve to a mode it already has" indicates that the functionality may have got too complicated.

You say it would do "no harm" to....  I would say this is clearly a change that is needed.  If I'd clicked Parametric in my scenario, it would have displayed, as you point out, so it's peverse not to show the Custom curve.

Is there a way to make it more obvious that the [1] parts are buttons?  However I'm not sure these are needed at all.  Couldn't the whole section be made to work quite simply and intuitively just by having the dropdowns [2]? Though I guess the dropdown list would need to highlight which choice was in use.

**Comment by Beep6581** [comment] 2017-08-16 09:41
> it doesn't change appearance between on and off states

That's the "RawTherapee" theme's fault.

> Having to use language like "setting a curve to a mode it already has" indicates that the functionality may have got too complicated.

"Pressing start on your microwave when you've already pressed start on your microwave".

> Couldn't the whole section be made to work quite simply and intuitively just by having the dropdowns [2]?

No because then you would have no way of showing/hiding the curve.

**Comment by Beep6581** [comment] 2017-08-16 10:08
"RawTherapee" theme fixed in commit 4429b6f. The TooWa* themes work fine.

Someone else will need to look at the events if it is desired that re-selecting an already-selected mode should trigger a curve show.

**Comment by RawConvert** [comment] 2017-08-16 13:10
"No because then you would have no way of showing/hiding the curve."
Why do you need to explicitly show or hide?  When you choose something in a dropdown, e.g. custom curve, that's the prompt for the system to display it, whether you've already been working on a custom curve, or it's a new one.  Regarding hiding, why do you need to, when you've done your curve or equaliser change, you leave it there and move on to the next thing, say sharpening, that's what happens generally surely?

**Comment by Beep6581** [comment] 2017-08-16 14:02
> Why do you need to explicitly show or hide?

- To not be distracted by something you're not using,
- To make the most of limited screen space,
- To keep focus on the relevant elements when taking screenshots,
etc.

Furthermore, if curve showing/hiding was completely automated and the user couldn't show/hide them manually:
- Being forced to change (or re-select) a curve's _mode_ just to show or hide said curve would be unintuitive and a regression not an improvement,
- Having to stare at all 9 L\*a\*b\* curves when you're only interested in one would be a regression not an improvement.

**Comment by RawConvert** [comment] 2017-08-16 22:05
I don't know why you say 9 curves, this would not be required, my suggestion would be keep that aspect as currently, i.e. all 9 "tools" use the same bit of the window.
Re. the 4th point, this is making it sound unduly messy.  All you would need to do is click the dropdown arrow then click the thing you're using, e.g. Custom.
Overall I think your 5 points are minor considerations.
Would the code not be easier to maintain over time with 9 fewer controls (removal of the the "1" buttons)?
I think the main thing is to at least make selecting a dropdown entry actually display it, even if nothing else can be done.

**Comment by Hombre57** [comment] 2017-08-18 22:29
@RawConvert From a user experience P.O.V., why would you get that tiny arrow and select a curve type (so 2 clicks) to show the curve you've already edited and want to edit again when doing so in one click on a bigger button is possible ? Going from curve to curve is done very often and making the process of switching curves as easy as possible was on my specifications for this feature. This is only a regular toggle button seconded by a drop down menu after all (as seen in other software) but they also act as radio buttons (being mutual exclusive), and can be reused elsewhere than curves (e.g. the rendering intent button). It was also done to fix a problem with Gtk : showing icon and label in drop down menu and only icon for the selected entry, to save a lot of space (unless I missed that in the doc).

However I'll try to solve the missing `show` event when selecting an already selected curve type.

@Beep6581 Thanks for fixing the theme.

**Comment by Hombre57** [comment] 2017-08-18 23:37
@RawConvert @Beep6581 Could you try this patch ? Works fine here.

```patch
diff --git a/rtgui/curveeditor.cc b/rtgui/curveeditor.cc
index f8beff5..9f2dbff 100644
--- a/rtgui/curveeditor.cc
+++ b/rtgui/curveeditor.cc
@@ -217,7 +217,7 @@
     curveType->set_tooltip_text(M("CURVEEDITOR_TYPE"));
     // TODO: Does this signal have to be blocked when on curve type change ?
     curveType->signal_toggled().connect ( sigc::mem_fun(*this, &CurveEditor::curveTypeToggled) );
-    typeconn  = curveType->signal_changed().connect (sigc::mem_fun(*this, &CurveEditor::typeSelectionChanged) );
+    typeconn  = curveType->signal_item_selected().connect (sigc::mem_fun(*this, &CurveEditor::typeSelectionChanged) );
 }
 
 void CurveEditor::setCurve (const std::vector<double>& p)
diff --git a/rtgui/curveeditorgroup.cc b/rtgui/curveeditorgroup.cc
index 29c8f5f..e8f636f 100644
--- a/rtgui/curveeditorgroup.cc
+++ b/rtgui/curveeditorgroup.cc
@@ -194,7 +194,7 @@
  */
 void CurveEditorGroup::typeSelectionChanged (CurveEditor* ce, int n)
 {
-    // Same type : do nothing
+    // Same curve and same type : do nothing
     if (ce == displayedCurve && n == (int)ce->selected) {
         return;
     }
diff --git a/rtgui/popupcommon.cc b/rtgui/popupcommon.cc
index 47d9efe..c79c690 100644
--- a/rtgui/popupcommon.cc
+++ b/rtgui/popupcommon.cc
@@ -100,9 +100,12 @@
 
 void PopUpCommon::entrySelected (int i)
 {
-    // Emit a a signal if the selected item has changed
+    // Emit a signal if the selected item has changed
     if (setSelected (i))
-        message (selected);
+        messageChanged (selected);
+
+    // Emit a signal in all case (i.e. propagate the signal_activate event)
+    messageItemSelected (selected);
 }
 
 void PopUpCommon::setItemSensitivity (int index, bool isSensitive) {
diff --git a/rtgui/popupcommon.h b/rtgui/popupcommon.h
index 8875f40..f4bdb58 100644
--- a/rtgui/popupcommon.h
+++ b/rtgui/popupcommon.h
@@ -42,7 +42,9 @@
 
 public:
     typedef sigc::signal<void, int> type_signal_changed;
+    typedef sigc::signal<void, int> type_signal_item_selected;
     type_signal_changed signal_changed();
+    type_signal_item_selected signal_item_selected();
     Gtk::Grid* buttonGroup;    // this is the widget to be packed
 
     PopUpCommon (Gtk::Button* button, const Glib::ustring& label = "");
@@ -57,7 +59,8 @@
     void setItemSensitivity (int i, bool isSensitive);
 
 private:
-    type_signal_changed message;
+    type_signal_changed messageChanged;
+    type_signal_item_selected messageItemSelected;
 
     std::vector<Glib::ustring> imageFilenames;
     std::vector<const RTImage*> images;
@@ -78,7 +81,12 @@
 
 inline PopUpCommon::type_signal_changed PopUpCommon::signal_changed ()
 {
-    return message;
+    return messageChanged;
+}
+
+inline PopUpCommon::type_signal_item_selected PopUpCommon::signal_item_selected ()
+{
+    return messageItemSelected;
 }
 
 inline int PopUpCommon::getEntryCount () const
```

**Comment by RawConvert** [comment] 2017-08-19 08:29
@Hombre57 , thanks for looking at this.  I accept the point about the 2 clicks and can see if you've made 6 changes and want to quickly review them all then the "1" buttons are good.  But I think others are and will over time be confused, not realising they are buttons.  Can the tooltips be amended to make clear they are buttons?

I'm afraid I don't know what to do with the patch!  I don't program these days and have never learnt C (guessing it's C?).  Having compiled RT, I guess I could compile a different branch if that's what required.  But finding a code module to put your patch in etc. is probably a step too far for me! (Also the time factor...)

**Comment by Hombre57** [comment] 2017-08-19 13:14
@RawConvert @Beep6581 Patch committed in rev 7394aa3806a9503ddaae0018d417b01448e4e4b0. Was quite safe anyway. I changed the theme too : now only the toggle button will be shown as pressed to make it more clear that it is linked to the arrow but behave differently.

**Closed as completed by Hombre57** 2017-08-19 13:14 UTC
