### ISSUE TITLE
Virtual Copy (like Lightroom)

### ISSUE THREAD

**Issue by ActarusLeGrand** [Beep6581/RawTherapee#6761] opened 2023-05-18 21:35 UTC
Virtual copy keep the same modifications made to the image. After the copy the 2 or more pictures are independent, you modify one and it does not modify the others.
A shortcut key do to virtual copy. It's very useful when cropping. I see a picture and I often see multiple pictures into that picture. These are different crops I would do. If I need 5 copies, I can do the shortcut key to do 5 virtual copy. 
Also it would be nice to be able in the crop tool to have a virtual copy field and a button to execute it. The field you enter how many extra virtual copy you need then you press the button to execute it.
You could also have a toggle button, where you can choose to copy the modifications made on the original image to the copy, then they are independent after (meaning you modify the original and their copy stay the same) or the other toggle: you can copy it without receiving any modification made to the original if there was any made before.

**Comment by Lawrence37** [comment] 2023-05-19 01:18
Persistent snapshots would cover this. Closing as a duplicate of #2624.

**Closed as not planned by Lawrence37** 2023-05-19 01:18 UTC
Labels: scope: sidecar, type: feature
