### ISSUE TITLE
Adapt CBDL to B&W tools

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3158] opened 2016-02-18 07:19 UTC
Hello all
As it is said in forum : https://discuss.pixls.us/t/request-to-move-the-b-w-tool-further-in-the-pipeline/879

I propose to satisfy users and minimize the work:

1) add a combo box in "CBDL" to choose the place where the process will be. Is now as in the "Lab process", ie after the "BW module" or at the beginning of the process, therefore before the "BW module", in "rgb process", but without tiles.
2) achieve a conversion rgb => lab, then its inverse, and put new call between
3) not taking into account the case of CIECAM
4) do not duplicate any code, everything is reusable
5) it seems to me simple

Of course, there are others solutions, a)as move "Wavelet", but it is considerably more complicated, b) do nothing ...

Jacques

**Comment by sguyader** [comment] 2016-02-18 11:23
On the [pixlus](https://discuss.pixls.us/t/request-to-move-the-b-w-tool-further-in-the-pipeline/879/8) forum, @Beep6581 proposed instead to move the Black&White conversion tool further down the pipeline, it is an interesting solution. However, if the processing of CBDL can be changed and allows one to use Film Simulation after CBDL, I would prefer the second solution as this would be more generally useful (for example, it would allow me to smooth people's skin and choose either a B&W film preset, or a color film preset).

**Comment by Desmis** [comment] 2016-02-18 12:31
@sguyader 
This second solution, seems to me, much more complex...
However, it is easy to move "simulation film" that is in the process rgb and place just after BW, and just before the conversion Lab.

But beware, you can not have your cake and eat it too

The solution I propose seems simple, without compromising the process or the code ... But it is not perfect, because the RT pipelines are what they are, in the present state of things you can not easily move functions
:)

**Comment by sguyader** [comment] 2016-02-18 12:41
@Desmis I know, it looks like I want "le beurre et l'argent du beurre" but any solution which helps my workflow will be great already, even if it's not the ideal solution from a user point of view.
I also hope your work will be potentially useful for other users, not just for me.

**Comment by Beep6581** [comment] 2016-02-18 22:06
I understand that moving B&W is complicated and for sure I don't want to tell anyone how to spend their time, but I do think we should discuss this first, because the solution should be one which can be re-used for other tools if needed and should be clear to the user. It would also be very helpful if we could see what the current toolchain actually is - this is just started http://rawpedia.rawtherapee.com/Toolchain%20Pipeline

**Comment by Desmis** [comment] 2016-02-19 08:06
@Beep6581 @sguyader 

Change the BW location is complicated, but I'm pretty sure the system response will be different ... Indeed the only place where we can put it is in the process Lab, therefore an obligation to conversion Lab = > rgb => Lab that in this direction will impoverish the results (probably)

I will try to offer a not too complex solution, which does not go too slow down the system. Indeed RT is built, there is only one way to manage "events"...

1) in BW, fixed the bug if  sum of the 3 channels = 0 (channel mixer)
2) invert the place of "BW tools" and "Film simulation" (old wish)
3) add a new process "before BW" to CBDL (main work)

Perhaps tomorrow :)

**Comment by Desmis** [comment] 2016-02-19 16:03
@Beep6581 @sguyader 
I just push a new branch "cbdlbw" with 1) 2) 3) above
:)

**Comment by heckflosse** [comment] 2016-02-19 16:51
@Desmis 
Jacques, I found a bug
To reproduce:
Open image with skin tones
Enable Cbdl
Press 'contrast +' 6 times
Set skin protection to 100
Enable/disable b&w several times
=> artifacts

**Comment by heckflosse** [comment] 2016-02-19 16:57
@Desmis 

Jacques, I just committed a fix for another thing to your branch instead of master. Sorry for that.
Ingo :(

**Comment by Desmis** [comment] 2016-02-19 17:05
@heckflosse 
Ingo
I don't know how to reverse ??

For the bug, I confirm :)
Thank you 
Jacques

**Comment by heckflosse** [comment] 2016-02-19 17:09
You can let the commit in your branch. No problem

**Comment by sguyader** [comment] 2016-02-19 17:25
Thanks Jacques for working on this. I just compiled you new branch, but the selection of Before/After B&W doesn't have any visible effect here. Whatever the selection, turning B&W on disables CBDL effect.

**Comment by Desmis** [comment] 2016-02-19 17:36
@sguyader 
With my test there is a difference between "after" and "before", but as says Ingo, there is a big bug. The system refresh then he should not

@heckflosse 
Ingo
Have you an idea for how to avoid the refresh ? Probbaly in Dcrop.cc and Improccoordinator.cc with 
*  if ((todo & (M_TRANSFORM)) && params.dirpyrequalizer.enabled...
Jacques

**Comment by sguyader** [comment] 2016-02-19 17:41
@Desmis it was just my fault, forgetting to reset the profile.
The big happens also with other tools, for example simply toggling on and off one of the curves in HSV equalizer brings the refreshing artifacts.

**Comment by heckflosse** [comment] 2016-02-19 17:44
@Desmis Jacques, I look

**Comment by Desmis** [comment] 2016-02-19 17:45
@heckflosse 

Ingo, thank you :)

**Comment by heckflosse** [comment] 2016-02-19 18:07
@Desmis 
Jacques, dcrop.cc line 715 should have only one & after todo
Shall I change and push or will you do?

Ingo

**Comment by Desmis** [comment] 2016-02-19 18:16
Ingo

You push, thank you very much :)

**Comment by heckflosse** [comment] 2016-02-19 18:26
@Desmis I pushed

**Comment by Desmis** [comment] 2016-02-19 18:36
@heckflosse 

Ingo

Now it's work fine !
I am very dizzy :)

Thank you again

**Comment by heckflosse** [comment] 2016-02-19 18:42
@Desmis 
Jacques, can I make some changes or should I wait?
Ingo

**Comment by Desmis** [comment] 2016-02-19 18:44
My english is bad, perhaps "dizzy" is not the good word...En français: étourdi, tête en l'air !

I have yet examined this line several times without seeing that instead of & there were &&

:)

**Comment by Desmis** [comment] 2016-02-19 18:44
@heckflosse 

Ingo

Yes you can, no problem :)

**Comment by sguyader** [comment] 2016-02-19 19:06
Strange behaviour regarding refresh and CIECAM02:
1- activate B&W then activate CBDL with "before B&W" selected -> effect is visible, ok
2- activate CIECAM02 and adjust something there -> effect visible, ok
3- deactivate CBDL -> CBDL effect removed, ok
4- reactivate CBDL -> CBDL effect not visible

**Comment by heckflosse** [comment] 2016-02-19 19:13
@Desmis @sguyader I'll look

**Comment by Desmis** [comment] 2016-02-19 19:25
Ingo, Sébastien

I think it is very easy to solve...just suppress "!params.colorappearance.enabled" in dcrop, improccoordinator, simpleprocess (with call to dirpyrequalizer)
I had put this condition, but I think it is unnecessary unlike the "after" mode where there must be a specific mode CIECAM.

Ingo, can you suppress with your next change

Thank you :)

**Comment by sguyader** [comment] 2016-02-19 19:32
Anyways, Jacques let me thank you again. With this move, I can get great B&W skin smoothing, and combined with Wavelet edge sharpness and Retinex (your tools again) I can remove some of the unwanted haziness.
Bravo !

**Comment by Desmis** [comment] 2016-02-19 20:02
@sguyader  @heckflosse 

Thank you Sébastien, this is really fun. But if I am on the initiative of these tools, nothing would have been possible without the excellent cooperation with Ingo for development, and the numerous assessments by you, Paul, or ... I forget ...:)

**Comment by heckflosse** [comment] 2016-02-19 20:06
@Desmis 
Jacques, ok, I'll include it into my changes. Thanks for the hint. Works fine :)
Ingo

**Comment by sguyader** [comment] 2016-02-19 20:19
Of course, I appreciated everyone's dedication, and fast response to feature requests.
Here's a quick A|B screenshot of combining CBDL targeting skin hues for softening, a little bit of Retinex, Film Simulation (Ilford 3200 3+  Yayyy!!!), Wavelet edge sharpening and Final touchup contrast curve... Showing before and after toggling CBDL.
![cbdlbw](http://i.imgur.com/ornKbXi.png)

**Comment by heckflosse** [comment] 2016-02-19 20:55
I pushed the fix for the issue with ciecam02 and some code cleanups.
@Desmis 
Jacques, I want to make some further changes (cleanup, SSE version for lab->rgb->lab conversion) but I'll wait for your OK :)
Ingo

**Comment by Desmis** [comment] 2016-02-19 21:06
No problem.  You can :)
Jacques


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Ingo Weyrich <notifications@github.com> 
Date : 19/02/2016  21:55  (GMT+01:00) 
A : Beep6581/RawTherapee <RawTherapee@noreply.github.com> 
Cc : Desmis <jdesmis@gmail.com> 
Objet : Re: [RawTherapee] Adapt CBDL to B&W tools (#3158) 
 
I pushed the fix for the issue with ciecam02 and some code cleanups.
@Desmis 
Jacques, I want to make some further changes (cleanup, SSE version for lab->rgb->lab conversion) but I'll wait for your OK :)
Ingo

**Comment by Hombre57** [comment] 2016-02-19 22:04
@sguyader 

Stunning result! I couldn't master RT better (in fact way worst) than you - no kidding.

**Comment by michaelezra** [comment] 2016-02-19 22:36
+1, excellent!

**Comment by sguyader** [comment] 2016-02-19 23:40
Thanks JC and Michael. It wouldn't have been possible to get this before
this change. I think it really expands the photographer's artistic
possibilités.

**Comment by Desmis** [comment] 2016-02-22 07:42
I will be little available, starting tomorrow, because my grand son come on holiday in Fréjus.

Also from March 5 until March 20, I would be in the French Antilles (Guadeloupe).

On this branch, I have no more additions to make. 
Ingo when your changes are ready, you'll be no problems "merge" with "master" of course if no one has any objection. :)

Jacques

**Comment by Beep6581** [comment] 2016-02-22 13:26
Useful changes leading to great results, +1 for commit.
One question: what is the use of having CbDL after B&W? In other words, why not hard-code it to "Before Black-and-White"?

**Comment by Beep6581** [comment] 2016-02-22 13:31
```
TP_CBDL_METHOD_TOOLTIP;Choose whether the Contrast by Detail Levels tool is to be positioned after the Black-and-White tool, which makes it work in L*a*b* space, or before it, which makes it work in RGB space.
TP_CBDL_AFT;After Black-and-White
TP_CBDL_BEF;Before Black-and-White
```

**Comment by Desmis** [comment] 2016-02-23 08:46
One can do what one wants, but "before" will always be different from "after" (except for Neutral), especially for "exposure"...to and preserve compatibility.

Moreover CIECAM requires special treatment, we must work in JC mode instead of L*a*b* to avoid artifacts, and CIECAM is always after.

There is always a bug in the current version, which means that in "before" mode if you activate CIECAM, CBDL is called 2 times. The attached patch should solve the problem

http://jacques.desmis.perso.neuf.fr/RT/ciecam23-2.patch

Ingo, can you take into account this (small) modification :)

Now I go to the station, to get my grand sons
Jacques

**Comment by heckflosse** [comment] 2016-02-23 14:04
@Desmis Yes, sure :)

**Comment by sguyader** [comment] 2016-02-29 16:46
After @Desmis' patch is commited by @heckflosse, can the cbdlbw branch be merged with master and/or Gtk3 branch?

**Comment by Beep6581** [comment] 2016-02-29 17:06
> can the cbdlbw branch be merged with master and/or Gtk3 branch?
Yes, that is the plan.

Currently there are some merge conflicts between `master` and `gtk3`, so I hope @adamreichold can help out with those when he has time.

> Is there an not-to-difficult way for me to select 2 branches and generate a diff file comparing both?
Yes, producing a diff is easy. Example:
`git diff master...origin/cbdlbw`

**Comment by heckflosse** [comment] 2016-03-01 18:19
I pushed the modifications and created #3188

**Comment by Beep6581** [comment] 2016-12-14 10:15
> On this branch, I have no more additions to make.

Can we close?

**Closed** 2016-12-14 13:46 UTC
Labels: enhancement, patch

**Comment by Desmis** [comment] 2016-12-14 15:05
No problem for me :)
