### ISSUE TITLE
Frequent RawTherapee crash

### ISSUE THREAD

**Issue by fsenore** [Beep6581/RawTherapee#4588] opened 2018-06-06 07:10 UTC
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

Windows 7 ultimate version 6.1.7601 Service Pack 1 7601
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 3201 Mhz, 4 core, 4 processori logici

Downloaded from:
http://rawtherapee.com/releases_head/windows/RawTherapee_5.4_WinVista_64.zip

I have downloaded RawTherapee a couple of months ago and I like it a lot.
I am experiencing very frequent crashes: they are frequent enough to be annoying but they are not reproducible. After some time the program crashes in an apparent random way.
I have attached a couple of stack backtraces: it looks like both show the same problem.

Please let me know if I can help in any way to fix this problem.

[rt-log.txt](https://github.com/Beep6581/RawTherapee/files/2075082/rt-log.txt)
[rt-log2.txt](https://github.com/Beep6581/RawTherapee/files/2075083/rt-log2.txt)

**Comment by Floessie** [comment] 2018-06-06 07:43
That looks like the same `CropWindow::pointerMoved()` case as in [#4580](https://github.com/Beep6581/RawTherapee/issues/4580#issuecomment-393043471). @Hombre57 is already at it...

**Comment by Beep6581** [comment] 2018-06-06 07:57
Closing as a duplicate of #4580.

**Closed as completed by Beep6581** 2018-06-06 07:57 UTC
