### ISSUE TITLE
TIFF Exif data format incompatible with Windows and some programs

### ISSUE THREAD

**Issue by Kolli96** [Beep6581/RawTherapee#4393] opened 2018-02-13 14:37 UTC
If I save a Nikon NEF raw file to a .tiff format, (uncompressed, compressed) the metadata will not be added (Date and time information, lens info etc). Only camera model, program name and picture resolution information included.

I have Windows 10 64-bit and RawTherapee version 5.3 ( I have tested the developer version 5.4 but the same problem. If I save RAW file in jpeg format, metadata follows with it.

Edit: Windows 10 does not see metadata but If I open this tiff file in FastStone Image Viewer, it show all metadata! But old .tiff pictures which I edited this program about 6 month ago are displayed metadata in Windows 10 own file properties.

**Comment by heckflosse** [comment] 2018-02-13 16:20
@Vike95 I just tested all combinations (8/16/32 bit, compressed/uncompressed) using developer version with a D700 NEF.
Works fine here. Maybe you set this to `Strip all metadata` by accident?

![grafik](https://user-images.githubusercontent.com/13733487/36160657-02e9df02-10e2-11e8-90d9-7c8950befbf6.png)

**Comment by Kolli96** [comment] 2018-02-13 16:29
I tested this but Windows own "File properties" function can not find metadata. But if I test this FastStone Image Viewer program, it find all metadata!

Old .tiff files metadata is displayed Windows file properties even though they have also been saved Rawtherapee version 5.3 and same Windows 10 64-bit version.

**Comment by heckflosse** [comment] 2018-02-13 16:49
@Vike95 I confirm that Windows `File properties` does not show the metadata with the exception of the camera model. I also confirm that for tiff files saved from old rt versions, Windows `File properties` shows the metadata.
This is clearly a bug.

**Comment by heckflosse** [comment] 2018-02-13 16:53
@Hombre57 Do you have an idea what could cause this behaviour?

**Comment by Kolli96** [comment] 2018-02-13 17:23
Now I installed version 5.3 back and it inform "TIFFOpenW error" and below it "C:\Users\user\Pictures\picture.tiff" if I save Nef file to .tiff format (uncompressed or compressed). Tiff file still open and works normally. 

And now metadata work in Windows File properties but only uncompression mode. 
I would like to use compression mode with metadata because it saves a little bit space and it is lossless. 

Is it so that compressed tiff does not support metadata?


If I remove 5.3 version and all it folder+ install 5.4 RC version, metadata does not work both modes.

**Comment by heckflosse** [comment] 2018-02-13 18:00
> Is it so that compressed tiff does not support metadata?

No, it does support metadata, as you can see when opening compressed tiff files in RawTherapee, FastStone Image Viewer or IrfanView (which show the metadata).

Looks like an endianess problem... Maybe @Hombre57 can shed some light on this

**Comment by Hombre57** [comment] 2018-02-13 20:55
@Vike95 @heckflosse Testing...

**Comment by Hombre57** [comment] 2018-02-13 21:51
@Vike95 @heckflosse I made a test with a D850 NEF file, export to tiff 8bits with metadata set to 'as is', compressed and uncompressed : files has the metadata, ExifTool shows that they are the same, IrfanView only show a subpart of the metadata and where some fields has different values between the compressed and uncompressed files. Test done with Win7. Windows also show some metadata but very few.

Which is the software that reads metadata correctly here ?

To be short : tell me how to reproduce.

**Comment by heckflosse** [comment] 2018-02-13 22:34
@Hombre57 Simple answer: Windows shows much less metadata for tiff files saved from current rt than it showed from tiff files saved from old (5.2/5.3 don't know exactly) builds.
I can provide a tiff saved by an old version of RT if needed

**Comment by Hombre57** [comment] 2018-02-14 00:01
@heckflosse Yes please, with the raw file too. You have my private mail if necessary.

**Comment by heckflosse** [comment] 2018-02-14 00:17
@Hombre57 Here you go : https://filebin.net/o99qe8houes6daea

**Comment by Kolli96** [comment] 2018-02-16 13:07
Any ideas? Can I save my pictures compressed tiff and your fix later this problem and then metadata comes to the pictures?

**Comment by Beep6581** [comment] 2018-02-16 18:37
There are differences in the contents of the metadata between the two sample TIFF files:
`exiftool -G5 -s -a -m -u -args` https://www.diffchecker.com/SEW5u8cx
`exiv2 -pa` https://www.diffchecker.com/wP5twW2J
`tiffinfo` https://www.diffchecker.com/I6TRzRoH
Both TIFF files _seem to_ store metadata using big-endian - I'm not certain yet.

> Windows 10 does not see metadata

You can file a bug report here:
https://answers.microsoft.com/

**Comment by Hombre57** [comment] 2018-02-16 22:13
The difference is that the new version dump the EXIFIfd  at the beginning of the file, then IFD0 is dumped, but this is fine with the Tiff specs : the offset for the IFD0 is set correctly for both old and new version (8 and 3fc9e0 respectively), but windows doesn't seem to follow the offset of 3fc9e0, then go back to beginning of the file (EXIFIfd).

**Comment by Kolli96** [comment] 2018-02-17 09:41
Is this Windows 10 problem, not RawtheRapee? Did I understand correctly?

**Comment by Hombre57** [comment] 2018-02-19 08:35
@Vike95 @Beep6581 @heckflosse

It's a bit tricky here : we're using the [libtiff function to create the ExifIFD tag](https://github.com/Beep6581/RawTherapee/blob/fc751a0ccead9a21d62364b394e700dedcf5f34e/rtengine/imageio.cc#L1381) now, but libtiff creates this tag with a data type of 13 (0x000d) while the official Exif 2.3 specs from 2010 says it should be data type LONG, i.e. 0x0004. That's the most evident difference I can see between the old and the new version, put apart that the ExifIFD is placed at the beginning of the file, but that's totally valid regarding the specs.

ExifTool and IrfanView seem to understand the data type of 13, which is not in the Exif 2.3 specs at all (I don't even know where it is defined), but the specs says that new data type could exist. Windows doesn't understand that data type, so I don't know who doesn't stick to the rules here. From a dev p.o.v., we're using the correct library and correct function.

**Comment by Beep6581** [comment] 2018-02-19 14:14
@Hombre57

> we're using the libtiff function to create the ExifIFD tag now

Which function and data type did we use before?
Let's compare what darktable and GIMP do, since they will have dealt with the same issue.

**Comment by Beep6581** [comment] 2018-02-19 15:22
dt uses Exiv2 not libtiff.

**Comment by Kolli96** [comment] 2018-02-28 15:12
Any ideas? Do I contact Microsoft?

Edit. Same problem with latest RC version.

**Comment by Beep6581** [comment] 2018-02-28 15:27
> we're using the libtiff function to create the ExifIFD tag now, but libtiff creates this tag with a data type of 13 (0x000d) while the official Exif 2.3 specs from 2010 says it should be data type LONG, i.e. 0x0004

@Hombre57 is it possible to test whether that changes anything with minimal effort? If not "with minimal effort," I would discourage wasting time on this and focus on #3801 instead.

**Comment by Hombre57** [comment] 2018-02-28 20:02
@Beep6581 I'll have a look tonight.

**Comment by Hombre57** [comment] 2018-02-28 23:18
@Beep6581 It is confirmed that replacing `0x000d` by `0x0004` let Windows find the Exif section. Exiftool and Irfanview find them too (as before).

![exif info](https://user-images.githubusercontent.com/13788115/36818566-e283a12a-1ce5-11e8-8581-5b92039d6239.png)

Trying to make a dirty but functional hack...

**Comment by Hombre57** [comment] 2018-03-01 09:16
@Beep6581 @heckflosse Patch is almost ready, but it was too late yesterday. I should commit tonight.

The bugfix (i.e. dirty hack) is to reopen the file after it was saved, find the tag (it will be fast) and write the new datatype (that's basically what I've done for my test). If someone has a nicer implementation, I'm listening.

**Comment by Hombre57** [comment] 2018-03-01 23:17
@Beep6581 @heckflosse Could you test the `tweaked-exiftag` branch ?

I've compared the exiftool output (`-v2` mode), they are the same excepted for the updated datatype, But I've only tested with Ingo's file which is Big Endian, but I'm confident that it'll work with Little Endian file as well.

Off for today.

**Comment by Hombre57** [comment] 2018-03-02 00:08
@Beep6581 @heckflosse Small bugfix committed in abec60d.

**Comment by heckflosse** [comment] 2018-03-02 13:43
@Hombre57 
```
/rtexif/rtexif.h:66:13: warning: inline function 'void rtexif::sset2(short unsigned int, unsigned char*, rtexif::ByteOrder)' used but never defined
 inline void sset2 (unsigned short v, unsigned char *s, ByteOrder order);
```
and
```
[100%] Linking CXX executable rawtherapee.exe
../rtengine/librtengine.a(imageio.cc.obj):imageio.cc:(.text+0x43f6): undefined reference to `rtexif::sset2(unsigned short, unsigned char*, rtexif::ByteOrder)'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Hombre57** [comment] 2018-03-02 16:51
@heckflosse Same warning here, but it doesn't stop the linker.

Should I remove the inline statement or move the function to the header file ? I'd choose the first solution.

**Comment by heckflosse** [comment] 2018-03-02 18:11
@Hombre57 Whatever you prefer :)

**Comment by Hombre57** [comment] 2018-03-02 21:12
@heckflosse Done.

**Comment by heckflosse** [comment] 2018-03-02 21:50
@Hombre57 Works fine here. Thanks a lot :+1:

**Comment by Hombre57** [comment] 2018-03-02 22:35
@heckflosse @Beep6581 @Vike95 Branch `tweaked-exiftag` merged into dev, with agreement of @heckflosse on IRC. I'm deleting this branch.

**Comment by Kolli96** [comment] 2018-03-03 16:29
Is this problem corrected for future release? Did I understand correctly? I do not really understand "technical language".

**Comment by Beep6581** [comment] 2018-03-03 16:35
@Vike95 yes, will be fixed in release 5.4.

**Closed as completed by Beep6581** 2018-03-03 16:35 UTC
Labels: type: bug, scope: metadata

**Comment by Beep6581** [comment] 2018-03-03 17:16
Test files:
https://filebin.net/4cl0gw1nkwtq1vsp/rt_issue4393_test.zip
`5.3-664-g`5441e896
@Vike95 you can open those files in any program and you should see metadata in Windows.
The IPTC description for the `amsterdam` images in the `modified` folder should show:
* IPTC description = `iptcdesc:ɑmstərˈdɑmåäöąćęłńóśźż`
* Exif User Comment = `iptcdesc:ɑmstərˈdɑmåäöąćęłńóśźż`

The `colorspace` images should show:
* Exif Artist = `ExifArtist123`
* Exif Copyright = `ExifCopyright123`
* Exif ImageDescription = `ExifImageDesc123`
* Exif UserComment = `ExifUserComment123`

@Hombre57 it seems that the Exif UserComment is only saved to JPG files. I haven't checked older versions of RT yet.

**Comment by Kolli96** [comment] 2018-03-03 21:22
> Test files: https://filebin.net/4cl0gw1nkwtq1vsp/rt_issue4393_test.zip``

The link does not work.

**Comment by heckflosse** [comment] 2018-03-03 21:35
Link works fine here

Edit: Not the one you quoted, but the link from @Beep6581 works fine
