### ISSUE TITLE
SIGSEGV in get_colorsCoeff with Canon PowerShot G5

### ISSUE THREAD

**Issue by MikrofiberPingvin** [Beep6581/RawTherapee#4000] opened 2017-08-02 04:41 UTC
RawTherapee crashes to desktop when opening RAW-files from Canon PowerShot G5.
Steps to reproduce:
1. Navigate to folder with RAW-files
2. Double-click RAW-file. Editor view opens, the picture shows briefly, and the application crashes to desktop.

When doing the above, a .pp3-file is generated for the RAW-file. When this .pp3 file is present, RawTherapee crashes immediately upon navigating to the folder with the RAW-file and .pp3-file in the File Browser. A sample RAW-file that triggers the crash is attached.

Version information:
Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

Link used to download RawTherapee: http://rawtherapee.com/releases_head/windows/RawTherapee_5.2_WinVista_64.zip

System Information:
Windows 8.1
Processor: Intel(R) Core(TM) i5-4460 CPU @ 3.2GHz
Installed memory (RAM): 16,0 GB
System type: 64-bit Operating System

Attempted to do a stack backtrace, but gdb crashed a few seconds after running "thread apply all bt full", so the log might be incomplete. I'm attaching it anyways, though, just in case. The RAW-file wouldn't attach directly, so I added it, and the .pp3 to a zip archive.

[log.txt](https://github.com/Beep6581/RawTherapee/files/1192659/log.txt)
[100_0062.CRW and 100_0062.CRW.pp3.zip](https://github.com/Beep6581/RawTherapee/files/1192661/100_0062.CRW.and.100_0062.CRW.pp3.zip)

**Comment by Beep6581** [comment] 2017-08-02 09:46
Confirmed.

The segfault happens when opening the containing folder from the File Browser:
```
Thread 36 "pool" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 7258]
0x0000000100cc8dea in rtengine::RawImage::get_colorsCoeff () at /home/morgan/programs/code-rawtherapee/rtengine/rawimage.cc:139
139                     float *tempdata = data[0];
(gdb) bt full
#0  0x0000000100cc8dea in rtengine::RawImage::get_colorsCoeff () at /home/morgan/programs/code-rawtherapee/rtengine/rawimage.cc:139
        dsumthr = {0, 0, 0, 0, 0, 0, 0, 0}
        sum = {1.40129846e-45, 0, -4.23518089e-22, 4.59163468e-41}
        tempdata = 0x7f0
        cblackfloat = {129, 129, 129, 129}
        whitefloat = {4070, 4070, 4070, 4070}
        cblack_ = 0x7fffd582d850
        this = 0x7fffc401ea30
        W = 2616
        H = 1960
        dsum = {0, 0, 0, 0, 1281840, 1281840, 1281840, 1281840}
        val = 0
```

Opening the photo by passing it as a parameter seems to work fine https://i.imgur.com/djzCVPy.jpg

**Comment by heckflosse** [comment] 2017-08-07 18:05
This patch fixes the crash. Thumb is still wrong...
```diff
diff --git a/rtengine/rawimage.cc b/rtengine/rawimage.cc
index 7b6ee878..f36e798d 100644
--- a/rtengine/rawimage.cc
+++ b/rtengine/rawimage.cc
@@ -112,7 +112,7 @@ void RawImage::get_colorsCoeff( float *pre_mul_, float *scale_mul_, float *cblac
         }
     }
 
-    if ( this->get_cam_mul(0) == -1 || forceAutoWB) {
+    if (data && (this->get_cam_mul(0) == -1 || forceAutoWB)) {
         memset(dsum, 0, sizeof dsum);
 
         if (this->isBayer()) {
@@ -552,7 +552,7 @@ int RawImage::loadRaw (bool loadData, unsigned int imageNum, bool closeFile, Pro
             crop_masked_pixels();
             free (raw_image);
             raw_image = nullptr;
-        } else { 
+        } else {
             if (get_maker() == "Sigma" && cc && cc->has_rawCrop()) { // foveon images
                 int lm, tm, w, h;
                 cc->get_rawCrop(lm, tm, w, h);

```

**Comment by Hombre57** [comment] 2017-08-07 19:06
Patch above committed in rev. b183a0b on behalf of @heckflosse. Closing ?

**Comment by Hombre57** [comment] 2017-08-07 20:57
Closed as discussed on IRC with @heckflosse. The thumbnail looks wrong, probably because of the lack of metadata, however the image is read correctly.

**Closed as completed by Hombre57** 2017-08-07 20:57 UTC
Labels: type: bug, patch provided
