### ISSUE TITLE
wrong colors .CR2 image (reddish) Canon EOS 5D Mark IV

### ISSUE THREAD

**Issue by pierre1618** [Beep6581/RawTherapee#6724] opened 2023-03-22 09:19 UTC
**Short description**
I"m trying to work with .CR2 image but when i opened them in Rawtherapee with (neutral) processing profil the white balance looks wrong as the colors in general (even with the correct profile (standard or auto)

**Steps to reproduce**
1. Go to (https://drive.google.com/drive/folders/1ySb446_BETNHn8Sh85PFHhgT1fc0iMQg?usp=sharing) download the 3 .CR2 examples 
2. Open Rawtherapee 5.9-57- g21afbaf90
3. open the 3 files in (neutral) profil
4. See the weird color
![image](https://user-images.githubusercontent.com/119874897/226854050-8d840081-d8d4-4cff-b6e2-920ab2ecfc06.png)

**Expected behavior**
i would expect image to automaticly have natural colors similar to Shotwell or any image viewer app 

**Additional information**
- Rawtherapee 5.9-57- g21afbaf90
- Ubuntu 22.10
- Version: 5.9-57-g21afbaf90
Branch: dev
Commit: 21afbaf90
Commit date: 2023-01-06
Compiler: cc 12.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.7
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -ffp-contract=off -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.19.0-29-generic x86_64
Build date: Tue, 24 Jan 2023 10:24:51 +0000 UTC
Build epoch: 1674555891
Build UUID: cb276b9a-104e-4b63-8c5e-910ae7106339

Other useful information:
- ![image](https://user-images.githubusercontent.com/119874897/226856012-6643a531-86c8-4d0d-9769-643cdc30822d.png)
- ![image](https://user-images.githubusercontent.com/119874897/226856491-2b0634bf-9691-4b82-9865-63b84793ece7.png)

**Comment by ghost** [comment] 2023-03-22 14:38
I just looked at your RAW and the 2 sidecars and I'm not able to reproduce the above shown result.

To make sure I tried using the official stable 5.9, an appimage (5.9-107) and the latest self build version (5.9-138), with and without your sidecars. This is what it looks like on my side of things using RT 5.9-107 with one of your sidecars loaded and as a reference the embedded JPEG as seen by XnViewMP:

![Screenshot_2023-03-22_15-08-31](https://user-images.githubusercontent.com/56407344/226931383-8754689d-965f-4f3c-a68f-4c5afe4a57b3.png)

All three RT version I tested with show the same, what seems to be correct result.

Do you have a colour calibrated system? I can see that you do not have set a specific profile. Not sure if that might be the problem, just set mine to *None* and have the same, basically correct, result (slight difference).

I'm also on Linux, Debian in my case.

Do you see the same issue with a newer RT version? These are development builds and although they are good-to-go most of the time, maybe yours is a bit wonky. Worth a try.

**Comment by pierre1618** [comment] 2023-03-24 10:15
Hi, thank you for your answer, actually, I tried again with  Ubuntu 22.04.2 ARM64 on another computer and I did"t find the same problem. So I tried to reinstall it (5.9-128-g5481a8bbe) but got the same problem. The apt compiled version 5,8 however is working.

**Comment by Lawrence37** [comment] 2023-03-26 01:43
I think this is the same issue reported in #6720, so let's track the issue there and close this one.

**Closed as not planned by Lawrence37** 2023-03-26 01:43 UTC
