### ISSUE TITLE
Big slowdown on preview between 4.2.312 and 4.2.363 and later

### ISSUE THREAD

**Issue by zster2** [Beep6581/RawTherapee#3068] opened 2016-01-07 14:27 UTC
I have 4.2.312 installed (I can't find the download link anymore but it must have been there). When I slide the exposure or any other control the preview updates smoothly (almost realtime). From 363 onwards (I've tried all) its choppy and takes a good second or two to updated. I suspect its the retinex merger which caused it and somehow its processing without it even been turned on. I surprised nobody else has noticed

**Comment by Beep6581** [comment] 2016-01-07 15:44
Try to reproduce using the latest version with the (Neutral) profile applied, specify the latest version you reproduced it on, provide your system info, etc.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
If you use Windows, get a recent build from https://discuss.pixls.us/t/new-windows-builds/615/1

**Comment by heckflosse** [comment] 2016-01-07 17:03
Search in your options file for
AdjusterMinDelay and AdjusterMaxDelay and set them to lower values (default is 200)

**Comment by TooWaBoo** [comment] 2016-01-07 22:09
I've set min/max to 100 and RT is much faster responsible.
btw. Why are there two values when they are equal. What happens, when I set them to diffrent values?

cu TooWaBoo

**Comment by heckflosse** [comment] 2016-01-07 22:19
AdjusterMaxDelay is used when the action behind the Adjuster may take quite long (as for example Raw False Colour Suppression Steps, which will demosaic the image again). AdjusterMinDelay is for the faster ones.

Ingo

**Comment by heckflosse** [comment] 2016-01-07 22:39
@TooWaBoo The reason for AdjusterMaxDelay is, that, when you move an adjuster slowly and the action behind the adjuster needs more time than the delay, you get a lot of useless processing and in the end it will take a lot more time. Currently AdjusterMaxdelay is mainly used for the Adjusters in RAW tab.

ingo

**Comment by TooWaBoo** [comment] 2016-01-07 22:41
Thanks for the info. So it's better to leave max on 200 and set only min to lower value?

cu TooWaBoo

**Comment by heckflosse** [comment] 2016-01-07 22:43
Exactly ;-)

**Comment by TooWaBoo** [comment] 2016-01-07 22:55
Now I've set 
 AdjusterMinDelay =100
 AdjusterMaxDelay =200
and RT feels now twice as fast as before. :-)

**Comment by heckflosse** [comment] 2016-01-08 00:12
IMHO this needs documentation in rawpedia. So please don't close the issue. I'll reopen it if someone closes it ;-)

Ingo

**Comment by Beep6581** [comment] 2016-01-08 08:01
Documented:
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Preview_refresh_delay

@heckflosse do you think we should change the default to 100? I tested here, I would call my system average with regard to desktop computers, above average w.r.t. laptops, and 100 seems to work fine.

**Comment by Beep6581** [comment] 2016-01-08 16:20
adjusterMinDelay = 100
Changed in master and RawPedia after IRC discussion.

**Closed** 2016-01-08 16:19 UTC
