### ISSUE TITLE
Verbose feedback when cannot save processing profile

### ISSUE THREAD

**Issue by user2155** [Beep6581/RawTherapee#5643] opened 2020-02-07 20:42 UTC
I'm not sure is it a bug or a feature.

How to reproduce it:

Open any raw file, edit it, quit the RT.
Change PP3 file attributes to "Read Only".
Open the raw file, edit it, quit the RT.
Open the raw file again, you'll see that changes are not saved.

RawTherapee:
Version: 5.8
Branch: releases
Commit: 9a9e0acbf
Commit date: 2020-02-04
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

OS:
Windows 10 Pro
Version    2004 (OS Build 19041.21)
BuildLab   19041.vb_release.191206-1406
BuildLab   19041.1.amd64fre.vb_release.191206-1406

**Comment by Benitoite** [comment] 2020-02-07 20:55
It seems logical that you will not be able to save changes into a read-only file...

**Comment by user2155** [comment] 2020-02-07 20:57
> It seems logical that you will not be able to save changes into a read-only file...

But there is no warning, that's the problem.

**Comment by Benitoite** [comment] 2020-02-07 21:22
I think what you are looking to do is file a Feature Request for a warning dialog then? You might want to edit the title as such.

**Comment by user2155** [comment] 2020-02-08 08:12
> I think what you are looking to do is file a Feature Request for a warning dialog then? You might want to edit the title as such.

OK, done

**Comment by Beep6581** [comment] 2020-06-18 11:22
Duplicate of #4386

**Closed as completed by Beep6581** 2020-06-18 11:22 UTC
Labels: type: enhancement
