### ISSUE TITLE
Command line option "-t" causes a crash of rawtherapee-cli.exe

### ISSUE THREAD

**Issue by Nyko666** [Beep6581/RawTherapee#3909] opened 2017-06-05 01:46 UTC
This command line : 
_rawtherapee-cli.exe -q -o outputFile -p param.pp3 -t -c myFile.tif_
gets this error : 
![image](https://cloud.githubusercontent.com/assets/29188169/26767485/bb9803f8-49a0-11e7-9526-887f28f55382.png)
Some tests show me that **the option "-t" causes the crash** : "-tz" is ok, "-tu" is ok... but not "-t".

**Comment by Beep6581** [comment] 2017-06-05 09:44
Duplicate of #3891

**Closed as completed by Beep6581** 2017-06-05 09:44 UTC
Labels: type: bug
