### ISSUE TITLE
Fujifilm X-T2 X-Trans CMOS III raw support

### ISSUE THREAD

**Issue by FabryFire** [Beep6581/RawTherapee#3462] opened 2016-10-16 15:45 UTC
I tried to open Fujitsu XT2 Compressed Lossless RAW files, while the preview is good, once opened, the image displayed is just of a split rectangle, half white, half black.
The same files are perfect on Adobe Camera RAW

**Comment by Beep6581** [comment] 2016-10-16 17:29
@FabryFire please upload a sample raw file using http://filebin.net/

**Comment by Beep6581** [comment] 2016-10-16 17:30
Duplicate of #3229

**Closed by Beep6581** 2016-10-16 17:30 UTC
Labels: raw

**Comment by FabryFire** [comment] 2016-10-16 17:35
Done !

**Comment by heckflosse** [comment] 2016-10-16 17:47
@FabryFire `Done !` : where?

Question: `Can you please tell me what time it is?`
Answer: `Yes`

;-)

**Comment by FabryFire** [comment] 2016-10-16 18:05
Sorry, forgot a “paste”

https://filebin.net/vce5wdfqbqod0z7x

**Comment by heckflosse** [comment] 2016-10-16 18:56
@FabryFire Thanks for uploading the file. As I mentioned in a few other Issues, I already started porting support for compressed xtrans files from libraw code to rawtherapee. But I won't manage this before rt 5.1 (hopefully end of the year) as we want to release rt 5.0 soon (end of October) and there's still s lot of other work to do.

**Comment by FabryFire** [comment] 2016-10-16 18:57
Thank you very much for your work!

Fab
