### ISSUE TITLE
Editor mode clearing rank and color label

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#7268] opened 2024-12-13 10:01 UTC
Entering "Editor" clears rank and color label of the image/s opened/viewed in Editor (but change only visible in UI upon restart).

**Steps to reproduce**
- Apply rank and color label to an image (in File browser or Editor)
- Exit RT
- Open RT and enter Editor for the marked image
- exit RT without changing anything
- Open RT -> rank and color label are gone

**Additional information**
I initially suspected cache/processing file priority loading but settings for "Processing profile handling" being set to cache/file make no difference. Observing the image processing profile file, the rank and color label are being overwritten in Editor immediately but the change is only visible in UI upon RT restart which makes it more likely the user will miss the change being applied.

Tested with appimage:
Version: 5.11-82-g3e8d58119
Branch: dev
Commit: 3e8d58119
Commit date: 2024-11-23

**Comment by Lawrence37** [comment] 2024-12-14 19:42
Thanks for reporting, but this is a duplicate of #7218.

**Closed as not planned by Lawrence37** 2024-12-14 19:42 UTC
Labels: type: bug
