### ISSUE TITLE
Lumix HI Res Raw files

### ISSUE THREAD

**Issue by maz4200** [Beep6581/RawTherapee#5257] opened 2019-04-02 10:18 UTC
I am experimenting with 80MP raw files on Lumix G9 (80 MP).
The files are imported into Photoshop with no issues but Raw Therapee imports these files as noise. (see attached screenshot) this problem is also true of Affinity Photo, ON1 imports them as readable files  but with the wrong size (20MP).

![image](https://user-images.githubusercontent.com/21952948/55395222-082a5680-5539-11e9-893d-484917fc0216.png)

**Comment by Beep6581** [comment] 2019-04-02 10:45
> If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.

Duplicate of #5104

**Closed as completed by Beep6581** 2019-04-02 10:45 UTC
Labels: scope: file format

**Comment by iliasg** [comment] 2019-04-03 19:48
@maz4200 Please try a recent RT build .. G9 HiRes added recently 
Only problem is that the black level needs correction for Hires files and the companion first shot of the 8shots set .. for the moment we can use Raw.Black.Levels at -15.00 to compensate.
