### ISSUE TITLE
Wavelet Level Functions not working at all in dev

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#4405] opened 2018-02-17 20:41 UTC
Hi, I have just compiled the latest dev release and non of the Wavelet Level functions make any change to the displayed image. Changes to settings take the normal processing time by no change appears.

Example no change occurs if I toggle Wavelet  Levels on or off,

![screenshot from 2018-02-18 07-40-02](https://user-images.githubusercontent.com/7539943/36345457-fb257574-147e-11e8-8d53-752046243f20.png)

Version: 5.3-641-gb1d673a2b
Branch: dev
Commit: b1d673a2b
Commit date: 2018-02-17
Compiler: cc 7.2.0
Processor: core2
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -std=c++11 -march=core2 -Werror=unused-label -flto -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=core2 -flto
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment] 2018-02-17 20:49
Can't confirm. Works fine here. Please submit a raw and the corresponding pp3

**Comment by heckflosse** [comment] 2018-02-17 20:59
@dnw3039 Tested again. Confirmed. Looks like a silly bug. Preparing a fix

**Comment by Beep6581** [comment] 2018-02-17 21:16
Cannot reproduce.

**Comment by heckflosse** [comment] 2018-02-17 21:35
Accidently pushed to Release5.4. Will push to dev soon to close the issue.

**Closed as completed** 2018-02-17 21:39 UTC
