### ISSUE TITLE
RawTherapee 5.4 crashes/closes when I turn on the Queue to export

### ISSUE THREAD

**Issue by AP215301** [Beep6581/RawTherapee#4752] opened 2018-08-27 22:12 UTC
RawTherapee 5.4 crashes/closes when I turn on the Queue to export

**Comment by heckflosse** [comment] 2018-08-27 22:15
@AP215301 please post the content of `AboutThisBuild.txt`

**Comment by AP215301** [comment] 2018-08-27 22:57
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment] 2018-08-27 22:59
@AP215301 http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by AP215301** [comment] 2018-08-28 02:04
I edited a DNG image file, taken using OpenCamera app on Pixel 1 phone. I then put it in export and start the export. The app closes itself (assume crashes) after about 2 seconds. There is no visual details to share from this process. I tried restarting PC, reinstalling the app, changing output to different folder, changed output type from JPG to TIF and PNG but the same error occured each time.

**Comment by AP215301** [comment] 2018-08-28 02:05
[pp.zip](https://github.com/Beep6581/RawTherapee/files/2326200/pp.zip)

**Comment by Thanatomanic** [comment] 2018-08-28 04:54
I have no trouble exporting your image using the latest `dev` build.

**Comment by Beep6581** [comment] 2018-08-28 08:53
Processed without issues using `5.4` and `5.4-691-g`871188a1 in Linux.

**Comment by heckflosse** [comment] 2018-08-28 09:10
@AP215301 Maybe you ran out of free memory? Processing your file needs about 1.3 GB of free RAM (measured on my 8 core machine). You can reduce the amount of free memory needed for noise reduction by changing this setting to e.g. `1`

![grafik](https://user-images.githubusercontent.com/13733487/44713164-d046c680-aab2-11e8-8719-8e4919e9fd5a.png)

http://rawpedia.rawtherapee.com/Preferences#Maximum_Number_of_Threads_for_Noise_Reduction

**Comment by AP215301** [comment] 2018-08-29 02:02
I changed setting to 1 but still the same. I also moved the files from external drive to C:\ drive but the same.   
My machine has 8GB of RAM. Before running the queue, there was 5GB free.  While running, CPU goes to 100% and RAM has 4.5GB free. There is no spike in RAM usage, it never goes below 4.5GB. 
I tried to export just 1 image, it worked. I tried to export 40, it failed without exporting eve one of them.  

An off topic question, is there an easier way to clear the queue? I usually export in a batch, so add 40 or more at the same time and then let it run while I step away. But if there is a mistake or I make more changes, i can't find an easier way to clear/disregard the queue. I have to click close on each one in the queue list.

**Comment by heckflosse** [comment] 2018-08-29 09:15
@AP215301 Right click/Select all + Right click/Cancel job

**Comment by gaaned92** [comment] 2018-08-29 12:11
Rawtherapee 5.4 on Windows10 cannot reproduce
I put 50 identical jobs with above photo in queue. Start queue. Finish ok

Memory usage
-before starting queue: 5GO
-during processing: 5.3 to 6 GO
about 6sec to process a photo

@AP215301 

Could you delete the cache subdir and option file inside the config folder; see https://rawpedia.rawtherapee.com/File_Paths and try again.

**Comment by heckflosse** [comment] 2018-08-29 12:21
@AP215301 please post a screenshot showing your RT queue tab

**Comment by Beep6581** [comment] 2018-08-29 12:49
@AP215301 
1. Please test using the latest development build:
https://keybase.pub/gaaned92/RTW64NightlyBuilds/RawTherapee_dev_5.4-755-g3c543d2ef_WinVista_64.zip
2. If you can reproduce using the latest dev build, then follow the simple steps to provide a stack backtrace:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

**Comment by lukasz83krk** [comment] 2018-09-03 09:58
RT crashed when I exported images by Ctrl+B (add image to queue). The problem was the dot "." in directory name (directory with pentax PEF files). I export JPGs to ./jpg (where . is the directory with PEF).

I use RT (the newest release ver from repo) @opensuse leap 42.3

**Comment by Beep6581** [comment] 2018-09-03 10:27
@lukasz83krk as I just wrote above, please test using the latest development version, provide the build info, steps to reproduce and a stack backtrace if possible. See the "how to write useful bug reports" link. A [screencast](http://www.maartenbaert.be/simplescreenrecorder/) showing how to reproduce would be great.

**Comment by Beep6581** [comment] 2018-11-11 20:29
Closing due to lack of useful info and due to several changes to relevant code since 5.4.

**Closed as completed by Beep6581** 2018-11-11 20:29 UTC

**Comment by bw35** [comment] 2018-11-25 19:37
I'm using RT5.4 from the openSUSE leap 42.3 repo https://download.opensuse.org/repositories/home:/rawtherapee/openSUSE_Leap_42.3/ and noticed the same bug. I know this is closed now but I have some detail which might help finding the root cause and verify that it has been fixed.

RT crashes on fast export, depending on the export options. The crash occurs when using the "Dedicated (full processing on resized image)" processing pipline in the Fast Export Options. Using the "Standard (bypass some steps, resize at the end)" processing pipline works fine without crash.

FWIW I'm converting Pentax PEF files

Using RT from 

Version information from about dialog:

Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc-7 7.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.20.1
Lensfun: V0.3.1.0
Build type: release
Build flags: -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by Thanatomanic** [comment] 2018-11-25 19:42
@bw35 I have tried to build the current development version of RT on Leap 42.3 but ran into so much trouble that I suggested to drop support for this OS version. See here https://github.com/Beep6581/RawTherapee/issues/4947

If you manage to build the latest dev version of RT on your system and still get the same bug, please report back. Otherwise, I am afraid we cannot be of more use to you.

**Comment by sk7711** [comment] 2020-06-14 12:57
Had the same problem, turned out I had Cyrillic names in the path which RT could not process. Solved by renaming everything to Latin.
