### ISSUE TITLE
color change

### ISSUE THREAD

**Issue by fasssc2** [Beep6581/RawTherapee#5052] opened 2018-12-01 19:54 UTC
when I edit the photo on raw therapee it's a good photo with good color etc...
but when i look at the photo from the computer the color of the image just change, i don't know why, I think it's for some setting, but I can't understand what setting, can someone help me?

here is an exemple:
![image](https://user-images.githubusercontent.com/45392484/49332299-255f1080-f5ab-11e8-8293-d6ee66089bda.png)
![image](https://user-images.githubusercontent.com/45392484/49332302-2bed8800-f5ab-11e8-8c7b-cd84a22254dc.png)

**Comment by Thanatomanic** [comment] 2018-12-01 19:57
Most likely is that the Windows photo viewer is not properly color managed.
Can you please upload the RAW + PP3 + exported JPEG? Just to verify.

**Comment by fasssc2** [comment] 2018-12-01 21:15
How can i do that? Ahahah

Il giorno Sab 1 Dic 2018, 20:57 Roel Baars <notifications@github.com> ha
scritto:

**Comment by Thanatomanic** [comment] 2018-12-01 21:17
https://filebin.net is the easiest. Just upload there and copy the link here.

**Comment by heckflosse** [comment] 2018-12-01 21:27
@Thanatomanic Roel, I really appreciate your patience :+1:

**Comment by Beep6581** [comment] 2018-12-01 22:32
@fasssc2 in addition to possibly incorrect color management, it looks like you're using one or more of the tools marked as "1:1", specifically it looks like you're using Tone Mapping or Wavelets.
See https://discuss.pixls.us/t/problem-with-rendering-photos/10090/7?u=morgan_hardwood

**Comment by fasssc2** [comment] 2018-12-02 11:53
sorry but i don't understand. 
i had to upload RAW + PP3 + exported JPEG of what? plus i don't know how to export in jpeg

**Comment by Thanatomanic** [comment] 2018-12-02 11:57
@fasssc2 Your sceenshots show that you have a CR2 file in RawTherapee, but a JPEG file in Windows Photo viewer. Is this JPEG straight from the camera, or did you export it from RawTherapee (by putting it in the 'coda di sviluppo' or through 'fast export')?

**Comment by fasssc2** [comment] 2018-12-02 11:57
also @Beep6581 i'm not using tone mapping or wavelets, i tried to read the link that you send but i can't understand what option I need to change

**Comment by fasssc2** [comment] 2018-12-02 11:58
@Thanatomanic  i just saved the image from raw therapee
i look like a dumb but i'm not really good with computers ahahah

**Comment by Thanatomanic** [comment] 2018-12-02 12:00
> @Thanatomanic i just saved the image from raw therapee
> i look like a dumb but i'm not really good with computers ahahah

No problem, but if you saved it from RawTherapee, then please upload that JPEG file together with the original raw (CR2) file and the PP3 file with the same name. You should find the PP3 file next to your raw file.

**Comment by fasssc2** [comment] 2018-12-02 12:05
upload here ?

**Comment by fasssc2** [comment] 2018-12-02 12:13
ok maybe i understand. i should upload the photo on the link and then publish it here?

**Comment by Thanatomanic** [comment] 2018-12-02 12:20
@fasssc2 As I said before:
> https://filebin.net is the easiest. Just upload there and copy the link here.

**Comment by fasssc2** [comment] 2018-12-02 18:53
https://filebin.net/6jtw53wrjx93f3rv

**Comment by Beep6581** [comment] 2018-12-02 19:28
@fasssc2 there is a difference between the preview and the saved images because you're using extreme Dynamic Range Compression settings - a tool which is marked "1:1".

No bug, closing.

**Closed as completed by Beep6581** 2018-12-02 19:28 UTC

**Comment by Thanatomanic** [comment] 2018-12-02 19:33
@fasssc2 Thank you for uploading. Here's what I get:

![image](https://user-images.githubusercontent.com/6567747/49343685-8ef42300-f66e-11e8-8a94-034157dcd0a5.png)

A few observations:
- Your JPEG looks the same in Windows Photo viewer (maybe colour managed) and IrfanView (definitely colour managed). So there's nothing wrong with the output.
- As @Beep6581 already suspected, you are using a tool with the 1:1 icon, the `HDR Tone Mapping` tool. For this tool, you will need to look at 100% magnification if you want to see exactly how the saved JPEG will look like. This may explain the differences you noticed.
- Interestingly, my own JPEG looks almost/exactly the same as the preview in RT, but the colors are different compared to your JPEG, e.g. the shirt is more pink, less red. This can be caused by two things: 1) the HDR Tone Mapping tool has been modified after the release of v5.4 and produces slightly different colours now, or 2) you have a monitor colour profile selected which causes your colours to appear different in the preview of RT.
![image](https://user-images.githubusercontent.com/6567747/49343938-16db2c80-f671-11e8-851a-2caa16aeaf4f.png)

So, I think the issue may be a little more complex than what @Beep6581 just wrote. But he's right: this is not a bug.

Can you check what happens if you select 'None' for the monitor colour profile and do not use the HDR Tone Mapping tool? Do you still get different colours between the preview in RT and the saved JPEG?

**Comment by Beep6581** [comment] 2018-12-02 20:15
@Thanatomanic another reason for the difference in colors when "HDR Tone Mapping" AKA "Dynamic Range Compression" is turned off is that 5.4 had a different input profile for the Canon EOS 1300D than dev - I created a new DCP for that camera in April 2018.

**Comment by fasssc2** [comment] 2018-12-03 00:47
i selected 'none' for the monitor colour profile and didn't use the hdr tone mapping tool and it works
so it won't happen again now?

**Comment by iliasg** [comment] 2018-12-05 13:12
.. selecting "none" for the monitor profile could give very wrong rendering .. especially with wide gamut monitors

As I see it (viewing at 1:1) there is a small difference between RT preview and output jpeg using my monitor profile (preview is a bit darker at the dark tones).

This could come from 
- tools acting differently on preview vs output .. (I also checked with DynamicRangeCompression OFF .. same result) 
- or simply by using a less accurate gamma correction for the preview ..

**Comment by Beep6581** [comment] 2018-12-05 13:34
@iliasg the preview matches the saved image perfectly here (Geeqie), check your black-point compensation both in RT and outside.

**Comment by iliasg** [comment] 2018-12-05 14:15
@Beep6581
- BlackPointCompensation is ON at both preferences.color_management.monitor and RT output profile
- I only use RT these days ;)

Maybe RT misbehaves with my monitor profile ??
https://drive.google.com/file/d/1s_VNGW9Hd1eVRPXJ9hCTlJEZT1tVSr3Y/view?usp=sharing

But .. It's not only the rendering slightly different, histogram and the RGB/Lab/HSV values are also different (which I think are not affected by the monitor profile selected ..)
