### ISSUE TITLE
Another local adjusts inverse toggle / gamma slider GUI issue

### ISSUE THREAD

**Issue by chaimav** [Beep6581/RawTherapee#6517] opened 2022-07-05 20:39 UTC
Toggling the []Inverse checkbox for the Color & Light tool makes Gamma slider appear.

Same issue as #6507 where @Desmis provided a fix.

**Comment by Desmis** [comment] 2022-07-06 09:05
@chaimav 

I just push a change which should solve this GUI problem
These are minor changes (at the GUI level) but they are important

Jacques

**Comment by Desmis** [comment] 2022-07-19 09:11
@Lawrence37 @chaimav 
I think we can close this issue, unless of course it doesn't work.
For me it works and the emoticon of @chaimav  tends to prove it

Jacques

**Comment by chaimav** [comment] 2022-07-19 16:05
I have actually not tested it yet. I have been away from home and don't have access to my PC. The thumbs up was a thanks and not a verification.
Having said that, if it has been verified, I am ok with closing it. I tested the fix for #6507  and it worked there.

**Comment by Lawrence37** [comment] 2022-07-20 04:13
I can confirm the issue is fixed. By the way, is gamma supposed to be hidden in the advanced interface when inverse is checked? It's behaving that way both before and after the fix.

**Comment by Desmis** [comment] 2022-07-20 08:11
@Lawrence37 @chaimav 
Yes in inverse mode, gamma is always hidden 

The inverse mode is very restrictive. I think, in most cases, it is better to use the normal mode, and for the area not to be modified use "excluding spot" (it is in the Rawpedia documentation)

Jacques

**Closed as completed** 2022-07-20 15:08 UTC
Labels: type: bug, scope: GUI
