### ISSUE TITLE
Add an option to merge 2 frames from Dual Pixel RAW to a single image with improved dynamic range 

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6078] opened 2021-01-29 03:31 UTC
There is an SN mode already, but this is a bit different. I think you can even hardcode that the first frame is exactly 1 EV brighter than the second. There is DPR Split, but it is not open source, and it would be great to have the extended dynamic range in a single click

Maybe I should submit this to HDRMerge first?

**Comment by Beep6581** [comment] 2021-01-29 08:38
Duplicate of #1972

**Closed as completed by Beep6581** 2021-01-29 08:38 UTC
Labels: type: enhancement
