### ISSUE TITLE
Canon EOS R CR3 raw support

### ISSUE THREAD

**Issue by DawidLoubser** [Beep6581/RawTherapee#5317] opened 2019-05-06 22:04 UTC
Hi, not sure if this helps, but I have added two sample file (RAW and C-RAW) CR3 files from the Canon EOS R to https://raw.pixls.us/

I can't wait until Rawtherapee supports Canon's new CR3 format - and if there is anything else I can do to support the reverse-engineering efforts, please let me know!

**Comment by LebedevRI** [comment] 2019-05-08 20:34
Duplicate of #4531.

**Comment by Beep6581** [comment] 2019-05-11 09:28
I opened issue #5319 for tracking support for decoding the CR3 format. Let's use this issue only for auxiliary support (white levels, matrix, DCP, etc.) specific to the Canon EOS R, once decoding is implemented.

**Comment by Beep6581** [comment] 2019-11-19 18:31
@DawidLoubser RawTherapee now supports decoding CR3 raw files (but not metadata). Feel free to supply daylight + incandescent tungsten shots of a [color target](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles) as well as LENR=on [white frame](http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) shots (set 2).

**Comment by DawidLoubser** [comment] 2019-11-20 11:13
Oh nice! I ended up selling my EOS-R body because none of the open-source RAW editors supported CR3 after such a long time, so I won't be able to contribute those shots right now, apologies.

**Closed as completed** 2019-11-20 11:43 UTC
Labels: type: enhancement, scope: file format

**Comment by Krijger** [comment] 2019-12-11 19:16
This issue is closed; does that mean the shots have already been provided? I own a R, but do not have color cards or anything.

**Comment by Beep6581** [comment] 2019-12-12 11:45
@Krijger the shots have not been provided. If you would like to contribute, see:
http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats#White_Levels

**Comment by Krijger** [comment] 2019-12-13 17:20
@Beep6581 please see https://we.tl/t-XWzKNQzj2I for the white level pictures - I used wetransfer as filebin kept giving me network errors. I hope I executed everything correctly (I kept the histogram completely of the charts by about 1 stop for all pictures), because the promised huge compression is not really happening.

I added the JPEGs as well, for purposes of the EXIF data (since CR3 metadata is not implemented yet)

**Comment by Krijger** [comment] 2019-12-13 17:41
Also, while we do not have the actual data for the color profiles, it would make sense to copy the 5D IV files for that, since the sensor is very similar:

> A familiar pixel count of 30MP that’s used only in one other Canon camera currently—the Canon EOS 5D Mark IV—suggests that Canon uses the same sensor or a variant of it in the EOS R. Our testing appears to bear that out, as the EOS R’s sensor results are very close to those of the EOS 5D Mk IV. Comparing the EOS R”s ISO 2742 against the EOS 5 D Mk IV’s ISO 2995, there’s less than 0.13 EV difference in low-light ISO (Sports), just a 0.3-bit difference in color depth (Portrait) at base, and a difference of less than 0.1 EV at the base ISO of 100 in dynamic range (in other words, both cameras have effectively the same dynamic range).

(source https://www.dxomark.com/canon-eos-r-sensor-review/)

**Comment by Krijger** [comment] 2019-12-17 12:34
@Beep6581 can you please respond to the post where I supply the white level files? I don't know how long wetransfer keeps the link active, so it would be nice to know that the files have been downloaded

**Comment by Beep6581** [comment] 2019-12-17 12:49
Hey @Krijger , I have downloaded the files.

**Comment by albfe** [comment] 2020-07-20 10:15
Hello, any update on completing Canon EOS R support? Anything that we can do to help with this?
