### ISSUE TITLE
Feature request: allow the user to set the center of the Vignette Filter in the Exposure tab

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3921] opened 2017-06-12 20:55 UTC
As asked by Marco_Colnaghi [here](https://discuss.pixls.us/t/rawtherapee-decentered-vignetting-filter/4428), it would be nice the user could be allowed to specify the center of the vignette in the Vignette filter from the Exposure tab, just like it is in the Vignetting correction from the Transform tab.
The advantage of having this in the Exposure tab, is that it would be applied to the cropped area, not to the whole image.

**Comment by Beep6581** [comment] 2017-06-18 12:34
Duplicate of #2675

**Closed as completed by Beep6581** 2017-06-18 12:34 UTC
Labels: type: enhancement
