### ISSUE TITLE
Error in blue/red equalizer since RawTherapee 5.11

### ISSUE THREAD

**Issue by fodoh-info** [Beep6581/RawTherapee#7233] opened 2024-10-27 16:31 UTC
**Short description**

When testing a colour wheel with RawTherapee 5.11 I had an unexpected behaviour when using  blue/red equalizer at maximum value of 2. The error happens with other images as well, may be the change/error happens at other values of blue/red equalizer.

**Steps to reproduce**

Expected  behaviour is that the amount of red is increasing. Instead ithe picture swaps to a blue one.

**Additional information**

**Comment by Lawrence37** [comment] 2024-10-27 19:00
There are some combinations of temperature, tint, and equalizer that are beyond what the white balance tool was designed to do. An equalizer value of 2 is usable for some temperature and tint ranges, which is why you can set it to 2. Users just have to be aware that pushing adjustments to the extreme may produce undesirable results.

**Comment by fodoh-info** [comment] 2024-10-28 07:05
Thank you for the information.
V5.11 behaves other than v5.10 and v5.8. In last both it is somehow a linear behaviour, the more I move the slide the more the picture gets read. In v5.11 it's only linear to a certain value and then the pictures turns with one little increment from red to blue feeling.
Imho this is a bug or at least a change in implementation. Because I love to work with RawTherapee I created this issue.

**Comment by Lawrence37** [comment] 2024-10-29 04:04
The maximum equalizer value in 5.10 was 1.5. The range was extended to handle more extreme situations, such as images taken on an ultraviolet-converted camera. Unfortunately, RawTherapee flips between using temperature-tint and RGB multipliers which means its flexibility is limited by the weakest link, the temperature-tint model. Using an RGB-multipliers-first implementation internally could improve the situation.

**Comment by Lawrence37** [comment] 2024-12-23 00:29
Closing because this is not actually a bug.

**Closed as not planned by Lawrence37** 2024-12-23 00:29 UTC
