### ISSUE TITLE
Add to queue does not work / crash RT on modern Windows when files are in a folder which's name contains special characters (e.g. Zdjęcia)

### ISSUE THREAD

**Issue by ravak** [Beep6581/RawTherapee#3387] opened 2016-07-24 16:09 UTC
1. Run RT
2. Add a file to queue (doesn't matter what profile)
3. View queue - fine, run manually, fine
4. Add another file to queue
5. View queue - crash

Also queue doesn't work with auto-run. I can save a file manually though. Running Windows 10 Home. 

Attached log.txt: [log.txt](https://github.com/Beep6581/RawTherapee/files/380351/log.txt)

About build:

```
Branch: gtk3
Version: 4.2.1148
Changeset: 2bfb0acdd7ea202bb716e84585802d1875e41da4
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: debug
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -fopenmp -O0 -g2
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -O0
OpenMP support: ON
MMAP support: ON
```

Also shows up:

```
(rawtherapee.exe:5220): glibmm-CRITICAL **:
unhandled exception (type Glib::Error) in signal handler:
domain: g_convert_error
code  : 1
what  : Invalid byte sequence in conversion input


(rawtherapee.exe:5220): glibmm-CRITICAL **:
unhandled exception (type Glib::Error) in signal handler:
domain: g_convert_error
code  : 1
what  : Invalid byte sequence in conversion input


(rawtherapee.exe:5220): glibmm-CRITICAL **:
unhandled exception (type Glib::Error) in signal handler:
domain: g_convert_error
code  : 1
what  : Invalid byte sequence in conversion input
```

**Comment by Beep6581** [comment] 2016-07-28 20:23
@Floessie @heckflosse do you see anything usable in that stack backtrace?

@ravak "Add a file to queue (doesn't matter what profile)" Have you tried using the "(Neutral)" profile?

**Comment by ravak** [comment] 2016-07-28 20:38
@Beep6581 Yes, just tried it: opened a file, selected Neutral profile, added to queue from editor -> could view the queue, closed the editor -> could still view the queue tab, added to queue from file browser -> viewing queue crashed RT.

Another test: opened file 1 in editor, added to queue (can view queue), opened file 2 in editor, added to queue -> view queue crashed RT.

**Comment by Floessie** [comment] 2016-07-29 09:42
@Beep6581 Although it says to be a debug build, there are only very few symbols present, and I couldn't determine the problematic location. Maybe you are able to reproduce the problem and provide a better backtrace. Is it only on gtk3 or also on master?

**Comment by ravak** [comment] 2016-07-29 09:46
It looks like libcairomm is missing debugging info. Where can I find non-gtk3 debug build for Win64?

**Comment by Beep6581** [comment] 2016-07-29 14:06
@ravak https://filebin.net/xebizj40bdqongsf/RawTherapee_WinVista_64_Master_Debug_4.2.992.zip
@Floessie haven't been able to reproduce it.

**Comment by ravak** [comment] 2016-07-29 17:57
@Beep6581 This build works fine. Although cannot make Auto-start processing to work. After manually kickstarting the process, next added to queue stops the queue:

```
(rawtherapee.exe:11012): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(rawtherapee.exe:11012): glibmm-CRITICAL **:
unhandled exception (type Glib::Error) in signal handler:
domain: g_convert_error
code  : 1
what  : Invalid byte sequence in conversion input


(rawtherapee.exe:11012): glibmm-CRITICAL **:
unhandled exception (type Glib::Error) in signal handler:
domain: g_convert_error
code  : 1
what  : Invalid byte sequence in conversion input
```

**Comment by Beep6581** [comment] 2016-07-30 15:38
I guess the queue stops because some error is encountered, and that error could be "Invalid byte sequence in conversion input". Can you reproduce the problem with these?
http://rawtherapee.com/shared/test_images/amsterdam_moving_boat_1.pef
http://rawtherapee.com/shared/test_images/amsterdam_moving_boat_2.pef
http://rawtherapee.com/shared/test_images/amsterdam_moving_boat_3.pef
Are you editing the metadata in RT, or have you edited in the input images in some other software before using RT? Upload a sample image file which exhibits this problem using https://filebin.net/

**Comment by ravak** [comment] 2016-07-30 17:35
Yes, those files work. I'm using Nikon D750's RAWs, no processing, fresh from SD card. Attaching a file: https://filebin.net/21kb9i9zbbef5xed

**Comment by ravak** [comment] 2016-08-05 18:48
Anything else I can provide to help triage this bug?

**Comment by Beep6581** [comment] 2016-08-06 11:40
I cannot reproduce the crash nor the queue stopping in Linux, but I get these in the console when saving:
```
TIFFFillStrip: Read error on strip 11; got 104848 bytes, expected 289152.
TIFFFillStrip: Read error on strip 11; got 285072 bytes, expected 289152.
TIFFFillStrip: Read error on strip 12; got 180240 bytes, expected 289152.
TIFFFillStrip: Read error on strip 12; got 286736 bytes, expected 289152.
```

With `verbose=true` I also get these:
```
TIFFFetchNormalTag: Warning, ASCII value for tag "Artist" contains null byte in value; value incorrectly truncated during reading due to implementation limitations.
TIFFFetchNormalTag: Warning, ASCII value for tag "Copyright" contains null byte in value; value incorrectly truncated during reading due to implementation limitations.
TIFFFetchNormalTag: Warning, ASCII value for tag "Artist" contains null byte in value; value incorrectly truncated during reading due to implementation limitations.
TIFFFetchNormalTag: Warning, ASCII value for tag "Copyright" contains null byte in value; value incorrectly truncated during reading due to implementation limitations.
TIFFFillStrip: Read error on strip 14; got 122128 bytes, expected 289152.
```

Maybe related to #3367?

**Comment by jaghaimo** [comment] 2016-08-26 22:50
~I can confirm this to be Windows 10 specific issue. Just downgraded to 8.1 and it's fine.~

Not an W10 specific issue.

**Comment by heckflosse** [comment] 2016-08-26 23:14
@ravak That's good and bad to know. Good because you tracked it down to Windows 10. Bad because no dev is on Windows 10 currently afaik. At least I'm not (I'm on windows 7)

**Comment by ravak** [comment] 2016-09-26 07:40
@heckflosse And now it happens on Windows 8.1 as well (latest build / 1148).

**Comment by Beep6581** [comment] 2016-09-26 11:15
@ravak does it happen with 4.2.936 (Gtk+ 2 not Gtk+ 3)?

**Comment by heckflosse** [comment] 2016-09-26 11:25
@ravak Can you upload your [options file](http://50.87.144.65/~rt/w/index.php?title=File_Paths#Config) please?

**Comment by ravak** [comment] 2016-09-28 22:30
@heckflosse [RawTherapee.zip](https://github.com/Beep6581/RawTherapee/files/499384/RawTherapee.zip)

@Beep6581 I wanted to test on https://filebin.net/xebizj40bdqongsf/RawTherapee_WinVista_64_Master_Debug_4.2.992.zip but it's no longer available

**Comment by heckflosse** [comment] 2016-09-28 22:49
@ravak Can you trigger the crash also when language is set to `English (UK)` ?

**Comment by Beep6581** [comment] 2016-09-29 06:57
@ravak you can get and test on new builds from https://filebin.net/y0hivouboulbzadn

**Comment by ravak** [comment] 2016-09-29 09:04
I will be traveling for a week so all testing will be done after Wed. Sorry.

**Comment by ravak** [comment] 2016-10-09 08:07
@heckflosse Yes, triggeres on {{English (UK)}} as well

**Comment by ravak** [comment] 2016-10-09 08:15
@Beep6581 on 1069 (master) I get "Invalid byte sequence in conversion input" after each file that gets saved via Queue (queue stops, but does not crash the program). Each image develops fine.

On 1234 (GTK3) it crashes.

**Comment by ravak** [comment] 2016-10-09 08:21
And just crashed (on 1234 build) a crash while developing old E-300 photos. Same problem.

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rawtherapee.exe
  Application Version:	0.0.0.0
  Application Timestamp:	57ebce45
  Fault Module Name:	libcairomm-1.0-1.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	0000000000001b3f
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	2057
  Additional Information 1:	b870
  Additional Information 2:	b8703fe0b5f85b60ffc795ad11be146e
  Additional Information 3:	3915
  Additional Information 4:	391560f94c3fde6bf0fa5dda6fce34e5
```

**Comment by Beep6581** [comment] 2016-10-09 20:23
@ravak can you reproduce using http://www.imaging-resource.com/PRODS/nikon-d750/Y_DSC0612.NEF.HTM ?
Can you record a [screencast](https://getsharex.com/) from the moment you first run RT?

**Comment by ravak** [comment] 2016-10-09 21:31
@Beep6581 any specific version of RT?

**Comment by heckflosse** [comment] 2016-10-09 21:33
@ravak latest master build

**Comment by ravak** [comment] 2016-10-09 21:42
@heckflosse It will be 1069 master provided by @Beep6581 in https://github.com/Beep6581/RawTherapee/issues/3387#issuecomment-250386017

**Comment by heckflosse** [comment] 2016-10-09 22:07
@ravak That should be good too

**Comment by ravak** [comment] 2016-10-12 18:40
@Beep6581 @heckflosse master won't do, as it only pops up an error (and does not crash). Recording screencasts on both versions anyway. It seems to cause issues on my files, and it may have something to do with 'author' / 'copyrights' fields being set up (both on E-300 and D750).

Your file (fine) + my D750 file (error) on master 1069 : https://db.tt/Y40mXKki
My E-300 file (error) on master 1069 : https://db.tt/TEcUOnqj
Your file (fine) + my D750 file (crash) on gtk3 1234 : https://db.tt/sdOakzZb
File itself (D750)  : https://www.dropbox.com/sh/3ss956q9lwj1sbt/AABh1rayysIu0_C6oEFfTUB9a?dl=0

**Comment by Beep6581** [comment] 2016-10-12 19:40
@ravak you uploaded an Olympus file, not a Nikon D750 one.

**Comment by ravak** [comment] 2016-10-12 19:45
@Beep6581 Sorry, that was the first integration on ShareX. Yes, E-300 file is fine as that's the file that crashed RT in last screencast. I can crash it on both E-300 and D750, thus my conjecture that it's metadata (author / copyright tag) related... I'll update previous comment.

**Comment by Beep6581** [comment] 2017-04-15 20:50
No update, closing.

**Comment by jaghaimo** [comment] 2017-06-17 21:24
Hi, I've narrowed the issue down to polish characters in a filepath, e.g. "D:\Zdjęcia" crashes RT (even latest 5.1). Renaming to "D:\Zdjecia" solves the issue.

**Comment by heckflosse** [comment] 2017-06-18 10:54
@ravak Dou you mean the filepath of the raw files or the destination filepath of the queue?

**Comment by jaghaimo** [comment] 2017-06-19 11:30
@heckflosse it's the location of the original RAW file, e.g. changed the output folder for queue and it still happened.

On Windows 8.1, UK locale but PL keyboard and thus some filepaths will contain characters like: "ą, ę, ł, ż, ź, ć, ó".

**Comment by heckflosse** [comment] 2017-06-19 11:37
@raval Crash confirmed. I will take a look now.

**Comment by heckflosse** [comment] 2017-06-19 16:21
This patch fixes the crash:

```diff
diff --git a/rtgui/batchqueue.cc b/rtgui/batchqueue.cc
index f1d29c4d..68061486 100644
--- a/rtgui/batchqueue.cc
+++ b/rtgui/batchqueue.cc
@@ -237,7 +237,7 @@ bool BatchQueue::saveBatchQueue ()
             const auto& saveFormat = entry->saveFormat;
 
             // Warning: for code's simplicity in loadBatchQueue, each field must end by the '|' character, safer than ';' or ',' since it can't be used in paths
-            file << entry->filename << '|' << entry->savedParamsFile << '|' << entry->outFileName << '|' << saveFormat.format << '|'
+            file << entry->filename.c_str() << '|' << entry->savedParamsFile << '|' << entry->outFileName.c_str() << '|' << saveFormat.format << '|'
                  << saveFormat.jpegQuality << '|' << saveFormat.jpegSubSamp << '|'
                  << saveFormat.pngBits << '|' << saveFormat.pngCompression << '|'
                  << saveFormat.tiffBits << '|'  << saveFormat.tiffUncompressed << '|'

```

@agriggio @Floessie Can there be possible side effects or is there a better solution?

**Comment by heckflosse** [comment] 2017-06-20 09:29
I tested the patch from above also with chinese characters. Works fine on Windows. On linux it works fine even without patch.

**Closed** 2017-06-20 09:31 UTC
Labels: bug
