### ISSUE TITLE
Noise reduction does not render at less than 100% zoom

### ISSUE THREAD

**Issue by erentar** [Beep6581/RawTherapee#7228] opened 2024-10-24 21:45 UTC
**Short description**
here is the frame at 50% zoom
![image](https://github.com/user-attachments/assets/8da8c47a-cecb-48cd-a70d-a62ee9f2e305)

here it is at 100% zoom
![image](https://github.com/user-attachments/assets/38ae9a93-cd69-406c-9bf9-7356d054470e)

as it can be seen there is a dramatic difference between the two zoom levels, this makes it impossible to look at the effects of noise reduction to the entire frame.

**Steps to reproduce**
1. open noisy image
2. max out noise reduction
3. 50% looks noisy and 100% looks dramatically blurry, makes it very hard to make tuning changes for the larger frame.

**Additional information**
version 5.11

**Comment by erentar** [comment] 2024-10-24 21:47
the only way i can tune the noise reduction whilst looking at the entire frame is to export repeatedly and look at how it looks when exported

which is very inconvenient and also slow, creates a lot of files etc

**Comment by syyrmb** [comment] 2024-10-26 01:13
At the right side of Noise Reduction tool, there is a "1:1" icon which indicates this tool's effect will only show at 1:1 (100%) zoom or more. You can use detail window widget to get around this (https://discuss.pixls.us/t/how-do-you-deal-with-the-1-1-modules-in-rawtherapee/14945/6).

**Comment by Lawrence37** [comment] 2024-10-26 17:11
Closing as a duplicate of #6077.

**Closed as not planned by Lawrence37** 2024-10-26 17:11 UTC
Labels: type: enhancement
