### ISSUE TITLE
Sony ILCA-68 raw support

### ISSUE THREAD

**Issue by FlorianPerennes** [Beep6581/RawTherapee#3295] opened 2016-05-20 20:04 UTC
Hi,( I'm sorry for the English, I'm french)
I've got a problem, when I open my RAW , they are colored, some are pink, the other blue or purple, and I don't know how to fix this bug, and it's very embarrassing...
I hope you could help me, I put photos with that ;)

 http://www.cjoint.com/c/FEuudY6mHSM

**Comment by sguyader** [comment] 2016-05-20 20:09
Hi Florian,

Please upload problematic RAW files and their PP3 files to http://filebin.net
Without RAW files and we so few details, we cannot tell you what's happening.

Sébastien

**Comment by FlorianPerennes** [comment] 2016-05-20 20:28
Hi Sebastien :
http://filebin.net/62pplaohvk, 
I've tried some things so I think it will be in the PP3

**Comment by ClaesGitHub** [comment] 2016-05-21 13:12
@FlorianPerennes It is the RAW file that we need, not a .png.

**Comment by FlorianPerennes** [comment] 2016-05-21 17:45
@sguyader  @ClaesGitHub 
Here are the RAW file and the PP3 : http://filebin.net/kmiftmqsuo

**Comment by ClaesGitHub** [comment] 2016-05-21 18:20
Salut, Florian!
I have looked at the photo & your pp3. As I see it, it is not what you did in the pp3, instead it is what you did _not_ do :-) Try the following:

- Open the photo in RT.
- Select Processing Profile | Neutral (just to null everything out).
- Select Processing Profile | Bundled Profiles | Default ISO High.
- Tab Exposure | Tone curve 1 | Custom: drag the upper right dot to the left so that the dot gets much closer to the high spike. 
- Still in Tone curve 1: drag the lower left dot so that the dot get much closer to where the histogram starts.

Is that result more to your liking?

**Comment by FlorianPerennes** [comment] 2016-05-21 19:28
@ClaesGitHub, I've tried what you've said but it's still the same result : I've already the same horrible pink "filter" even if there is some ameliorations... while I've a "normal" RAW when I open it in trial version of Adobe Lightroom (takes end tomorow :( )...
Thanks anyway :)

**Comment by ClaesGitHub** [comment] 2016-05-21 19:32
Test to set white balance in RT to
Temperatue 6368
Tint 0.656
Blue/Red equalizer 1.000

**Comment by FlorianPerennes** [comment] 2016-05-22 08:10
@ClaesGitHub It's better with that ! And I've tried with DCP of sony ILCA-68 and there is a little amelioration... It's almost good :)

**Comment by iliasg** [comment] 2016-05-22 08:11
@FlorianPerennes Hi Florin, Sony ILCA-68 is not yet supported by RT, that's why it uses wrong "Black Level" for these files.
You can either set the Raw Black levels at +512 

or better insert the following lines in your camconst.json file (yoy will find it in the installation folder of your RT) .. just after ILCA 77M2 lines ..

```
    { // Quality B,
        "make_model": "Sony ILCA-68",
        "dcraw_matrix": [ 6435,-1903,-536,-4722,12449,2550,-663,1363,6517 ], // adobe DNGv9.5 d65
        "raw_crop": [ 0, 0, 6024, 4024 ],
        "ranges": { "black": 512, "white": 16300 }
    },
```

**Comment by ClaesGitHub** [comment] 2016-05-22 08:22
Good morning! I have not yet made the changes that iliasg sugegsted a few minutes ago. Instead, I tested another method: I converted your arw to dng (using Adobe's free DNG converter), and then processed both using the Default Medium ISO processing profile. Here is the result:
![sony_arw](https://cloud.githubusercontent.com/assets/19223977/15453059/7b8bbd64-2006-11e6-8354-83453372bc9f.png)

**Comment by ClaesGitHub** [comment] 2016-05-22 08:39
@iliasg Your camconst.json modification works just fine :-)
@FlorianPerennes What do you think about this result? 
![json](https://cloud.githubusercontent.com/assets/19223977/15453136/5a374ee6-2009-11e6-8fb6-e3e45674c683.png)

**Comment by FlorianPerennes** [comment] 2016-05-22 08:48
Hi !,
@ClaesGitHub When I convert the RAW file into a .dng , it work too for me ! :)
@iliasg  I've put the lines into the camcost but it doesn't work, I have to do a manip after copy the lines or no ?

**Comment by iliasg** [comment] 2016-05-22 08:48
@ClaesGitHub hi .. which is the exact size RT displays for the DNG converted file ?. Can you upload it ?
I see some garbage columns at the right with my suggested camconst raw crop ..
By eye detecting we have to crop at least 6 columns so change raw crop to [ 0, 0, -30, 0 ]

Negative values in camconst raw crop are subtracted from the full size raw frame i.e 6048x4016 become 6018x4016 and this format (subtracting insted of setting absolute size) is better suited for cameras with multiple frame sizes (like Nikon - Sony APS-C crops etc).

**Comment by Beep6581** [comment] 2016-05-22 09:05
@ClaesGitHub the problem is lacking support for Sony ILCA-68 which the code @iliasg provided fixes, so let's focus on the proper solution and not give workarounds and subjective PP3s here in GitHub, as this is an issue tracker which notifies all devs every time an issue is updated. Workarounds and user support happens in our forum over at http://discuss.pixls.us/

**Comment by iliasg** [comment] 2016-05-22 09:27
@FlorianPerennes yoy have to restart RT to see the effect of the changes ;)

**Comment by FlorianPerennes** [comment] 2016-05-22 09:55
@iliasg Well, I think I will wait  a new version of raw therapee x) I've copied the lines in the camconst.json , save it, restart RT but still nothing...
Thanks anyway :)

**Comment by ClaesGitHub** [comment] 2016-05-22 09:58
@iliasg Of course:

- Original ARW: 6016 x 4008
- DNG: 6016 x 4008
- json: 6016 x 4008
- http://filebin.net/4mmb9hv2mt

**Comment by ClaesGitHub** [comment] 2016-05-22 10:02
@FlorianPerennes 
I think I know what is your problem. Please join the friendly forum over at http://discuss.pixls.us/ and put your camconst.json question there...

**Comment by Beep6581** [comment] 2017-01-04 23:10
SONY ILCA-68 is supported in camconst.json.
Links are expired.
DCP missing - open a new issue if you can shoot a colortarget.
Closing.

**Closed by Beep6581** 2017-01-04 23:10 UTC
Labels: raw
