### ISSUE TITLE
Problem with auto matched tone curve button and old profiles - version 5.5 RC1 

### ISSUE THREAD

**Issue by esby** [Beep6581/RawTherapee#5089] opened 2018-12-11 21:48 UTC
Hello, just to report a potential bug:

It affects the 5.5 branch, probably 5.4 too, not sure actually.

Tested under Debian Linux 5.5.

It's linked to the auto matched tone curve "button".

From my understanding, apparently, if you previously loaded a profile in which the pp3 values linked to the histogram were present and set to true (or if you activated it previously), if the profile you are loading does not contain such parameter (which happends with either old profiles or some profiles (eg:   Skintones/Skintones - Natural.pp3) , it will activate and most of the exposure tool sliders will be reset.

How to reproduce it:
1 - get the profiles.zip (NB: I can't attach pp3 files, maybe this could be corrected.)
[profiles.zip](https://github.com/Beep6581/RawTherapee/files/2669561/profiles.zip)

2 - unzip it somewhere.
3 - get a test raw and open it.
4 - apply "profile_using_histo.pp3"
the luminance should be 'high.
5- apply "profile_not_using_histo.pp3".
the luminance should be darker, but the button triggers and resets the sliders.

by changing a slider, one can get the "profile_not_using_histo.pp3" to load correctly.

the concerned pp3 sections are:
HistogramMatching=true
FromHistogramMatching=true
ClampOOG=true

My understanding is that a profile loaded priorly should not affect in that way a profile that is loaded after it. I assume new pp3 will contain the proper pp3 to enable or disable it, so in order to be compatible, the values should be disabled if no profile is found?

**Comment by Beep6581** [comment] 2018-12-11 21:55
The issue seems to be that when the following values are missing from a PP3:
```
HistogramMatching
FromHistogramMatching
```
then the assumption is that `HistogramMatching=true`, and when that happens it destroys some of the exposure settings, and possibly it also destroys tone curve 1 (not tested).

Expected behabior:
When a PP3 does not have those keys, RT assumes `HistogramMatching=false` and leaves the values alone.

@agriggio do you agree, and if so, any chance you could include the fix for 5.5?

**Comment by heckflosse** [comment] 2018-12-11 21:57
@agriggio alberto, please tell me if you don't have time to fix it. I will have a look then.

**Comment by agriggio** [comment] 2018-12-11 22:05
Sorry, I have no idea what `FromHistogramMatching` is, nor what it does :-/ It's not something I remeber having done, actually...

**Comment by Beep6581** [comment] 2018-12-11 22:14
@agriggio as I just learned, it means that the curve in the PP3 file derives from a previous histogram matching run, in order to skip unnecessary future runs.

**Comment by heckflosse** [comment] 2018-12-11 23:05
I will have a look tomorrow

**Comment by heckflosse** [comment] 2018-12-12 11:21
@esby I can not reproduce

If the processing profile fill mode button is pressed (means the missing values are replaced with default values) the image is darker (correct)

If the processing profile fill mode button is not pressed (means the missing values are not replaced with default values) the auto matched tone curve stays active (correct)

**Comment by esby** [comment] 2018-12-12 12:44
@heckflosse 

Well, the issue is that button will press itself after loading a profile, not that the button actually performs its job.

video illustrating the issue - https://www.youtube.com/watch?v=_hcjWASGYZQ&feature=youtu.be%3Fcc_load_policy%3D1

added the rw2 raw in the samples.zip

[samples.zip](https://github.com/Beep6581/RawTherapee/files/2671927/samples.zip)

**Comment by heckflosse** [comment] 2018-12-12 13:01
@esby The processing profile fill mode button is not pressed in your video, means missing values from pp3 are not touched. For that reason histogram matching stays active.
![grafik](https://user-images.githubusercontent.com/13733487/49871400-6e6a5c80-fe16-11e8-89c2-a9db99da0983.png)

**Comment by Beep6581** [comment] 2018-12-12 14:15
I was wrong yesterday, when the `*HistogramMatching` keys are missing from a PP3 then the assumption is **not** that `HistogramMatching=true`. I was thrown off by what @heckflosse correctly pointed out. I tested now using profiles from 5.5-rc2 where I removed the `*HistogramMatching` keys, and using profiles from 5.3 where those keys didn't exist, and confirm that RawTherapee 5.5-rc2 does the right thing, just keep the "fill mode" button in mind.

**Comment by esby** [comment] 2018-12-12 16:53
Can someone clarify what the wiki is saying on the partial profil fill mode?

https://rawpedia.rawtherapee.com/Sidecar_Files_-_Processing_Profiles#Partial_Processing_Profiles_and_Fill_Modes

> The processing profile fill mode lets you decide what happens when you apply a processing profile to an image when that profile does not contain information about all of the tool settings.
> 
> "Fill" mode Profile-filled.png
> When in "Fill mode", the missing values will be taken from RawTherapee's hard-coded default values (typically neutral). For instance if you apply a partial profile which contains only sharpening settings, all of the remaining tools (such as Exposure, Tone Mapping, Noise Reduction, Resize, etc) will pop into their default positions.
> "Preserve" mode Profile-partial.png
> When in "Preserve mode", only those values in the profile will be applied, and the missing ones remain unchanged.

it only applies to settings inside a tool that would be missing, it is not supposed to reset tool that are not set in this partial profile, isn't it ? I am trying to understand the utility of this mode.  

Let's say a pp3 contains only these lines, partial fill mode won't change anything to its load?

> [Impulse Denoising]
> Enabled=true
> Threshold=50
> 
> [Directional Pyramid Denoising]
> Enabled=true
> Enhance=false
> Median=false
> Luma=28.75
> Ldetail=59.939999999999998
> Chroma=15
> Method=Lab
> LMethod=SLI
> CMethod=MAN
> C2Method=AUTO
> SMethod=shal
> MedMethod=soft
> RGBMethod=soft
> MethodMed=Lonly
> Redchro=0
> Bluechro=0
> Gamma=1.7
> Passes=1
> LCurve=1;0.050000000000000003;0.14999999999999999;0.34999999999999998;0.34999999999999998;0.55000000000000004;0.040000000000000001;0.34999999999999998;0.34999999999999998;
> CCCurve=1;0.050000000000000003;0.5;0.34999999999999998;0.34999999999999998;0.34999999999999998;0.050000000000000003;0.34999999999999998;0.34999999999999998;

**Comment by Beep6581** [comment] 2018-12-12 17:18
@esby I think your confusion comes from this part:

> and the missing ones remain unchanged.

That is correct, so here's why in some cases the Black, Lightness and Contrast sliders change:

- When Auto-Matched Tone Curve is disabled and then you apply a profile which does not have a `HistogramMatching` key but has custom Black, Lightness and Contrast slider settings, AMTC remains off, regardless of fill mode because its default, hard-coded setting is "off", and so your Black, Lightness and Contrast slider settings are applied as in the applied profile.
- When AMTC is enabled and you apply a profile which does not have a `HistogramMatching` key, AMTC remains enabled if fill mode is "preserve". Since the profile had no `HistogramMatching` key, and since AMTC was enabled, then it remains enabled. And since AMTC requires setting the Black, Lightness and Contrast sliders to 0, it does that, thereby overriding those three values if the applied profile had them.
- As in the previous point but if fill mode is set to "fill", then AMTC is disabled. Since it's disabled, the Black, Lightness and Contrast sliders are not touched, and the values from the PP3 are visible.

**Comment by esby** [comment] 2018-12-14 10:57
@Beep6581 thanks for the clarification.

If I understand well, in partial fill mode, we are talking of tools that have incomplete settings, probable due to the rt evolution over time I'd assume. 
I am assuming this setting acts as a compatibility layer, which allows to reset incorrectly parametred tools to their default values.

Partial profiles (which can be generated by ctrl + save profile) are partial in the sense that they corresponds to the tool/filters being selected at the point of the save. Still, they are 'complete' at the tool level as the application should generate correctly the settings (unless there is a bug, but it should not happend in released version).

I am wondering if the partial fill mode (and icons) should not be at some point 'renamed' to avoid the confusion to users, I also think the icon could be changed, since both looks like 'active icons' while it would probably be better to have a 'on / off' style : the icon being striked or changing of color, what ever is the way to mark the difference, because currently one does not have really a way of guessing which one of the icons does what, from the icon difference. 

Something like 'tool fallback loading value: on/off' (maybe with a warning that turning it off can lead to issues or bugs with old profile loading) or what ever formulation might be clearer, so the  drop the partial association can be dropped... 

Anyway, this is definitely out of 5.5 scope.

**Comment by Beep6581** [comment] 2018-12-14 12:00
You're welcome.

> in partial fill mode, we are talking of tools that have incomplete settings, probable due to the rt evolution over time I'd assume.

The intention behind the fill mode is to allow having a profile which, for example, contains only color-related settings, so that when pasting the profile in partial fill mode it changes the images colors but does not touch exposure, noise reduction, etc. Think of it as applying to keys, not to tools, where tools are just groups of keys. So if you're pasting only the "Exposure" group of keys, and in this group the `Compensation` key is missing, then what happens is up to the mode. Likewise, you're pasting the whole profile and the "Wavelet" group of keys is missing, what happens is again up to the fill mode.

Issue resolved (everything worked correctly), closing.

**Closed as completed by Beep6581** 2018-12-14 12:00 UTC
