### ISSUE TITLE
Segfault in LUT.h from ipshadowshighlights.cc

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4922] opened 2018-11-02 08:55 UTC
I get a segfault when opening a folder with an image with the attached PP3.

PP3: [amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2541726/amsterdam.pef.pp3.txt)
Stack backtrace: [log.txt](https://github.com/Beep6581/RawTherapee/files/2541728/log.txt)

```
Version: 5.4-1060-gc362c0566
Branch: dev
Commit: c362c0566
Commit date: 2018-11-02
Compiler: cc 6.4.0
Processor: Intel(R)\ Core(TM)\ m3-6Y30\ CPU\ @\ 0.90GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: debug
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -g -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Thanatomanic** [comment] 2018-11-02 08:59
Confirmed. 

Update yet again: derp, hadn't seen @Beep6581 's backtrace 🙄  Removed mine.

**Comment by agriggio** [comment] 2018-11-02 10:55
Here's a fix, can you please test and commit on my behalf (assuming it works)? Thanks!

```diff
diff --git a/rtengine/ipshadowshighlights.cc b/rtengine/ipshadowshighlights.cc
--- a/rtengine/ipshadowshighlights.cc
+++ b/rtengine/ipshadowshighlights.cc
@@ -160,7 +160,7 @@
                     float orig = 1.f - blend;
                     if (l >= 0.f && l < 32768.f) {
                         if (lab_mode) {
-                            lab->L[y][x] = f[l] * blend + l * orig;
+                            lab->L[y][x] = intp(blend, f[l], l);
                             if (!hl && l > 1.f) {
                                 // when pushing shadows, scale also the chromaticity
                                 float s = max(lab->L[y][x] / l * 0.5f, 1.f) * blend;
@@ -173,7 +173,10 @@
                             float rgb[3];
                             lab2rgb(l, lab->a[y][x], lab->b[y][x], rgb[0], rgb[1], rgb[2]);
                             for (int i = 0; i < 3; ++i) {
-                                rgb[i] = f[rgb[i]] * blend + rgb[i] * orig;
+                                float c = rgb[i];
+                                if (!OOG(c)) {
+                                    rgb[i] = intp(blend, f[c], c);
+                                }
                             }
                             rgb2lab(rgb[0], rgb[1], rgb[2], lab->L[y][x], lab->a[y][x], lab->b[y][x]);
                         }
```

**Comment by Beep6581** [comment] 2018-11-02 10:58
@agriggio fix confirmed.

I'll let it simmer for a short while before committing.

**Comment by Thanatomanic** [comment] 2018-11-02 11:01
Is this how it should look like? (fix applied)

![image](https://user-images.githubusercontent.com/6567747/47911880-fdd73400-de96-11e8-8626-513fc9706aa1.png)

**Comment by agriggio** [comment] 2018-11-02 11:17
@Thanatomanic if the image is just a big patch of red, then sure ;-)
otherwise, please test starting from neutral. That red blob might be caused by some tweaks I made to the new color toning mode, that made old pp3's invalid

**Comment by Thanatomanic** [comment] 2018-11-02 11:19
@agriggio I think it is indeed due to the color toning. Normally you would see the nice Amsterdam canal, and disabling `Color toning` gets rid of the red.
So if @Beep6581 agrees, this fix can be merged.

**Comment by Beep6581** [comment] 2018-11-02 11:35
@Thanatomanic that's the red light district ;)

**Comment by agriggio** [comment] 2018-11-02 11:36
@Thanatomanic good, to double check please try again by setting reasonable color toning values, just to make sure. Thanks!

**Comment by Beep6581** [comment] 2018-11-02 12:02
@agriggio 72787cd99 looked like this:
![screenshot_20181102_125733](https://user-images.githubusercontent.com/5844619/47914259-35e27500-de9f-11e8-962e-a38cb497ec12.png)
HEAD with the patch looks like this:
![screenshot_20181102_125843](https://user-images.githubusercontent.com/5844619/47914270-4135a080-de9f-11e8-9d98-3efc00d1c7f7.png)

Resetting the CCG tool eliminates the cast, but then if I move the CCG points any amount it goes magenta again.

This happens even if I open a new, unedited image, or apply Neutral, so unfortunately something is broken and the patch cannot me committed.

**Comment by agriggio** [comment] 2018-11-02 12:21
I'll check

**Comment by heckflosse** [comment] 2018-11-02 12:26
It's not the patch which causes this. HEAD without the patch already has this bug.

**Comment by agriggio** [comment] 2018-11-02 12:44
@Beep6581 the bug has nothing to do with the patch. I'll fix both asap

**Closed as completed** 2018-11-02 12:49 UTC
Labels: type: bug

**Comment by Beep6581** [comment] 2018-11-02 13:43
I should have but hadn't tested vanilla-dev, sorry about that.
