### ISSUE TITLE
RawTherapee 5.2 crashes with Canon G3 images

### ISSUE THREAD

**Issue by esjaytee** [Beep6581/RawTherapee#4099] opened 2017-09-23 10:00 UTC
Version:
Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

OS:
Windows 7 Ultimate x64
SP1
Current Windows Updates installed

System:
AMD Athlon II x 4 620
4GB ram

RT download location:
http://rawtherapee.com/releases_head/windows/RawTherapee_5.2_WinVista_64.zip

---

Default Processing Profile for RAW photos: Neutral

When browsing to a folder with Canon G3 CR2 files, RawTherapee shows preview images, but on load (writes .pp3 file) and crashes. With .pp3 files in the folder it crashes instantly when browsing such folder.

Can't get full stack backtrace as gdb crashes ;) but these are the last lines from the gdb window when RawTherapee stalls:

[New Thread 4872.0x1208]
[New Thread 4872.0x11fc]
[New Thread 4872.0x26c]
[New Thread 4872.0x73c]
[New Thread 4872.0xa68]
[New Thread 4872.0x1064]
[New Thread 4872.0x65c]
[New Thread 4872.0x1048]
[New Thread 4872.0xc20]
[New Thread 4872.0x1130]
[New Thread 4872.0x1108]
[New Thread 4872.0x1060]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 4872.0xc20]
0x0000000000876f30 in rtengine::RawImage::get_colorsCoeff ()
    at C:/msys64/home/sguyader/rtrepo-gtk3/rtengine/rawimage.cc:139
139     C:/msys64/home/sguyader/rtrepo-gtk3/rtengine/rawimage.cc: No such file o
r directory.
(gdb)

files:

https://filebin.net/60snk31eax0bwljh

And no - it won't do this with Canon G2 files and no, RawTherapee 4.2.1 doesn't do this.

Samppa

**Comment by heckflosse** [comment] 2017-09-23 10:16
Duplicate of #4000 
Closing

**Closed as completed by heckflosse** 2017-09-23 10:16 UTC
