### ISSUE TITLE
Mouse wheel scroll don't work for all sliders in "CIE Color..." module

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#4219] opened 2017-12-09 16:26 UTC
When I use mouse wheel scroll in the "CIE Color Appearance Model 2002"-module, scrolling (often) gets stuck on certain sliders. It's a little tricky because it doesn't happen all the time and just wanted to see if others have experienced the same?

Using:
Version: 5.3-279-gd7fb8c913
Branch: dev
Commit: d7fb8c913
Commit date: 2017-12-09
Compiler: cc 7.2.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment] 2017-12-09 17:29
@mks9900 please explain what you're doing (are you scrolling the tool panel or scrolling the slider values or something else?) and what the problem is a bit more clearly.

**Comment by ghost** [comment] 2017-12-09 18:30
Sorry, I realise the description was a bit vague now :-)
I'm trying to scroll in the panel up or down with the mouse wheel. When the mouse pointer happens to get over a slider in the CIECAM module, the scrolling stops and I have to point the mouse pointer away from the slider, often further to the right. 
[Image showing the panel and pointer](https://www.dropbox.com/s/0og6a2xk2xbnddi/rt_mouse_scrolling_panel.png?dl=0)

**Comment by Beep6581** [comment] 2017-12-10 18:32
@mks9900 if you go to Preferences > General > Layout, what is the status of "Hide vertical scrollbar"?
Make sure it is not ticked, restart RT. Does it work well now?

**Comment by ghost** [comment] 2017-12-10 18:40
Ah, now it works! Thanks. I've had it hidden and didn't think of testing that.
As the issue isn't a big deal and this works as a workaround, should I close the issue?

**Comment by Beep6581** [comment] 2017-12-10 20:22
Then it's a duplicate of #3413 

@mks9900 which Linux distro and which version of Gtk+ are you using?

**Closed as completed by Beep6581** 2017-12-10 20:22 UTC

**Comment by ghost** [comment] 2017-12-11 08:20
I run Ubuntu 17.10 and gtk+ is at 3.22.25.
