### ISSUE TITLE
Feature request: JPEG XL

### ISSUE THREAD

**Issue by abnormally-distributed** [Beep6581/RawTherapee#6375] opened 2021-10-22 22:27 UTC
I think it would be nice to have JPEG XL support added for both importing and exporting in RT 5.9

- Supports up to 32 bit float encoding
- Has both lossy and lossless compression modes 
- Supports alpha (transparency) channel
- Is explicitly intended to replace the legacy JPEG format 

For more information: https://jpeg.org/jpegxl/

**Comment by Lawrence37** [comment] 2021-10-23 19:12
Duplicate of #6273.

**Closed as completed by Lawrence37** 2021-10-23 19:12 UTC
