### ISSUE TITLE
WXP master branch Compilation error for version 4.2.594

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#3076] opened 2016-01-09 10:40 UTC
When trying to build:
Branch: master
Version: 4.2.594
Changeset: cc266431646867831f8797689bfd7f1628eebdd4
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -m32  -mthreads -mstackrealign -std=gnu++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m32 -mthreads  -static-libgcc -Wl,--large-address-aware,--verbose  -march=native -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

I get this compilation error:

E:/RTSOURCE/rawtherapee/rtgui/batchqueue.cc: In member function 'bool BatchQueue::saveBatchQueue()':
E:/RTSOURCE/rawtherapee/rtgui/batchqueue.cc:227:25: error: variable 'std::ofstream file' has initializer but incomplete type
     std::ofstream file (fileName, std::ios::trunc);
                         ^
E:/RTSOURCE/rawtherapee/rtgui/batchqueue.cc: In member function 'bool BatchQueue::loadBatchQueue()':
E:/RTSOURCE/rawtherapee/rtgui/batchqueue.cc:267:33: error: variable 'std::ifstream file' has initializer but incomplete type
     std::ifstream file (fileName);
                                 ^
rtgui/CMakeFiles/rth.dir/build.make:2502 : la recette pour la cible « rtgui/CMakeFiles/rth.dir/batchqueue.cc.obj » a échouée
make[2]: *** [rtgui/CMakeFiles/rth.dir/batchqueue.cc.obj] Erreur 1
make[2]: *** Attente des tâches non terminées....
CMakeFiles/Makefile2:235 : la recette pour la cible « rtgui/CMakeFiles/rth.dir/all » a échouée
make[1]: *** [rtgui/CMakeFiles/rth.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Branch: master
Version: 4.2.583
Changeset: 7d28c2531c73f87775231959fd916684d59ae1df
Compiler: gcc 5.3.0
Processor: undefined
System: Windows
Bit depth: 32 bits
Gtkmm: V2.24.4
builds and runs fine

**Comment by Beep6581** [comment] 2016-01-09 11:03
This is a duplicate of #3074

**Closed by Beep6581** 2016-01-09 11:03 UTC
