### ISSUE TITLE
CR3 metadata decoding support

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#6248] opened 2021-05-20 15:13 UTC
Continuation from #5319

**Comment by Thanatomanic** [comment] 2021-05-20 17:07
This seems to only require a few minor changes to the `metadata-exiv2` branch in #5889.
See e.g. for ART https://bitbucket.org/agriggio/art/commits/1469a0a8225cb44fe7f130f375879aef23496a8b and darktable https://github.com/darktable-org/darktable/search?q=ISOBMFF

**Comment by feuerrot** [comment] 2021-06-27 18:51
@Thanatomanic I can confirm that the `metadata-exiv2` branch can use CR3 metadata with the new release of libexiv2:
![screenshot of a rawtherapee window](https://pbs.twimg.com/media/E46LVB1XwAQND0a.png)

I currently do not have a patch, as I couldn't find the right place to `Exiv2::enableBMFF(true);`, instead I patched my libexiv2 so BMFF is always enabled.

**Comment by KarlMagnusLarsson** [comment] 2022-05-26 15:31
I would like to try the metadata-exiv2 branch for CR3 metadata decoding support.

@feuerrot, Thank you for an interesting test. Can you make your libexiv2 patch available?

I am on Debian 11.3 with exiv2 0.27.3 installed. I will need to upgrade exiv2 to 0.27.4 or 0.27.5 anyway, to get CR3 support. I might as well patch it, if I build exiv2 from source for RT metadata-exiv2.

**Comment by feuerrot** [comment] 2022-06-03 15:07
@KarlMagnusLarsson I'm not quite sure if I still got the patches somewhere.

IIRC I used `apt-get source`, patched `static bool enabled = false` [here](https://github.com/Exiv2/exiv2/blob/main/src/bmffimage.cpp#L63), defined `EXV_ENABLE_BMFF` and build a package using standard debian tools.

According to [the debian package changelog](https://salsa.debian.org/qt-kde-team/extras/exiv2/-/blob/master/debian/changelog#L12) libexiv2 0.27.5-2 enables BMFF per default, so there's only a missing `Exiv2::enableBMFF(true);`. Maybe [`open_exiv2()`](https://github.com/Beep6581/RawTherapee/blob/metadata-exiv2/rtengine/imagedata.cc#L44) just before the ifdef is the correct location?

**Comment by KarlMagnusLarsson** [comment] 2022-06-04 14:26
@feuerrot, @Thanatomanic, @Beep6581, metadata-exiv2 branch works for me with patch from @feuerrot in rtengine/imagedata.cc and exiv2 upgraded to v0.27.5 with -DEXIV2_ENABLE_BMFF=On.

@feuerrot, Thank you for the feedback. You pinpointed a working position to patch open_exiv2() in RT rtengine/imagedata.cc file of metadata-exiv2 branch: Exiv2::enableBMFF(true).

rtengine/imagedata.cc
```
Exiv2::Image::AutoPtr open_exiv2(const Glib::ustring& fname)
{
/// Patch to enable BMFF
Exiv2::enableBMFF(true);
#ifdef EXV_UNICODE_PATH
    glong ws_size = 0;
    gunichar2* const ws = g_utf8_to_utf16(fname.c_str(), -1, nullptr, &ws_size, nullptr);
    std::wstring wfname;
    wfname.reserve(ws_size);
    for (glong i = 0; i < ws_size; ++i) {
        wfname.push_back(ws[i]);
    }
    g_free(ws);
    auto image = Exiv2::ImageFactory::open(wfname);
#else
    auto image = Exiv2::ImageFactory::open(fname);
#endif
    return image;
}
```
This is what I did on Linux Debian 11.3. Debian stable has exiv2 0.27.3 installed as system version. I decided to use the exiv2 git repo source for exiv2 v0.27.5.
1. Download and build exiv2 tag v0.27.5 from https://github.com/Exiv2/exiv2.git using -DEXIV2_ENABLE_BMFF=On
2. Set up PKG_CONFIG_PATH and LD_LIBRARY_PATH to pick up my new local build of exiv2 v0.27.5
3. Patch rtengine/imagedata.cc adding Exiv2::enableBMFF(true); just before the ifdef (as code block above)
4. Build patched RT metadata-exiv2 branch using exiv2 v0.27.5.
5. I can now decode CR3 metadata! Screenshot added.

![Screenshot from 2022-06-04 16-09-30](https://user-images.githubusercontent.com/42386052/172006310-31c591fc-3727-4ec4-bbb1-5bb77994d790.png)

**Comment by KarlMagnusLarsson** [comment] 2022-06-07 21:04
The metadata-exiv2 branch is 252 commits behind dev: https://github.com/Beep6581/RawTherapee/tree/metadata-exiv2. I understand it could be a hard job merging metadata-exiv2 branch into current dev. Nevertheless I wanted to try as a hack.

This is what `git merge metadata-exiv2` results in when merging into current dev (after committing small `Exiv2::enableBMFF(true);` patch to  metadata-exiv2:
```
Removing tools/generateRtexifUpdates
Auto-merging rtgui/thumbnail.h
CONFLICT (content): Merge conflict in rtgui/thumbnail.h
Auto-merging rtgui/thumbnail.cc
Auto-merging rtgui/filmnegative.cc
Auto-merging rtgui/editwidgets.h
Auto-merging rtgui/editwidgets.cc
Auto-merging rtgui/editorpanel.cc
CONFLICT (content): Merge conflict in rtgui/editorpanel.cc
Auto-merging rtgui/controlspotpanel.cc
Auto-merging rtgui/controllines.h
Auto-merging rtgui/controllines.cc
Auto-merging rtgui/CMakeLists.txt
Removing rtexif/stdattribs.cc
Removing rtexif/sonyminoltaattribs.cc
CONFLICT (modify/delete): rtexif/rtexif.h deleted in metadata-exiv2 and modified in HEAD. Version HEAD of rtexif/rtexif.h left in tree.
CONFLICT (modify/delete): rtexif/rtexif.cc deleted in metadata-exiv2 and modified in HEAD. Version HEAD of rtexif/rtexif.cc left in tree.
Removing rtexif/pentaxattribs.cc
Removing rtexif/panasonicattribs.cc
CONFLICT (modify/delete): rtexif/olympusattribs.cc deleted in metadata-exiv2 and modified in HEAD. Version HEAD of rtexif/olympusattribs.cc left in tree.
Removing rtexif/nikonattribs.cc
Removing rtexif/kodakattribs.cc
Removing rtexif/fujiattribs.cc
Removing rtexif/canonattribs.cc
Removing rtexif/CMakeLists.txt
Auto-merging rtengine/simpleprocess.cc
Auto-merging rtengine/rtthumbnail.cc
CONFLICT (content): Merge conflict in rtengine/rtthumbnail.cc
Auto-merging rtengine/rtengine.h
Removing rtengine/rawmetadatalocation.h
Auto-merging rtengine/rawimagesource.cc
Auto-merging rtengine/procparams.h
Auto-merging rtengine/procparams.cc
Removing rtengine/iptcpairs.h
Auto-merging rtengine/iplocallab.cc
Auto-merging rtengine/improcfun.h
Auto-merging rtengine/improcfun.cc
Auto-merging rtengine/improccoordinator.cc
Auto-merging rtengine/imagesource.h
CONFLICT (content): Merge conflict in rtengine/imagesource.h
Auto-merging rtengine/imageio.h
Auto-merging rtengine/imageio.cc
CONFLICT (content): Merge conflict in rtengine/imageio.cc
Auto-merging rtengine/imagedata.cc
CONFLICT (content): Merge conflict in rtengine/imagedata.cc
Auto-merging rtengine/dfmanager.cc
Auto-merging rtengine/dcrop.cc
Auto-merging rtengine/dcp.h
Auto-merging rtengine/dcp.cc
Auto-merging rtengine/CMakeLists.txt
Auto-merging CMakeLists.txt
```
I tried to resolve merge conflicts (content) and keep files deleted in metadata-exiv2 (modify/delete). Then I got:
```
[  1%] Building CXX object rtengine/CMakeFiles/rtengine.dir/dcp.cc.o
/home/magnus/test/rt_exiv2/RawTherapee/rtengine/dcp.cc: In constructor ‘rtengine::DCPProfile::DCPProfile(const Glib::ustring&)’:
/home/magnus/test/rt_exiv2/RawTherapee/rtengine/dcp.cc:1121:54: error: no matching function for call to ‘fopen(const char*, const char [3])’
 1121 |     FILE* const file = g_fopen(filename.c_str(), "rb");
```
But `rtengine/dcp.cc` was auto-merged. 

It was a nice try! I ended up breaking something fundamental since RT code has many existing references to `g_fopen(filename.c_str(), "rb")`.

**Comment by speakk** [comment] 2022-07-11 10:04
I wonder if there's anyone who could pick up where this got left?

**Comment by KarlMagnusLarsson** [comment] 2022-07-11 10:48
Hello @speakk,

I did continue, but there is more work to do. The error in `rtengine/dcp.cc` was solved with help from @Floessie and I merged the metadata-exiv2 branch https://github.com/Beep6581/RawTherapee/tree/metadata-exiv2 with the latest dev code of RT repo. The new code is here: https://github.com/KarlMagnusLarsson/RawTherapee/tree/metadata-exiv2-update in the `metadata-exiv2-update` branch.

However the current issue is that even if CR3 metadata is now visible, the output from RT does not contain any embedded color profile at all. 

The discussion is here: https://discuss.pixls.us/t/cr3-metadata-decoding-test-of-feature-branch-on-linux/31181

**Comment by zeus86** [comment] 2024-01-21 09:38
For anyone else following this thread:  
even tough this issue is open, because the change is not in a stable release yet, the merge above means that cr3-metadata-support is now working when grabbing a **dev-build** from the releases.  

metadata works while editing and also for writing exif-data into exported images. haven't tested compressed cr3s, but normal cr3s from my EOS RP worked just fine. Really hoping we don't have to wait years until this is going to be in a stable release.

**Closed as completed** 2024-01-22 01:37 UTC
Labels: scope: metadata, type: feature

**Comment by gonzaloriestra** [comment] 2024-01-22 10:30
Thanks a lot to everyone for the work here!

I've been testing the dev build with raw files from my M50 and it's working as expected. A huge improvement for me!
