### ISSUE TITLE
Review rtdata/languages/default

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#5984] opened 2020-11-07 23:49 UTC
All translations must wait for a review of [`rtdata/languages/default`](https://github.com/Beep6581/RawTherapee/blob/dev/rtdata/languages/default).

**Comment by Thanatomanic** [comment] 2020-11-10 08:26
Duplicate of https://github.com/Beep6581/RawTherapee/issues/5664. Closing that issue because it is much older.

**Closed as completed** 2020-11-29 23:27 UTC
Labels: scope: localization
