### ISSUE TITLE
Compilation error errors in batchqueue.cc [gtk3]

### ISSUE THREAD

**Issue by sguyader** [Beep6581/RawTherapee#3085] opened 2016-01-11 18:00 UTC
While compiling the Gtk3 branch, I get this:

```
[ 85%] Building CXX object rtgui/CMakeFiles/rth.dir/batchqueue.cc.obj
[ 86%] Building CXX object rtgui/CMakeFiles/rth.dir/lwbutton.cc.obj
C:/Rawtherapee-sources/rtrepo-gtk3/rtgui/batchqueue.cc: In member function 'bool BatchQueue::saveBatchQueue()':
C:/Rawtherapee-sources/rtrepo-gtk3/rtgui/batchqueue.cc:223:25: error: variable 'std::ofstream file' has initializer but incomplete type
     std::ofstream file (fileName, std::ios::trunc);
                         ^
C:/Rawtherapee-sources/rtrepo-gtk3/rtgui/batchqueue.cc: In member function 'bool BatchQueue::loadBatchQueue()':
C:/Rawtherapee-sources/rtrepo-gtk3/rtgui/batchqueue.cc:263:33: error: variable 'std::ifstream file' has initializer but incomplete type
     std::ifstream file (fileName);
                                 ^
rtgui/CMakeFiles/rth.dir/build.make:2502 : la recette pour la cible « rtgui/CMakeFiles/rth.dir/batchqueue.cc.obj » a échouée
make[2]: *** [rtgui/CMakeFiles/rth.dir/batchqueue.cc.obj] Erreur 1
make[2]: *** Attente des tâches non terminées....
CMakeFiles/Makefile2:235 : la recette pour la cible « rtgui/CMakeFiles/rth.dir/all » a échouée
make[1]: *** [rtgui/CMakeFiles/rth.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

**Comment by adamreichold** [comment] 2016-01-11 18:09
This is a duplicate of #3074, the fix just has not yet been merged from master. Will fix this ASAP.

**Comment by sguyader** [comment] 2016-01-11 18:15
Ooops sorry, I searched the issues before, but probably not deeply enough as I didn't see it.

**Comment by Beep6581** [comment] 2016-01-11 18:18
I'll close this as it's already fixed. @adamreichold could you merge?

**Closed by Beep6581** 2016-01-11 18:18 UTC
Labels: Compilation

**Comment by adamreichold** [comment] 2016-01-11 18:21
@Beep6581 I closed by one adding the patch, this way we do not need to do a full blown merge for a single line. (If more people are beginning to seriously test the `gtk3` branch, dropping `master` and getting this one up to shape sounds more reasonable in the long run...)
