### ISSUE TITLE
Blue Curve with Luminosity Mode do nothing (Color Tab - RGB Curves) even in sRGB color space

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3266] opened 2016-04-27 08:33 UTC
I'm sorry.  I tried to open a bug # 3265, but he was immediately closed with a reference to the Desmis's explanations at [https://discuss.pixls.us/t/conversion-to-black-white-something-not-right/868/6](url): "Solution: Don't use ProPhoto working space".
Ok. I read [https://discuss.pixls.us/t/conversion-to-black-white-something-not-right/868/6](url).
I switched Working Profile to sRGB. When I change Red or Green curve with Luminocity Mode I see changes. But when I change Blue curve with Luminocity Mode I almost do not see the changes. They are too small.
I think that the proposed solution ("Don't use ProPhoto working space") is wrong. Somewhere there is a problem that does not allow the Blue Curve with Luminosity Mode.
Maybe I'm wrong.
Thank you.

**Comment by iliasg** [comment] 2016-04-27 09:04
It's because B is the smallest factor of luminosity .. Y = 0.2126 R + 0.7152 G + 0.0722 B

**Comment by geoderix** [comment] 2016-04-27 09:21
Why in this case, the blue curve? Is it possible to make it work as well as red and green curves?
In addition, it seems to me, red and green curves work about the same with Luminosity Mode.

**Comment by Beep6581** [comment] 2016-04-27 13:15
@geoderix can you link to a sample raw file + PP3? Upload using http://filebin.net/

http://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.709-6-201506-I!!PDF-E.pdf (page 4)
https://en.wikipedia.org/wiki/Relative_luminance
https://en.wikipedia.org/wiki/YPbPr

**Comment by geoderix** [comment] 2016-04-27 13:38
For what sample raw file + PP3?
You can open any file and see how blue curve does nothing even with sRGB.
I do not dispute the calculating method of luminance.
If the tool exists, it should work. The blue curve is not working.
Or I did not understand the principle of RGB Curves with Luminosity Mode.
Darken the sky it would be fun with blue curve.
Thank you!

**Comment by geoderix** [comment] 2016-04-27 14:03
How does the RGB curves work with Luminosity Mode?
Maybe use a color model HSV or HSL instead Lab? For the blue curve could be used?

**Comment by iliasg** [comment] 2016-04-27 15:39
Hi geoderix,  ..it's better to use the "HSV equalizer" tool (drag the curve lower) to darken the blue sky .. and better first choose the color you want to manipulate with the pipette tool (the cross with up/down arrows at the left side)

**Comment by Beep6581** [comment] 2016-04-27 16:47
> You can open any file and see how blue curve does nothing even with sRGB.

If that were true, I wouldn't be asking for a raw file.

![scrot_2016-04-27 184308](https://cloud.githubusercontent.com/assets/5844619/14860250/3f08657a-0ca8-11e6-9231-e23de6352854.png)

> Darken the sky it would be fun with blue curve.

Use the LH curve in the L\*a\*b\* tool.

**Comment by geoderix** [comment] 2016-04-28 07:31
> If that were true, I wouldn't be asking for a raw file.

I see a very small change to the steep curve. In а real image contrast will not change depending on the color blue with blue curve.

> Use the LH curve in the L*a*b* tool.

Ok, thank you. I use this tool.

RGB Curves with Luminosity Mode is really cool and powerful tool to change contrast according to the color. It replaces the whole sequence of actions. I like it. Great job. But I was upset that there is virtually no possibility to change contrast according to blue channel.

What is the transformation algorithm is used in RGB Curves with Luminosity Mode?

Thank you.

**Comment by geoderix** [comment] 2016-05-13 13:30
The same effect when converting to B/W (color - black-and-white). The blue slider do nothing if working space is ProPhoto and quite a bit if working space is sRGB.
For what RawTherapee uses television model of luminocity? It seems to me that this is not a video editor yet.

**Comment by Beep6581** [comment] 2016-05-20 10:01
Closing, not a bug.

**Closed by Beep6581** 2016-05-20 10:01 UTC
