### ISSUE TITLE
Icons are tiny on high DPI Displays, while text sizing is okay

### ISSUE THREAD

**Issue by skycyclepilot** [Beep6581/RawTherapee#4458] opened 2018-03-22 20:46 UTC
RawTherapee 5.4 is unusable on high DPI displays.  Text sizing is okay, but icons and such are tiny.

**Comment by heckflosse** [comment] 2018-03-22 20:56
You clearly missed some things as you opened the issue:
``` 
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
```

**Comment by Beep6581** [comment] 2018-03-22 21:25
Duplicate of #3547

**Closed as completed by Beep6581** 2018-03-22 21:25 UTC

**Comment by skycyclepilot** [comment] 2018-03-22 21:27
You have all the information you needed to resolve this problem.  It's not like it's a tedious problem that requires a ton of explanation.  If you'd rather make people jump through hoops, fine.  I'll just use another product.  Thanks.

**Comment by heckflosse** [comment] 2018-03-22 21:40
@skycyclepilot To solve this problem, we need to be able to reproduce it, fix it and test the fix. The part in the middle (fix it) will be the easy part, if we have a Hi Dpi Display to reproduce before making a fix and to confirm the fix once it's fixed. Simple, isn't it?

So we have some informations (still not all), but no way to go further.

**Comment by heckflosse** [comment] 2018-03-22 21:43
@skycyclepilot I edited the header to fit your post

**Comment by skycyclepilot** [comment] 2018-03-22 21:44
Actually, it's very easy to reproduce.  Just open the program on a high
resolution display, such as any UHD (3840 X 2160) monitor.  The problem
will be painfully obvious.  All the icons and such will be tiny.

**Comment by agriggio** [comment] 2018-03-22 21:45
> Just open the program on a high resolution display, such as any UHD (3840 X 2160) monitor.

None of us (RT devs) has one, unfortunately.

**Comment by skycyclepilot** [comment] 2018-03-22 21:45
Okay.  Thanks...

**Comment by skycyclepilot** [comment] 2018-03-22 21:52
Okay.  Lots of people have them now, so others are going to have this issue.
