### ISSUE TITLE
Nikon RAW HLG photos displayed as black

### ISSUE THREAD

**Issue by zasdfgbnm** [Beep6581/RawTherapee#6884] opened 2023-11-11 15:40 UTC
This is how my pictures looks like in Nikon Studio

<img width="1103" alt="image" src="https://github.com/Beep6581/RawTherapee/assets/1032377/0c73fb6b-0a31-49cc-9591-3ee05bbbba22">

This is how it looks like in RawTherapee:

<img width="853" alt="image" src="https://github.com/Beep6581/RawTherapee/assets/1032377/14e39a18-1b8b-48e6-a0c6-ee19307f0d33">

Example picture:
https://drive.google.com/file/d/10A6c67piDc6dwuHQu3p8EtWi-PZM0PzJ/view?usp=drive_link

**Comment by kmilos** [comment] 2023-11-12 18:33
Nothing to do w/ HLG output profile.

This is a duplicate of https://github.com/Beep6581/RawTherapee/issues/6408

**Comment by Lawrence37** [comment] 2023-11-13 01:17
The sample you provided uses the high efficiency compression which is not supported at the moment. If it is possible to take an HLG image using lossless compression, please try it and let us know if it opens properly.

Closing as a duplicate of #6408. I'll reopen the issue if we receive evidence of problems with HLG lossless compression NEFs.

**Closed as not planned** 2023-11-19 22:59 UTC
Labels: scope: file format
