### ISSUE TITLE
Does HDR Tone Mapping start too aggressively 

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#4280] opened 2018-01-07 06:53 UTC
Hi,
I have had a go at the New HDR Tone Mapping tool on dev branch. My image is created by HDRMerge from a 7 shot sequence at 1 stop exposures.
To see my issue this load the image with auto levels and select HDR Tone Mapping set at Strength = 1.

I feel it it has started with a too extreme HDR look at 1 and I have to do some some heavy work with tone curves to get the window not being over exposed. I may be expecting too much.

![screenshot from 2018-01-07 17-53-54](https://user-images.githubusercontent.com/7539943/34647305-c9f2638e-f3d3-11e7-9fd6-eeba55cb6ad3.png)

The original dng file is at: https://filebin.net/sb6we1n3gig8dkph

**Comment by Floessie** [comment] 2018-01-07 09:28
@dnw3039 David, see Morgan's and Alberto's comments in #4255.

Best,
Flössie

**Comment by agriggio** [comment] 2018-01-07 12:36
@dnw3909 HDR TM is best applied when starting from neutral, it is a known problem that you might get bad results in combination with auto levels...

**Comment by Beep6581** [comment] 2018-01-07 16:36
> I have to do some some heavy work with tone curves to get the window not being over exposed

That has not been my experience at all. Fixing the unwanted overexposure is simple. I think you might be over-cooking the meal ;]

The effect HDR Tone Mapping (Fattal) has depends on the contents of the image. In some cases, enabling it with minimal values leads to almost no changes (see the History frame):
![imgur-2018_01_07-17 27 51](https://user-images.githubusercontent.com/5844619/34651410-470425a0-f3d0-11e7-8b7d-6ebb053710f0.png)

In other cases, minimal values cause significant change:
![imgur-2018_01_07-17 28 36](https://user-images.githubusercontent.com/5844619/34651415-4bd9bcd4-f3d0-11e7-834a-b37fc1bce3ac.png)

Regardless, fixing unintentional clipping is as simple as applying negative exposure compensation or using highlight compression.

Neutral + HDR Tone Mapping:
![imgur-2018_01_07-17 33 25](https://user-images.githubusercontent.com/5844619/34651486-05834b3c-f3d1-11e7-823e-ba354d850dfd.png)

Strength=50
![imgur-2018_01_07-17 33 38](https://user-images.githubusercontent.com/5844619/34651488-10aa7350-f3d1-11e7-8f9d-b1a782dd7d8d.png)

Highlight compression = 100
![imgur-2018_01_07-17 34 10](https://user-images.githubusercontent.com/5844619/34651489-185d1d28-f3d1-11e7-9189-b6ff12dccda2.png)

Closing as duplicate of #4255

**Closed as completed by Beep6581** 2018-01-07 16:36 UTC

**Comment by dnw3039** [comment] 2018-01-07 20:43
Thanks to all. I am getting much better results by not using Auto Levels first.
