### ISSUE TITLE
Rawpedia missing tools

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#4549] opened 2018-05-12 08:05 UTC
I just checked rawpedia and it lacks info about hdr tone mapping and local contrast.

Since they are great and interesting features it would be cool to have a good explanation of the various sliders!

Thank you!

**Comment by Beep6581** [comment] 2018-05-12 08:43
I'm slowly working on that.
Duplicate of #4243 and of #4245

**Closed as completed by Beep6581** 2018-05-12 08:43 UTC
Labels: external: RawPedia
