### ISSUE TITLE
SAMSUNG NX500 12-bit raw support

### ISSUE THREAD

**Issue by emanuele** [Beep6581/RawTherapee#3000] opened 2015-12-01 15:21 UTC
Hi, I am using Rawtherapee v4.2, on Ubuntu 14.04 through ppa:dhor/myway and specifically the latest version, as of today: 4.2-4dhor~trusty .

My RAW files come from a Samsung NX500 and had no problems to read them with Rawtherapee, until today. Today I was processing some RAW files and, among them, ten shots turn out to be a completely white image, with some vertical ines, that you can see in the attached screenshot.
![screenshot from 2015-12-01 16 17 37](https://cloud.githubusercontent.com/assets/69366/11504699/e1ca7fea-9846-11e5-81e0-425a3af22252.png)
It seem quite clear to me that the there is an issue in interpreting/decoding the SRW file.

Here you can find one of the related troubling RAW file:
  http://nilab.cimec.unitn.it/people/olivetti/tmp/issue.SRW

Notice that the same RAW file can be correctly read by Darktable, so it is not a corrupted file but, more likely, an issue in how Rawtherapee decodes some RAW file of the Samsung NX500.

**Comment by Beep6581** [comment] 2015-12-01 15:30
Confirmed in latest gtk3 branch.

**Comment by heckflosse** [comment] 2015-12-01 15:32
I take this one

**Comment by emanuele** [comment] 2015-12-01 15:41
Minor fix to my bug report: I am not using RT v4.2 but v4.3. Specifically:
  Version: 1:4.3+git20151130-134~ubuntu14.04.1
which is the package rawtherapee-unstable . Anyway I also tried rawtherapee-fresh (4.2.380) and got the same issue. Note: in the stable (4.2) version of rawtherapee the RAW file of the NX500 is not supported.

**Comment by iliasg** [comment] 2015-12-01 16:06
Latest Dcraw v9.26, rev1.476 crashes on this file. Darktable uses Libraw instead of Dcraw ..

**Comment by heckflosse** [comment] 2015-12-01 16:55
The file you uploaded is a 12 bit srw. Looks like 12 bit srw is not correctly supported (at least for NX 500) in dcraw. I downloaded some 14 bit NX500 srw files. All are decoded fine.

**Comment by iliasg** [comment] 2015-12-01 17:18
Hmm .. if I remember correctly .. I think RT has no problem with NX1's 12bit files (should be same with NX500) .. struggling to find some NX1 12bit samples ..  
Ingo, can you take a look in libraw ?.

**Comment by heckflosse** [comment] 2015-12-01 18:04
Ilias, libraw or rawspeed? DT is using rawspeed I guess: https://github.com/darktable-org/darktable/blob/master/src/external/rawspeed/RawSpeed/SrwDecoder.cpp

**Comment by iliasg** [comment] 2015-12-01 23:27
Ingo, with rawdigger we can use modified-dcraw or rawspeed as  decoding engine and both work fine ..

**Comment by heckflosse** [comment] 2015-12-01 23:48
Ilias, yes, maybe, but dcraw currently does not support this files and dcraw is, what RT uses. So'll have to wait for a dcraw update. Workaround could be to shoot 14-bit files meanwhile...

Ingo

**Comment by iliasg** [comment] 2015-12-01 23:53
Ingo, OK .. as David usually releases Dcraw updates at the end of a year we will not need to wait for long. And there is always the workaround of converting to DNG (Adobe's or Samsung's converters).
  
BTW in rawspeed one can find the link to Samsung's official open source code http://opensource.samsung.com/ ... keyword "DNG" :)

**Comment by emanuele** [comment] 2015-12-02 09:56
Thank you for taking care of this issue. I can confirm that, at a certain point, I switched to "compressed RAW" (12bit) when I was shooting because I was running out of space in the memory card. Anyway I have (supposedly) 12bit RAW file shot after the problematic ones that can be read by RT with no problem. How can I check whether a RAW file is 12 bit (compressed) or 14 bits (normal)?

**Comment by heckflosse** [comment] 2015-12-02 10:38
@emanuele You can use exiftool to check: http://www.sno.phy.queensu.ca/~phil/exiftool/

**Comment by emanuele** [comment] 2015-12-02 11:08
Thank you @heckflosse . I just used exiftool and checked the "Bits Per Sample" field. Interestingly, all the pictures I took at that event are 12 bits... as well as all other pictures I took in the last couple of months, unexpectedly. So I can conclude that RT works quite well with the 12 bits RAW files of the NX500, but there are some rare cases in which it does not.

**Comment by iliasg** [comment] 2015-12-02 17:01
Emanuele, does NX500 give the option of more compression on 12 or 14 bit raws ? Your problematic sample has a very small size in MB !.

**Comment by Beep6581** [comment] 2015-12-02 18:29
http://rawpedia.rawtherapee.com/How_to_convert_raw_formats_to_DNG

**Comment by emanuele** [comment] 2015-12-03 13:19
I've just learned that the NX500 uses 12 bits in continuous shooting and 14 bits for single shot mode, irrespective whether the RAW compression is on or off. This is not surprising since the compression is declared 'lossless'. Unfortunately it is not easy to always shoot 14 bits, because the various continuous shooting modes are really handy and I guess that the "Continuous Normal" mode is the default one.

Here is a related discussion:  http://redmine.darktable.org/issues/10523

**Comment by trenzterra** [comment] 2015-12-23 12:48
Is there any resolution to this issue? So far for me this happens whenever I save 12-bit files using normal compression. Uncompressed 12-bit and compressed/uncompressed 14-bit files have no issues.

**Comment by Beep6581** [comment] 2015-12-23 13:44
@trenzterra we will look into it after a new dcraw version is released.
Watch this page:
http://www.cybercom.net/~dcoffin/dcraw/dcraw.c

**Comment by Beep6581** [comment] 2018-12-11 09:39
Still valid in RT 5.5 using dcraw 9.28.

**Comment by LebedevRI** [comment] 2020-01-01 19:29
@trenzterra @emanuele etc
Terribly sorry for necro-posting offtopic question, but i wonder if anyone here still has that camera?
I would *love* to get a sample set (preliminary info: two raws with same content, one 12bit and one 14bit) from it for https://raw.pixls.us/

**Comment by LebedevRI** [comment] 2020-01-01 19:36
> (preliminary info: two raws with same content, one 12bit and one 14bit)

Err, looking at http://downloadcenter.samsung.com/content/UM/201503/20150313082358453/NX500_English.pdf, it seems it would be awesome to have 4 samples:
* 14bit "Normal Compression"
* 14bit "Lossless Compression"
* 12bit "Normal Compression"
* 12bit "Lossless Compression"

**Comment by emanuele** [comment] 2020-01-02 09:54
@LebedevRI : I can provide them, probably within tomorrow - I still have the NX500. About the content, I can provide very similar shots, clearly not identical. Please let me know if you have further instructions about the content.

**Comment by LebedevRI** [comment] 2020-01-02 10:00
Yay, thank you!
No need for pixel-perfect identicity, at best put the camera on a tripod or something,
but it's just a wish, not a strict requirement. As stated on https://raw.pixls.us/,
ideally the image content should be something like daylight landscape - so that
the images are at low ISO but still well-exposed, with no people in the frame.

**Comment by emanuele** [comment] 2020-01-04 09:02
Hi, I've just submitted 4 almost identical shots just taken with the
Samsung NX500 and kit lens to https://raw.pixls.us/ , as agreed. I've put a
comment in the description of each shot, as below:
- SAM_2923.SRW : 12bit normal compression (20Mb)
- SAM_2930.SRW : 12bit lossless compression (26Mb)
- SAM_2921.SRW : 14bit normal compression (24Mb)
- SAM_2928.SRW : 14bit lossless compression (32Mb)

Here, "normal compression" means lossy compression, as opposed to "lossless
compression". I selected the compression level from the camera's menu.

The 12bit vs 14bit cannot be directly selected from the camera's menu but
in the following way: when enabling continuous shooting - in my case I
enabled "Drive: continuous high" - the camera automatically switches to
12bit. For single shot, i.e. "Drive: single", the camera automatically
switches to 14bit. The sizes of the files confirm that.

Thanks for working on the NX500 12bit raw support!
The Samung NX500 has a really great sensor - the best of all current APS-C
cameras, according to DXOMark. It's a pity that Samsung left from the
camera business.

Let me know if you need further files.

**Comment by LebedevRI** [comment] 2020-01-04 09:06
> Hi, I've just submitted 4 almost identical shots just taken with the Samsung NX500 and kit lens to https://raw.pixls.us/ , as agreed.

Ooh, thank you so much for these! Verified uploads.

**Comment by Thanatomanic** [comment] 2023-01-01 10:06
Not sure how, not sure when, but this is fixed in the current `dev` branch.

**Closed by Thanatomanic** 2023-01-01 10:06 UTC
Labels: type: enhancement, scope: file format
