### ISSUE TITLE
RawTherapee crash on startup

### ISSUE THREAD

**Issue by gh-gm24** [Beep6581/RawTherapee#7192] opened 2024-09-02 08:31 UTC
After launching RawTherapee, the UI appears for a short time, but a crash happens before the UI becomes operable.

Both RT 5.10 of my distro and Appimage 5.11 (downloaded from RT homepage) are affected.

System: Kubuntu 24.04 LTS

uname -r
6.8.0-41-generic

Error message (console):
> xxx@amd64:~/src$ rawtherapee
>
> (process:53827): Gtk-WARNING **: 10:24:49.745: Locale not supported by C library.
>         Using the fallback 'C' locale.
> terminate called after throwing an instance of 'Gio::Error'
> Abgebrochen (Speicherabzug geschrieben)`

Error message (gdb)
> terminate called after throwing an instance of 'Gio::Error'                                                                              
> 
> Thread 1 "rawtherapee" received signal SIGABRT, Aborted.
> Download failed: Das Argument ist ungültig.  Continuing without source file ./nptl/./nptl/pthread_kill.c.
> __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
> Warnung: 44     ./nptl/pthread_kill.c: Datei oder Verzeichnis nicht gefunden

[log.txt](https://github.com/user-attachments/files/16834714/log.txt)

**Comment by Lawrence37** [comment] 2024-09-02 23:56
Thanks for reporting this issue.

An unhandled exception is thrown after attempting to monitor a directory for changes. Closing as a duplicate of #6600.

**Closed as not planned by Lawrence37** 2024-09-02 23:56 UTC
Labels: type: bug
