### ISSUE TITLE
Crop parameters saved incorrectly

### ISSUE THREAD

**Issue by rgcmce** [Beep6581/RawTherapee#7152] opened 2024-07-24 23:59 UTC
**Short description**

This bug reflects my experience with RT 5.10 on Win 10

If I save my crop parameters to the clipboard and then paste them into another image, the orientation parameter comes through incorrectly.

Open an image in landscape orientation.  Initially the orientation parameters are: lock ratio checked and orientation is "As image".  I now change the orientation to portrait and set an appropriate crop.  I selectively save the crop to the clipboard.  Now when I paste this crop into other images, the left, top, width, height, and ratio come through correctly.  But the resultant orientation parameter is now "landscape" rather than "portrait".  However, the resultant crop displays correctly, presumably because the left, top, width, and height parameters are correct.  But if I now attempt any sort of adjustment to that crop, it immediately changes from portrait to landscape.

**Expected behavior**

The orientation parameter should come through unchanged.

**Comment by Benitoite** [comment] 2024-07-25 00:59
Not reproduced as described on macos with `dev`.  (probably I don't follow the step-by-step correctly).  I am not sure what 'selectively saving to clipboard' is.  I can selectively copy to clipboard.  I can selectively paste.  Either way, the crop parameters all come thru and adjusting the crop does not affect the orientation.
Possibly duplicates https://github.com/Beep6581/RawTherapee/issues/7138

**Comment by rgcmce** [comment] 2024-07-25 01:11
'selectively saving to clipboard' = 'selectively copying to clipboard'

I know about "processing profile fill mode set to preserve instead of fill" and it was correctly set. So not #7138 

I'll consider what else I can add to illustrate the issue but that will have to wait until tomorrow.

**Comment by Benitoite** [comment] 2024-07-25 01:31
Thank you! If at all possible, do your double-check on the `dev` branch.
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by Lawrence37** [comment] 2024-07-25 01:38
I can reproduce, but I think it is more of a problem about telling RawTherapee to do contradictory things. On one hand, you are telling RawTherapee to set a crop with a specific height and width. On the other hand, you are telling it to lock the ratio to the image's original ratio. The lock's purpose is to automatically set the height or width when you adjust the other dimension. Thus, when you apply the profile, RawTherapee chooses the width and height in the profile. Then when you adjust the width or height manually, RawTherapee does the auto-calculation on the other dimension.

**Comment by rgcmce** [comment] 2024-07-25 13:49
I was gratified to learn that @Lawrence37 could reproduce the issue.

I tested to see if I could reproduce this behaviour with the dev branch.  I could not.  I went back and retested with 5.10 and now I was unable to reproduce my issue.

Something strange is going on.  The key is to identify what triggers it.  However, at the moment I am out of ideas and lack the time to investigate further.  I will return to this issue but not immediately.

**Comment by Lawrence37** [comment] 2024-07-27 18:14
I will close this for now because it's probably not a bug. Feel free to comment if you see something that indicates otherwise.

As for enhancements to make this less confusing, see #4856.

**Closed as not planned by Lawrence37** 2024-07-27 18:14 UTC

**Comment by rmills** [comment] 2025-02-02 23:54
I think this needs to be reviewed. Have tested on the latest dev on win64 and the crop copy/paste is kind of messy as currently implemented with mixed size images. Don't have the hardware to test if this is a windows issue or an application issue. Only tested on win11 x64

**Steps to reproduce:**

1. Load 4 images with different orientations and overall sizes.
2. Make sure the first image is bigger than the rest.
3. Apply a crop with a ratio of anything but 1:1 to the first image. For example 16:9
4. Then copy paste to the rest of the images. 

Expected behavior is that that crop is applied with that ratio to the image obeying the orientation, but the resulting crops do not obey the ratio despite the UI saying it is indeed cropped to 16:9. If you change it to 16:10 then back to 16:9 then you get the crop as expected in the correct ratio. It seems to apply based on px dimensions blindly. If the source image is larger, it will copy paste with the correct ratio but won't scale and I don't know of many situations where that is ideal. This is independent of "lock ratio", checking or unchecking does not change the result. 

This is very brittle, since mixed cameras, prior edits or prior crops breaks it and breaks it in a way you cant trust the UI is giving you the correct ratio without changing it to another ratio then back to confirm. 

I would suggest crops be applied by using percents so the behavior is closer to lightrooms crop copy/paste. I think a better expected behavior is that the crop will copy paste first checking the orientation, rotate if needed then apply the crop ratio as close as it can to the original using percents. Obviously it would never work to the exact pixel but most workflows using the copy paste of a crop are doing it for specific output ratios a to speed up workflow by copying the bulk of their changes then fine tuning per photo. For example if I know I am going to print a bunch of photos as 8x10 images, its faster to give every photo a 8x10 crop then fine tune the placement than it is crop one by one using the tools. It might be personal opinion but I would much rather see it obey the crop ratio over the exact dimensions of the crop since it can't do the exact dimension 100% of the time anyway,

My current issue is having to prepare thousand images for a website and I need 4:5 specifically. The images are from different cameras and orientations. I simply can't use rawtherapee because it would force me to go image by image, select the ratio, select the crop tool, crop, thousands of times. Vs applying the crop to all of them then only having to drag/fine tune the placement.

**Comment by Lawrence37** [comment] 2025-02-03 00:51
Thanks for the proposal. There are a couple of details that we need to figure out before it can be implemented.
1. Percentage of what? Width, height, long edge, short edge, diagonal, area, or something else?
2. How is orientation decided if landscape or portrait is selected? Will it stay the same, or will it also depend on the image orientation?
3. What if someone wants to apply the crop by the exact pixel values? How would you choose between respecting the original values or automatically re-adjusting the crop?

For you current situation, are you aware that you can crop from the file browser?
If you have a few cameras involved, you can filter by camera, select all, then paste a crop that works for that camera.
It's also unnecessary to change and reset the aspect ratio because you can easily achieve the same thing by just clicking and dragging one of the crop boundaries.

**Comment by rmills** [comment] 2025-02-04 03:49
I think I will need put a little more careful thought into it and double check the behavior in lightroom to make sure im not misremembering. I think it could be done in a way it worked regardless of pixel size. But there could still be a question of if there are use cases to hang a crop over the edge of an image as it currently does, I can't think of one but maybe there is.

It will probably come down to how and where it was hooked in code wise, it might require reading in properties of the target image (height, width, etc) that might not be there currently. I don't know the current code well enough to comment on specifics but there already seems to be a validation function that's called when you grab and edge that corrects the ratio, wont fix the scale if its too small but does work when its too big. An intermediary step might be calling that but you would have to call it as if you were grabbing a single edge and that could be hit or miss. I also don't know if there is any other validation on any other properties or if its purely copying properties from one pp3 to another, a special case just for crop probably needs some careful thought on how best to do validation type checks when copy pasting. 

The exact code will beyond where I can help, but I could work on the math for conversions at least as a starting point if there is someone else who knows better how to implement it.

**Comment by Lawrence37** [comment] 2025-02-04 06:31
Don't think about the code yet. We need the design first. Don't let the code dictate the design.

**Comment by PaulNerd** [comment] 2025-05-03 16:01
> I can reproduce, but I think it is more of a problem about telling RawTherapee to do contradictory things. On one hand, you are telling RawTherapee to set a crop with a specific height and width. On the other hand, you are telling it to lock the ratio to the image's original ratio. The lock's purpose is to automatically set the height or width when you adjust the other dimension. Thus, when you apply the profile, RawTherapee chooses the width and height in the profile. Then when you adjust the width or height manually, RawTherapee does the auto-calculation on the other dimension.

I get the reasoning behing it, but I find it to be not as contradictory if you think that manually selecting another Orientation ("Landscape" or "Portrait") and then selecting back "As Image" does exactly what you expect it to do in the first place.

**Comment by Lawrence37** [comment] 2025-05-03 18:04
Something is either contradictory or it isn't. There's no in-between.

In the GUI, you are always changing one parameter at a time. By doing so, you are requesting RawTherapee to honor that parameter and adjust others as needed. When you change the orientation, the RawTherapee GUI ensures the orientation is correct and makes adjustments to the width and/or height if necessary. When you change the width or height, the GUI ensures that the width or height is correct and will adjust the other dimension and/or the orientation if necessary.

When you paste processing profiles, however, you are simultaneously setting all three parameters. RawTherapee has no clue which ones you intend to keep and which ones you are ok with being readjusted.

**Comment by PaulNerd** [comment] 2025-05-03 18:12
Well... I think that setting should override the others and the dimensions be treated more like absolute values.

If I wanted to crop a vertical picture in landscape mode, I could always say so explicitly ("Landscape")... if I say "As Image", I think I mean it... and I assume the risk of it behaving differently depending on the picture.

**Comment by Lawrence37** [comment] 2025-05-03 18:53
As of now, there is no way for you to tell RawTherapee which setting you want to preserve. If you paste a profile that has an as-image orientation with 4000x3000 (horizontal) pixel dimensions into a vertical image, it doesn't know if you want to keep the as-image orientation or the 4000x3000 pixel dimensions.

**Comment by PaulNerd** [comment] 2025-05-03 18:55
To me, that's horizontal only if the dropbox says so... otherwise it's image-dependent if the dropbox says "As Image".
But I get it, the issue is with all the "legacy" profiles that would break if that setting were changed now.

**Comment by Lawrence37** [comment] 2025-05-03 19:13
Compatibility aside, there is still the issue of conflicting parameters. Sure, it may make sense to prefer the as-image orientation over the dimensions, but not every user will agree. Someone could be cropping an image using the width and height without even thinking about the orientation (since the desired crop is the same orientation as the image). If the as-image orientation is preferred, this would lead to surprising behavior when pasting the crop. The user may not have been aware of the orientation setting since you don't even need to open the crop tool to set the crop. The point is that this issue is not straightforward.

**Comment by PaulNerd** [comment] 2025-05-04 16:39
Ok, then here's my suggestion.
We either keep or remove this parameter (it doesn't matter, see details below) and add another one, called something like "Adapt" or whatever.

This new one overrides the W/H pair and if necessary will switch it, based on the image it's applied to.

The old one can be either kept, and will continue to work as it does now, or deprecated/dropped, and it will be interpreted by future versions of the software the way it is interpreted now.
For what is does(n't) do, the routine could be as simple as (pseudocode):
if Horizontal [...], if Vertical [...], if Adapt [...], else (if W > H then Horizontal, else Vertical)

It's more code, but to me the "As Image" parameter as it is now might as well not exist, it does nothing meaningful... there's not one use case I can think of that couldn't be solved by using Horizontal/Vertical, not even if I try to imagine other people's particular needs.

I'm not a software developer, so feel free to correct me / point out possible pitfalls.
Best regards

**Comment by Lawrence37** [comment] 2025-05-04 21:13
I'm not sure if I understand your suggestion. It seems no different from changing the behavior to prefer keeping the orientation over the width/height, except that it will be named "Adapt" instead of "As Image".

The "As Image" option is useful when adding a crop. The default setting is to preserve the image's aspect ratio and orientation. This allows the user to enable the crop tool, then click-and-drag to instantly create a crop with the aspect ratio and orientation locked to the original image's.

**Comment by PaulNerd** [comment] 2025-05-05 06:20
Ok now I think I get it, kinda makes sense.
I don't care if the behavior is simply changed when pasting a profile, I was suggesting to keep the old way in order not to break anything in the already-existing profile files and in case someone liked it better.
The change I propose only affects the behavior when a profile is pasted, and overrides the order of W and H

**Comment by rmills** [comment] 2025-05-05 16:37
I wanted to just add, I was trying to figure out a catch all solution more in line with how lightroom handles it but it requires a lot of extra logic. For example, two mismatched size images, one portrait and one landscape and copy pasting from one to the next. You need to both scale and position the start X, Y. Because if an image is drastically larger than the next its start X, Y could be outside the bounds of the image. The same goes in reverse, and asks the question, if the source crop is on the bounds, should the pasted crop be on the bounds regardless of size or if the crop is say 50px in from the bounds should it use that ratio in the paste as well. I can see use cases for both. Plus more basic logic, if the source is landscape and you paste on a square image you would want to favor the source direction. 

This is more of the direction I would love for it to go, but we are talking about a "smart" crop and how does that effect reverse compatibility, and the exact implementation may not please everyone. There are use cases where I would want to crop a static size regardless of everything just as it is now. At this time I don't have a solution that can really catch all in a single copy/paste action.
