### ISSUE TITLE
Image preview not sharp enough on 4K screen

### ISSUE THREAD

**Issue by pkolaczk** [Beep6581/RawTherapee#4367] opened 2018-02-05 08:11 UTC
In the editor window, the main image preview (not the thumbnails) is a bit blurry, even though it is scaled down from the original size (14 mpx) a lot. At first I thought the problem was with all my pictures, but then I zoomed in, and the details were fine. The same image viewed by the Ubuntu builtin viewer is much sharper when displayed at the exactly same size on the screen. I did not apply post-resize sharpening. 

Could the rescaling / interpolation algorithm be better for the main image preview and can it use the full PPI of the screen? I wonder if it is maybe rendering to a lower PPI and then upscaling?

RawTherapee version 5.3.
System: Ubuntu 17.10.
Graphics stack: Intel driver, Xorg. 
Display: Dell Precision 5520 IGZO UHD 15'' 3840x2160

**Comment by Beep6581** [comment] 2018-02-05 08:23
Duplicate of #3547

**Closed as completed by Beep6581** 2018-02-05 08:23 UTC

**Comment by Beep6581** [comment] 2018-02-05 08:25
Also, Advanced point 10:
http://rawpedia.rawtherapee.com/Getting_Started#Advanced

**Comment by pkolaczk** [comment] 2018-02-05 08:50
The point 10 makes sense, thanks. However, it would be nice to have a background thread that updates the preview with a better one a second or two later and replaces the image to a less-blurry, similar to how many image viewers deal with high-res pictures. Or if not in background, then an on-demand button "generate high quality preview". Currently I don't know how the picture would really look like until I do full export. And often, it looks much better after exporting :)  Anyways, thanks for an awesome tool!

**Comment by Beep6581** [comment] 2018-02-05 09:07
That would be nice, but keep in mind that RawTherapee is not an image viewer, it processed raw data, and processing a raw photo takes significantly longer than one second. Ubuntu's image viewer, and most other image viewers, don't show you the real raw data, they only show you the embedded JPEG which is why they appear to be fast.

We will see what new possibilities arise after the pipeline unification which will commence once 5.4 is released.

> an on-demand button "generate high quality preview"

I do that using the Ctrl+e shortcut and Geeqie, see:
http://rawpedia.rawtherapee.com/Preferences#External_Editor

**Comment by marcolaux** [comment] 2018-04-19 14:39
every image is definitely blurry on HiDPI. When comparing with Darktable at HiDPI it's a massive difference. It seems like RT is scaling everything up.

Would it be possible to just scale the UI but not the images? They should be pixel perfect.

EDIT: btw this is not the case when using LowDPI monitors.

**Comment by Beep6581** [comment] 2018-04-19 14:45
Until RT gets HiDPI support, which is handled by issue #3547, you can always turn scaling in your operating system off (100% zoom).

**Comment by marcolaux** [comment] 2018-04-19 14:46
I'm sorry - I thought it's already HiDPI ready as the UI is scaling. Thank you for the information.

Nice hint with geeqie btw.
