### ISSUE TITLE
[Feature request] Filebrowser image items with dynamic width (panoramas in image folder)

### ISSUE THREAD

**Issue by da-phil** [Beep6581/RawTherapee#3427] opened 2016-09-11 22:29 UTC
I'm pretty sure that I opened a feature request at googlecode some time ago about that issue.
Unfortunately I didn't find it here at github, although I'm pretty sure @Beep6581 converted all of them to github. You can close this issue in case it's somewhere here.
Now to the topic:
I'm often working with panoramas in my image folder, but when I'm browsing them in RT the filebrowser list gets messed up because the panoramas also define the width of all other file items and then I can only see one image in one row.
Just like in this [screenshot](https://cloud.githubusercontent.com/assets/810285/18420953/d5f4220c-787e-11e6-9a74-33c66fd47380.png).
I'm pretty sure we already discussed options how we want the filebrowser behave when we have panoramas in it. Everything is fine for me, as long as I can have a few thumbnails per row, instead of only one :D

**Comment by heckflosse** [comment] 2016-09-11 23:19
@da-phil I can confirm the issue as I also often have panoramas in a folder. Unfortunately I can't really help on this one because I'm mainly working on speedups and bug (crash fixes). I'm almost a gui noob. But maybe @Floessie or @Hombre57 can have a look.

Ingo

**Comment by Floessie** [comment] 2016-09-12 05:58
@heckflosse Sorry, but I'm a GUI amateur, either. :)

**Comment by Beep6581** [comment] 2016-09-12 12:16
Duplicate of #1239

**Closed by Beep6581** 2016-09-12 12:16 UTC
