### ISSUE TITLE
GPS tags not piped to TIFF

### ISSUE THREAD

**Issue by nmalykh** [Beep6581/RawTherapee#4305] opened 2018-01-14 17:26 UTC
The program does not save GPS tags when exporting to the TIF format. In the files of JPG and PNG, the tags are normally stored. There was this problem at the end of 2017 (between 300 and 400 commits, approximately). You can see Exiftool (-Composite:all) outputs made in version 5.3-469-gcbcb09633.
[JPG.tags.txt](https://github.com/Beep6581/RawTherapee/files/1629584/JPG.tags.txt)
[TIF16.tags.txt](https://github.com/Beep6581/RawTherapee/files/1629585/TIF16.tags.txt)
[NEF.tags.txt](https://github.com/Beep6581/RawTherapee/files/1629586/NEF.tags.txt)

**Comment by Beep6581** [comment] 2018-01-14 19:35
@nmalykh please upload a sample raw file using https://filebin.net/

**Comment by nmalykh** [comment] 2018-01-14 20:03
https://filebin.net/v5t0eufcg63nnp14/_DSI1586.NEF

**Comment by Beep6581** [comment] 2018-01-14 21:26
Confirmed, none of the possible TIFF modes (8/16/32 compressed/uncompressed) contain the GPS tags. I tested using "Copy unchanged" mode.

**Comment by Beep6581** [comment] 2018-06-17 19:30
Duplicate of #4464

**Closed as completed by Beep6581** 2018-06-17 19:30 UTC
Labels: type: bug, scope: metadata
