### ISSUE TITLE
RT clear profile errors

### ISSUE THREAD

**Issue by olhof** [Beep6581/RawTherapee#4102] opened 2017-09-25 08:12 UTC
The File Browsers processing profile operation “clear” should clear the profile, so the green checkmark indicating the existence of a profile goes away and the thumbnail shifts to the jpg-picture imbedded in the raw file. This status should be maintained until the photo is reopened in the Editor then the default profile stated in the Image Processing tab in preferences should be applied.

This is not what happens. I have noticed the following situations not complying with the above description:

**Clearing the profile, closing RT (CTRL+Q) and subsequently reopening RT**
Sometimes the thumbnail maintain the cleared status  after reopening RT and sometimes the thumbnail is shown in the cleared status but immediately shifts to the green checkmark-status and the default profile is applied without opening the photo in the Editor!

The status of the cleared profile is thus unpredictable after having closed RT

You can easily provoke this by closing and reopening RT a number of times (5-10) after having cleared the profile. Try to close RT with the thumbnail in “current” status after having cleared the profile, close RT when the thumbnail has been cleared but is no longer current (right click outside the thumbnail), and close RT when the thumbnail has been cleared, then put in the no current status and at last put back in the current status by right-clicking on the thumbnail.

The above description is only correct if you have set the raw default profile to a “fixed” profile in the Image Processing tab of the Preferences.
If the default profile is set to “dynamic” then the dynamic profile is not used in the situations where the green checkmark reappears after reopening RT. Some other, but to me unknown, profile is applied in this situation.  

**Clearing the profile and opening the raw photo in the Editor**
If the profile has been cleared (no green checkmark) the default profile is always applied when you subsequently open the photo in the Editor but only if the default profile is a “fixed” profile.
If the default profile is “dynamic” then the “dynamic” profile is never used when opening the photo in the editor! Some other profile is used.

In my understanding the default dynamic profile should be applied exactly as the fixed default profile except that the actual profile is chosen according to the rules specified in the Dynamic Profile Rules. As described in this and the previous paragraph this is not the case.

PC-info:
Windows 10

RT info:
Version: 5.2
Branch: release-5.2
Commit: 78e921cb
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0

**Comment by heckflosse** [comment] 2017-09-25 11:04
@olhof 
> Sometimes the thumbnail maintain the cleared status after reopening RT and sometimes the thumbnail is shown in the cleared status but immediately shifts to the green checkmark-status and the default profile is applied without opening the photo in the Editor!

This happens if you clear the profile of a file in filebrowser while the file is opened in editor.

**Comment by olhof** [comment] 2017-09-25 15:49
Hi' Ingo

Thank you for your response. Very interesting.....

How can you tell in the File Browser which photo is open in the Editor?

And what do you think about my observation about the fixed default profile
versus the dynamic default profile?

**Comment by agriggio** [comment] 2017-09-25 16:06
@olhof the problem is exactly what @heckflosse described. If you clear the profile of an image that is open in the editor, when closing RT (or when switching to another image in the editor) then a neutral profile is saved for that picture. This is why you see that no dynamic profile is applied. I agree that this is a weird behaviour and it should be fixed (thaks for reporting, indeed!). Not sure though it will happen in time for the next release (5.3), which is due very soon.

Regarding the other issues about dynamic vs fixed default profile that you reported, I wasn't able to reproduce them: assuming you clear the profile of an image that is not open in the editor, I get the expected behaviour in both cases...

**Comment by Beep6581** [comment] 2017-09-25 16:18
The part not involving dynamic profiles sounds like a duplicate of #2857

**Comment by Beep6581** [comment] 2017-09-25 16:20
@olhof when you reply via email, your full name and phone number are exposed. I edited your post and removed them, but consider that for the future.

**Comment by olhof** [comment] 2017-09-26 14:58
Thank you for comments and explanations

You are all absolutely correct. The apparently random behaviour of clear profile was caused by the photo being open in the Editor in some cases and not in other cases while clearing the profile.

I was not aware that a photo could be open in the Editor after having switched to the File Browser. My normal editing process is to open the File Browser, select a photo, edit the photo, return to the File Browser and rank it and then select the next photo. After having finished editing I do a Fast Export of all the ranked photos and eventually upload the edited photos to Google Photo. In this process the File Browser is the natural way in and out of editing, for me at least……

Maybe it would be a good idea to put a symbol on the thumbnail in the File Browser to show that the photo is currently open in the Editor?

**Comment by Hombre57** [comment] 2017-09-26 20:53
@olhof Beware : "Fast Export (low quality and bypasses some tools but fast saving - don't use this for typical saving!)" / from [Rawpedia](http://rawpedia.rawtherapee.com/Getting_Started) (however a little bit hidden below the image on the right...)

You should put you image to queue the classical way instead of using fast export for final images.

**Comment by olhof** [comment] 2017-10-08 20:40
@Hombre57 
Thank you for your good advice. All my photos became much more brilliant and nicer after being converted to jpg using the full process and not only the Fast Export (using the standard processing option for Fast Export in RT 5.2). It turns out that the dedicated option results in better pictures but not as good as the result of the full process. 

I started using RT in January this year and I have now reprocessed and re-uploaded all my pictures to Google Photo. I was not aware that I could select any number of photos In the File Browser and put them in the Queue for full processing by ctrl+b. 

You have to put a lot of effort in learning how to use RT.

**Closed as completed** 2017-10-15 16:27 UTC
