### ISSUE TITLE
Highlight reconstruction/colorpropagation new artifact

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#4610] opened 2018-06-14 08:59 UTC
Testing Rawtherapee 5.4-397-g67b032cc6 on Amsterdam .pef, I noticed a new artifact.

![rt5 4-397-g67b032cc6](https://user-images.githubusercontent.com/13785581/41401194-7573556c-6fbf-11e8-88b6-685ad824c3b2.jpg)

 RT5.4 output with exactly the same pp3

![rt5 4](https://user-images.githubusercontent.com/13785581/41401338-df3d63fc-6fbf-11e8-9348-63c8c2b97d91.jpg)

In the sky of first image, there is a grey zone around the steeple.

[amsterdam.pef.pp3.txt](https://github.com/Beep6581/RawTherapee/files/2101538/amsterdam.pef.pp3.txt)

**Comment by Beep6581** [comment] 2018-06-14 12:37
Confirmed in `dev`, neutral + color propagation:
![screenshot_20180614_143645](https://user-images.githubusercontent.com/5844619/41412474-653bb61e-6fe0-11e8-9d31-de1aacdf6a39.png)

**Comment by heckflosse** [comment] 2018-06-14 15:47
There is also a race condition which leads to inconsistent behaviour. The settings in before and after are identical in the following screenshot:

![grafik](https://user-images.githubusercontent.com/13733487/41422952-5d3e22b6-6ffa-11e8-9e8a-441fd8d6798f.png)

Though this could be fixed with the following patch, the fixed code blows up the tower a bit (as in right side of the screenshot) because of the gaussian blur in the current code. I vote to go back to the old code.

```diff
diff --git a/rtengine/hilite_recon.cc b/rtengine/hilite_recon.cc
index a1f5b5e4a..b109cd366 100644
--- a/rtengine/hilite_recon.cc
+++ b/rtengine/hilite_recon.cc
@@ -950,6 +950,9 @@ void RawImageSource :: HLRecovery_inpaint (float** red, float** green, float** b
 
     //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     // now reconstruct clipped channels using color ratios
+    if (!recovered_partial) {
+        recovered_partial.reset(new PixelsMap(width, height));
+    }
 
 #ifdef _OPENMP
     #pragma omp parallel for schedule(dynamic,16)
@@ -1132,9 +1135,6 @@ void RawImageSource :: HLRecovery_inpaint (float** red, float** green, float** b
                                                    (notclipped[0] * clipfix[0] + notclipped[1] * clipfix[1] + epsilon))));
                 }
 
-                if (!recovered_partial) {
-                    recovered_partial.reset(new PixelsMap(width, height));
-                }
                 recovered_partial->set(j, i);
            }
 
```

**Closed as completed** 2018-06-14 16:06 UTC
Labels: type: bug
