### ISSUE TITLE
Clicking on "Load a profile from file" button after Alt-Tab to other application causes load window to be hidden

### ISSUE THREAD

**Issue by maxiking01** [Beep6581/RawTherapee#3132] opened 2016-02-03 19:25 UTC
Steps to reproduce:
1. Open any file to editor
2. Alt-tab to other open program
3. Return to RawTherapee
4. Click on load profile buton
5. Up to several seconds the load profile window hides

Repeatability: often
OS: Windows 10 
App version: 4.2.699. It was downloaded from rawtherapee download site from this link http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_4.2.699-g3c016c4_gtk3.zip

**Comment by Beep6581** [comment] 2016-02-03 20:36
@maxiking01 what do you mean "hidden"? What happens after several seconds?

**Comment by maxiking01** [comment] 2016-02-04 18:48
By hidden I meant that profile loading window is opened but it is not visible on top of the main RawTherapee window. It should be like on this screen
![screenshot](https://cloud.githubusercontent.com/assets/17032029/12825719/f5eea97e-cb77-11e5-81e6-2d02700778fa.jpg)

**Comment by Beep6581** [comment] 2016-02-04 20:33
You are testing version 3c016c41 (please include this info next time - see [this](http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports)) and that was supposed to have been fixed by version 375ed17.
Can someone confirm this problem in gtk3?
@adamreichold @Hombre57

**Comment by Hombre57** [comment] 2016-02-05 20:13
Nope, doesn't happen on Win7 with Gtk3 branch.

**Comment by TooWaBoo** [comment] 2016-02-06 13:28
II can confirm this in Gtk3 Win 10 x64
Look at this issue: https://github.com/Beep6581/RawTherapee/issues/3099

**Comment by adamreichold** [comment] 2016-02-06 13:43
I think this is indeed the same as #3075 and #3099, i.e. we create modal instances of `Gtk::FileChooserDialog` but do not tell the window system that RT's main window is their parent, i.e. our event handling is blocked, but the window system will bring us into the foreground anyway.

I will try to find all instances of at least parent-less file chooser dialogs and post a branch here for testing on Windows. I'll also close #3099 as a duplicate of this one to reduce the issue tracking overhead.

**Comment by adamreichold** [comment] 2016-02-06 14:00
Could any building from source on Windows give [the branch](https://github.com/adamreichold/RawTherapee/tree/fix-file-chooser-dialog-missing-parent) a try? Thanks!

**Comment by adamreichold** [comment] 2016-03-27 13:23
Ping?

**Comment by Hombre57** [comment] 2016-03-27 13:35
Sorry, went under my radar. Building and trying now...

**Comment by Hombre57** [comment] 2016-03-27 15:12
As said earlier, it was already working fine before the patch, but maybe because I'm using only one monitor and/or am using Win7.

Anyway, it is still working fine after the patch, plus it solve the problem of parent window for this transient object. It's also what I was trying to achieve (without success so far) in my own patch for the MyFileChooserButton replacement class (see issue #3223).

+maxiking01 should test first (or anyone on Win 10?), but it's a +1 to commit for me.

**Comment by TooWaBoo** [comment] 2016-03-27 15:16
@Hombre57 
I'm on Win 10 x64, If you provide a download link, I'll test it.

**Comment by TooWaBoo** [comment] 2016-03-27 15:39
I've copied the .exe into my install folder and received folling error message:
Something wasn' found.
![unbenannt](https://cloud.githubusercontent.com/assets/13800920/14066143/b049fec0-f442-11e5-803d-c6bb83c778b0.png)

**Comment by adamreichold** [comment] 2016-03-28 11:28
@Hombre57 I'll rebase and merge this since there are regressions reported so far and it can't really be worse than having no parent window... Thanks for testing in any case!

**Closed** 2016-03-28 11:44 UTC

**Comment by adamreichold** [comment] 2016-03-28 12:03
Also merged `master` into `gtk3` to propagate the fix.

**Comment by Beep6581** [comment] 2016-03-29 13:07
(Still) works fine in [Awesome](https://en.wikipedia.org/wiki/Awesome_(window_manager)).
Thank you for the merge.
