### ISSUE TITLE
Flatfield creating circular-colored artefacts with Fujifilm RAF file

### ISSUE THREAD

**Issue by Congles** [Beep6581/RawTherapee#7199] opened 2024-09-14 07:08 UTC
RAF files from my GFX100S II are producing strange green and blue artefacts when the flatfield is applied.

**sample files**
https://drive.google.com/drive/folders/1bdrImdrDyWaHnuwDqMauzwxbL4pscLxP?usp=sharing

**Steps to reproduce**
1. Load example image
2. apply flatfield image
3. Observe error

**Additional information**
- RawTherapee 5.9 and 5.9-472-g31bf942d9 both exhibit the si
- Windows 11

Other useful information:
![image](https://github.com/user-attachments/assets/115ad15b-ef5b-4c92-aca9-986d7b6bc527)

**Comment by Lawrence37** [comment] 2024-09-14 22:45
Confirmed in 5.9. Cannot reproduce in 5.11. Closing as fixed.

**Closed as completed by Lawrence37** 2024-09-14 22:45 UTC
Labels: type: bug
