### ISSUE TITLE
Avoid desaturation and colour tint caused by RAW-CA correction

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#4777] opened 2018-09-05 15:39 UTC
The RAW-CA correction tool desaturates images. See https://github.com/Beep6581/RawTherapee/issues/4774#issuecomment-418732568
It would be great if the desaturation can be reduced. Ping @heckflosse 
CA off
![ca-off](https://user-images.githubusercontent.com/13800920/45104188-cae02080-b131-11e8-837a-3004d1555a45.png)
CA on
![ca-on](https://user-images.githubusercontent.com/13800920/45104205-d3d0f200-b131-11e8-83b6-d5c2f61c64c0.png)

CA off
![ca-off2](https://user-images.githubusercontent.com/13800920/45104334-28746d00-b132-11e8-9bbf-389739c15824.png)
CA on
![ca-on2](https://user-images.githubusercontent.com/13800920/45104350-34602f00-b132-11e8-8be8-0d602cc80b4c.png)

Upload the files later
`Filebin is currently unavailable (503) due to maintenance. Please retry later.`

**Comment by TooWaBoo** [comment] 2018-09-05 23:35
@heckflosse 
https://filebin.net/grdfzgriwg8tbsqy

**Comment by heckflosse** [comment] 2018-09-06 09:52
@TooWaBoo first result:

left is old code, middle is without ca correction, right is new code with `avoid desaturation`

![grafik](https://user-images.githubusercontent.com/13733487/45150038-3c1fe200-b1cb-11e8-8a0c-b8f2d4ebba60.png)

**Comment by TooWaBoo** [comment] 2018-09-06 11:53
This looks awesome, Great job. 👍

**Comment by agriggio** [comment] 2018-09-06 13:57
@heckflosse Ingo, do we really need an option for this? Who could possibly want the colour shift introduced by the "old" behaviour?

**Comment by heckflosse** [comment] 2018-09-06 14:04
@agriggio Alberto, I'm also fine without an option for this. @Beep6581 @Floessie @TooWaBoo @Hombre57 @Desmis @Thanatomanic @iliasg ?

**Comment by Thanatomanic** [comment] 2018-09-06 14:07
Agreed with @agriggio to avoid colour shift by default.

**Comment by heckflosse** [comment] 2018-09-06 14:17
@Thanatomanic It is default, but currently only for new files.

**Comment by agriggio** [comment] 2018-09-06 14:35
To me the colour shift is a bug, so it seems strage that we have a checkbox that says "do you want to apply the bug fix?" :-)

**Comment by TooWaBoo** [comment] 2018-09-06 14:58
Found a bug in Avoid color shift. I get a green circle in this picture .
Iteration = 2 and Avoid color shift = on.
![grafik](https://user-images.githubusercontent.com/13800920/45165476-33dc9c80-b1f5-11e8-9d78-3aaaa715d4d0.png)
https://filebin.net/kxo1638t5mzfl1qz

**Comment by heckflosse** [comment] 2018-09-06 14:59
Let's complete the work on it first. It still has some bugs. Until they are solved it's very nice to have the option in gui to disable `avoid colour shift`. For example this file, right is with `avoid colour shift`, ouch

![grafik](https://user-images.githubusercontent.com/13733487/45165928-1a882000-b1f6-11e8-97a2-39cf1e0fa36c.png)

**Comment by heckflosse** [comment] 2018-09-06 15:03
@TooWaBoo Thanks for the example. That should be easy to fix

**Comment by agriggio** [comment] 2018-09-06 15:18
@heckflosse fair enough, that answers my question :)

**Comment by TooWaBoo** [comment] 2018-09-06 15:20
...and another one.
https://filebin.net/rdjs84o0wwjehtc3
![grafik](https://user-images.githubusercontent.com/13800920/45166840-37bdee00-b1f8-11e8-9de3-f25906969149.png)

**Comment by heckflosse** [comment] 2018-09-06 15:27
Fix follows soon

**Comment by heckflosse** [comment] 2018-09-06 15:59
Fixed.

**Comment by heckflosse** [comment] 2018-09-06 16:19
I just detected a nice side effect from using large number (e.g. 5) of raw ca correction iterations:
It brings out some details in LED blue regions:

Left without raw ca correction, right with raw auto ca correction 5 iterations
![grafik](https://user-images.githubusercontent.com/13733487/45170891-42c94c00-b201-11e8-87fd-89a550c93ab0.png)

**Comment by TooWaBoo** [comment] 2018-09-06 18:22
Tested, works fine. Merge it. 😄

**Comment by heckflosse** [comment] 2018-09-06 18:28
@TooWaBoo Let's wait a day or two :laughing:

**Comment by agriggio** [comment] 2018-09-06 19:34
I'm still :-1: on merging with the parameter, fwiw. I'd rather wait a bit more, make sure that there are no side effects, and get rid of the parameter when it's ready. just my 2c of course

**Comment by heckflosse** [comment] 2018-09-06 19:39
@agriggio I agree if there are no side effects. For example we have to test with high ISO files too.

**Comment by agriggio** [comment] 2018-09-07 05:03
I'll give it a try when I have the chance

**Comment by Desmis** [comment] 2018-09-07 06:13
I agree with Ingo, and test if there are no side effects :)

**Comment by heckflosse** [comment] 2018-09-09 11:08
I just pushed new code which executes `avoid colour shift` per iteration instead of once after all iterations.
This improves the correction of the colour shift a bit when using a large number of iterations though there is still some desaturation when using large number of iterations.

Left is old code with 10 iterations, middle is without raw ca correction, right is new code with 10 iterations.
![grafik](https://user-images.githubusercontent.com/13733487/45263818-55c26300-b431-11e8-8786-9bdc54ae0f99.png)

**Comment by agriggio** [comment] 2018-09-11 15:13
@heckflosse I tested a little bit, and in general I like the "avoid colour shift" feature! :+1: 
I don't know if this is a known problem, but I got some serious artifacts when pushing the number of iterations too high. This happens regardless of the "avoid colour shift" setting. Here is a raw file and a couple of renderings (neutral profile, just raw CA correction enabled with 10 iterations):
https://filebin.net/8jj8czw7ab1n9x50

**Comment by heckflosse** [comment] 2018-09-11 15:15
@agriggio Alberto, thanks for testing. I set the max. number of iterations to 10 only for testing. We should reduce it to 5 or less imho.

**Comment by heckflosse** [comment] 2018-09-11 19:13
I tested the new ca correction code with a lot of files. My findings:

1.) I detected no case, where `avoid colour shift` gave a worse output
2.) for images with moderate ca, 2 iterations almost always gives the best result
3.) for images wit really heavy ca, more than 2 iterations are needed but also can lead to artifacts
4.) for images without or with very low ca even 1 iteration (default before my changes) can lead to artifacts

**Comment by Beep6581** [comment] 2018-09-11 21:04
I tested ~50 raw photos mostly from Pentax and Sony but also from a bunch of other cameras.
* A default of 2 iterations worked very well in most cases.
* The more iterations, the more red/blue detail would be altered which should not be altered. Not all photos have such detail.
* Using more than 3 iterations in most cases was a sign that I was trying to fight something which was not normal CA, in which case using a different tool would lead to a better result, e.g. purple fringing caused by extreme contrast is better fixed using the Defringe tool. https://i.imgur.com/Z7cDJjw.jpg
* I agree about hard-coding "avoid color shift" to be always enabled even for old PP3 files.

**Comment by heckflosse** [comment] 2018-09-11 21:19
Ok, I will reduce the max. number of iterations to 5 then and hard code 'avoid colour shift'. In first step I will remove 'avoid colour shift' from gui only and keep the procparams/paramsedited stuff for some weeks.
That will allow easier testing of cases, where avoid colour shift could be a culprit.

**Comment by Desmis** [comment] 2018-09-12 05:54
With my usual raws, 1 or 2 iterations are enough  :)

**Comment by heckflosse** [comment] 2018-09-12 13:26
Here's an example (very littel ca) to show the effect of the last fix:

left is 2 iterations without last fix (small greenish border caused by wrong interpolation)
middle is without ca correction (small reddish border)
right is 2 iterations with last fix (perfect)

![grafik](https://user-images.githubusercontent.com/13733487/45427786-09308f00-b6a0-11e8-8a39-ff21c86aef87.png)

**Comment by heckflosse** [comment] 2018-09-15 07:47
merged with f940490

**Closed as completed by heckflosse** 2018-09-15 07:47 UTC
Labels: type: enhancement, scope: file format
