### ISSUE TITLE
5.3 crash in macOS when switching to Queue

### ISSUE THREAD

**Issue by paulinster** [Beep6581/RawTherapee#4128] opened 2017-10-03 01:34 UTC
Hi, I have upgrade to RT5.3 but look like I can't put file to queue and then process them. When I click the queue tab, the application close and the crash report from mac os open.  

Operating system: MacOS Sierra 10.12.6
Rawtherapee version: 5.3

Step to reproduce: 
1. Open RT
2. From File Browser tab, put a 1-2 files to the queue
3. Click the queue tab 

The application should then close and a popup from MacOS shoud appear saying "Rawtherapee qui unexpectedly"  I have attach the crash report if this can be of any help ..  

[rawtherapee-bin_2017-10-02-211616_mtl-mac-lpaulin.crash.zip](https://github.com/Beep6581/RawTherapee/files/1350885/rawtherapee-bin_2017-10-02-211616_mtl-mac-lpaulin.crash.zip)

If you require more information let me know!

**Comment by Benitoite** [comment] 2017-10-03 04:22
Thanks for the crash report.
RT 5.3 doesn't crash for me in this way.  
I can try rebuilding cairomm 1.12.2 though.

**Comment by Benitoite** [comment] 2017-10-03 04:48
@paulinster See if this build makes any difference.  Also try deleting your options file if you haven't already.
...

**Comment by paulinster** [comment] 2017-10-03 13:11
The new build didn't change anything ..  However I think that I found the
issues...  Look like the issues is due to the directory naming...  After
doing some test I found that I was able to add picture from other folders.
It turn out that the folder from which I was trying to add content to the
queue had french character. Once I rename the folder it work great...

Folder name I had issue with: "09-23 - Québec"

So look like the bug is rather that the application isn't handling properly
filename/directory with french character, most likely it could be the same
issues for other language as well..



--
                         !!!!!
                       ( o o )
 --------------oOO----(_)----OOo--------------
   Luc Paulin
   email: paulinster(at)gmail.com
   Skype: paulinster


2017-10-03 0:48 GMT-04:00 Benitoite <notifications@github.com>:

**Comment by Benitoite** [comment] 2017-10-03 15:46
@paulinster Thanks.  Reproduced crash as reported by renaming my folder to `09-23 - Québec`.
@Floessie could this be another `Glib::ustring` locale convert error?  I could not reproduce the crash in debug, so I have no backtrace.

**Comment by Benitoite** [comment] 2017-10-03 16:27
@Floessie very similar crash as in  https://github.com/Beep6581/RawTherapee/issues/3951#issuecomment-312648719

**Comment by Floessie** [comment] 2017-10-03 17:11
@Benitoite 
> could this be another Glib::ustring locale convert error? I could not reproduce the crash in debug, so I have no backtrace.

We could tell for sure, if we had a backtrace. You can try to obtain one from a release build, though some symbols will be missing. What strikes me most is that it crashes with a release but not with a debug build. If we have a problem with the locales, I'd expect it to crash in both builds. And then still the question remains, why there are those locale problems at all, given the fact that everything is fine under Linux.

> very similar crash as in #3951

Yes, the backtrace is similar, but I haven't found **the** solution to the crash in that issue. Maybe @heckflosse remembers? As such, it looked more like a race than a locale problem...

**Comment by Benitoite** [comment] 2017-10-03 17:45
@Floessie Cannot reproduce any error with release running in lldb. 
Release by itself, I can't get the same crash consistently. Sometimes it won't crash... then I get this error when trying to process the queue: 
![screen shot 2017-10-03 at 10 34 14 am](https://user-images.githubusercontent.com/17919239/31139639-0be6f6ea-a827-11e7-823f-31f25a04e561.jpg)

**Comment by Benitoite** [comment] 2017-10-03 20:23
@Floessie Maybe I should try this: https://discuss.pixls.us/t/error-processing-queue-invalid-byte-sequence-in-conversion-input/1188/18?u=hiram

**Comment by Benitoite** [comment] 2017-10-03 21:21
@paulinster https://filebin.net/t7fe4j4j0eq1ct2q/RawTherapee_OSX_10.9_64_5.3-2-gc6c9ad5e.zip
Here is another build with those changes https://github.com/Beep6581/RawTherapee/issues/4128#issuecomment-333966735 in the executable loader.  I'm not getting a crash or error processing a folder named `é` as I was previously.

**Comment by paulinster** [comment] 2017-10-04 12:32
@Benitoite Yeah the new build seem to have solve the issue I have successfully been able to put files in queue without a crash, even if the filename or path had french character... 

Thanx for your help everyone...

**Comment by Floessie** [comment] 2017-10-04 12:43
@paulinster Luc, thanks for reporting and testing!

@Benitoite Great investigation and quick solution! Thanks a lot! 👍 

Merged.

**Comment by direvius** [comment] 2019-03-06 21:53
Reproduces on RT 5.5 macOS 10.14.3 with cyrillic symbols in path.

**Comment by Benitoite** [comment] 2019-03-06 22:16
@direvius can you post the system crash report?

**Comment by direvius** [comment] 2019-03-12 08:03
[raw_therapee_crash.txt.zip](https://github.com/Beep6581/RawTherapee/files/2955690/raw_therapee_crash.txt.zip)

**Comment by Benitoite** [comment] 2019-03-12 10:37
Thanks.  In 2 weeks I’ll be at home from overseas vacation and able to try things out.  First thing to try is upgrading to the newest Cairo version, and add more quartz flags to its configuration.

**Comment by Beep6581** [comment] 2019-12-03 12:14
Closing as duplicate of #4394 #4191

**Closed as completed by Beep6581** 2019-12-03 12:14 UTC
Labels: type: bug, os: macOS
