### ISSUE TITLE
Local adjustments lost when applying partial profile

### ISSUE THREAD

**Issue by epadepa** [Beep6581/RawTherapee#6150] opened 2021-02-28 20:54 UTC
**Short description**
Local adjustments are reset to null  when applying partial profile even if the partial profile doesn't touch local adjustments.

**Steps to reproduce**
1. Save partial profile containing only say a resize or a colour toning
2. Open new image or reset to neutral profile
3. Add one or more local edit spot with one or more tools associated to them.
4. Ensure Processing profile fill mode is set to partial
5. Load profile from file selecting profile saved in step 1 above
6. Observe how previously created Local adjustment spots have been removed

**Expected behavior**
In step 6 above I expect the previously created spots to remain in the saved profile doesn't touch the Local Adjustments module

**Additional information**
- Version of RawTherapee: 5.8-2896-g50d040fff
- Version of your operating system: Debian Sid

```
Version: 5.8-2896-g50d040fff
Branch: dev
Commit: 50d040fff
Commit date: 2021-02-28
Compiler: cc 10.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags: -std=c++11 -Wno-deprecated-declarations -Wno-unused-result -O3 -msse2 -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native -flto
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.10.0-3-amd64 x86_64
Build date: Sun, 28 Feb 2021 20:22:17 +0000 UTC
Build epoch: 1614543737
Build UUID:
```

**Comment by Thanatomanic** [comment] 2021-03-01 07:07
~~This was reported literally a few days ago. https://github.com/Beep6581/RawTherapee/issues/6136~~

**Comment by Thanatomanic** [comment] 2021-06-22 11:27
Thanks to a friendly message on Pixls, this is actually a bug. @Desmis Can you take a look why all Local adjustment spots are removed when a simple partial profile is applied even when the partial copy mode is active?

You can test with this pp3 if you like:
[testprofile-RGBCurves.pp3.txt](https://github.com/Beep6581/RawTherapee/files/6693832/testprofile-RGBCurves.pp3.txt)

**Comment by Desmis** [comment] 2021-06-22 11:33
@Thanatomanic 
I don't master everything in Local Adjustments, especially this part with "partial profile".

I prefer, if he agrees, to let the designer of this part take care of it  @Pandagrapher 

Jacques

**Comment by epadepa** [comment] 2022-06-13 11:03
I have some additional observations that may help bug tracking. Using the batch panel of the File Browser can trigger the same or similar bug. 

1. Add local edit spots to image using the Local tab in the Editor window
2. Switch to File browser and select multiple files including the above one with LA spots
3. Change the settings of any module using the batch panel. (resize or output profile for instance)
4. Open image from no 1 above and find all local edits are gone

Interestingly the spots from 1 remain if you at 2 select just  the **one** file with spots and make the same changes. I have to say this is a very serious bug as it means you can destroy all LA work across a large number of files by using the basic functionality of the RT file browser. The batch view and applying a partial profile to multiple images are currently the only way to tweak output for different media etc. So anyone producing for print and web will be bitten and there are countless other use cases.

**Comment by Floessie** [comment] 2022-06-13 12:58
@Pandagrapher @epadepa Does this solve the problem?

```patch
diff --git a/rtgui/paramsedited.cc b/rtgui/paramsedited.cc
index 529d57da6..166b588b2 100644
--- a/rtgui/paramsedited.cc
+++ b/rtgui/paramsedited.cc
@@ -3388,8 +3388,10 @@ void ParamsEdited::combine(rtengine::procparams::ProcParams& toEdit, const rteng
         toEdit.locallab.selspot   = mods.locallab.selspot;
     }
 
-    // Resizing locallab spots vector according to pedited
-    toEdit.locallab.spots.resize(locallab.spots.size());
+    if (locallab.spots.size() >  toEdit.locallab.spots.size()) {
+        // Resizing locallab spots vector according to pedited
+        toEdit.locallab.spots.resize(locallab.spots.size());
+    }
 
     // Updating each locallab spot according to pedited
     for (size_t i = 0; i < toEdit.locallab.spots.size() && i < mods.locallab.spots.size() && i < locallab.spots.size(); i++) {
```

**Comment by epadepa** [comment] 2022-06-14 07:57
@Floessie , a hero has appeared! I does seem like the above solves the problem. Spent a few minutes stressing the file browser with batch and profile application of numerous unsuitable combinations and the spots remain!

Interestingly applying my various LA presets only affects the first spot which is an improvement beyond this bug. I have LA preset profiles for log mapping and face sharpening for instance.  If I apply these to an image with a stack of spots only the first spot in the list is replaced with the "new" one whilst the others remain unchanged. Complete side note but perhaps of interest for reaching complete LA profile management compatibility.

**Comment by Desmis** [comment] 2022-06-14 08:18
@epadepa 
I'm glad that this patch (thanks to @Floessie ), solves this bug.

On the other hand, full compatibility (i.e. being able to integrate LA in batch files ("batch edit") is not possible in the near future, unless specialists such as @Pandagrapher  who is at the origin of the LA GUI advise otherwise.

Excuse my very bad english....

Thank you

Jacques

**Comment by Pandagrapher** [comment] 2022-06-14 18:43
@Floessie Thanks for the patch :): I just tested and it solves the issue

> being able to integrate LA in batch files ("batch edit")

To give some history: In fact, LA was originally integrated in batch edit. Due to some remarks about the fact LA is not really relevant in batch edit (because it should be locally applied on each photo), I removed that functionality. Honestly, I prefered that option because it was such a pain to implement and maintain LA in batch edit GUI.
Perso I prefer using the copy/paste or save/apply functions than the batch edit one. That's why I implemented LA in these functions.

Pierre

**Comment by Lawrence37** [comment] 2022-06-14 20:17
>  If I apply these to an image with a stack of spots only the first spot in the list is replaced with the "new" one whilst the others remain unchanged.

@Pandagrapher Is this the expected behavior?

**Comment by epadepa** [comment] 2022-06-25 13:51
I've now processed approximately 200 images with this patch. About 25% local adjustments. So far no new issues have been found.

**Comment by Pandagrapher** [comment] 2022-07-13 17:24
> > If I apply these to an image with a stack of spots only the first spot in the list is replaced with the "new" one whilst the others remain unchanged.
> 
> @Pandagrapher Is this the expected behavior?

@Lawrence37 I am testing an improved version of the Floessie patch (thanks to have pointed where the issue was) that is also fixing the "merge issue". Now if you apply/paste a profile with LA, current LA spots are replaced by the profile ones (and not anymore merged). It is more coherent of the behavior with the other tools. For now, it's available on the `locallabpatch` branch in my fork. Gonna perform more tests before submitted a PR

Pierre

**Comment by Floessie** [comment] 2022-07-15 19:43
@Pandagrapher Thank you for picking this up properly! :+1:

**Closed as completed** 2022-07-18 17:03 UTC
Labels: type: bug, tool: selective editing
