### ISSUE TITLE
Curve pipette applies node without ctrl

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3862] opened 2017-05-04 12:53 UTC
1. Open any raw.
2. Custom curve, enable pipette
3. Regardless of zoom level, left-click in the preview. A node is placed on the curve. This should only happen when ctrl is pressed while clicking, but it happens without ctrl. This is a problem if you want to pan the preview without placing a node. Bug 1.
4. Furthermore, bug 2, if I pan the preview any amount and then simply move the mouse cursor from the preview area over to the curve area, this triggers an event and the status bar shows "Processing image..." for a second. It shouldn't because I didn't click anything, I just moved the mouse cursor. To make it happen again, just pan the preview a small amount, then move the mouse cursor over the curve area again.
5. Bug 3, if I place a point using the pipette it appears in the curve as red (red=selected), and then if I just move the mouse cursor over the curve area the red dot disappears.

**Comment by heckflosse** [comment] 2017-05-04 12:59
confirmed both bugs

**Comment by Beep6581** [comment] 2017-05-04 15:58
@Hombre57 any chance you could look into this for 5.1?

**Comment by agriggio** [comment] 2017-05-04 20:06
@Beep6581 @Hombre57 I'm taking a look

**Comment by agriggio** [comment] 2017-05-04 20:32
I just pushed a candidate fix. Please confirm it works as intended

**Comment by heckflosse** [comment] 2017-05-04 21:04
Fix confirmed

**Comment by Beep6581** [comment] 2017-05-04 22:08
All three bugs confirmed fixed, thank you again.

**Comment by Hombre57** [comment] 2017-05-08 21:25
May I reopen the issue to propose another fix ?

https://gist.github.com/Hombre57/e7ed68751b13835304795e1b0beabe74

I'd prefer to keep the modifier key for pipette in `cropwindow.cc`, if you don't mind.

**Comment by agriggio** [comment] 2017-05-09 06:39
sure, no problem!

**Comment by Hombre57** [comment] 2017-05-09 18:15
Patch committed to dev.

**Closed as completed by Hombre57** 2017-05-09 18:15 UTC
Labels: type: bug
