### ISSUE TITLE
DNG build-in lens correction support

### ISSUE THREAD

**Issue by Eneen** [Beep6581/RawTherapee#4049] opened 2017-08-28 11:33 UTC
I was looking for this option inside RT but it doesn't seem to apply build in DNG lens profiles. Some cameras (like FC6310 in my case) write lens correction info into DNG directly. Here is very short info about this from adobe:
https://helpx.adobe.com/x-productkb/multi/lens-profile-support.html#Create%20your%20own%20lens%20profiles
I can share sample file if needed, but only privately.

**Comment by Beep6581** [comment] 2017-08-28 17:31
@Eneen please upload a sample raw file using https://filebin.net/

**Comment by Beep6581** [comment] 2017-08-28 22:42
I examined the raw file from a DJI FC6310 drone and it contains no lens correction parameters that I could read. Several possibilities present themselves:
1. It does not contain any lens correction parameters. The correction in Adobe products might be based on the lens model and properties.
2. It does contain lens correction info in a proprietary format. Maybe Adobe DNG Converter can read it and use it.
3. It might contain lens correction parameters in opcodes - indeed it does have `Exif.SubImage1.OpcodeList1` and `Exif.SubImage1.OpcodeList3` but I don't have software to read that, tried [dngconvert](https://github.com/jmue/dngconvert) but it fails to compile and the project is dead. This seems like the most likely option.

We already have an issue for adding support for WarpRectilinear opcodes to RT, I'll close this issue as a duplicate of issue #2838

@Eneen if issue #2838 takes off we will need raw files to test. In that case it would be good if you could take a photo of something which you can publicly upload and share.

More importantly, there is issue #3826 which more people would find useful.

**Closed as completed by Beep6581** 2017-08-28 22:42 UTC
Labels: type: enhancement

**Comment by Eneen** [comment] 2017-08-29 08:29
Thank you @Beep6581
I've googled a bit and here is response from Camera Raw Engineer Chris Castleberry:
https://feedback.photoshop.com/photoshop_family/topics/unable-to-disable-built-in-lens-profile-applied-for-raw-files?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all
Scroll a little bit down to find original.

> Hi Louie,
> 
> Per request from Sony, Lightroom will enable the external lens profile automatically for raw files if the lens comp settings are enabled in the camera and an external profile is available in the version of the application you are running. The external profile corrects for geometric distortion and vignetting only. The chromatic aberration correction is **baked into the raw file using opcodes** that cannot be disabled in Lightroom.
> 
> If you wish to disable the external profile by default, you can set a new lens profile default (with it disabled) for each lens/camera combination.

Fo this particular drone there is however additional correction profile made by some forum user, so this build in one is not perfect.

**Comment by Beep6581** [comment] 2017-08-29 09:44
@Eneen the fastest solution is for you to get an LCP or make your own LCP:
http://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles

**Comment by Eneen** [comment] 2017-08-29 10:55
Thank you. It's no problem here as I asked for already corrected tiff.

**Comment by Beep6581** [comment] 2017-08-29 11:24
@Eneen one more thing - please consider uploading `DJI_0027.DNG` to https://raw.pixls.us/ so that we and other open-source programs can benefit. I chose 0027 specifically because in addition to the lens distortion it also shows magenta highlights.
