### ISSUE TITLE
Thumbnails in file browser have grotesque margins on Mac

### ISSUE THREAD

**Issue by reagle** [Beep6581/RawTherapee#3936] opened 2017-06-19 19:44 UTC
# Problem

The attached image shows when I have very large thumbnails, but you can see most of the space is empty.

<img width="1517" alt="screen shot 2017-06-19 at 3 35 48 pm" src="https://user-images.githubusercontent.com/596814/27302573-9b382230-5505-11e7-994a-f6d3426c66e1.png">

# System info

```
Model Name:	iMac
Model Identifier:	iMac16,2
Processor Name:	Intel Core i5
Processor Speed:	3.1 GHz
Number of Processors:	1
Total Number of Cores:	4
Memory:	8 GB

rawtherapee: 5.1
http://rawtherapee.com/
/usr/local/Caskroom/rawtherapee/5.1 (3 files, 830B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/rawtherapee.rb

Version: 5.1
Branch: 5.1
Commit: f23d70fd
Commit date: 2017-05-15
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
```

**Comment by reagle** [comment] 2017-06-19 19:48
I wonder if this is related to Retina Screen and hdpi? They look about quarter size...

**Comment by Beep6581** [comment] 2017-06-19 19:56
Yes. Duplicate of #3547

**Closed as completed by Beep6581** 2017-06-19 19:56 UTC
