### ISSUE TITLE
Lumix GH5 Mark 2 RW2 raw format support

### ISSUE THREAD

**Issue by ccharn** [Beep6581/RawTherapee#6626] opened 2022-12-02 02:31 UTC
The Lumix GH5 mark 2 is about 1.5 years since announcement and the .rw2 files have never worked for me. Was hoping it would in Version 5.9 but it is still not. Here is a sample file together with the associated pp3 and screen shot. Really appreciate all the work that went into RawTherapee over the years. 

https://filebin.net/ddfuwvosqf7r1ihq

**Comment by Thanatomanic** [comment] 2022-12-02 09:15
I have downloaded your files, no one reported before about the GH5 M2 not working.
The fix for this is to update our Panasonic decoder, perhaps by borrowing from LibRaw.

**Comment by Thanatomanic** [comment] 2022-12-02 09:16
Also, probably related #6469 for GH6

**Comment by kmilos** [comment] 2023-06-16 13:27
> Also, probably related #6469 for GH6

GH5M2 is a v6 codec (although at 12b), while GH6 is a newer v8.

**Comment by austincbrooks** [comment] 2023-09-11 21:52
Is there anything I can do to help with GH5 Mark 2 support?  I have this camera and would love to use RawTherapee for it.  I have used RawTherapee for years with my older G85 camera and appreciate everyone's work!

**Comment by Lawrence37** [comment] 2023-09-13 01:28
LibRaw can decode the raw files. You could try finding what they did, although their commit (history) messages are not very helpful and so it's difficult for someone who can't read code. If rawspeed can decode the files, you could also have a look at their history.

**Comment by Lawrence37** [comment] 2024-05-11 22:27
Duplicate of #6297.

**Closed as completed by Lawrence37** 2024-05-11 22:27 UTC
Labels: scope: file format
