### ISSUE TITLE
Curve container partially covered until user hovers mouse over curve button

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3525] opened 2016-12-06 00:40 UTC
The "Transmission" tool and "Gain and Offset" shows a distorted layout when showing a curve.
This happens with theme TooWaBlue, RawTherapee and without any theme.
How to reproduce this bug:
1. Choose a curve type to show and don't move the mouse away from the button.
2. The layout is distorted (see screenshot pic. 1)
3. Move the mouse to any button in the same frame.
4. The layout will refresh (see screenshot pic. 2)

![retines](https://cloud.githubusercontent.com/assets/13800920/20908347/8cf442a8-bb54-11e6-8cbd-8520e1645d34.png)

**Comment by Beep6581** [comment] 2021-04-02 12:08
> Thanatomanic added this to the v6.0 milestone 28 days ago

Brave :)

**Comment by ghost** [comment] 2023-06-20 18:06
Hello to everyone,

it was a short but hard time and I am far away of understanding whats going on. But because other people are also working on this issue (or at least were working), I want to motivate everyone to share information, so we can get rid of that bug.

First of all: I cannot find any bug report related to gtk in general which covers this bug. So for now my information is: This is a bug in rawtherapee and not in gtk. Please let me know if anyone has other information.

Now, what I have found out so far:
- Every hover effect on buttons inside the related ToolParamBox (here I tested with RGB Curves) leads to a redraw? resize? of the box and after that everything looks right.
- I added a lot of queue_resize/resize_children/... and so on to different Gtk::Box, cause I thought this might be just a problem of not resizing or redrawing the box. Well, ... without success.

My current state is: Maybe this is a problem of css inside gtk. Maybe showing a new widget won't directly or correctly update all layout features of the gtk ui.

Every information is welcome, as I cannot find the bug for now, but I won't stop searching and testing so far. For me it is a little bit of a hard task coming from qt and not from gtk.

Greetings.

**Comment by ghost** [comment] 2023-06-21 19:54
Hello to everyone,

just for documentation reasons:

After adding `set_resize_mode(Gtk::ResizeMode::RESIZE_IMMEDIATE);` to the constructor of ToolVBox solves th
e problem but opens other unwanted results. Never the less, this might lead to the right direction. So what changes with this code change:

- Curve windows get scaled and every gets resized correctly as we want.
- The ToolVBox as a container doesn't seem to be sized automatically anymore , which leads to a wrong position of the toolbox-end-image.
- Resizing will update the ToolVBox container, but after that it wont get updated anymore.

In the appended image you can see, that I colored the ToolVBox yellow and the ToolParamBlock red. It shows, that after inserting the code, the yellow container shrinks at the beginning and the image goes up. After resizing the width of the toolbox, the ToolVBox height gets updated.

Another problem is, that setting the resize mode is deprecated and marked as "not needed". Cause frame clock (I just don't understand) makes it obsolete and using it can lead to unwanted effects. Well we see one of this.

So, I won't give up but every help is welcome.

Greetings.
![Bildschirmfoto vom 2023-06-21 21-49-50](https://github.com/Beep6581/RawTherapee/assets/201798/b9a84b0b-7d29-4309-926b-3b28857ef73d)
![Bildschirmfoto vom 2023-06-21 21-48-43](https://github.com/Beep6581/RawTherapee/assets/201798/7e06d13d-8be3-4d5b-a477-e61ec03db94a)

**Comment by Lawrence37** [comment] 2023-06-22 04:22
I don't have much background on this, but I'll give you my thoughts. At least a few people have looked into this but we're unable to find anything suspicious. The problem only happens to these curve widgets. They are custom, so it's likely there is some issue with the size and/or position implementation. The fact that some of the widgets that go below are in the correct place but others aren't and that the problem goes away after hovering over certain widgets leads me to believe the size/position initially reported by the curve widget is wrong but it's correct after a second query. The resize mode *might* be a red herring.

I wish you luck in finding the cause and will try to answer any questions you have.

**Comment by Hombre57** [comment] 2023-06-22 07:21
I'll investigate as well, since I've made this ...thing. I never managed to find a synthetic documentation of how Widgets were handled, from creation to destruction, so it was a bit of guess thoughts. However IIRC the widget was working fine for some times, and it broke in a certain Gtk release. The _frame clock_ is related to animations. Maybe there's something to set in the CSS ?

**Comment by ghost** [comment] 2023-06-23 19:48
Hello to everyone,

just for documentation:

I put some print statements inside the custom curve widget. I conclude, that the widget returns the right width and height constantly on resizing (by change the width of the tool panel). But the panel itself won't update its height (see first image). Also it now opens initially with the right height, as long as no one changes the width of the tool panel.

Maybe just a short additional information: Opening the gnome shell menu (top right) will also correct the sizing, not only the hover on an inside button.

For me, it still looks like any of the (feels like hundreds of them :-P) sub-container, sub-boxes and so on doesn't get the information right and just doesn't update on child size change, till some reevaluation (whatever that means) which connects it the right way.

I will now try to get information or other code examples of how to create full custom widgets. Just to be sure, nothing comes from a wrong implementation. But what I have seen so far looks good.

Question: Is there any known graph or other self impemented ui element, changing the height related to the width in the tool panel which works the right way? It might be, that we only see the problem here, cause this is the only tool panel widget which changes the height related to the width.

Thanks in advance for your help.

![Bildschirmfoto vom 2023-06-23 21-36-54](https://github.com/Beep6581/RawTherapee/assets/201798/c20b0d76-9510-4567-843f-fbd648989f6e)
![Bildschirmfoto vom 2023-06-23 21-36-00](https://github.com/Beep6581/RawTherapee/assets/201798/5cf8d038-29bc-4b8a-8f1d-a1b3358ad055)

**Comment by Hombre57** [comment] 2023-06-23 22:46
I discovered that the problem is gone if you enable the point editing spin buttons. It might be related to the show/hide function of this Gtk::Grid. I'll continue tomorrow.

**Comment by ghost** [comment] 2023-06-24 04:39
Hello Hombre57,

thank for your invest. I tried it and if you mean the spin button that gets showed on the bottom, I cannot comfirm, that this solved the issue. Maybe you are doing something additionally?

![Bildschirmfoto vom 2023-06-24 06-37-08](https://github.com/Beep6581/RawTherapee/assets/201798/016f06a3-209a-4adb-a8c0-bab22600b381)

**Comment by Hombre57** [comment] 2023-06-24 10:16
I confirm that I've tested with current code, but with the HSV Equalizer. Strangely, RGB Curves and HSV Equalizer doesn't react the same :thinking:

**Comment by ghost** [comment] 2023-06-24 12:42
Hello, that might be an important information to me. I tried the same thing with the HSV Equalizer, but finally doesn't see any difference in the way they act (see attached image).

Never the less, I found a DiagonalCurveEditor in Color Toning that seem to work. This leads - maybe to the wrong - conclution, that the underling mycurve widget should work fine, cause there is no big difference in usage in both ToolPanelParam objects. There where some methods for the curve editor called in the contructor of colortoning but not in rgbcurve which I tried to implement in rgbcurve. Just for testing to have an identical implementation. In the end, that doesn't change anything to the behaviour of the rgbcurve. As far as I have seen, code above these objects (FoldableToolPanel...) threats every ToolPanelParam the same way. Finally this bug might be somewhere in rgbcurve directly. 

![Bildschirmfoto vom 2023-06-24 14-31-12](https://github.com/Beep6581/RawTherapee/assets/201798/3efa59f2-1685-45f4-b1f5-e5eef5b44429)

![Bildschirmfoto vom 2023-06-24 14-35-01](https://github.com/Beep6581/RawTherapee/assets/201798/8d16a6f9-329b-4817-bf79-391df4dd3889)

**Comment by Hombre57** [comment] 2023-06-24 21:35
I've implemented what is explained in the official documentation [here](https://developer-old.gnome.org/gtk3/stable/GtkContainer.html) and [here](https://developer-old.gnome.org/gtk3/3.24/GtkWidget.html), in the `Height for width geometry management` section. It says that the container must send back something valid even for a width-for-height negotiation, which is the height for the minimum width.

The negotiation is ok when the curve is displayed at application start (i.e. when it was open when RT was closed). The problem occurs only when (re)attaching the curve afterwards, and for some curves only. E.g. the one in Split toning are working fine but the RGB curves or HSV curves aren't. I don't see any difference in the code though.

You can see that depending on the width of the ToolPanel, the curve editor is cropped to the height returned by `get_preferred_height_vfunc`, which basically send a constant value. That's why it's cropped to a constant height, whatever the Curve editor width is.

In the second link, you can read :
> For this reason, [GtkWidget](https://developer-old.gnome.org/gtk3/stable/GtkWidget.html) caches a small number of results to avoid re-querying for the same sizes in one allocation cycle.

Could this be part of the problem ?

**Comment by Lawrence37** [comment] 2023-06-24 22:17
As long as the functions are returning the correct height/width, there shouldn't be a problem due to caching. If GTK really is using the preferred height instead of the preferred height for width, that's a big clue. Why is the preferred height used? It implies the parent container is a width-for-height widget (vertical container?).

**Comment by ghost** [comment] 2023-06-25 07:27
Hello to everyone,

I'll put some print statements in `MyCurve::get_preferred*()` (image 1). Finally I got:
- No calls on `get_preferred_height_vfunc()`.
- On hitting the curve button and showing the curve (where it is higher and cut-off on height) I get multiple calls on `get_preferred_height_for_width_vfunc()` they all have different width values given to the methods (image 2).
- While changing the width of the toolpanel, I get periodic calls on `get_preferred_height_for_width_vfunc()`. The height of the curve changes, but the cut-off height does not change.

Maybe this information makes it more clear what happens.

![Bildschirmfoto vom 2023-06-25 09-16-46](https://github.com/Beep6581/RawTherapee/assets/201798/6adbab53-8de5-48c5-bdd0-742a79888590)
![Bildschirmfoto vom 2023-06-25 09-20-00](https://github.com/Beep6581/RawTherapee/assets/201798/fbef51d7-9cea-4ef4-8e43-02b90460bcd8)
![Bildschirmfoto vom 2023-06-25 09-26-32](https://github.com/Beep6581/RawTherapee/assets/201798/0e94b68c-75c2-48e2-8e9f-5acc16da4a47)


Greetings

**Comment by Hombre57** [comment] 2023-06-25 10:00
When you spy the `ToolParamBlock` container of the curve with the GTK inspector (start RT with `GTK_DEBUG=interactive`), you can see that its request mode is height-for-width if the curve is opened in RT start, then it switch to constant when toggling it of.  If you toggle it on again, it doesn't restore the height-for-width mode immediately, but after some mouse-over.

`ToolParamBlock` was already vertically oriented, so I've overridden its `get_request_mode_vfunc` method to always send back height-for-width ...and it seem to fix the issue !

Please test this patch.

[3525-fix-01.patch.txt](https://github.com/Beep6581/RawTherapee/files/11859347/3525-fix-01.patch.txt)

**Comment by ghost** [comment] 2023-06-25 11:56
Hello Hombre57,

I gave it a try and for me, this solved the issue. Congratulations and thanks for your invest of time. This bug has been open since 2016/2017 and now you got it in just few days.

I also haven't found any problems with the patch.

Hopefully, if no one finds any problems with your patch, we will see it in dev soon. :-)

Greetings

**Comment by Hombre57** [comment] 2023-06-25 13:03
Thanks Christian, I'll wait for another tester and I can commit then, if you don't mind.

**Comment by Lawrence37** [comment] 2023-06-25 20:02
Nice! Because GTK4 doesn't have VBox, could you keep inheriting from Box (see #6103)?

**Comment by Hombre57** [comment] 2023-06-25 22:15
@Lawrence37 Sure, I thought that Box was deprecated as a whole anyway.
It looks like I can't push anymore. Would you mind making the 4 lines revert and commit ?

**Comment by Lawrence37** [comment] 2023-06-26 00:52
@Hombre57 Like this? #6781

**Comment by Hombre57** [comment] 2023-06-26 06:07
@Lawrence37 Yes, thanks.

**Closed** 2023-06-26 11:00 UTC
Labels: type: bug, patch provided, scope: GUI, priority: medium
