### ISSUE TITLE
rawtherapee-cli crashing on saving uncompressed TIFF

### ISSUE THREAD

**Issue by fliker09** [Beep6581/RawTherapee#3926] opened 2017-06-14 13:53 UTC
I try this:

> rawtherapee-cli -o test.tif -p rawtherapee.pp3 -Y -t -c DSC_3382.NEF    
RawTherapee, version , command line
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 2) >= this->size() (which is 2)
Aborted (core dumped)

If I try this - all good:

> rawtherapee-cli -o test.tif -p rawtherapee.pp3 -Y -tz -c DSC_3382.NEF
RawTherapee, version , command line
Processing: DSC_3382.NEF
  Merging procparams #0

Info:

> Version: 
> Branch: 
> Commit: 
> Commit date: 
> Compiler: x86_64-linux-gnu-gcc 5.4.0
> Processor: x86_64
> System: Linux
> Bit depth: 64 bits
> Gtkmm: V3.18.0
> Build type: Release
> Build flags: -O3 -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations
> Link flags:  -Wl,-Bsymbolic-functions -Wl,-z,relro
> OpenMP support: ON
> MMAP support: ON

> apt-cache show rawtherapee
> Package: rawtherapee
> Priority: extra
> Section: graphics
> Installed-Size: 66199
> Maintainer: Dariusz Duma <dhor@toxic.net.pl>
> Architecture: amd64
> Version: 5.1-1dhor~xenial

**Comment by heckflosse** [comment] 2017-06-14 14:09
Duplicate of #3891. Already fixed.

**Closed as completed by heckflosse** 2017-06-14 14:09 UTC
