### ISSUE TITLE
No RGB HSV and Lab readings in small detail windows using big zoom

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#2376] opened 2015-08-11 19:44 UTC
Originally reported on Google Code with ID 2393

```


Win 7 64bit build 179, 165 and maybe earlier on a intel 4 core with 8gb or RAM

Open any file and expand detail box above 100%. Place cursor in center of  box. No
RGB, LAB or HSV readings under the histogram. 

Why is this important? It's very useful tool for matching colors from photographs off
the web in order to duplicate a 'look'. See my latest tutorial, which should go up
today or tomorrow, for details on the workflow.

```

Reported by `scribble1@charter.net` on 2014-05-22 15:20:52

**Comment by Thanatomanic** [comment] 2018-06-30 18:44
While browsing through the outstanding issues, I found I could not reproduce this. Both the bar in the histogram and the navigator seem to give accurate pixel readings even at very high magnification or very small crop windows.
Can be closed?

**Comment by heckflosse** [comment] 2018-06-30 18:46
@Thanatomanic Thanks for having a look. I think we can close this. @Beep6581 ?

**Closed** 2018-07-01 22:34 UTC
Labels: bug
