### ISSUE TITLE
IPTC (and EXIF) metadata encoded in UTF-8 with non-latin characters read like gibberish

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3646] opened 2017-01-30 10:56 UTC
If input file have IPTC (and EXIF) metadata encoded in UTF-8 with non-latin characters, then Rawtherapee read this data like gibberish.
For example, If the image have IPTC description "Метаданные фотографии", than Rawtherapee read them as "РњРµС‚Р°РґР°РЅРЅС‹Рµ С„РѕС‚РѕРіСЂР°С„РёРё".
It looks that Rawtherapee does not support the UTF-8 encoding for IPTC and EXIF metadata.
RT 5.0 for Windows Vista/7/8/10 64-bit - fast, gtk3, from http://rawtherapee.com/downloads.
Any input files (raw, jpeg, tiff or png, 8-bit or 16 bit) with IPTC (or EXIF) metadata encoded in UTF-8 with non-latin characters.

**Comment by Beep6581** [comment] 2017-01-30 21:03
Duplicate with no working solution over the years:
https://github.com/Beep6581/RawTherapee/issues/1314#issuecomment-129958160
https://github.com/Beep6581/RawTherapee/issues/922#issuecomment-129929125

Closing as a duplicate. Feel free to re-open if there's a working patch.

**Closed by Beep6581** 2017-01-30 21:03 UTC

**Comment by geoderix** [comment] 2017-01-30 22:48
@Beep6581 
I am frustrating. # 1314 is closed. #922 is closed. This bug is closed too. Closed bug is duplicate of closed bug? But this bug is true. It is a pity that the UTF-8 will never appear in Rawtherapee. Twenty-first century today outside.

**Comment by Beep6581** [comment] 2017-01-30 23:09
@geoderix nobody said there was no problem. If you want to discuss this, comment in one of the original issues where we can reference what has already be said and found and linked to. This one is closed because it's a duplicate of a duplicate and nothing has happened in those issues for years and some people claim there is no good fix. As you perhaps ready in the other issues, other programs have decided to completely put this problem behind them and move on to XMP.
Closed does not mean deleted. If you can provide a patch or documentation which shows a solution which works reliably on all supported OS, shoot.

**Comment by geoderix** [comment] 2017-01-31 05:49
@Beep6581
You have a strong presence. You have the right. If you hide a bug, then he would never patched. For me, it is best to allocate this bug and stick. In such a case, it may be somebody someday will fix this bug. It is a pity that the program is obtained only for the English-speaking, well, or even Latin.
