### ISSUE TITLE
Flickering HSV Equalizer

### ISSUE THREAD

**Issue by nbrr** [Beep6581/RawTherapee#3169] opened 2016-02-22 13:02 UTC
I am only following guidelines from *rawpedia*/*Generic comments about some toolbox widgets*, this is my first time using Rawtherapee.

In HSV Equalizer tool, in the H : Minima/Maxima control points flat curve box.
When I right-click on a point of the curve (which is still flat, I haven't modified it so far), it becomes red and gets a red circle around it. The box starts flickering: some continuous color bar appears under the plot then disappears. Sometimes I manage to get out of the loop by panick-clicking everywhere.

When I launch rawtherapee from command line, I get no abnormal output.

Screenshots of the two alternating states of the loop :
![2016-02-22-135210_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6716630/13218778/00823c96-d96c-11e5-8794-0bfe8201f697.png)
![2016-02-22-135212_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6716630/13218791/129141f2-d96c-11e5-873a-5e5396b6121b.png)

Running on Archlinux, version:
community/rawtherapee 1:4.2+448.g26d182d-2

**Comment by Beep6581** [comment] 2016-02-22 13:36
It's because the vertical scrollbar appears and disappears. Solution: change the toolpanel's width, or go to Preferences and select "Hide vertical scrollbar".
Duplicate of #2531

**Closed by Beep6581** 2016-02-22 13:36 UTC
