### ISSUE TITLE
Fast Export settings not saved

### ISSUE THREAD

**Issue by listlfa** [Beep6581/RawTherapee#3840] opened 2017-04-24 13:23 UTC
The Fast Export settings are not saved between RawTherapee sessions.  Changed settings also dont seem to be used within the session either. This is for the latest RawTherapee on a Win 7 PC that's never had RawTherapee before.

Complete version information --
Version: 5.0-r1-gtk3
Branch: 5.0-r1-gtk3
Commit: 50114c1
Commit date: 2017-02-01
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

System information --
PS C:\Users\a> systeminfo

Host Name:                 -------------------
OS Name:                   Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          a
Registered Organization:
Product ID:                --------------------------------
Original Install Date:     31/07/2014, 7:21:37 PM
System Boot Time:          24/04/2017, 8:23:48 PM
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~3301 Mhz
BIOS Version:              American Megatrends Inc. 3603, 9/11/2012
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume4
System Locale:             en-au;English (Australia)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+08:00) Perth
Total Physical Memory:     8,159 MB
Available Physical Memory: 4,766 MB
Virtual Memory: Max Size:  12,253 MB
Virtual Memory: Available: 8,383 MB
Virtual Memory: In Use:    3,870 MB
Page File Location(s):     F:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\-----------------

Download --
http://rawtherapee.com/releases_head/windows/RawTherapee_5.0-r1-gtk3_WinVista_64.zip

Exact Steps
1. Open RT with default settings
2. (From File Browser) click on Fast Export
3. Double Click on Select/Unselect All (to clear all check boxes)
4. Exit RT
5. Open RT
6. Repeat steps 1 and 2, see that no change has been saved

Screenshots attached.  Following the steps for GDB creates an empty log file.

![01_defatulsettings](https://cloud.githubusercontent.com/assets/7302406/25339094/18b4860c-2934-11e7-9363-0d2de5f4a766.png)
![Uploading 01_DefatulSettings.png…]()
![02_mychange](https://cloud.githubusercontent.com/assets/7302406/25339102/1fe8d23e-2934-11e7-84c2-6d7d7e730fd1.png)
![03_settingsafterapprestart](https://cloud.githubusercontent.com/assets/7302406/25339106/24284e2e-2934-11e7-90b8-b5545c81aef8.png)

**Comment by Beep6581** [comment] 2017-04-24 13:51
I don't recall anyone ever claiming that they are saved between sessions (i.e. this is probably not a bug), but it does make sense that they should be, so I'll tag this as an enhancement.

**Comment by agriggio** [comment] 2017-04-24 13:54
@Beep6581 the code has been reworked significantly when I merged the fast export branch. Now they are saved

**Comment by Beep6581** [comment] 2017-04-24 14:16
@agriggio :+1: and noted :) Then I guess we can close?

**Comment by agriggio** [comment] 2017-04-24 14:17
yes :+1:

**Closed as completed** 2017-04-24 15:05 UTC
Labels: type: enhancement
