### ISSUE TITLE
Multiple Processing Profiles Per Image

### ISSUE THREAD

**Issue by raceviper13** [Beep6581/RawTherapee#3097] opened 2016-01-15 14:37 UTC
I couldn't find any issues out there to have the ability to save/create multiple processing profiles per image and switch between these stored profiles (per image).  Maybe there is a workaround that I don't know of either, but I would like the ability to save a processing profile to an image and the ability to create multiple profiles.  

I'd like something like a menu to create a different profile to begin working with (for that image) and then the ability to then switch between these multiple profiles.  The custom profile builder would also have to know which profile to work with.  That alone may make some of this very difficult to figure out.

I can see some options on how to accomplish the storage of this profile.  I am sure there are many more which would be better options.

1. Storing the alternate profiles as separate sections containing sub-sections which only detail the differences from the primary profile.
--a. In this case, the "Custom Profile Builder" in this case might have to work with the main profile that all of the other profiles are built off of.  I'd personally like this as my builder only adjusts the noise reduction, demosaicing, LCP and other items that wouldn't change between my processing profiles, but that would not be universally true for other users.

2. Storing the alternate profiles as separate sections containing all of the sub-sections and the complete profile for each alternate profile.
--a. In this case, the custom profile builder would have to be able to tell the profile stored in the one PP3 that would be worked on.

3. Storing the alternate profiles as separate PP3 files with a suffix to delineate.
--a. Could this cause issues with backward compatibility unless a different extension was used other than PP3 for the alternate profiles?  Maybe there's just a suffix on the PP3 file before the extension showing the profile?  Maybe can be stored with a name to easily identify these profiles in RT?

**Comment by Beep6581** [comment] 2016-01-15 15:18
Duplicate of #2624

**Closed by Beep6581** 2016-01-15 15:18 UTC
