### ISSUE TITLE
Fuji X-T2 Support - White Frames

### ISSUE THREAD

**Issue by dancat** [Beep6581/RawTherapee#5824] opened 2020-07-02 15:30 UTC
Hi,

I took some sets of white frames for Fuji X-T2 as specified in http://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats#White_Levels

They can be found in https://filebin.net/pd90j4akospyzca4

Let me know if more are needed. 

All the best,
Daniel

**Comment by Thanatomanic** [comment] 2020-07-02 15:32
Thanks!

**Comment by Thanatomanic** [comment] 2020-07-02 17:41
Interestingly, the sensor seems to be slightly non-uniform. Take a look at this:
![image](https://user-images.githubusercontent.com/6567747/86392475-cfc57b00-bc9b-11ea-805e-33175d176e58.png)

This is for DSCF7302.RAF (no LNR). Values scaled to enhance the differences. The actual difference in 14-bit raw values is a mere ~500 away from 2^14.

**Comment by dancat** [comment] 2020-07-02 19:34
Interesting indeed ... 

I read on dpreview some analysis regarding the use of the X-T2 for astrophotography and their finding was that the camera applies some sort of filtering over the raw data, what you see might be caused by this?!? I think the effect was very visible with longer exposures (over 5 seconds)

Another thing that might matter, for this type of cameras is the type of shutter used. In the same analize they found that using the electronic shutter or the continuous shooting mode makes the camera to switch to 10 bit. Should I make for this case another set of whites using the electronic shutter?

**Comment by Thanatomanic** [comment] 2020-07-07 05:37
Possibly related and similar to what you say about what you read on dpreview: https://discuss.pixls.us/t/handling-fujifilm-x-trans-auto-focus-pixels/19047

I'm not sure how to approach this properly...

**Comment by dancat** [comment] 2020-07-07 09:07
I have also took the same frames for the X-T3 and will upload them soon. However, I might have the LENR On files for X-T2 wrong, as the LENR was not applied to all of them. Should I redo them, making sure it does apply?

**Comment by Thanatomanic** [comment] 2020-07-07 10:10
@dancat If you think that you need to redo some shots, please provide a full new set. 

If you're going to redo things, please also pay attention that some low ISO shots were not fully overexposed in all channels (particularly DSCF7290.RAF). You can easily set the shutter speed to 1/10s to compensate. Also, according to the Exif metadata DSCF7309.RAF is ISO12800, DSCF7310.RAF is ISO 200, and DSCF7330.RAF is ISO12800 although your notes mention they should have been ISO25600, ISO100 and ISO25600 respectively. Can you double check that your camera is setting those values properly in the Exif?

**Comment by dancat** [comment] 2020-07-07 10:45
I'll try to be more careful :)

I am using the camera overexposure highlights and take the photos when all the screen blinks. But not being a raw histogram it can be that it is not overexposed completely. Is there a better way to do it?

**Comment by Thanatomanic** [comment] 2020-07-07 10:47
Not really, just be _very_ overexposed. If you do what you did initially, but set shutter speed to 1/10s or even 1/2s you're nearly 100% sure you've overexposed your image.

**Comment by dancat** [comment] 2020-07-07 10:54
OK, In this case I will redo the sets and check also what happens with the extended ISO values.

**Comment by heckflosse** [comment] 2020-07-07 13:27
@Thanatomanic 

> Interestingly, the sensor seems to be slightly non-uniform.

Just a dumb thought: Could that been caused by reflecting light from sensor back to rear element of lens and then back to sensor ?

**Comment by dancat** [comment] 2020-07-08 09:16
I've put the new files here: https://filebin.net/h4441zat3nyf5maa
I took care that:
* for Set1 the exposure was 1/2s from the beginning
* for Set2 the exposure was long enough so I could see that the camera actually made the second exposure to apply LENR

Should I redo also the Set3 for aperture values?

**Comment by dancat** [comment] 2020-07-08 09:28
BTW, I checked also the extend ISO range and the camera is writing it wrong in the EXIF. In Set1 and Set2 the first and last picture are the extended LOW (100 but camera writes 200) and extended High (25600 but the camera writes 12800).

The Fuji X-T3 writes the correct values. I will upload soon also the files for this camera.

**Comment by Thanatomanic** [comment] 2020-07-08 09:51
@dancat Thanks for reuploading and clarifying the ISO values. I've downloaded the images and will inspect them soon.
Please upload the X-T3 files in a separate issue, just to keep it ordered :-)

**Comment by Thanatomanic** [comment] 2020-07-09 13:20
@dancat Similar to your X-T3 samples I determined some useful white levels. Can you test them by finding and replacing the X-T2 data in your `camconst.json` and looking at a few regular and overexposed photos?

```
{ // Quality B
        "make_model": [ "FUJIFILM X-T20", "FUJIFILM X-E3", "FUJIFILM X100F", "FUJIFILM X-PRO2", "FUJIFILM X-H1" ],
        "dcraw_matrix": [ 11434,-4948,-1210,-3746,12042,1903,-666,1479,5235 ], // DNG_v9.4 D65
        // "raw_crop": [ 0, 5, 6032, 4032 ], // full raw 6160,4032, Usable 6032,4032 - for lossless compressed files
        // "raw_crop": [ 0, 0, 6032, 4032 ], // full raw 6160,4032, Usable 6032,4032 - for uncompressed files
        "raw_crop": [ 0, 5, 6032, 4026 ], // full raw 6160,4032, Usable 6032,4026 - for uncompressed and lossless compressed files (but reduces height by 6 pixels)
        "ranges": { "white": 16100 }
    },
    
    { // Quality A, samples provided by Daniel Catalina #5824
        "make_model": "FUJIFILM X-T2",
        "dcraw_matrix": [ 11434,-4948,-1210,-3746,12042,1903,-666,1479,5235 ], // DNG_v9.4 D65
        "raw_crop": [ 0, 5, 6032, 4026 ], // full raw 6160,4032, Usable 6032,4026 - for uncompressed and lossless compressed files (but reduces height by 6 pixels)
        "ranges": {
            "white": [ 16195, 16270, 16195 ] // typical LENR off: 16195, 16270, 16195
        } // With LENR on and ISO4000+ starts to overestimate white level, more realistic would be 16090
        // negligible aperture scaling effect
    },
```

**Comment by dancat** [comment] 2020-07-09 20:11
Sure, I will give it a go the next days and provide feedback.

**Comment by dancat** [comment] 2020-07-11 06:55
I've tested it with some older photos and I did not see anything wrong. I also used the various highlight recovery options and they were fine.

**Comment by Thanatomanic** [comment] 2020-07-11 07:16
Thank you, updated `camconst.json`, closing.

**Closed as completed by Thanatomanic** 2020-07-11 07:16 UTC
Labels: scope: file format
