### ISSUE TITLE
8-bit gamma-encoded files show incorrect color values

### ISSUE THREAD

**Issue by neilpho** [Beep6581/RawTherapee#2943] opened 2015-10-23 08:36 UTC
Rawtherapee shows 100% pixels as 99.6% (255/256).

If would be great if, like Capture One, the actual numeric value of the pixel could be displayed. >255 for files >8 bit.

**Comment by Beep6581** [comment] 2015-10-23 09:34
1- Supply a test case so we can reproduce this 99.6% issue.
2- Explain why that would be useful.

**Comment by neilpho** [comment] 2015-10-23 12:17
1) ![dsc03314_1_2](https://cloud.githubusercontent.com/assets/13761122/10692242/fb2546ba-7987-11e5-98e9-1fd416ffe7dc.jpg)

2) You are providing more accurate information with fewer characters. It would have been easier to track down this bug if one saw that the value never reached the correct limit. You match Gimp and Capture One, both highly respected.

**Comment by Beep6581** [comment] 2015-10-23 14:53
Test image:
http://rawtherapee.com/shared/test_images/8_bit_integer_gamma.png

**Comment by neilpho** [comment] 2015-10-23 21:59
It also occurs to me that the use of % for pixel value in the display is at odds with the use of actual integer values for the clipping indication thresholds in the general settings.

What happens for files that are >8 bit? Are the clipping values scaled in some way?

**Comment by Thanatomanic** [comment] 2018-11-23 22:01
Cannot reproduce with the test image provided. Closing.

**Closed by Thanatomanic** 2018-11-23 22:01 UTC
