### ISSUE TITLE
Please consider implementing a better way to preview and scroll through presets

### ISSUE THREAD

**Issue by Noexpert** [Beep6581/RawTherapee#7082] opened 2024-05-19 19:54 UTC
Assuming a user has presets organised by folder, then to select a preset involves several clicks.
See attached screenshot.
<img width="481" alt="Presets" src="https://github.com/Beep6581/RawTherapee/assets/10177518/896eba09-4b9c-4e84-8232-eaeb57eaf143">

The issue is that this process needs to be repeated every time a preset is selected.
It can be quite inefficient, having to select through several sub-menus.

It would be helpful if a more efficient way could be implemented, perhaps by just scrolling through the presets with the keyboard, without having to start the whole selection process from the start.

As a preset is selected, it should be applied, so the user can instantly see the effect.

Thanks

**Comment by Lawrence37** [comment] 2024-05-19 20:17
Duplicate of #2903 and #3043.

**Closed as not planned by Lawrence37** 2024-05-19 20:17 UTC
