### ISSUE TITLE
Save as floating-point TIFF

### ISSUE THREAD

**Issue by snibgo** [Beep6581/RawTherapee#4190] opened 2017-11-19 19:57 UTC
Although RT works in floating-point, it can't save to TIFF as floating-point. Are there plans to add this? It would seem a simple addition (though I could be wrong).

I'm not so concerned by the greater precision from floating-point (though that would be nice), but with out-of-gamut results. Then I could do my own processing after RT to deal with OOG, with Gimp or ImageMagick or my own software.

(My apologies if this is a FAQ. I couldn't see it anywhere.)

**Comment by Beep6581** [comment] 2017-11-20 10:52
Duplicate of #2357

**Closed as completed by Beep6581** 2017-11-20 10:52 UTC
