### ISSUE TITLE
Canon EOS 80D mRAW CR2 file displayed corrupt (in shifted stripes)

### ISSUE THREAD

**Issue by SarenT** [Beep6581/RawTherapee#4439] opened 2018-03-13 18:57 UTC
On Ubuntu 16.04 LTS 64-bit
19,3 GiB memory
Intel® Core™ i5-5200U CPU @ 2.20GHz × 4 
Intel® HD Graphics 5500 (Broadwell GT2) 

Downloaded from PPA repo's unstable branch.
Version: 
Branch: 
Commit: 
Commit date: 
Compiler: x86_64-linux-gnu-gcc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.2.8.0
Build type: Release
Build flags: -std=c++11 -O3 -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

I copied RAW file from the SD card or captured with gphoto2 (which automatically downloads). In both cases after opening it with RawTherapee (hereafter RT), the Canon (80D) raw file looks in shifted stripes.
https://imgur.com/a/VSGeh
RAW+PP3: https://filebin.net/5u8dybewbybu0f3i

**Comment by Floessie** [comment] 2018-03-13 19:11
Are you shooting mRAW? AFAIK, this isn't supported by RT (and not a good idea after all).

**Comment by Beep6581** [comment] 2018-03-13 20:01
Yes, it's an mRAW.
Duplicate of #3533

**Closed as completed by Beep6581** 2018-03-13 20:01 UTC
Labels: scope: file format

**Comment by SarenT** [comment] 2018-03-13 20:05
Yes, sorry. I didn't realize that mRAW is so much different.I assumed it to be a smaller version (resolutionwise) compared to RAW.
