### ISSUE TITLE
Thumbnail images in the Queue tab are displaying corrupted.

### ISSUE THREAD

**Issue by waxhead** [Beep6581/RawTherapee#3932] opened 2017-06-18 06:29 UTC
Not sure if this is reproducible, however I have been seeing this in my Queue tab for some time now.  Typically the first image of the display is corrupted, however this screen shots all three are this way.

![screenshot from 2017-06-18 16-22-23](https://user-images.githubusercontent.com/8608051/27258649-1b788566-5443-11e7-9094-fecd725a4d3a.png)

**Comment by heckflosse** [comment] 2017-06-18 10:41
@waxhead Duplicate of #3685 
Can you please post the content of your AboutThisBuild.txt?
Edit: In #3922 I could see that you're using Gtkmm: V3.18.0
I had the same with 3.18. Now I'm using 3.22 and the bug is gone.

**Comment by waxhead** [comment] 2017-06-18 11:31
Hi @heckflosse, for completeness, but it does appear you've worked it out.

Not sure I can upgrade GTK as I'm running Ubuntu Gnome and locked in with their update cycle.

Version: 5.1-75-g480d131
Branch: dev
Commit: 480d131
Commit date: 2017-06-18
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by waxhead** [comment] 2017-06-18 11:31
Oh, if you think it's a gtk issue then happy for this to be closed.

**Comment by heckflosse** [comment] 2017-06-18 12:23
Ok, I will close it.

**Closed as completed by heckflosse** 2017-06-18 12:23 UTC
