### ISSUE TITLE
RT crashes when using wavelet on completely overexposed image

### ISSUE THREAD

**Issue by mks9900** [Beep6581/RawTherapee#2971] opened 2015-11-10 17:07 UTC
RT compiled in debug mode, and upon opening of this file: https://drive.google.com/file/d/0B7pUaGeFwBEoZGFfYXlMeEFTTlk/view?usp=sharing

RT crashes and here's the backtrace:
http://pastebin.com/d9zm1mcw

Using RT 4.2.468, master branch.

BR,
Johan

**Comment by heckflosse** [comment] 2015-11-10 17:14
Johan, at my system it crashes only if I enable wavelet, not if I open it with 'Default' or 'Neutral' profile.

**Comment by mks9900** [comment] 2015-11-10 17:50
Ingo, you're (of course) quite right! Didn't remember that my profile had wavelets enabled...
Can I give any further information to help?

**Comment by heckflosse** [comment] 2015-11-10 18:04
Johan, no. The crash is reproducible, so it should be possible to find the reason :)

**Comment by heckflosse** [comment] 2015-11-11 13:36
I pushed a fix to waveletcrashfix branch.
@Desmis Jacques, can you please take a look at my changes before I merge into master?

Ingo

**Comment by Desmis** [comment] 2015-11-11 16:25
Ingo
I look at your changes and also I tested...
No problem, all works fine !

again you have corrected my mistakes  :)

**Comment by heckflosse** [comment] 2015-11-11 16:45
Jacques, thanks for testing :)

**Closed** 2015-11-11 16:46 UTC
