### ISSUE TITLE
HiDPI scaling problems

### ISSUE THREAD

**Issue by dsiroky** [Beep6581/RawTherapee#3774] opened 2017-03-24 09:31 UTC
Ubuntu 16.04, rawtherapee 4.3+git20170217-252~ubuntu16.04.1 (from http://ppa.launchpad.net/dhor/myway/ubuntu/pool/main/r/rawtherapee-unstable/)

I have a 4K monitor with environment variables GDK_SCALE=2 and GDK_DPI_SCALE=0.5. After last rawtherapee update the main canvas/preview area is scaled as well and thus the picture is always blurred. It does not utilize the full 4K resolution. When I remove GDK_SCALE and GDK_DPI_SCALE then i can see sharp "pixels" again.

Another problem is with browser. Thumbnails are broken - strange artefacts and no text: 
![screenshot_2017-03-24_10-30-02](https://cloud.githubusercontent.com/assets/1227818/24288274/03ea1464-107d-11e7-9172-d7517ad6c722.png)

**Comment by Beep6581** [comment] 2017-03-24 11:15
Duplicate of #3547

**Closed as completed by Beep6581** 2017-03-24 11:15 UTC
