### ISSUE TITLE
Local adjustments CIECAM-Model Mask is declared as „ZCAM“

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6500] opened 2022-06-11 08:34 UTC
May be i am totally misunderstanding this function….

Using the CIECAM module in local adjustments, you can activate and  use the mask as in each tool of LA.
But:
any change here is shown as a ZCAM-function in the history. 
The C-curve shows up as ZCAM brightness, 
The L-Curve  shows up as ZCAM contrast J
The LC(h)-curve shows up as  ZCAM contrast Q
The contrast-curve shows up as ZCAM chroma

Is ZCAM used as a mask here? If so, are the designations really correct 
If not, where to find the meaned ZCAM functions?

Version: 5.8-3096-gf86a45528
Branch: dev
Commit: f86a45528
Commit date: 2022-06-10
Compiler: cc 12.1.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.6
Lensfun: V0.3.3.0
Build type: release
Build flags:  -std=c++11 -fno-tree-loop-vectorize -mtune=generic -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-20348 3.3.5-341.x86_64 x86_64
Build date: Fri, 10 Jun 2022 16:57:11 +0000 UTC
Build epoch: 1654880231
Build UUID: 533d5020-e1f8-46d6-9873-366a2b41db0a

**Comment by Lawrence37** [comment] 2022-06-11 15:29
It's a bug: https://github.com/Beep6581/RawTherapee/pull/6458#issuecomment-1099158885

**Comment by marter001** [comment] 2022-06-12 06:15
uups, its only two month and i already had forgotten that thread :-(

**Comment by Desmis** [comment] 2022-06-12 09:06
@Lawrence37 @marter001 @Entropy512 

I will push a small change to the history message with "ZCAM" , it is only a problem with /* */

Of course #6458 will have to take this into account, but this bug was annoying

Jacques

**Comment by Desmis** [comment] 2022-06-12 09:10
Done with commit 404a584

Jacques

**Comment by marter001** [comment] 2022-06-12 09:23
great, thanks a lot! :-)

**Comment by Entropy512** [comment] 2022-06-12 11:11
OK, I'll remove the duplicate of this from mine later today.

**Closed as completed** 2022-06-12 15:48 UTC
