### ISSUE TITLE
Pictures are scaled on Wayland

### ISSUE THREAD

**Issue by diethardsteiner** [Beep6581/RawTherapee#3857] opened 2017-05-03 15:38 UTC
version: 5.0-r1-gtk3
source: from github
OS: Fedora 25

When I open a picture in RawTherapee it is scaled (a rough guess: scaled 2x). This might be in line with the issue explained [here](https://github.com/gnumdk/lollypop/issues/582).
Attached a screenshot which compares UFRaw's presentation of the same picture. Both pictures are shown at original size (100%).
![screenshot from 2017-05-03 16-14-23](https://cloud.githubusercontent.com/assets/1726057/25668555/ebe22566-301e-11e7-976f-d0b754778a9a.png)

**Comment by TooWaBoo** [comment] 2017-05-03 16:03
Are you using a hires monitor? The are some issues with RT and hires monitors.

**Comment by diethardsteiner** [comment] 2017-05-03 17:08
Yes, I am using a Dell XPS with a QHD+ display. It might be a problem with RT's high res display support (I thought this first as well), but I thought it is worth motioning the scaling differences with Wayland as well (as highlighted in the referenced ticket)

**Comment by Beep6581** [comment] 2017-05-03 17:39
Duplicate of #3547

**Closed as completed by Beep6581** 2017-05-03 17:39 UTC
