### ISSUE TITLE
gtk3: Compatibility problems with Ubuntu 16.10

### ISSUE THREAD

**Issue by dnw3039** [Beep6581/RawTherapee#3493] opened 2016-11-01 21:32 UTC
I have just done a fresh install of Ubuntu 16.10, and used git to download download of the gtk3 repository branch. it compiles without error.

However when I one an image open the tool options have very wide spaces between them and using the curve tools leave artifices of the moved cure on the screen.

 The console messages are many but of this type:

> (rawtherapee:23873): Gtk-WARNING **: Theme parsing error: TooWaBlue.css:876:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.
> 
> (rawtherapee:23873): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
> 

The same errors occur with the default rawtherapee theme.

See screen print: https://goo.gl/photos/h9vZ28YV3jHg9hR87

Branch: gtk3
Version: 4.2.1350
Changeset: b76611042763aadbe5730044aeedf6a2e30476b7
Compiler: cc 6.2.0
Processor: core2
System: Linux
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags:  -std=gnu++11 -march=core2 -Werror=unused-label -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -march=core2
OpenMP support: ON
MMAP support: ON

**Comment by Hombre57** [comment] 2016-11-02 01:17
@dnw3039 I hope you'll be able to update Gtk3 to v.3.22.x, since we've spent a lot of time to make RT compatible with this version and fix a lot of bugs. At least you should update to v3.18.

**Comment by Beep6581** [comment] 2016-11-02 07:52
Duplicate of #3446

**Closed by Beep6581** 2016-11-02 07:52 UTC

**Comment by Beep6581** [comment] 2016-11-02 07:54
By the way, your AboutThisBuild shows "Gtkmm: V3.16.0" but Ubuntu 16.10 uses Gtk+ 3.20.9. How is that possible?

**Comment by dnw3039** [comment] 2016-11-02 10:12
The Gtkmm: V3.16.0 must have been some left over from some previous version. I did a completely new checkout from git (I should have done this first)  now I have:

**Gtkmm: V3.20.1**

I have tried  the gtk3-bugfix branch and all is working properly again

 The lesson for me is to do a full new repository checkout with new versions of the software and read more about the various branches.

**Comment by Beep6581** [comment] 2016-11-02 10:20
I'm not sure what you mean by "full new repository checkout". If you mean "clone", then you don't have to. The key here was probably just to delete the "build" folder, or cmake and compile into a different build folder - "build-master", "build-gtk3", "build-gtk3-bugfix", etc.. I always do that when switching significantly-differing branches, otherwise trouble arises.
