### ISSUE TITLE
Canon CR2 input not working

### ISSUE THREAD

**Issue by Tibor-GH** [Beep6581/RawTherapee#4517] opened 2018-04-21 21:38 UTC
My computer, Win7-64, i5, 16G RAM.
I testing RawT W64 5.4, 5.3, 5.1, 4.1,
Just load Canon CR2 file, AffinityPhoto & Faststone view correct, but RawT not.
Tibor Kiraly

![2018-04-21_231008 raw-therapee_5 4_w64](https://user-images.githubusercontent.com/38594494/39088970-7ef398ae-45bc-11e8-8a8c-6954ca60db15.png)

**Comment by heckflosse** [comment] 2018-04-21 22:12
Looks like a Canon Mraw/Sraw file. Though without having access to the 'raw/or not raw' file we still have to guess...

**Comment by Tibor-GH** [comment] 2018-04-22 22:28
Yes I shot Canon M-Raw. I can send original raw file, 25 MB.

**Comment by Beep6581** [comment] 2018-04-23 09:26
Duplicate of #3533

**Closed as completed by Beep6581** 2018-04-23 09:26 UTC
Labels: scope: file format

**Comment by Tibor-GH** [comment] 2018-04-24 04:50
Thank you.

Tibor

2018-04-23 11:27 GMT+02:00 Beep6581 <notifications@github.com>:
