### ISSUE TITLE
Weird behavior of Auto white balance (Canon 7D Mark II)

### ISSUE THREAD

**Issue by fliker09** [Beep6581/RawTherapee#3355] opened 2016-06-21 11:55 UTC
Branch: master
Version: 4.3+git20160612-324~ubuntu16.04.1
Changeset: daily
Compiler: x86_64-linux-gnu-gcc 5.3.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -std=c++11 -O3 -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:  
OpenMP support: ON
MMAP support: ON

Source file: https://filebin.net/dywoqsmtxp72pmp9/C34A3915.CR2

Auto WB:
![autowb](https://cloud.githubusercontent.com/assets/18057950/16228409/82c54782-37bf-11e6-9843-f17d821611dd.png)

Camera WB:
![camerawb](https://cloud.githubusercontent.com/assets/18057950/16228410/82ca156e-37bf-11e6-829e-82d745a20cfd.png)

Is it a bug or I am doing something wrong?

**Comment by TooWaBoo** [comment] 2016-06-21 16:42
You don't do anything wrong. This happens when the image has clipped highlights.

**Comment by heckflosse** [comment] 2016-06-21 16:50
Maybe we should lower [this constant](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/rawimagesource.cc#L4644)?
@iliasg what do you think?

**Comment by TooWaBoo** [comment] 2016-06-21 16:55
Auto-WB with clipped highlights sets the wrong tint. I always set tint back to its initial value with a little bit of fine tuning..

**Comment by fliker09** [comment] 2016-06-22 09:23
Very strange... This image is one from a HDR stack. I am using RawTherapee from terminal, in an automated way. Till now this problem appeared only once... Many other stacks worked fine. Now it got out of hands, after switching to Git version instead of repo one (Ubuntu 16.04). Did you change something in White Balance processing?

**Comment by Beep6581** [comment] 2016-06-22 09:40
You should not be using auto white balance on a HDR stack.

> after switching to Git version

Which version did you use before?
Did you try to reproduce the problem in photos you processed in that older version?

**Comment by iliasg** [comment] 2016-06-22 13:34
> Maybe we should lower this constant?
> @iliasg what do you think?
May be .. and also exclude very dark areas and if possible corners which usually distort average level and especially when the image circle is smaller than the frame's diagonal.
I have only an hour available now and no time for the next days .. but a raw sample of this HDR stack mode would help .. maybe the black/white Levels are different for this mode than our camconst.json constants :(

**Comment by fliker09** [comment] 2016-06-22 13:43
Here you go (rest of the files, one I already gave you):
https://filebin.net/ylte3thrqk52wirk/C34A3912.CR2
https://filebin.net/ylte3thrqk52wirk/C34A3913.CR2
https://filebin.net/ylte3thrqk52wirk/C34A3914.CR2
https://filebin.net/ylte3thrqk52wirk/C34A3916.CR2
https://filebin.net/ylte3thrqk52wirk/C34A3917.CR2
https://filebin.net/ylte3thrqk52wirk/C34A3918.CR2

**Comment by fliker09** [comment] 2016-06-29 11:58
Any progress so far? Will there be any improvements for fish-eye photos as you mentioned?

**Comment by fliker09** [comment] 2016-07-19 13:09
Same problem detected with Nikon D7100. Yes, again fish-eye. Is there any hope for improvement?

**Comment by fliker09** [comment] 2016-09-01 12:30
One more time, desperate one, is there any hope? :\

**Comment by heckflosse** [comment] 2016-09-01 19:09
@fliker09 I'll try to solve this now

**Comment by heckflosse** [comment] 2016-09-01 19:16
@fliker09 Can you upload your raw file again please. Link seems to be expired. Thanks in advance.

Ingo

**Comment by Beep6581** [comment] 2016-09-02 05:43
https://filebin.net/canon7dmkii

**Comment by iliasg** [comment] 2016-09-02 09:40
@heckflosse Ingo, I checked the files .. everything is normal regarding raw Black/White Levels.

Iliah Borg says that at least for Canon models there is a possible issue  with values at the top 1/3 stop (non linear, so unreliable for WB calculations) .. there exists a related tag in exif:maker notes named by exitool as "linearityUpperMargin" which is usually set at 10000 (14bit). 

The other issue is for very low values where the read noise (electronic noise added on signal) distorts WB because read noise (WB = 1,1,1,1) is dominant there. My opinion is that we should exclude values lower than stdev of black area or maybe lower than 2X stdev. The problem is that read noise (i.e stdev of black frame) varies alot among various models and also varies alot depending on ISO.
 For Canons we can calculate black_stdev from the optically black area (the area from where Dcraw/RT calculate BlackLevel), but other brands give no optically black data.

For referense .. 7DII's at ISO100 stdev is around 5, for the other model mentioned (Nikon D7100) is around 2 (14bit) .. the lowest I know is for Nikon D7200 around 1 (14bit)

**Comment by barretina** [comment] 2016-12-15 21:27
Hello,

On Nikon D7200:
- histogram appears very "compressed" at the center, leaving wide flat areas at both sides. When adjusted automatically this changes to a histogram covering (nearly) all the width.
- White balance adjustment is awful, either if the "Camera" option is selected, or the "Auto", or the "Pick 
white area" option.

I used to have a Nikon D80 camera which worked very well with RawTherapee; now I've moved to D7200 and can't use it any more.
Oh I'm on linux Ubuntu 16.04 LTS installed on a laptop computer.

Attached: screenshots of the process (RAW file too large to upload)

Hope you can fix it soon...

Thank you very much
![1 - as opened - compressed histogram magenta hue camera wb](https://cloud.githubusercontent.com/assets/24595499/21242591/60cab4aa-c315-11e6-8f21-fd8a38ae8874.png)
![2 - after automatic levels](https://cloud.githubusercontent.com/assets/24595499/21242592/60d61764-c315-11e6-8917-1748f79a04b7.png)
![3 - after auto wb](https://cloud.githubusercontent.com/assets/24595499/21242593/60d889b8-c315-11e6-8df2-27529b7766a4.png)

**Comment by TooWaBoo** [comment] 2016-12-15 21:37
@barretina 

My guess, wrong camara input profile selectet or wrong settings.

**Comment by barretina** [comment] 2016-12-15 21:41
TooWaBoo you're probably right. Similar thing happens with UFRaw and it displays a warning: "White balance configuration not available for your camera model"...

**Comment by heckflosse** [comment] 2016-12-15 21:44
@barretina I guess rt 4.2.0 simply is too old to support Nikon D7200 correctly...

**Comment by Beep6581** [comment] 2016-12-16 09:19
@barretina Support for the Nikon D7200 was added on 2015-04-28 in commit 34a419a6caca30d219a90fcfcbe8b85956f6b4b1. RawTherapee 4.2.0 is from 2014-10-24.

**Comment by barretina** [comment] 2016-12-17 21:18
Thanks all and sorry for the delay. Just updated the rawtherapee version. 
It's much better (even if not perfect yet, maybe the profile needs further fine tuning).
Thank you anyway!
Cheers

![sky should be bright blue](https://cloud.githubusercontent.com/assets/24595499/21289819/b51feed4-c4a6-11e6-87b3-9f526b56773b.png)

**Comment by heckflosse** [comment] 2016-12-17 21:29
@barretina That's a screen shot from rt 4.2.0, not from current rt...

**Comment by barretina** [comment] 2016-12-18 15:53
@heckflosse You are right... I updated to the latest stable version according to 
http://rawtherapee.com/downloads:
"To install RawTherapee follow these simple steps:

    Open the terminal
    Paste this code into it:

    sudo add-apt-repository ppa:dhor/myway
    sudo apt-get update
    sudo apt-get install rawtherapee"
I'm using Ubuntu linux. 
I did it again and it said "rawtherapee is already the newest version (4.2-4)."
So it looks like the latest stable version is 4.2.0... (or 4.2.4?)

I have now updated to the development version:
"If you want a development version:

sudo apt-get install rawtherapee-unstable"

I usually do not install development versions, but it seems it have solved the issue:
![captura de 2016-12-18 16-48-57](https://cloud.githubusercontent.com/assets/24595499/21294646/04e3f078-c542-11e6-95e3-5d522f4a8b58.png)

Then it looks like the problem's solved. 
THANK YOU ALL!!

Marçal

**Comment by Beep6581** [comment] 2020-02-28 16:05
Closing as the link to the raw file has expired and the new Auto-ITC white balance algo probably handles this better.

**Closed by Beep6581** 2020-02-28 16:05 UTC
