### ISSUE TITLE
HDR Tonemapping triggers histogram matching each time an adjuster is changed

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#4350] opened 2018-02-01 12:03 UTC
If histogram matching is enabled, each time I change an adjuster in HDR tonemapping, the histogram matching is called. Is that intentional?

Edit: histogram matching is also triggered when I enable/disable vignetting correction, shadows/highlights and so on.

**Comment by Beep6581** [comment] 2018-02-01 12:20
I thought "Auto-matched Tone Curve" was a one-off button, not an enable/disabled thing. If it can remain enabled after being clicked then it should be a checkbox.

**Comment by Beep6581** [comment] 2018-02-01 12:22
I tested using branch `local-contrast-in-detail` and haven't observed the curve changing shape using the tools mentioned above. Haven't tested couting the code to see whether the function is called.

**Comment by heckflosse** [comment] 2018-02-01 12:27
@Beep6581 
It's easy to test using a D800 file, where histogram matching takes some time...

This patch fixes it:

```diff
diff --git a/rtgui/tonecurve.cc b/rtgui/tonecurve.cc
index 07822f85..25c6e2bf 100644
--- a/rtgui/tonecurve.cc
+++ b/rtgui/tonecurve.cc
@@ -961,7 +961,7 @@ bool ToneCurve::histmatchingComputed()
     shape->setCurve(nextToneCurve);
     shape2->setCurve({ DCT_Linear });
     shape->openIfNonlinear();
-
+    histmatching->set_active(false);
     enableListener();
 
     return false;

```

**Comment by agriggio** [comment] 2018-02-01 12:31
@heckflosse that was the old behaviour, which I changed intentionally. rationale: if you copy settings from one pic to another, you want to cppy "use histogram matching", and not "use the curve"

Besides, the curve is cached so recomputing should take essentially no time as long as the picture is in the editor. 

> If it can remain enabled after being clicked then it should be a checkbox.

that would be easy to do, if you like this better.

**Comment by heckflosse** [comment] 2018-02-01 12:39
@agriggio Then the cache seems not to work.

Open a D800 file
apply neutral profile
enable auto-matching
enable fattal
change anchor, takes 2 seconds
change anchor again, takes 2 seconds

and it's clearly auto matching
```
getAutoMatchedToneCurve took 2018 ms
```

**Comment by agriggio** [comment] 2018-02-01 12:43
@heckflosse more details please -- it works here (tried with a D850 file, but I don't think that's the culprit...)

```
Loading Nikon D850 image from /home/alb/Downloads/DSC_0804.NEF...
constants exists for "Nikon D850" in camconst.json
black levels: R:400 G1:400 B:400 G2:400 (provided by camconst.json)
white levels: R:16250 G1:16050 B:16250 G2:16050 (provided by camconst.json)
raw crop: 0 0 8288 5520 (provided by dcraw)
color matrix provided by camconst.json
cam_mul:[1.867676 1.000000 1.495605 0.000000], AsShotNeutral:[0.535425 1.000000 0.668626 0.000000]
pre_mul:[1.000000 0.528835 0.800784 0.528835], scale_mul:[4.134700 2.214518 3.311003 2.214518], cblack:[400.000000 400.000000 400.000000 400.000000]
rgb_cam:[ [ 1.400913 -0.124925 0.008026], [-0.312968 1.412522 -0.407745], [-0.087944 -0.287597 1.399719] ]
cam_mul:[1.867676 1.000000 1.495605 0.000000], AsShotNeutral:[0.535425 1.000000 0.668626 0.000000]
pre_mul:[1.000000 0.508531 0.785219 0.508531], scale_mul:[4.134700 2.129494 3.246646 2.129494], cblack:[400.000000 400.000000 400.000000 400.000000]
rgb_cam:[ [ 1.400913 -0.124925 0.008026], [-0.312968 1.412522 -0.407745], [-0.087944 -0.287597 1.399719] ]
Raw As Shot White balance: temp 4969.242096, tint 1.009229
Raw Reference (auto) white balance: temp 5014.766693, tint 0.957547, multipliers [2.231647 1.934952 1.375450 | 2.104476 1.513634 1.864163]
Load /home/alb/Downloads/DSC_0804.NEF: 1174576 usec
freeall starts 1
freeallcrop starts 1
setscale before lock
setscale starts (828, 552)
freeall starts 0
setscale ends
setscale ends2
LENSFUN:
  camera: AEE DV AEE DV
  lens: ---
  correction: NONE
Nikon D850 3000026.badpixels not found
Nikon D850.badpixels not found
Preprocessing: 176453 usec
Demosaic Bayer image n.1 using method: fast
Demosaicing Bayer data: fast - 361663 usec
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (828, 552)
setscale ends
setscale ends2
Can't load DCP profile '(cameraICC)'!
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=0
setcropsizes before lock
setsizes starts (1380, 919, -1, -1, 1380, 919)
setsizes ends
Can't load DCP profile '(cameraICC)'!
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
Can't load DCP profile '(cameraICC)'!
LENSFUN:
  camera: AEE DV AEE DV
  lens: ---
  correction: NONE
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (828, 552)
setscale ends
setscale ends2
Can't load DCP profile '(cameraICC)'!
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=0
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
Can't load DCP profile '(cameraICC)'!
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (828, 552)
setscale ends
setscale ends2
performing histogram matching for /home/alb/Downloads/DSC_0804.NEF on the embedded thumbnail
histogram matching: full raw image size is 8280x5512
histogram matching: extracted embedded thumbnail
Loading Nikon D850 image from /home/alb/Downloads/DSC_0804.NEF...
constants exists for "Nikon D850" in camconst.json
black levels: R:400 G1:400 B:400 G2:400 (provided by camconst.json)
white levels: R:16250 G1:16050 B:16250 G2:16050 (provided by camconst.json)
raw crop: 0 0 8288 5520 (provided by dcraw)
color matrix provided by camconst.json
cam_mul:[1.867676 1.000000 1.495605 0.000000], AsShotNeutral:[0.535425 1.000000 0.668626 0.000000]
pre_mul:[1.000000 0.528835 0.800784 0.528835], scale_mul:[4.134700 2.214518 3.311003 2.214518], cblack:[400.000000 400.000000 400.000000 400.000000]
rgb_cam:[ [ 1.400913 -0.124925 0.008026], [-0.312968 1.412522 -0.407745], [-0.087944 -0.287597 1.399719] ]
histogram matching: generated neutral rendering
histogram matching: generated curve with 7 control points
Can't load DCP profile '(camera)'!
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=1
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
Can't load DCP profile '(camera)'!
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (828, 552)
setscale ends
setscale ends2
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
performing histogram matching for /home/alb/Downloads/DSC_0804.NEF on the embedded thumbnail
tone curve found in cache
Can't load DCP profile '(camera)'!
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=0
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
Can't load DCP profile '(camera)'!
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (828, 552)
setscale ends
setscale ends2
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
performing histogram matching for /home/alb/Downloads/DSC_0804.NEF on the embedded thumbnail
tone curve found in cache
Can't load DCP profile '(camera)'!
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=1
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
Can't load DCP profile '(camera)'!
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
Applying white balance, color correction & sRBG conversion...
setscale before lock
setscale starts (828, 552)
setscale ends
setscale ends2
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
performing histogram matching for /home/alb/Downloads/DSC_0804.NEF on the embedded thumbnail
tone curve found in cache
Can't load DCP profile '(camera)'!
ImProcCoordinator / Auto CT:  indi=1   satH=0  satPR=0
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
setcropsizes before lock
setsizes starts (1380, 919, 1380, 919, 1380, 919)
setsizes ends
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
Can't load DCP profile '(camera)'!
ToneMapFattal02: alpha = 1, beta = 0.91, detail_level = 3
freeallcrop starts 1
freeall starts 1
```

**Comment by heckflosse** [comment] 2018-02-01 12:46
@agriggio Now it works here too, though I didn't change anything. Strange... Searching

**Comment by agriggio** [comment] 2018-02-01 12:46
@heckflosse can you share the file?

**Comment by heckflosse** [comment] 2018-02-01 12:47
@agriggio Found it. Maybe better to pick the curve from cache even when not in verbose mode.....

**Comment by agriggio** [comment] 2018-02-01 12:48
@heckflosse oh man :sob: 
what a stupid mistake...

**Comment by agriggio** [comment] 2018-02-01 12:48
I'll push immediately

**Comment by heckflosse** [comment] 2018-02-01 12:48
ok

**Comment by agriggio** [comment] 2018-02-01 12:49
@Beep6581 @heckflosse should I also use a checkbox instead of a toggle button? (in a separate commit, in case)

**Comment by heckflosse** [comment] 2018-02-01 12:50
👍 for checkbox

**Comment by agriggio** [comment] 2018-02-01 12:52
shouldn't "auto-levels" be a checkbox too then? I used a toggle for consistency...

**Comment by Beep6581** [comment] 2018-02-01 12:56
Playing around with CSS I see that Auto Levels is also a persistent-state (toggle) button. So let's keep it as a button (else we'd have to change all toggle-buttons) and instead improve the CSS theme.

I updated both RawTherapee GTK themes, but I can only test `rtdata/themes/RawTherapee-GTK3-20_.css` and guessed at `rtdata/themes/RawTherapee-GTK3-_19.css`.
IIRC @agriggio you still use GTK+ <=3.18 - could you test `_19.css` please?

If there is a problem, it should complain in the console.

Branch https://github.com/Beep6581/RawTherapee/tree/btncss

**Comment by heckflosse** [comment] 2018-02-01 12:57
@Beep6581 👍

**Comment by agriggio** [comment] 2018-02-01 12:59
@Beep6581 works fine also on 3.18 :+1:

**Comment by Beep6581** [comment] 2018-02-01 13:01
It should look like this:
![screenshot_20180201_135923](https://user-images.githubusercontent.com/5844619/35679684-4828195a-0758-11e8-83c0-5cb292f308f1.png)
![screenshot_20180201_135933](https://user-images.githubusercontent.com/5844619/35679685-484b4f74-0758-11e8-836e-de967eeba1af.png)

Note that only the auto-levels and histogram-matching buttons are affected, and the flip-horizontal/vertical, curve adjustment points, node in/out, and other buttons should not be affected.

**Comment by agriggio** [comment] 2018-02-01 13:02
I confirm that it looks like that for auto-matching. I didn't test the others though

**Comment by Beep6581** [comment] 2018-02-01 13:02
Thanks, merging.

**Comment by agriggio** [comment] 2018-02-01 14:25
@Beep6581 sorry, I just noticed a regression in the GTK theme right now:
![screenshot from 2018-02-01 15 24 14](https://user-images.githubusercontent.com/11982086/35683407-107cfb9a-0764-11e8-8bf5-db9c252287e7.jpeg)

**Comment by agriggio** [comment] 2018-02-01 14:46
Here's a patch:

```diff
diff --git a/rtdata/themes/RawTherapee-GTK3-_19.css b/rtdata/themes/RawTherapee-GTK3-_19.css
--- a/rtdata/themes/RawTherapee-GTK3-_19.css
+++ b/rtdata/themes/RawTherapee-GTK3-_19.css
@@ -514,3 +514,11 @@
 GtkButton.text-button:checked {
     background-image: linear-gradient(to bottom, rgba(30,30,30,.3), rgba(0,0,0,.4));
 }
+
+GtkCheckButton.text-button {
+    background-image: none;
+}
+
+GtkCheckButton.text-button:checked {
+    background-image: none;
+}
```

**Comment by Beep6581** [comment] 2018-02-01 15:14
@agriggio could you show a screenshot without this?
```css
GtkButton.text-button {
    background-image: linear-gradient(to bottom, rgba(100,100,100,.3), rgba(30,30,30,.3));
}

GtkButton.text-button:checked {
    background-image: linear-gradient(to bottom, rgba(30,30,30,.3), rgba(0,0,0,.4));
}
```

**Comment by Beep6581** [comment] 2018-02-01 15:31
It's better to avoid the problem in the first place than to deal with the side-effects. I think this patch should prevent the problem:
https://github.com/Beep6581/RawTherapee/compare/togglebtncss

We were also missing `:hover` animation - added in this branch.

**Comment by agriggio** [comment] 2018-02-01 15:41
@Beep6581 here are a few screenshots:

- old look
![old](https://user-images.githubusercontent.com/11982086/35687263-86c56026-076e-11e8-9c85-ac5b9ceb052a.jpeg)

- current (broken) look
![new](https://user-images.githubusercontent.com/11982086/35687268-8d906da6-076e-11e8-9bb1-f7523538938e.jpeg)

- my patch/pr
![patched](https://user-images.githubusercontent.com/11982086/35687281-93f8e9d4-076e-11e8-9816-b627c09d0434.jpeg)

- your patch
![drslony](https://user-images.githubusercontent.com/11982086/35687291-9b0c81ea-076e-11e8-9f96-890f856edcf4.jpeg)

It seems to me that yours is no different than the old look, or am I looking at the wrong widgets?

**Comment by Beep6581** [comment] 2018-02-01 16:25
@agriggio yes it seems like my patch isn't matching the widgets anymore. Could you please try this and send me a screenshot? Show the Exposure tool and set Auto Levels = off and histmatch=on.
https://filebin.net/1wsl1s8aur5bq2eo/RawTherapee-GTK3-_19.css

P.S. bee52d74 works fine in gtk+ 3.22.19, and the buttons animate when hovering in both on and off states:
![screenshot_20180201_172737](https://user-images.githubusercontent.com/5844619/35690082-43096ea2-0775-11e8-94e2-82d50b1ab77a.png)
![screenshot_20180201_172755](https://user-images.githubusercontent.com/5844619/35690084-432b751a-0775-11e8-8f50-cc25a9b9d8a3.png)

**Comment by agriggio** [comment] 2018-02-01 16:30
@Beep6581 here you go. Auto Levels off, histmatch on
![theme](https://user-images.githubusercontent.com/11982086/35690179-862c9be6-0775-11e8-9e14-2e98bfe682d3.jpeg)

**Comment by Beep6581** [comment] 2018-02-01 16:47
@agriggio ok, that implies that those toggle buttons don't have the `.toggle` class assigned in 3.18, but I can't find docs on the subject.

Could you try two things?

1. swap:
```diff
-GtkButton.text-button.toggle {
+GtkButton.toggle.text-button {
```
Does that change anything?

2. After trying 1, try replacing `GtkButton` with `button` in all 5 selectors. Does that change anything?

3. If still nothing, could you try running GtkInspector, clicking on the "Select an object" button in the GtkInspector top-left corner, then clicking on "Auto-matched" in RT, and seeing what style classes are available in the "CSS nodes" tab?
You can run GtkInspector either by launching RT with:
```
GTK_DEBUG=interactive ../rawtherapee/rawtherapee
```
or by enabling it globally (this only needs to be done once ever):
```
gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true
```
and then running RT normally and hitting `Ctrl+Shift+i`.

This screencast shows how to do it:
https://filebin.net/grv1ci7mietbyb53

Sorry if this is a bother, but it would be good to understand what's different since we will still support <=3.18 for some time.

**Comment by agriggio** [comment] 2018-02-01 16:49
@Beep6581 thanks for the instructions, I have done this before so I should be able to do it... But just out of curiosity, what's wrong with my patch?

**Comment by Beep6581** [comment] 2018-02-01 16:55
@agriggio this style we're introducing is specific to toggle buttons, we want other buttons to remain as they are. Instead of applying the style to all buttons and then undoing it for some, better to only apply it to the ones we want to apply it to.

I don't know why a style assigned to `GtkButton` also applies to `GtkCheckButton`. Unless there is something that I missed, that behavior would be a bug in real CSS, and by the fact that GTK+ 3.22 doesn't do that I also conclude it's a bug in 3.18.

**Comment by agriggio** [comment] 2018-02-01 16:57
@Beep6581 I understand the argument, and I agree with it *for GTK 3.22+*. My understanding (@TooWaBoo  might comment as well) however is that CSS support in older versions is buggy and half-done, so doing this "properly" might require a lot of effort. That's why I was suggesting a hack for this...

**Comment by Beep6581** [comment] 2018-02-01 17:00
@agriggio yes that is a fair point as well. IMHO both CSS files need to be re-written from scratch, and as such it doesn't really matter how clean the CSS is. On the other hand, I don't see myself rewriting them any time soon, and when I do I will only rewrite the 3.20 one, so worth doing it properly if possible.
And I'm curious.

It's fine if you want to commit your version, but it would be nice if you could include the `:hover` effects as well.

**Comment by agriggio** [comment] 2018-02-01 17:02
@Beep6581 I'll try to do your tests later tonight. If they lead nowhere though, I'd suggest that we move on... ok?

**Comment by Beep6581** [comment] 2018-02-01 17:06
Absolutely!

**Comment by TooWaBoo** [comment] 2018-02-01 17:44
@agriggio 
Instead of "GtkButton:checked" use ".button:checked" this should prevent to set the background of the checkbox.

**Comment by Beep6581** [comment] 2018-02-01 18:31
I'm installing a distro with GTK+ 3.18 and will sort this out.

**Comment by agriggio** [comment] 2018-02-01 18:32
:+1:

**Comment by Beep6581** [comment] 2018-02-02 01:31
PR #4354 does the same for GTK+ <=3.18 as it does for 3.20 - only modifies the targeted widgets without affecting others, and includes `:hover` for on/off states.

**Comment by agriggio** [comment] 2018-02-06 15:50
we can close this, right?

**Closed as completed** 2018-02-06 18:08 UTC
Labels: type: bug, patch provided
