### ISSUE TITLE
Loading partial profile using Local Adjustments spot(s) = Double/Unwanted result.

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6411] opened 2022-01-21 10:23 UTC
**Short description**
Loading a partial, LA related, profile results in double/merged spots instead of the current spot(s) being replaced by those in the partial profile.

**Steps to reproduce**
1. Load any RAW,
2. Activate Local Adjustments,
3. Add 2 spots,
4. Save these 2 spots using *ctrl-click* on *Save current profile*,
5. Reset RAW. Result should be a clean LA module with no spots,
6. Create 2 new spots,
7. Load the partial profile saved in step 4 (make sure the *Preserve* mode is selected),
8. You now have 2x2 spots instead of the 2x1 spots that are in the partial profile.

**Expected behavior**
The behaviour for all the other modules is as follows: _Partial loaded profiles fully replace the module/tool they target._

I tested this with many modules, but especially  with the 2 other modules that have "spots" or "instances", namely *Wavelet Levels* and *Color Toning* I do get the expected behaviour (what is already there is fully replaced).

**Additional information**
A visualization of the above 8 steps:

https://user-images.githubusercontent.com/56407344/150508480-5fa795c8-808a-4e22-b818-4479f299d033.mp4

- The amount of spots is irrelevant (so not necessarily 2+2 as shown above).
- If the partial file has less spots then currently used, the extra spot(s) are removed and the overlapping is merged as described above.
- It does not matter if there are more then 1 tool attached to spot(s).

I initially thought that @Desmis was responsible for this, but he told me that this part of the code was created by @Pandagrapher.

There is another, related(??), issue that deals with LA and partial profiles: #6150

**Comment by Lawrence37** [comment] 2022-01-23 06:18
This comment is relevant: https://github.com/Beep6581/RawTherapee/issues/6136#issuecomment-787483194. To summarize, this is currently the intended behavior but in the future, applying partial profiles should either add or replace spots. I think there should be at least an option to add spots since it would be difficult to achieve the same result otherwise.

**Comment by ghost** [comment] 2022-01-23 07:21
@Lawrence37 : Thanks for pointing this out.

I have to agree to there being the ability to choose, but: I really think that the way it is implemented now is the wrong way around. Everywhere in RT what is there is fully replaced by the loaded profile and this should be the default for the Local Adjustments too.

Fixing this seems to be a lot of work and, if I understand correctly, will not be started on until the new stable 5.9 rolls out.

So, I'll shut up for now and patiently wait (I'm going to leave this one open for the time being).

**Comment by Pandagrapher** [comment] 2022-07-18 17:17
Fixed by commit [1e2dc30](https://github.com/Beep6581/RawTherapee/commit/1e2dc30738daea8b7e14077db870a9310e84d209)

**Closed as completed by Pandagrapher** 2022-07-18 17:17 UTC
Labels: type: enhancement, tool: selective editing
