### ISSUE TITLE
~50% of Canon EOS REBEL T5i CR2 -> Adobe DNG files are decoded incorrectly (pink cast)

### ISSUE THREAD

**Issue by afontenot** [Beep6581/RawTherapee#5329] opened 2019-05-19 19:12 UTC
Hi, I'm dealing with a situation similar to this old issue: https://github.com/Beep6581/RawTherapee/issues/2383

As far as I can tell, all my CR2 files display correctly in RawTherapee. However, I have a folder converted to DNG by a recent version of Lightroom. All the files were converted at the same time, but roughly half of them display incorrectly in RawTherapee. (Adobe's "lossy" mode was not enabled when converting to DNG.) There is no obvious pattern to the ones that work and the ones that don't. Note that the color cast affects the whole image, which I believe implies that this isn't a highlight clipping issue. All images display correctly in Darktable. 

Changes to processing profile / highlight clipping / highlight reconstruction / demosaicing method / white point correction do not affect the issue at all.

Tested on: 5.6 and latest -dev. Arch Linux, kernel 5.0.13. Intel graphics.

Screenshot of the issue:

![Screenshot_20190519_120156](https://user-images.githubusercontent.com/3870410/57986840-c85af800-7a2e-11e9-9e12-7f2ee9005bda.png)

File with the issue: https://filebin.net/4knmpjq3ovo0t36h

**Comment by Beep6581** [comment] 2019-05-20 13:37
@afontenot 
1. Upload the original raw.
2. Did you tick "Embed fast load data"?

**Comment by Beep6581** [comment] 2019-05-20 13:43
Yes you did. Disable "Embed fast load data".

Duplicate of #4695

**Closed as completed by Beep6581** 2019-05-20 13:43 UTC
Labels: type: bug, scope: file format
