### ISSUE TITLE
TooWaLight-GTK3-_19

### ISSUE THREAD

**Issue by russellcottrell** [Beep6581/RawTherapee#3795] opened 2017-04-01 19:44 UTC
If you are filing a bug report, please first read the guide How to Write Useful Bug Reports:
http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports
You must provide the required information in order for your bug report to be valid.
Delete this text before posting.
[TooWaLight-GTK3-_19.zip](https://github.com/Beep6581/RawTherapee/files/887908/TooWaLight-GTK3-_19.zip)

**Comment by russellcottrell** [comment] 2017-04-01 20:49
I found two more items:
[TooWaLight-GTK3-_19.css.zip](https://github.com/Beep6581/RawTherapee/files/887948/TooWaLight-GTK3-_19.css.zip)

**Comment by russellcottrell** [comment] 2017-04-01 20:50
I found two more items.
[TooWaLight-GTK3-_19.css.zip](https://github.com/Beep6581/RawTherapee/files/887951/TooWaLight-GTK3-_19.css.zip)

**Comment by russellcottrell** [comment] 2017-04-09 04:37
[TooWaLight-GTK3-20_.css.zip](https://github.com/Beep6581/RawTherapee/files/907979/TooWaLight-GTK3-20_.css.zip)

**Comment by Beep6581** [comment] 2017-04-09 11:50
@russellcottrell 
1. Describe what the issue is about in both the subject and the first comment. 
2. Showing a screenshot wouldn't hurt.
3. If you're making a color variation of a theme, import that theme and change only what needs to be changed. See `TooWaBlue-Dark-GTK3-20_.css` for reference.

**Comment by russellcottrell** [comment] 2017-04-09 16:21
Since incorporating the GIMP Toolkit, RawTherapee has not had a light theme.  I have modified the TooWaBlue theme by TooWaBoo for use with RT 5.0-r1-gtk3, 64-bit.

![toowalight](https://cloud.githubusercontent.com/assets/26843507/24838895/c8f85ec0-1d05-11e7-8d71-84fc5dd3dee9.png)

http://www.russellcottrell.com/photo/BTDZS/RTLight.htm

**Comment by Beep6581** [comment] 2017-04-09 18:13
* TooWaLight:
![imgur-2017_04_09-19 53 50](https://cloud.githubusercontent.com/assets/5844619/24839636/be6cbed4-1d5e-11e7-99f4-6c11dd279ae6.png)
* TooWaBlue:
![imgur-2017_04_09-19 54 22](https://cloud.githubusercontent.com/assets/5844619/24839639/d18711ae-1d5e-11e7-840a-ab763e78a1d3.png)
* TooWaLight with replaced icons:
![imgur-2017_04_09-19 56 05](https://cloud.githubusercontent.com/assets/5844619/24839645/e08ae2de-1d5e-11e7-877f-055da218cff7.png)
* TooWaBlue with replaced icons:
![imgur-2017_04_09-19 55 41](https://cloud.githubusercontent.com/assets/5844619/24839649/eb2a8924-1d5e-11e7-9150-75730765bf9e.png)

Problems with this issue:
1. The theme is entirely based on TooWaBlue and only changes colors, but doesn't do so cleanly by importing TooWaBlue and changing only what's needed, thereby being unmaintainable.
2. The theme looks bad using current icons.
3. The theme attempts to fix this by overwriting current icons and breaking current themes.
4. We already ship icons for light backgrounds. The theme does not use them.
5. The icons it requires come as a set of PNG files, not as instructions how to generate them from SVG, making them unmaintainable. I am interested in cutting down on our icon overhead (#3547), not in increasing it.

I'm sorry, this is not workable in its current form. I am against this until all points are solved.

**Comment by Beep6581** [comment] 2017-05-03 17:40
No progress, closing.

**Closed as completed by Beep6581** 2017-05-03 17:40 UTC
