### ISSUE TITLE
Some RT adjustments don't follow the responsiveness params in Options file

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#4072] opened 2017-09-11 16:39 UTC
Hardly a showstopper but FWIW - Many adjustments adhere to the AdjusterMinDelay and AdjusterMaxDelay values but some don't, including CieCAM, RGB (custom) Curves, the HSV Equaliser in the Colour toolbox.

**Comment by Hombre57** [comment] 2017-09-12 11:16
@RawConvert What do you mean by "adhere to" ? Some slider that are know to take time to process have an hardcoded delay. The options' parameter is for standard sliders.

**Comment by Hombre57** [comment] 2017-09-12 11:20
@RawConvert @Beep6581 I don't know how those option's parameter has been designed, but we might change the behavior (if not already the current design) to :

- Use `AdjustMinDelay` for _fast refresh_ parameters
- Use `AdjustMaxDelay` for _slow refresh_ parameters

... then remove all hardcoded values.

**Comment by heckflosse** [comment] 2017-09-12 14:22
@Hombre57 
> (if not already the current design)

That is the current design

**Comment by RawConvert** [comment] 2017-09-12 16:20
Aha,  I assumed RT was following what's in Rawpedia -
"AdjusterMinDelay
    Default value = 100ms.
    This is the minimum time to wait before the preview is refreshed.
AdjusterMaxDelay
    Default value = 200ms.
    This is the maximum time to wait before the preview is refreshed. If you keep changing a parameter, RawTherapee will not wait longer than this short time period before triggering a preview refresh. While the minimum delay is there to prevent overloading your CPU with unnecessary preview refreshes, this delay is to guarantee that you can see what happens to the image as you slowly change some parameter."

I just tested RT and the Max doesn't affect Exposure Compensation adjustments, in line with what @heckflosse says.  So Rawpedia needs updating I guess...

Folks, which parameters are "fast" and which are "slow"?

I think the functionality as per Rawpedia is a nice feature!

**Comment by heckflosse** [comment] 2017-09-12 17:10
@RawConvert 

currently the following adjusters use the `AdjusterMaxDelay`:

```
Microcontrast Quantity and Uniformity adjusters
Edges Iterations and Quantity adjusters
Demosaicing adjusters
Raw Black Points adjusters
Raw White Point adjuster
Raw CA correction Red and Blue adjuster
Hot/Dead pixel Threshold adjuster
Colour Management Free gamma adjusters
Flat-Field Blur radius and Clip control adjusters
CIE Colour Appearance Model 2002 adjusters
Raw preprocessing Line noise filter and Green equilibration adjusters
```

**Comment by RawConvert** [comment] 2017-09-12 20:34
Thanks for the info.
Since my previous post, I've realized the Rawpedia version is in fact much better than the current functioning in one important way.  If you continually move something, say white balance, then in a WYSIWYG world you'd expect the software to respond, following you.  With RT as it stands, it will never respond as long as you keep the mouse moving.  Why does no one seem to mind? I guess we've all got used to pausing the mouse so the screen updates.  But if you've got a fast processor, and you want to make use of it, why not have RT respond as quickly as it can? - just set fairly low values for the min and max (assuming they worked like Rawpedia says).  I'd suggest re-considering how these params work and whether there is mileage in going back to the original way.  Perhaps 2 pairs are needed, the second pair for the "slow" adjusters?

**Comment by heckflosse** [comment] 2017-09-12 20:38
> With RT as it stands, it will never respond as long as you keep the mouse moving

It does when you set the AdjusterMinDelay to a small value

Edit: Except for the tools I mentioned above which use AdjusterMaxDelay

**Comment by RawConvert** [comment] 2017-09-12 20:52
Ok, yes, I was trying 50 and it didn't respond, but now I try 5, it does keep up pretty well.  But it's not nicely controllable like having both parameters!
This testing has explained something that has been bugging me for a while.  Sometimes the mouse does not latch the slider, you move the mouse but the slider stays put.  I now see what's happening. When you click Temperature (white bal) initially there is a thin blue line (on the default theme anyway) and the mouse will latch onto the slider whilst it is thin.  But after about 1 second, the line becomes thicker, and once this happens, the slider doesn't move.  What's happening?!!

**Comment by Beep6581** [comment] 2017-09-12 22:21
@RawConvert the thick line is a GTK+ feature and it means that the slider is in fine-adjustment mode, in which is decreases the movement's sensitivity. The slider only goes into fine-adjustment mode if you either click-and-hold the slider without moving it for 1 second, or if you press the shift key while moving the slider with the mouse (press shift once to enable it, press shift again to disable it).

Sliders in all GTK3 programs do that, unless the programmer disables that, which would suck :) Without that, it would be impossible to, for example, change the white balance temperature with the slider and mouse by 1 degree.

**Comment by RawConvert** [comment] 2017-09-13 09:12
Thanks, I simply hadn't realized it had gone to fine mode, I was by then looking at the image wondering why nothing (in reality a very little I guess) was happening...

**Comment by Beep6581** [comment] 2017-11-16 11:01
@heckflosse 

> That is the current design

IIRC we discussed this in IRC before I wrote that info in RawPedia. It seems that the info in RawPedia is completely wrong. I just confirmed that moving CM > Free Gamma or CIECAM02 > Lightness J will not update the preview until I let go of the slider.

My settings:
```
AdjusterMinDelay=100
AdjusterMaxDelay=200
```

If this is the intended behavior and not a bug, i.e. if RawPedia is wrong, could you please explain what `AdjustMaxDelay` is supposed to do?

**Comment by heckflosse** [comment] 2017-11-16 12:32
Moving the CIECAM02 > Lightness slider updates the preview after the delay without letting go of the slider.
Win7, latest gtk3

**Comment by Beep6581** [comment] 2018-01-31 00:26
Confirmed what @heckflosse wrote - the preview is updated if I pause moving the slider, without having to let go.

RawPedia needs to be updated:
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Preview_refresh_delay

**Comment by Beep6581** [comment] 2018-01-31 00:43
Documentation fixed:
http://rawpedia.rawtherapee.com/The_Image_Editor_Tab#Preview_refresh_delay

**Closed as completed by Beep6581** 2018-01-31 00:43 UTC
Labels: external: RawPedia
