### ISSUE TITLE
Tie mouse scrollwheel scrolling speed to thumbnail height  in File Browser

### ISSUE THREAD

**Issue by Eneen** [Beep6581/RawTherapee#4048] opened 2017-08-28 08:06 UTC
Currently when I try to scroll in file browser RT moves thumbnails really slow. Even with really small thumbnails it takes several mouse wheel revolutions to move one thumbnail.
This should take displayed thumbnail size into account, so e.g. 1 wheel step moves 1 or more (adjustable) full thumbnail size regardless of thumbnail size.

RT version: 5.2
Platform: Windows

**Comment by Nindaleth** [comment] 2018-08-10 09:25
This might be resolved since https://github.com/Beep6581/RawTherapee/pull/4652 has been merged?

**Comment by Beep6581** [comment] 2018-08-10 10:01
@Nindaleth thank you.
Cannot reproduce in `5.4-662-g`f70cdd011, closing.

**Closed as completed by Beep6581** 2018-08-10 10:01 UTC
Labels: type: enhancement

**Comment by Eneen** [comment] 2018-08-10 10:05
Works under linux! Thank you so much!
