### ISSUE TITLE
All text characters display as squares

### ISSUE THREAD

**Issue by gryffinwings** [Beep6581/RawTherapee#5007] opened 2018-11-22 00:35 UTC
Font issue. When Rawtherapee 5.4 is loaded, all font is displayed as squares.

VersionRawTherapee 5.4
Info from build file:
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

Dell Precision T3500, Intel Xeon X5675 - 6-Core 3.06 GHz, 8GB DDR3 1066MHZ.
Operating System: Windows 10 Pro
Steps: I just opened the program as usual and all font is displayed as Squares.
Download location: https://rawtherapee.com/releases_head/windows/RawTherapee_5.4_WinVista_64.zip`
![rawtherapeebug](https://user-images.githubusercontent.com/45247122/48875354-73a33100-edad-11e8-9d7e-ae3fbd786698.jpg)
`

**Comment by gryffinwings** [comment] 2018-11-22 01:17
Went into debugging mode and got this, no idea how to fix this:
![debugging](https://user-images.githubusercontent.com/45247122/48876098-4bb5cc80-edb1-11e8-8f99-75cb848a3b06.jpg)

**Comment by TooWaBoo** [comment] 2018-11-22 05:32
> Steps: I just opened the program as usual and all font is displayed as Squares.

Does it mean it worked in the past?
Change the font in Preferences to e.g. Arial and see if this helps.
I don't think it's an RT issue. Looks like there is something wrong in your system

**Comment by Thanatomanic** [comment] 2018-11-23 18:12
Closing this, since it is (most likely) not a bug on RT's side

**Closed as completed by Thanatomanic** 2018-11-23 18:12 UTC
