### ISSUE TITLE
FR: File browser option for looking into subfolder as well

### ISSUE THREAD

**Issue by X-Raym** [Beep6581/RawTherapee#4434] opened 2018-03-09 16:33 UTC
Hi,

Maybe I miss a setting or something (v5.3)

but it seems that the the file browser only display files/Images of the current folder, and not of its subfolders.

Did I miss something ?

Else, it would be a nice feature to have.

Thanks !

**Comment by Beep6581** [comment] 2018-03-09 16:36
Duplicate of #3756

**Closed as completed by Beep6581** 2018-03-09 16:36 UTC

**Comment by X-Raym** [comment] 2018-03-09 16:39
@Beep6581 oops sorry. I didn't search for "dir tree" keyword.
