### ISSUE TITLE
Batch Edit "Transform-Resize" randomly changes default values in USM

### ISSUE THREAD

**Issue by romandocent** [Beep6581/RawTherapee#4014] opened 2017-08-13 16:26 UTC
I noticed that Batch Edit function changes default values in Transform->Resize->Post-Resize Sharpenning (UNSHARP MASK)-> Amount. Default value in USM Amount is 200, and it's normal for most cases. But when I do batch operation it randomly changes this value to 400, 800 or 1000 EVEN if I don't switch on Resize panel during batch. I forced to check it every time to reset back to 200 when I need to resize an image, processed with batch previously. 
![selection_006](https://user-images.githubusercontent.com/19542067/29251426-2d26d506-805d-11e7-966f-a4a56d427935.png)

**Comment by Beep6581** [comment] 2017-08-14 08:27
@romandocent 
1. Which [version](http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports)?
2. Preferences > Batch Processing, is it set to ADD or SET? 
3. What are the steps to reproduce? A [screencast](http://www.maartenbaert.be/simplescreenrecorder/) would help.
4. When does it change the value?

**Comment by romandocent** [comment] 2017-08-14 16:28
1. Up to 5.2 release (Ubuntu 16.04)
2. Everything by default (can't find there "resize" or "post-resize sharpening" string)
3. Choose some raw pictures, go to Batch edit, change something (for exampe I change input profile to my Nikon camera, and output to No ICM, switch on Noise reduction, and in Raw panel switch on Auto-Correction in chromatic aberration but I noticed  it doesen't matter what to change). Then open one of these raws for edition, go to Transform->Resize-> Method: Unsharp Mask, watch the Amount value (also check it for non-batch-edited raws).
4. It changes after Batch edit.

@Beep6581

**Comment by Beep6581** [comment] 2017-08-14 16:51
@romandocent 

> Everything by default

Is everything ADD or SET? "Default" means nothing in this case, because their default state was buggy until a few days ago.

Cannot reproduce in `dev`. A screencast would help.

**Comment by romandocent** [comment] 2017-08-14 20:41
Then try to reproduce in "release", I'm using it. 
Some strings "add" others "set". I touched nothing there after install from release branch.

**Comment by Beep6581** [comment] 2017-08-15 07:15
@romandocent click "All to 'Set'" then try to reproduce. A screencast would help.

**Comment by romandocent** [comment] 2017-08-17 22:55
@Beep6581 
No effect. Especially set "Amount" to 200 went to Batch Edit and switched on Chromatic Aberration-Auto Correction, jumped back to same image and found "Amount" 400.

**Comment by Hombre57** [comment] 2017-08-20 20:07
Sorry, can't reproduce.

**Comment by heckflosse** [comment] 2017-08-20 22:17
From my experience, if an issue is not reproducible, one of the possible reasons is that the steps to reproduce are not clear enough and lead to misunderstandings while trying to reproduce.

@romandocent Could you please post the steps to reproduce step by step instead of prosa?

Especially 3. from your second last post is a lot of steps in two large sentences which can lead to misunderstandings. Please take this as constructive criticism. We really take this issue serious, bu we need to be able to reproduce it to solve it.

Ingo

**Comment by romandocent** [comment] 2017-08-21 02:55
@Beep6581 @heckflosse Looks like I can't reproduce it too after "All to Set" setting mentioned by Beep6581 above.

**Comment by cuniek** [comment] 2017-08-28 19:33
I decided not to start a new thread, as this one seems to cover a bug I have found (the hard way, after I sent photos to the client).

RT 5.2, win 7 64 bit

How to reproduce:

Open folder with some photos, and apply this pp3 profile
[test.zip](https://github.com/Beep6581/RawTherapee/files/1257949/test.zip)

Now IN THE FILE BROWSER click BATCH EDIT tab and select SINGLE image. Notice sharpening amount, vibrance settings, vignette and post resize sharpening amount.

Select all images and notice, that while they are selected, all those values are resetted, but they are ok when you select only one image (all in BATCH EDIT TAB).

Select all of them and in BATCH EDIT turn post resize sharpening off and on again. The amount has changed (increased) for good.

**Comment by Hombre57** [comment] 2017-08-28 21:48
Thanks @cuniek , I managed to reproduce the bug. The PRSharpening tool need some fix, as well as the Sharpening tool and Resize tool (didn't checked all others).

**Comment by Hombre57** [comment] 2017-08-30 22:37
@cuniek @romandocent @Beep6581 Branch `resize-add-set` should solve everything.

**Comment by romandocent** [comment] 2017-08-30 22:59
@Hombre57 how use it? Need I reinstall RT from this branch now? Or is it possible to add features from other branches to single installation? (sorry for noob's questions)

**Comment by cuniek** [comment] 2017-08-31 10:35
@Hombre57 thanks for the patch, it makes things  better, still not perfect:

- I confirm that PRSharpening amount is now not changed after turning resize off and on when multiple images are selected. The same with USM amount and vibrance
- unfortunately vignette is still resetted
-When all images have the same profile applied, USM amount (as well as vibrance...) have wrong value displayed (0 insted of lets say 300)

**Comment by Hombre57** [comment] 2017-08-31 22:19
@romandocent If you can build RT yourself, you just have to build this new branch and copy the rawtherapee.exe file (if you're on Windows) to your install directory, for testing purpose.

@cuniek If a parameter is set to ADD mode in Preferences AND if you select multiple images, then the slider switch to 0 because it works in incremental/decremental (see above). The USM amount and Vibrance works fine here.

> Vignette is reseted

What do you mean ?

**Comment by cuniek** [comment] 2017-09-01 09:17
> > Vignette is reseted
> What do you mean ?

Use vignette tool from exposure tab on several images, select them all in file browser, and turn resize on and off using batch edit tab -> vignette is set to 0 (strength, feather and roundness).

**Comment by Hombre57** [comment] 2017-09-02 00:06
@cuniek It works fine here. Could you upload your options files please ?

**Comment by cuniek** [comment] 2017-09-02 13:20
here is a screengrab showing the phenomenon. Just change the extension from .pdf to .mp4
[screengrab.pdf](https://github.com/Beep6581/RawTherapee/files/1272187/screengrab.pdf)

PP3 file is available few posts higher.

Here is the options file (just remove the .pdf extension)[options.pdf](https://github.com/Beep6581/RawTherapee/files/1272175/options.pdf)

**Comment by Hombre57** [comment] 2017-09-02 16:23
Thanks @cuniek , fixed in bfe24ab1950037369b4d71dabc19c5451c457cd3

Can we close ?

[EDIT]
Dh'o ! The commit message is wrong, should have been "ParamsEdited::combine fixed". Anyway, that's not important.

**Comment by cuniek** [comment] 2017-09-02 20:33
I compiled last version and it seems it works fine. I don't have time for in depth testing, still I believe #4014 can be closed.

Good job.

**Closed as completed** 2017-09-02 20:38 UTC
Labels: type: bug

**Comment by Hombre57** [comment] 2017-09-07 19:42
I forgot to merge the `resize-add-set` branch into dev. Done just now.

**Comment by romandocent** [comment] 2017-09-07 20:30
Don't forget to merge it into release ))

**Comment by heckflosse** [comment] 2017-09-07 20:55
`dev` is the base for next `release`. No need to worry ;-)
