### ISSUE TITLE
CIECAM02 curves buggy when using different modes

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3019] opened 2015-12-12 02:37 UTC
Set CIECAM02's TC1=Lightness to some strong shape, and TC2=Brightness to linear:
http://i.imgur.com/ndMqwSL.jpg

Click a point on TC2 along the diagonal so that the shape of the curve stays the same:
http://i.imgur.com/W8pEIHW.jpg

Now ctrl+move that node just a pixel. There should be no difference, but:
http://i.imgur.com/O9BzNaJ.jpg

**Comment by Desmis** [comment] 2015-12-14 05:22
Hello I returned from a trip to the tropics :)
This problem is an old problem...for which I worked there 3 years ago with Michael....(the cat that bites its own tail!). You can see what I tried to do line 2350 in Improcfun.cc....but in some cases it's does not work (if you enable curve 2 after curve 1), its work  if you enabled curve 1 after curve 2.

I think the only solution is with GUI is to reduce the number of choices (it's the same thing with "chroma curve" where I reduce the number of sliders!!!)

In this case the choices will be : 
Tone curve 1 = Lightness  ==> Tone curve 2= Lightness

Tone curve 1 = Brightness  ==> Tone curve 2= Lightness
Tone curve 1 = Brightness  ==> Tone curve 2= Brightness

Tone curve 1 = Lightness and  Tone curve 2= Brightness Forbiden

**Comment by Beep6581** [comment] 2015-12-14 06:48
We are having some tropical above-zero temperatures too http://i.imgur.com/IMCiwTR.png
:P Real tropics sound lovely.

I will have to check some older PP3s to see if I ever found the TC1=Lightness and TC2=Brightness combination to be useful. If not, then it might be good to prevent that combination in the GUI. But if it is useful, then we just document it and leave it. Do you find it useful?

**Comment by Desmis** [comment] 2015-12-14 07:52
I just spent 11 days in Mauritius ... and it was between 23 and 30 ° C.

I think GUI is a good solution....the most useful combinations are from my point of view;
*lightness and lightness
*brightness and brightness
and we have one combination : brightness + lightness !

**Comment by sguyader** [comment] 2015-12-14 10:59
This is just to bring some warmth from where I live in the Caribbean:
http://imgur.com/HGPoels
Jacques you visited one of my dream location, I hope I can visit Mauritius
one day too.

**Comment by Desmis** [comment] 2015-12-14 11:49
Hello squyader

I see you're in Guadeloupe..or near!
I regularly go to this island that I found at least as pretty as Mauritius...

I'll be in Guadeloupe in March this year at St Francois :)

**Comment by Lawrence37** [comment] 2023-08-27 19:06
Cannot reproduce in `dev`. Likely resolved by #6350, therefore closing.

**Closed by Lawrence37** 2023-08-27 19:06 UTC
Labels: type: bug
