### ISSUE TITLE
moving the image without distortion (Settings)

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#6694] opened 2023-02-27 21:41 UTC
Hey, thanks for this 💯 

When zooming into the image in the image editor and moving it by grabbing with my mouse, _the image gets pixeled_ to reduce the sytem resources usage.

I am working on gigapixel images and i have to view every inch at 100%. But if i move or not my (todays powerful) system has a 0% usage (zero usage) when moving the image.

Can you make an option to set/unset this in the Settings?

I want to see the image all the time in 100% without any distortion by moving it.

Thank you :)

**Comment by Lawrence37** [comment] 2023-02-28 02:07
Duplicate of #956

**Closed as not planned by Lawrence37** 2023-02-28 02:07 UTC
Labels: type: enhancement, scope: GUI
