### ISSUE TITLE
"Save as" grows up on every open

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3532] opened 2016-12-12 23:25 UTC
When you open and close the "Sava as" dialog several times , it will grow up a bit on every open. I figured out, that the different of the size is exactly the amount of the window decoration (see screenshots).
The screenshot with the blue border is the area with box-shadow on, orange is box-shadow off. This is the part, which is used as resize area when box-shadow is on.
The size saved in the option file is the size which includes the window decoration. This is OK, because the Preferences dialog does the same and works perfect.

For me it looks like when opening the "Save as" dialog the window size is assigned to the **content area** instead of to the **decoration area**.

![unbenannt1](https://cloud.githubusercontent.com/assets/13800920/21120857/b38b67b4-c0c9-11e6-848a-4fc80d00f84d.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/13800920/21120859/b7514cc4-c0c9-11e6-808d-44937399c1c3.png)

**Comment by heckflosse** [comment] 2016-12-12 23:46
@TooWaBoo Thanks for reporting the bug. Confirmed in master branch on Win7/64

**Comment by Beep6581** [comment] 2016-12-13 08:15
I could not reproduce using gtk3-bugfix in KDE Plasma.

**Comment by Hombre57** [comment] 2016-12-15 14:27
When discussing about GUI problem, please provide your gtkmm lib version as reported in AboutThisBuild.txt.

**Comment by heckflosse** [comment] 2016-12-15 15:03
In master branch: Gtkmm: V2.24.4
Hmm, tested again. Now size is constant, but the window moves a bit bottom right with each save until some point where it opens again top left and so on

**Comment by TooWaBoo** [comment] 2016-12-27 08:21
Maybe this helps:
http://www.manpagez.com/html/gtk3/gtk3-3.22.0/ch32s10.php

**Comment by Hombre57** [comment] 2016-12-27 13:34
Nice catch @TooWaBoo . Patch committed in master. Closing.

**Closed by Hombre57** 2016-12-27 13:34 UTC
Labels: bug, Component-UI

**Comment by Beep6581** [comment] 2016-12-27 15:28
@Hombre57 could you come to IRC if you're around?
