### ISSUE TITLE
Feature request: add high quality image preview mode

### ISSUE THREAD

**Issue by eugene-rom** [Beep6581/RawTherapee#7115] opened 2024-06-24 08:18 UTC
Regular image view during raw development does not looks "crisp" as resulting image. Some tools like sharpness and noise reduction only applied on 1:1 preview, applying distortion correction and rotation makes preview yet more blurry, etc.

So, to preview my work I need save processed image and view it externally.

It would be nice to have a high quality preview mode, when all tools applied and image in preview area looks exactly as result image.

It may be activated by button and preview looks HQ until no other modifications applied, or by check box and then preview fully processed after any modifications (may be slow, but, for example, Canon Digital Photo Professional uses something like this).

**Comment by syyrmb** [comment] 2024-06-28 10:26
Would be great if this can be done, though I'd use a big detail window (or multiple small ones) to get around this.

**Comment by Lawrence37** [comment] 2024-06-29 21:12
Duplicate of #4527.

**Closed as not planned by Lawrence37** 2024-06-29 21:12 UTC
Labels: type: enhancement, scope: GUI
