### ISSUE TITLE
Unstable output w/ same PP3 and RAW CA auto-correction when image height % 2 == 1

### ISSUE THREAD

**Issue by Floessie** [Beep6581/RawTherapee#3258] opened 2016-04-20 18:04 UTC
Hi,

there seems to be a problem on master with RAW CA auto-correction, which results in different images whenever they are saved, even successively in the same session.

Reproduction:
1. Open a CR2.
2. Chose "Neutral".
3. Enable "Sensor with Bayer Matrix / Chromatic Aberration / Auto-correction".
4. Save current image as 8b uncompressed TIFF named "test1.tif".
5. Wait until saved.
6. Save current image as 8b uncompressed TIFF named "test2.tif".
7. Quit RT.
8. `compare test1.tif test2.tif diff.tiff`

Depending on the image you will see arbitrary stripes and/or blocks of differences. When running RT with `OMP_NUM_THREADS=1` those problems are gone.

This is on Debian Stretch.

A good sample is [this](http://rawtherapee.com/shared/test_images/snow_street_night_shot.cr2). The PP3 is here: [snow_street_night_shot.cr2.pp3.zip](https://github.com/Beep6581/RawTherapee/files/228530/snow_street_night_shot.cr2.pp3.zip)

Best,
Flössie

**Comment by heckflosse** [comment] 2016-04-20 18:36
@Floessie Thanks for the report and for the example. With your file I could immediately reproduce it. Looking...

**Comment by heckflosse** [comment] 2016-04-20 18:52
@Floessie, I saw your cr2 has an odd height. Maybe it's related to that. Still searching...

**Comment by heckflosse** [comment] 2016-04-21 14:41
@Floessie It really seems caused by image height % 2 == 1. I verified that using camconst raw_crop

**Comment by heckflosse** [comment] 2016-04-21 18:54
Should be fixed with this [commit](https://github.com/Beep6581/RawTherapee/commit/58fb7af2bbd79b8797f8b80c9062899dd38c5113). @Floessie Can you confirm please?

**Comment by Floessie** [comment] 2016-04-22 06:11
@heckflosse: Yep, it's gone. Well done! :)

**Closed** 2016-04-22 10:57 UTC
