### ISSUE TITLE
Combobox text overflow Gtk3

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3186] opened 2016-02-29 17:11 UTC
**All** comboboxes with a long text don't cut off the text at the end.
RT Gtk3, Win 10 x64

![unbenannt](https://cloud.githubusercontent.com/assets/13800920/13402198/8fdb5d02-df0f-11e5-8ea7-d9b14cd0ed14.png)

**Comment by Beep6581** [comment] 2016-02-29 18:07
Confirmed using 3.18.7, could not reproduce in 3.16.7.

**Comment by Hombre57** [comment] 2016-03-01 11:07
Yes, see the MyComboBox class in guiutils.cc. If there is plain Gtk::Combobox somewhere, we could easily convert them to MyCombobox.

Is this a Gtk bug ? We never had to do this before.

**Comment by Beep6581** [comment] 2016-03-01 12:05
The Gtk+ people consider it a bug.
"The defaults have not changed. What has changed is the overdraw behavior of cell renderers. They used to be clipped, and (apparently) now they aren't. That's a bug".

**Comment by Beep6581** [comment] 2016-04-22 17:33
@Hombre57 I tried but did not manage to figure out how to set `PANGO_ELLIPSIZE_MIDDLE`.

**Comment by Beep6581** [comment] 2016-04-22 17:33
I set a "patch" label in the sense that the solution is known, I just don't know how to implement it.

**Comment by Beep6581** [comment] 2016-05-23 20:43
I'm setting this issue as a blocker for a new major stable release. If anyone knows how to implement PANGO_ELLIPSIZE_MIDDLE where @Hombre57 described, help would be much appreciated.

**Comment by Beep6581** [comment] 2016-09-26 20:20
@Hombre57 is this something you could do? I tried repeatedly and failed :(

**Comment by Hombre57** [comment] 2016-09-26 20:41
Gtk3 bug. I don't know if I can spend time on this. I already tried to solve the FileChooser button, but circumventing this bug need a lot of code to duplicate what's already in Gtk3 + the workaround. Really, they have to solve that in gtk3.

**Comment by Beep6581** [comment] 2016-09-26 21:42
The bug is that the default overflow clipping state is not-clipped, so we'd need to set that, but I don't know how. It seems like an easy peasy one-liner in the Gtk+ C docs, but I don't know how to translate that to C++.

> The GtkCellRendererText object needs to have ellipsize set to anything but PANGO_ELLIPSIZE_NONE. PANGO_ELLIPSIZE_MIDDLE works nicely there.

**Comment by Hombre57** [comment] 2016-09-27 00:10
Fixed in commit 3bdf384, thanks for the hint @Beep6581 :)

**Closed by Hombre57** 2016-09-27 00:10 UTC
Labels: bug, gtk3, patch

**Comment by Beep6581** [comment] 2016-09-27 06:44
Woo! Thank you!
