### ISSUE TITLE
preview updated too often while panning

### ISSUE THREAD

**Issue by pwnage101** [Beep6581/RawTherapee#4833] opened 2018-09-24 20:06 UTC
While panning the preview, the entire view is recalculated, including regions that were previously visible.  Would it be possible to cache the preview in memory, and while panning only calculate the L-shaped region that is being uncovered?

**Comment by Beep6581** [comment] 2018-09-25 06:33
Hi Sankey

This is a duplicate of #956

**Closed as completed by Beep6581** 2018-09-25 06:33 UTC
