### ISSUE TITLE
Highlights go pink as zoom decreases

### ISSUE THREAD

**Issue by RawConvert** [Beep6581/RawTherapee#5318] opened 2019-05-09 23:21 UTC
Files are here - https://filebin.net/rtoj3z92icwwqra7
RT 5.6-16...  Ubuntu 16.04

The image shows pink/magenta highlights when the preview window is less than 100%, and it's almost the more you zoom out the pinker they get.  The jpeg output is not (as) pink as the preview at less than 100%.  Screenshots at 18% and 100% zoom in the file bin show this.

The white point in the raw is 14,733.  My Camconst.json has 14,690 for 100iso, so I believe that should be ok. However the pinkness is generally reduced for this raw by setting the white point correction to 1.15, I don't understand that.  The lens is manual and so RT shows the f stop as zero.

So there might be an issue within RT; or this image has some particular problem; or I'm confused...  but it does seem wrong the pink increases by zooming out from 100% to 33%, for example.

**Comment by Beep6581** [comment] 2019-05-10 07:05
Duplicate of #1625

**Closed as completed by Beep6581** 2019-05-10 07:05 UTC

**Comment by heckflosse** [comment] 2019-05-10 11:27
@RawConvert 
> The white point in the raw is 14,733

That's the brightest green in your raw file.

The reds go up to at least 14,967
The blues go up to at least 14,776

**Comment by RawConvert** [comment] 2019-05-10 17:20
@heckflosse     hi, I got my value from DCRAW, apparently there are only 74 pixels beyond 14733 (across the channels), so I thought these could not have much impact -

value  |  no.of pixels
. . .
14729 | 227
14730 | 191
14731 | 219
14732 | 195
**14733 | 2318391**
14739 | 1
14754 | 1
14758 | 1
14776 | 1
14779 | 1
14788 | 1
14795 | 1
14797 | 2
14799 | 1
14801 | 2
14803 | 1
14806 | 1
14810 | 1
14812 | 1
14821 | 1
14822 | 2
14824 | 1
14826 | 1
14831 | 2
14833 | 1
14839 | 1
14842 | 2
14844 | 3
14846 | 2
14853 | 1
14855 | 2
14858 | 1
14862 | 1
14864 | 1
14867 | 1
14875 | 1
14876 | 1
14891 | 1
14900 | 1
14905 | 1
14923 | 1
14924 | 1
14930 | 1
14947 | 1
14954 | 1
14956 | 1
14957 | 1
14997 | 1
15135 | 1
15170 | 1
15242 | 1
15260 | 1
15288 | 1
15326 | 1
15333 | 1
15415 | 1
15425 | 1
15477 | 1
15492 | 1
15505 | 1
15696 | 1
15796 | 1
15858 | 1
15878 | 1
15906 | 1
16079 | 1
16240 | 1
16383 | 3

Do you think the last 3 are what they call "stuck pixels" ?

I expect you've thought about how to counteract this highlights effect, presumably it's difficult to fix?

**Comment by heckflosse** [comment] 2019-05-10 18:13
@RawConvert I'm not an expert at this (@iliasg is the expert here), but the white levels seem not to be equal across the channels...
