### ISSUE TITLE
Inconsistent-wrong preview with LCP distortion correction

### ISSUE THREAD

**Issue by iliasg** [Beep6581/RawTherapee#2996] opened 2015-11-29 11:40 UTC
With RT Version: 4.2.487
Changeset: a27327de33a77f2f32e048c4bf67d281c7b339ab
win32 bit

When we apply LCP distortion correction RT shows correct preview only when we are at "fit to screen".

With 100% view the distortion correction is not applied
With 50% & 33% the screen gets black (when we pan to the borders) or grey (center crop)  
With 25%-20% the preview is not 25%-20% but bigger (equal to 100%-50% ?? ) and part of the frame is hidden. The distortion correction is OK.
The navigator shows the correction applied correctly
The exported file has the correction applied correctly :)

Sample  raw http://www.imaging-resource.com/PRODS/sony-rx1r-ii/RX1R2FAR2I0100.ARW.HTM

Screenshots & lcp profile https://drive.google.com/folderview?id=0B0NqktTgc54sNldJS2w3Nk9feFE&usp=sharing

**Comment by heckflosse** [comment] 2015-11-30 16:10
Ilias, https://github.com/Beep6581/RawTherapee/issues/1791

**Comment by Beep6581** [comment] 2015-12-01 15:52
Duplicate of #1791, closing.

**Closed by Beep6581** 2015-12-01 15:52 UTC
