### ISSUE TITLE
Fit to screen action is offset on Windows

### ISSUE THREAD

**Issue by X-Raym** [Beep6581/RawTherapee#3750] opened 2017-03-10 08:56 UTC
Hi !

## Bug report

It seems that on Windows 10 x64, *Fit to screen* action (triggered by <kbd>f</kbd>), is offset to the left border of the image; it doesn't fit according to its center. According to my test, it doesn't seem to take into account the width of the preview space, only the heigh.

## Config

```
Version: 5.0-r1-gtk3
Branch: 5.0-r1-gtk3
Commit: 50114c1
Commit date: 2017-02-01
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -m64 -mwin32 -mthreads -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -msse -msse2 -mwindows -fopenmp -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mwin32 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

### Linux Mint (working)

![Screenshot](http://i.imgur.com/oFjbb2r.gif)

### Windows (problem)

![Screenshot](http://i.imgur.com/jKHxTYz.gif)

## Reproduce

1. Import an image, and resize the width of the preview panel so that it become small than the image width.
1. Press <kbd>f</kbd>
1. See the results. Expected (working) results : we see the whole image.
1. (optional) Try with adjusting preview panel height. => Image should adjust.

Thanks for listening!

**Comment by TooWaBoo** [comment] 2017-03-10 09:14
Look at the top and bottom buttons. The smallest possible width of the image area belongs to the smallest possible size of these button toolboxes. You can thrink the width until you'll see ALL buttons. If you reach this limit, the sidebar begins overlapping the image area.

It's not a bug.

EDIT: The zooming also has changed in RT5.x. It's not zooming from the center of the image, it's zooming from the current mouse position within the image.

**Comment by X-Raym** [comment] 2017-03-10 09:44
@TooWaBoo 
Ok ok so there is a minimal width possible for this preview, and this minimal width depends on the buttons below it.

I would have expect that the image gets resized anyway, and that the zoom center on the image. So maybe not a bug, but feature requests:

* Right Panel don't go hover image (to allow
* Image gets resized if right panel is
* **Fit to screen action zoom to center**

Buttons could be collapsed or set as *vertical sidebar* to leave more room for resizing. Currently, min preview width seems to be something around 770.

I understand that this would be hard to code and would take time, so it is more low priority ideas. 😸 

----
In fact, you make me notice that there is a graphical bug in Linux (screenshot 1) as toolbar buttons overlaps the left panel.

Thanks for your support !

**Comment by Beep6581** [comment] 2017-03-10 09:50
I'm inclined to close this issue because https://discuss.pixls.us/t/local-lab-build/1430/142?u=morgan_hardwood

**Comment by Beep6581** [comment] 2017-03-10 09:51
I must add that we became used to the buttons overlapping on unsupported low screen resolutions because GTK2 had no native way of making the buttons dynamically flow and wrap inside their container, but perhaps GTK3 does?

**Comment by Beep6581** [comment] 2017-09-06 06:10
#4035

**Closed as completed by Beep6581** 2017-09-06 06:10 UTC
Labels: type: enhancement
