### ISSUE TITLE
Clarify Processing Profile Handling buttons in Preferences

### ISSUE THREAD

**Issue by geoderix** [Beep6581/RawTherapee#3830] opened 2017-04-17 19:45 UTC
It seems like regreession from RawTherapee 5.01-r1.
With RawTherapee_dev_5.0-r1-gtk3-446-g931db7ab_WinVista_64 on Windows 7 64 bit .pp3 are always written to the directory with the source raw file. It is not possible to disable it from Preferences - Image Processing - Processing Profile Handling. Processing Profile Handling settings do nothing at all.

**Comment by heckflosse** [comment] 2017-04-17 19:55
@geoderix Can you clarify please? Did you try to disable both options (Save ... next to input file and Save ... to cache)? That won't work because you need a processing profile for each file you want to process.
But I would agree that this could be presented more transparent to the user.

**Comment by geoderix** [comment] 2017-04-17 20:21
Yes, I tried disable and enable both - no effect. Each time you open raw file in the editor,to the source directory writes .ppt3. Even if I did not do anything with the file, I just wanted to see it. Why do I need garbage in the directories with pictures? If I need this, I can always save the processing profile manually or enable automatic recording. But why does it always and everywhere? RawTherapee 5.01-r1 worked correctly. Please return.

**Comment by heckflosse** [comment] 2017-04-17 20:48
@geoderix Let me try. Maybe it's a bug. I'll report in a few minutes

**Comment by heckflosse** [comment] 2017-04-17 20:57
@geoderix I can confirm the bug. We should clarify in preferences dialog that you need to choose at least one of the options (Save next to input file or save to cache). Currently if you disable both it falls back to save next to input file which is ok but confusing if you disabled that option.

Thanks for reporting this :+1: That deserves improvement.

Ingo

**Comment by geoderix** [comment] 2017-04-17 21:10
@heckflosse 
And you can make it so that if both are disabled, it is not recorded anywhere?
Let's say I want to see what the pictures did, play around with the settings, but do not convert anything. Then I go out, forget about it, and when I return to these pictures again, the settings that are not necessary to me are read. And I'm in confusion going to delete all these profiles from the directories and the cache with filthy curses to the devil.
Return it as it was, do not decide for the user.

**Comment by Beep6581** [comment] 2017-04-17 21:17
@heckflosse how about three radio buttons, or one combobox with three entries?

**Comment by geoderix** [comment] 2017-04-17 21:20
@Beep6581 
`how about three radio buttons, or one combobox with three entries?`

In my opinion - a disgusting idea. Return as was, do not invent a bicycle with square wheels.

**Comment by heckflosse** [comment] 2017-04-17 21:27
@geoderix 

> And you can make it so that if both are disabled, it is not recorded anywhere?

No, if you open a file in rt a processing profile (even if it's neutral) will be applied and that settings have to be recorded somewhere.

**Comment by Beep6581** [comment] 2017-04-17 21:40
Not saving a PP3 if nothing has changed is handled by #2857

**Comment by geoderix** [comment] 2017-04-17 22:05
`Clarify Processing Profile Handling buttons in Preferences`
Why did you change the meaning of what I wrote? I did not mean the buttons, but the behavior of the program. You acted incorrectly. Write your own bug, return the meaning of what I wrote. I did not give you the authority to make such decisions.
Please return what I wrote in the title.

**Comment by heckflosse** [comment] 2017-04-17 22:24
@geoderix 

> .pp3 are always written to the directory with the source raw file. It is not possible to disable the recording .pp3.

Your title was wrong because it is possible to not write .pp3 files to source directory by enabling 'Save to cache' and disabling 'Save next to input file'

As I admitted some posts above it's not possible to avoid writing a pp3 file at all (if not next to input file it will be in cache at least).

For that reason I think changing the topic of the issue (as @Beep6581 did) is appropriate

**Comment by geoderix** [comment] 2017-04-17 22:28
@heckflosse 
In this case, it will be correct to open a new topic. I meant something completely different.

**Comment by heckflosse** [comment] 2017-04-17 22:39
@geoderix I agree that opening a new topic is the best way if the title or the description of the old topic in op is wrong or incomplete ;-)

**Comment by geoderix** [comment] 2017-04-18 07:29
Please, open another topic or  return what I wrote in the title.

**Comment by Beep6581** [comment] 2017-04-18 07:30
I split the problem discussed here into two sections: the "Not saving a PP3 if nothing has changed" part which is already handled elsewhere, and the required UI improvement part which comes about as a result of the user confusion described in the third comment. I'm not closing this issue and opening a new one and reverting the results of bug triage (aligning the topic with what will actually happen, referencing other issues, etc.) 10 hours after having made them because you say so, in impolite terms nonetheless.

**Comment by agriggio** [comment] 2017-04-18 09:34
@Beep6581 how about something like this?

![profilesave](https://cloud.githubusercontent.com/assets/11982086/25124106/fe95642a-242a-11e7-8071-e8b976e3905b.png)

**Comment by Beep6581** [comment] 2017-04-18 10:02
@agriggio exactly what I had in mind - either that or a combo with those three options. As there already is a combo in that frame, it would probably look more consistent to use a combo for both.

@agriggio btw I'm almost done with a patch, but it's lunch time now ;)

**Comment by agriggio** [comment] 2017-04-18 10:33
@Beep6581 oops, sorry! I saw only now that you were working on this :sob: I just pushed to `dev` (using the combo as you suggested)

**Comment by Beep6581** [comment] 2017-04-18 11:29
@agriggio nice after-lunch surprise :) Thank you.

I tested it and it works fine. I did find a bug related to this, but I confirm that the bug existed before the patch, so I'll open a new issue for that.

**Closed as completed by Beep6581** 2017-04-18 11:29 UTC
Labels: type: enhancement

**Comment by heckflosse** [comment] 2017-04-18 18:27
@agriggio works fine here too :+1:
