### ISSUE TITLE
v5.3: scaling issues on Hi DPI screens

### ISSUE THREAD

**Issue by Auxx** [Beep6581/RawTherapee#4199] opened 2017-11-27 15:47 UTC
I'm using high DPI screens with 150% and 200% scaling ratios. In both cases the whole UI and image previews are upscaled and look blurry. While tool icons are bearable, working with upscaled photos is impossible.

Another related issue is when moving zoomed photo with mouse, it moves proportionally faster than the mouse.

**Comment by TooWaBoo** [comment] 2017-11-27 16:48
screenshot? operating system?

**Comment by Auxx** [comment] 2017-11-27 17:00
Oh yeah, sorry. Windows 10 x64 with all the updates.

Here's [a screenshot of folder browser](https://www.flickr.com/photos/96275023@N08/24809275188/sizes/o/) in full resolution.

And here I have [image editor screen](https://www.flickr.com/photos/96275023@N08/37794366655/sizes/o/) together with Nomacs window showing image at real 1:1. My current monitor has 4K resolution running at 200% scale factor. As you can see, RawTherapee just doubles all the pixels across the app and applies some filtering (bi-linear?). It should show 1:1 pixels in previews and image editor.

**Comment by TooWaBoo** [comment] 2017-11-27 17:14
RawTherapee is not fully highres compatible.
At 200% scalling Windows doubles all images including the RAW image.
Try using a scaling lower than 200% and use one of the TooWaBlue themes.
I'll hope this helps.

**Comment by Beep6581** [comment] 2017-11-27 17:35
Duplicate of #3547

**Closed as completed by Beep6581** 2017-11-27 17:35 UTC
