### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by scx** [Beep6581/RawTherapee#5113] opened 2018-12-25 08:21 UTC
I created the flatpak package for RawTherapee.
https://github.com/scx/rawtherapee-flatpak

I am in the process of submitting it to the Flathub repo.
https://github.com/flathub/flathub/pull/789
https://github.com/scx/flathub/tree/com.rawtherapee.RawTherapee

It would be nice if the author decided to participate in the further development of this flatpak package.

**Comment by Beep6581** [comment] 2018-12-26 20:10
I have no personal interest in flatpaks and we already have a well performing AppImage which requires far less fiddling to run.

Duplicate of #4860

**Closed as completed by Beep6581** 2018-12-26 20:10 UTC

**Comment by scx** [comment] 2018-12-27 05:03
@Beep6581 

> I have no personal interest in flatpaks and we already have a well performing AppImage which requires far less fiddling to run.

I have to disagree with you.
AppImage is not as trouble-free as you think:
https://github.com/flathub/flathub/pull/566#issuecomment-414643604

Because of this, you may occasionally encounter some problems like this:
https://github.com/Beep6581/RawTherapee/issues/4687

This is not the case with Flatpak.
What's more, Flathub provides free infrastructure for building packages for various architectures (arm, aarch64, i386, x86_64).
Please keep in mind that any Flatpak/Flathub package can be easily installed and updated using GNOME Software.
![avidemux-flathub-gnome-software-app.png](https://2.bp.blogspot.com/-zwRlqfWAW1s/WxRAfDTQTFI/AAAAAAAAAqA/zdWM0UwDHJAYAro5hW7kDsKHnZNbXqL5ACLcBGAs/s1600/avidemux-flathub-gnome-software-app.png)

Of course, I am not urging you to abandon AppImage. Moreover, I will try to take care of this flatpak package as much as I can. What I care about is bringing the [AppData](https://github.com/Beep6581/RawTherapee/issues/5117) file to Flathub standards.

**Comment by adds68** [comment] 2019-04-21 13:37
Hi, Is there no chance to reconsider accepting @scx flatpak on Flathub? He has done all of the work, the only updates required would be bumping the version number when you release? 

The app would the be installable from GNOME software and from here: https://flathub.org/apps/category/Graphics across all distros.

**Comment by scx** [comment] 2019-08-09 11:22
I've provided a single-file bundle for x86_64.
https://github.com/scx/rawtherapee-flatpak/releases

**Comment by scx** [comment] 2019-09-26 06:20
I've updated my flatpak package for RawTherapee to version 5.7.
https://github.com/scx/rawtherapee-flatpak
https://github.com/scx/rawtherapee-flatpak/releases
https://github.com/scx/rawtherapee-flatpak/releases/tag/v5.7+20190926
It is worth to mention that it can use GIMP as an external editor. This wasn't possible earlier.
