### ISSUE TITLE
Several build failures on OpenSUSE build service

### ISSUE THREAD

**Issue by mbajor** [Beep6581/RawTherapee#3070] opened 2016-01-08 09:07 UTC
I'm not able to build packages for Debian 7 and Univention 4 because of error
```
[ 1244s] /usr/src/packages/BUILD/rtgui/cachemanager.cc: In member function 'Thumbnail* CacheManager::getEntry(const Glib::ustring&)':
[ 1244s] /usr/src/packages/BUILD/rtgui/cachemanager.cc:135:21: error: 'using Entries = class std::map<std::basic_string<char>, Thumbnail*>' has no member named 'emplace'
[ 1244s] /usr/src/packages/BUILD/rtgui/cachemanager.cc: In member function 'void CacheManager::renameEntry(const string&, const string&, const string&)':
[ 1244s] /usr/src/packages/BUILD/rtgui/cachemanager.cc:205:17: error: 'using Entries = class std::map<std::basic_string<char>, Thumbnail*>' has no member named 'emplace'
```
[Deiban i586: full build log ](https://build.opensuse.org/build/home:rawtherapee/Debian_7.0/i586/rawtherapee/_log)

**Comment by Beep6581** [comment] 2016-01-08 09:27
I don't know if that's the cause, but GCC-4.7 is unsupported. The oldest version of GCC we now support is 4.9.

**Comment by adamreichold** [comment] 2016-01-08 16:07
Yes, this is GCC 4.7's C++ standard library not supporting some C++11 extensions of the `std::map` container. I think this could be worked around with some marginal performance costs, but I guess at least #3040 will add a lot more of these, so the question is how hard a deprecation we want to perform?

**Comment by adamreichold** [comment] 2016-01-08 16:08
(This could probably also be worked around using `#ifdef` but I don't think we want to go there since C++11 is supposed to improve maintainability, not decrease it.)

**Comment by adamreichold** [comment] 2016-01-08 16:18
@Beep6581 Maybe we should CMake throw an error instead of printing a warning if an old compiler is detected as an automated build system like OBS will just ignore the warning?

**Comment by Beep6581** [comment] 2016-01-08 16:24
Good idea.
```
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4.9")
    message(FATAL_ERROR "RawTherapee requires GCC version 4.9 or higher!")
endif()
```

**Comment by adamreichold** [comment] 2016-01-08 16:43
I'll commit the change and close this?

**Comment by Beep6581** [comment] 2016-01-08 16:51
Please do.

I suppose it would be good to write a news article on the front page informing about the recent changes.

**Comment by mbajor** [comment] 2016-01-09 00:18
@Beep6581 @adamreichold 
Before I had a problem with build for Debian 7 and Univention 4. eg gcc 4.8.1 compile without any problem. Now I'm not able to build for most repositories. 
Here is full list(marked as failed) https://build.opensuse.org/package/show/home:rawtherapee/rawtherapee

Note that openSUSE 13.2 is latest stable version andLeap 42.1 is openSUSE's newest release of the stable distribution.

**Comment by adamreichold** [comment] 2016-01-09 09:45
@mbajor Sorry that this causes so much breakage for you, this was obviously not tested widely enough on my part. The problem with the SUSE versions however is that SUSE is notoriously conservative on the default GCC version even though they usually package a separate newer GCC version in the official repositories, e.g. Leap 42.1 contains the `gcc5` packages, 13.2 contains the `gcc49` packages and so on. Would be possible to depend on these packages and use them for your builds? Is there anything we can do in the build system to make that easier for you?

**Comment by adamreichold** [comment] 2016-01-09 09:49
@Beep6581 We could also downgrade our requirements to GCC 4.8 since its C++11 support is in pretty good shape langauge-wise (the standard library is a different beast), but this would loose us OpenMP 4.0 support which seems even more useful to RT as it is the defining technology of its processing core.

**Comment by adamreichold** [comment] 2016-01-09 09:54
@mbajor Do you have a tip for me: I would like to run a minimal OpenSUSE-based container on my Arch box to test building locally before pushing stuff upstream. Do you know what the best way to get a full chroot environment based on 13.2 or 42.1 would be?

**Comment by adamreichold** [comment] 2016-01-09 10:56
@mbajor I went using a Docker container of openSUSE 13.2 and were able to successfully build master by installing `gcc49-c++` and setting the environment variables
````
export CC=gcc-4.9
export CXX=g++-4.9
````
before running CMake. Would that work for your builds as well?

(The output
````
/usr/lib64/gcc/x86_64-suse-linux/4.9/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.8, needed by /usr/lib64/gcc/x86_64-suse-linux/4.9/../../../../lib64/libtiff.so, may conflict with libjpeg.so.62
````
worries me but I think this is not related to the GCC version?)

The resulting binary seems to work using X11 forwarding but I have not yet tried to develop anything. (Will try to make it a proper recipe/Dockerfile to easily reprocude.)

**Comment by adamreichold** [comment] 2016-01-09 13:16
@mbajor I'll reuse this issue to track our efforts to make the OBS builds working again, hope you don't mind.

**Comment by adamreichold** [comment] 2016-01-09 13:19
@mbajor I was able to build RT's current master using OpenSUSE 13.2 and GCC 4.9 as provided by the distribution using the following container:
````
FROM opensuse:13.2

MAINTAINER Adam Reichold "adam.reichold@t-online.de"

RUN zypper --non-interactive --gpg-auto-import-keys addrepo \
        -f http://download.opensuse.org/repositories/home:/rawtherapee/openSUSE_13.2/ \
        rawtherapee
RUN zypper --non-interactive --gpg-auto-import-keys refresh
RUN zypper --non-interactive update

RUN zypper --non-interactive source-install --build-deps-only rawtherapee
RUN zypper --non-interactive install --recommends --force-resolution gcc49-c++
RUN zypper --non-interactive install --recommends glibc-locale sudo git ninja patterns-openSUSE-fonts gtk2-engine-clearlooks

RUN useradd -m -u 1000 -g 100 build && \
        echo "build ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/build && \
        chmod 0440 /etc/sudoers.d/build

USER build
ENV HOME=/home/build CC=gcc-4.9 CXX=g++-4.9
CMD /bin/bash -il
````

Building using OpenSUSE Leap 42.1 and GCC 5.2 worked using the following container:
````
FROM opensuse:42.1

MAINTAINER Adam Reichold "adam.reichold@t-online.de"

RUN zypper --non-interactive --gpg-auto-import-keys addrepo \
        -f http://download.opensuse.org/repositories/home:/rawtherapee/openSUSE_Leap_42.1/ \
        rawtherapee
RUN zypper --non-interactive --gpg-auto-import-keys refresh
RUN zypper --non-interactive update

RUN zypper --non-interactive source-install --build-deps-only rawtherapee
RUN zypper --non-interactive install --recommends --force-resolution gcc5-c++
RUN zypper --non-interactive install --recommends glibc-locale sudo git ninja patterns-openSUSE-fonts gtk2-engine-clearlooks

RUN useradd -m -u 1000 -g 100 build && \
        echo "build ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/build && \
        chmod 0440 /etc/sudoers.d/build

USER build
ENV HOME=/home/build CC=gcc-5 CXX=g++-5
CMD /bin/bash -il
````

I'll have a look on how to integrate this into the OBS spec files next...

**Comment by adamreichold** [comment] 2016-01-09 16:13
@mbajor Can you give me a hint? I am trying to work out the build dependencies on the various OpenSUSE versions using conditionals like
````
%if 0%{?suse_version} == 1315
BuildRequires:  gcc5-c++
%elif 0%{?suse_version} == 1320
BuildRequires:  gcc49-c++
%else
BuildRequires:  gcc-c++
%endif
````
in the RPM specification. I am using the versions described [here](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto), but it looks like am not matching the correct distributions, e.g. Leap tries to build using `gcc49-c++` instead of `gcc5-c++`.

**Comment by mbajor** [comment] 2016-01-09 16:33
@adamreichold I'm working on it:
https://build.opensuse.org/package/show/home:marcinbajor:branches:home:rawtherapee/rawtherapee
Thanks for hints !

**Comment by mbajor** [comment] 2016-01-09 16:49
@adamreichold I'm finished. Builds for openSUSE 13.2 and Leap 42.1 in progress

**Comment by adamreichold** [comment] 2016-01-09 16:53
@mbajor Nice to see its already building again for most of them.

For CentOS 7, I think the `devtoolset-3` software collection from [here](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/) would be applicable. I am not sure if this is possible on OBS, but usually one would depend on that as described [here](https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/1/html-single/Software_Collections_Guide/index.html#sect-Using_a_Software_Collection_in_Your_Application).

**Comment by adamreichold** [comment] 2016-01-09 17:19
@mbajor For SLES12, there seems to exist something called the [tool chain module](https://www.suse.com/products/server/features/modules.html), but I have no idea how to make use of that.

**Comment by adamreichold** [comment] 2016-01-09 17:29
@mbajor Do you think this is resolved or should we look into any other distributions resp. versions?

**Comment by mbajor** [comment] 2016-01-11 22:22
@adamreichold I think you can close this issue.
OBS has limited resources. I had to stop using git services(limited bandwidth) and then .git folder in source package(limited storage space).
If I would use external services, then admin of OBS will warn me.
I'm thinking about disable checking of gcc version (on OBS) and to use compiler as newer as possible.

**Closed** 2016-01-11 22:35 UTC
Labels: Compilation

**Comment by scx** [comment] 2018-12-25 08:38
Some time ago I created COPR repo for EL7:
https://github.com/Beep6581/RawTherapee/issues/5115
