### ISSUE TITLE
Automated nightly builds have stopped working (part 2)

### ISSUE THREAD

**Issue by rebio** [Beep6581/RawTherapee#6267] opened 2021-05-29 19:39 UTC
Last nightly build was on:
- Windows: 2021-05-23 (5.8-2945-g36f1300a6)
- Linux: 2021-05-24 (5.8-2948-g6189a0e)

Related:
- #6139

**Comment by heckflosse** [comment] 2021-05-29 20:11
I think we're quite accurate with nightly builds atm. Have a look at the commit history.

**Comment by heckflosse** [comment] 2021-05-29 20:14
Closed by wrong click, sorry...

**Comment by rebio** [comment] 2021-05-30 05:39
> I think we're quite accurate with nightly builds atm. Have a look at the commit history.

Not sure what you mean with 'quite accurate'

> @rebio You're testing on a wrong commit (36f1300) instead of where @heckflosse actually made the fix (https://github.com/Beep6581/RawTherapee/commit/2f2720b763eb15118d4150d97c4e21ebcb497de7)
> I cannot reproduce this issue on the latest `dev` (https://github.com/Beep6581/RawTherapee/commit/6e68cab5d970191b92e03aa7da7e6b0be7d9a3e4).
> _Originally posted by @Thanatomanic in https://github.com/Beep6581/RawTherapee/issues/6259#issuecomment-848214748_

I wanted to test if explained behaviour from #6259 does still exist. As explained in the report: The issue is only a problem on my Windows 10 machine and not my Windows 7 machine, but still seems to exist in the latest nightly build nonetheless.
And since apparently you fixed this with 2f2720b and I currently have neither the time nor the infrastructure to build RT myself I have to rely on the nightly builds for that.

**Comment by heckflosse** [comment] 2021-05-30 07:50
2f2720b was commited a few hours after 36f1300. That's what I meant by 'quite accurate'.

Meanwhile you can use a nightly windows build from [here](https://keybase.pub/gaaned92/RTW64NightlyBuilds/)

**Comment by chaimav** [comment] 2021-06-29 12:25
> [2f2720b](https://github.com/Beep6581/RawTherapee/commit/2f2720b763eb15118d4150d97c4e21ebcb497de7) was commited a few hours after [36f1300](https://github.com/Beep6581/RawTherapee/commit/36f1300a6b39f5addb3aa47f156582089d8de375). That's what I meant by 'quite accurate'.
> 
> Meanwhile you can use a nightly windows build from [here](https://keybase.pub/gaaned92/RTW64NightlyBuilds/)

It seems as those nightlies have also stopped updating :-(

**Comment by Thanatomanic** [comment] 2021-06-29 14:08
Duplicate of the pinned issue https://github.com/Beep6581/RawTherapee/issues/6139

**Closed as completed by Thanatomanic** 2021-06-29 14:08 UTC
