### ISSUE TITLE
Automated nightly builds have stopped working

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#6139] opened 2021-02-26 13:13 UTC
Hi,
I noticed the **appimages weren't updated** for a while **in the "automated builds"** download section. Since it says it's "automated" I'm reporting it here so it's not overlooked.

I'd love a new appimage build (with the latest color propagation fix in it).
Thanks a lot!

**Comment by Thanatomanic** [comment] 2021-03-20 08:08
Ping @aferrero2707 for assistance

**Comment by simohno** [comment] 2021-04-12 09:52
Hello, I now notice that also Windows nightly builds are not being updated (last is n. 2826 of 22/03/2021).

**Comment by Lawrence37** [comment] 2021-04-18 00:06
There's a Python version problem when building AppImages.
https://travis-ci.org/github/aferrero2707/rt-appimage/jobs/767355890#L4877
```
ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.
```
For the Windows builds, CMake >= 3.20.0 is not happy with UpdateInfo.cmake
https://travis-ci.org/github/aferrero2707/rt-win64/jobs/764302920#L2643
```
CMake Error at /sources/UpdateInfo.cmake:117 (endif):
  Flow control statements are not properly nested.
```

**Comment by Thanatomanic** [comment] 2021-05-08 18:07
@Beep6581 While you may have fixed the AppImage build, the Windows builds seem to have completely disappeared. Any clue as to why?

**Comment by Beep6581** [comment] 2021-05-08 22:37
@Thanatomanic both the AppImage and Win64 were broken for months. I deleted both obsolete nightly builds, and the AppImage was recreated once I fixed the AppImage build process. I spent several hours trying to get the Windows build working again, but it's not fixed yet. The process is very messy, and I fear it might be failing in a third-party dependency from a repo to which I don't have write access, and the repo owner @aferrero2707 has not been online for 2 months. But that's just preliminary results, I need to dig some more.

**Comment by Thanatomanic** [comment] 2021-05-17 05:17
Hi all, there is a steady stream of users getting lost finding a nightly build (for Windows in particular). I've just updated RawPedia to reflect the download information: http://rawpedia.rawtherapee.com/Download and I have included the automated builds by @gaaned92 and @Benitoite 
I cannot update the website, but will make a post on Pixls to address some common questions.

Edit: here's the topic on Pixls https://discuss.pixls.us/t/where-to-find-the-latest-version-of-rawtherapee-and-other-questions/25025

**Comment by aferrero2707** [comment] 2021-05-17 08:41
Hi all, this message is just to let you know that I am hopefully back to business on this, and that I plan to finally put my hands on those issues starting from today. I really apologize for the long silence, but life had been quite tough lately and my spare time was reduced to zero. Hopefully things will get better from now on...

**Comment by aferrero2707** [comment] 2021-05-18 14:32
@Beep6581 @Thanatomanic the Win64 automated build should be fixed now, or at least I have been able to generate a fresh package. The main problem that remained on top of what Morgan already fixed was a mismatch in the GPG signatures of the MSYS2 packages. The solution to properly update the keyring (see [here](https://github.com/aferrero2707/rt-win64/blob/master/ci/build-msys2.sh#L24)) looks a bit hack'ish but it actually follows the recommendations from the MSYS2 developers (see the explanations [here](https://www.msys2.org/news/#2020-06-29-new-packagers)). It seems that the MSYS2 keyring needs to be updated in two steps...

As a better and more reliable solution, I will eventually incorporate the keyring update into the Docker image that is used for the builds, but for the time being it should work fine.

**Comment by Thanatomanic** [comment] 2021-05-18 15:04
Hi @aferrero2707, thanks for this and good to see you're back! I had the keyring issue on my machine as well and it was indeed very hacky to get MSYS2 working again... but the instructions were helpful and it worked. 

I would really like to learn about how the automated builds actually work - where do they come from - how can we fix things in the future when you're not be available - etc. Would you be willing to explain?

**Comment by Thanatomanic** [comment] 2021-06-26 09:43
The builds have stopped again at June 4th. @Beep6581 @aferrero2707 
Is there something I could do to help fixing these kind of issues sooner, if time permits?

**Comment by aferrero2707** [comment] 2021-06-26 14:49
There is currently an issue in the updating of the rocker image used for
the builds. I am investigating, but I will probably have to generate a new
image from scratch.

Le sam. 26 juin 2021 à 11:43, Thanatomanic ***@***.***> a
écrit :

**Comment by Beep6581** [comment] 2021-07-01 09:25
@aferrero2707 as https://www.travis-ci.org/ is now dead, could you grant me and @Thanatomanic access to `rt-appimage` and `rt-win64` on https://www.travis-ci.com/ ?

**Comment by Beep6581** [comment] 2021-08-10 10:51
Ping @aferrero2707

**Comment by boehs** [comment] 2021-10-03 19:32
At this point I think it is wise to start over

**Comment by simohno** [comment] 2021-10-03 19:50
I run Windows, and personally rely on "The unofficial builds by André Gauthier" Mentioned in the [donwloads page of RawPedia](https://rawpedia.rawtherapee.com/Download) (a really appreciated contribution!). There are also for MAC (by Richard Barber). Not for Linux.
One has just to unzip the .7z file.

**Comment by Thanatomanic** [comment] 2021-10-04 06:45
> 
> 
> At this point I think it is wise to start over

I am neither the owner of this repo, nor all too familiar with the process of doing CI, either externally or through GitHub Actions (which may incur charges iirc). So, while I would love to change something about this situation, we need help on how to approach this and the cooperation of @Beep6581.

**Comment by jonathanBieler** [comment] 2021-10-04 18:22
As I understand the current [workflow](https://github.com/Beep6581/RawTherapee/blob/dev/.github/workflows/main.yml) is already compiling RT and producing downloadable artifacts (do these work?), the only issue being that it's only for macos.

If the build instruction are the same across platforms adding windows and linux should be quite easy, e.g. : 

https://www.edwardthomson.com/blog/github_actions_3_crossplatform_builds.html

Edit : I see that installing dependencies is platform specific, so it's not a matter of adding a single line...

**Comment by Lawrence37** [comment] 2021-10-10 00:55
> ... through GitHub Actions (which may incur charges iirc)

It's completely free for public repositories. https://github.com/features/actions#pricing-details

**Comment by Lawrence37** [comment] 2021-10-17 05:58
I'm experimenting with building AppImages in GitHub. https://github.com/Lawrence37/RawTherapee/actions/workflows/appimage.yml

**Comment by chaimav** [comment] 2021-12-09 14:45
Are there any nightly builds currently being updated? Even ganeed92's builds seem to be frozen https://keybase.pub/gaaned92/RTW64NightlyBuilds/

**Comment by gaaned92** [comment] 2021-12-10 10:45
I had problems with MSYS2 and I reinstalled it.
New builds should be again available.

**Comment by gaaned92** [comment] 2021-12-10 10:50
There is a guy building appimages https://apprepo.de/appimage/rawtherapee

**Comment by chaimav** [comment] 2021-12-10 15:20
> I had problems with MSYS2 and I reinstalled it. New builds should be again available.

Thanks for your efforts!

**Comment by chaimav** [comment] 2021-12-10 15:45
@gaaned92 I just tried your -3058 Skylake build and crashes on open. Deleting my options file allows it to open, but it crashed shortly thereafter when I was navigating to a folder. Do you want me to file a bug report or is the issue with your build process?

**Comment by gaaned92** [comment] 2021-12-10 22:17
@chaimav I cannot reproduce here. It keeps working after processing files, changing dir...
 I will make more tests tomorrow.
Don't you have somewhere a corrupted file?
Edit: I observe that it is prone to crash on directories with jpg files. TBC

**Comment by Beep6581** [comment] 2022-01-12 16:58
Following Travis-CI's acquisition in 2019, it no longer offers free build infrastructure for open-source projects. GitHub Actions seems like the way forward.

**Comment by Lawrence37** [comment] 2022-01-13 05:40
They are advertising free build minutes for open source projects. https://app.travis-ci.com/plans
https://blog.travis-ci.com/oss-announcement

**Comment by chaimav** [comment] 2022-01-17 22:57
> @chaimav I cannot reproduce here. It keeps working after processing files, changing dir... I will make more tests tomorrow. Don't you have somewhere a corrupted file? Edit: I observe that it is prone to crash on directories with jpg files. TBC

@gaaned92 I just tried your latest build (3065 Skylake) and it once again crashed on open. If there is any troubleshooting you want me to do, let me know.

**Comment by Benitoite** [comment] 2022-01-17 23:10
@chaimav  is this crash involving a symbol in liblerc?  https://discuss.pixls.us/t/problem-with-rt-5-8-3065/28872/21

**Comment by chaimav** [comment] 2022-01-18 13:12
I get no error message. It just opens for a about a second or two then disappears. I have been having similar issues with the past couple of @gaaned92's builds

**Comment by Lawrence37** [comment] 2022-01-22 06:30
I'm adding a workflow for Windows. It is successfully compiling and uploading the builds. I just need to verify they run correctly and add the installer.

**Comment by Thanatomanic** [comment] 2022-02-07 04:42
Now that https://github.com/Beep6581/RawTherapee/pull/6413 is merged, @Lawrence37 has made an important step to finally close this issue. 🥳 

I have one little request though: could you rename the artifacts something else than `WinVista_64`? I think this may confuse  users, doubting whether they can use the build if they do not use Windows Vista. Perhaps just `win64`?

@Benitoite, could you look into adjusting your macOS workflow so that it also puts its artifacts into here https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions? That would complete the set of nightly builds.

**Comment by Lawrence37** [comment] 2022-02-07 05:16
@Thanatomanic I followed the naming convention from RawPedia (http://rawpedia.rawtherapee.com/Windows#Creating_a_distributable_package), but I will change it if there is agreement.

**Comment by Thanatomanic** [comment] 2022-02-07 05:51
Seeing as that portion of RawPedia is probably a few years old, I don't think there is anything against a different name. We'll just update RawPedia accordingly.

**Comment by Benitoite** [comment] 2022-02-07 06:05
@Thanatomanic Yes this can be done but are you sure you want those mixed in there?  They build as a check but the artefacts don't really work because they don't get notarized.   It would be confusing, I think, to present them as useable.

**Comment by Thanatomanic** [comment] 2022-02-07 06:20
Forgive my ignorance of how macOS operates. If I understand you correctly, the dmg inside the zip that is produced e.g. [here](https://github.com/Beep6581/RawTherapee/actions/runs/1804238479), cannot simply be used as updated version of RT?
If so, then we can definitely close this issue.

I will probably remove the older automated build to avoid confusion. Fwiw, the new one can become the official one. Any objection to this?

**Comment by Lawrence37** [comment] 2022-02-07 06:32
Seeing that there is only one Windows download option on the website, I guess `win64` or even just `win` suffices, as there is no need to distinguish between multiple Windows builds. I will make the name change.

**Comment by Benitoite** [comment] 2022-02-07 06:40
@Thanatomanic Right, to work on macOS the app and dmg must go thru a proprietary Apple malware check.  The automation skips that post compilation codesigning and notary transmission.

**Comment by Beep6581** [comment] 2022-02-08 11:33
> They are advertising free build minutes for open source projects. https://app.travis-ci.com/plans https://blog.travis-ci.com/oss-announcement

They're zig-zagging and doing 180° turns in their policy.

https://news.ycombinator.com/item?id=25338983

The info on their website is inconsistent.

https://docs.travis-ci.com/user/billing-overview/#credits-vs-oss-only-credits

> On occasion, an allotment of OSS Only credits may be granted by Travis CI. These credits may be used only for builds over public repositories and are meant for open source support. The OSS credits may be assigned as a one-time pool or renewable pool, subject to a case-by-case assessment of Travis CI staff.

It's unclear what the situation currently is - either open-source projects can't be built for free at all (not talking about a trial), or best case scenario is that open-source projects might get some free credits at the discretion of Travis staff, and these credits might be a recurring or one-time thing, again at the discretion of Travis staff. Regardless, providing credit card details is required, so I'm not interested, and very glad that you got GitHub Actions working.

**Comment by Beep6581** [comment] 2022-02-08 11:34
I closed this by accident - feel free to re-open if needed.

**Comment by Beep6581** [comment] 2022-02-08 11:51
> could you rename the artifacts something else than `WinVista_64`? I think this may confuse users, doubting whether they can use the build if they do not use Windows Vista. Perhaps just `win64`?

Haven't we discussed and agreed to this years ago? Anyhow I certainly agree. The only actively supported versions of Windows are 10 and 11. If someone is still making builds for versions of Windows older than that, I don't think that should come at a cost of confusing users of contemporary versions.

> Seeing that there is only one Windows download option on the website, I guess `win64` or even just `win` suffices, as there is no need to distinguish between multiple Windows builds. I will make the name change.

:+1:

**Comment by Beep6581** [comment] 2022-02-08 11:55
Any objection to deleting the [`nightly`](https://github.com/Beep6581/RawTherapee/releases/tag/nightly) tag and the `Automated Builds` release? Then updating `nightly-github-actions`, RawPedia and the website accordingly.

**Comment by Thanatomanic** [comment] 2022-02-12 06:09
@Beep6581 I just did the following:

- [x] Made the necessary changes for lensfun and win64 name
- [x] Removed old Automated Build 
- [x] Removed nightly tag
- [x] Renamed Lawrence's build to 'Automated Build'
- [x] Updated description, see https://github.com/Beep6581/RawTherapee/releases/tag/nightly-github-actions

What I haven't done is update RawPedia, because it doesn't let me login (I have this problem regularly actually... after the login screen, it just returns me to the homepage without any message, but I'm not logged in). I'll try this again later.

We should probably also dedicate a post to this change on Pixls.

**Comment by rebio** [comment] 2022-02-12 14:48
A request for the naming: Could we improve on the naming scheme a bit to make it more clear?

Eg. _RawTherapee_dev_win64_debug_ and _RawTherapee_dev_WinVista_64_debug_ seem to be the same. Because of this thread I would guess that it's an old version that was not deleted. If I didn't know this page existed I would be very confused.

Could the full version name (eg. 5.8-3072-g9a1423db6) or at least the number behind the version (eg. 5.8-3072) be added to the name so that it's more clear?

Also it's not very clear where the difference between _debug_ and _release_ release is. The _AboutThisBuild.txt_ shows some different compile flags, but aside from the size difference that's pretty much all you can _from the outside_. In other words: I want to test the latest features of RT and check if there are any bugs. Which one should I pick (I'm more thinking about an average user who might just want to check out the new features).

**Comment by Lawrence37** [comment] 2022-02-12 17:39
> Eg. _RawTherapee_dev_win64_debug_ and _RawTherapee_dev_WinVista_64_debug_ seem to be the same. Because of this thread I would guess that it's an old version that was not deleted.

Right. I've deleted the WinVista_64 files.

> Could the full version name (eg. 5.8-3072-g9a1423db6) or at least the number behind the version (eg. 5.8-3072) be added to the name so that it's more clear?

If someone with the right knowledge wants to make this change, it would be welcomed. As you can see, old uploads are not deleted automatically, but rather replaced with new files of the same name. For me, it's not worth the time and effort to learn how to delete old files. That's why the `...-AboutThisBuild.txt`s exist.
 
> Also it's not very clear where the difference between _debug_ and _release_ release is.

I updated the description to explain the difference.

**Comment by rebio** [comment] 2022-02-13 23:08
@Thanatomanic @Beep6581 RawPedia needs a small link update for the nightly build: http://rawpedia.rawtherapee.com/Download

**Comment by Thanatomanic** [comment] 2022-02-14 04:50
RawPedia is now updated! This officially closes this issue. Please make requests for name changes in a new issue.

**Closed as completed by Thanatomanic** 2022-02-14 04:50 UTC
Labels: priority: critical, scope: distribution

**Comment by Beep6581** [comment] 2022-02-21 10:12
@Thanatomanic thank you.

> What I haven't done is update RawPedia, because it doesn't let me login (I have this problem regularly actually... after the login screen, it just returns me to the homepage without any message, but I'm not logged in).

I've had the same problem across all computers and Chrome and Firefox. It's somehow related to HTTP/HTTPS. I notice that if I manually edit the URL and change HTTP to HTTPS during login, or maybe before login (haven't been able to reliably reproduce the solution yet), then login finally works. Alternatively, I'm forced to log in via incognito mode, that always works. Very frustrating.

**Comment by TechXavAL** [comment] 2022-02-21 12:39
@Beep6581 

It seems to be related with how the server is configured:
* if you login through http (unsecure connection), you're logged in and sent to the unsecure home page. You can see your account icon on the right side of the top bar.
* if you login through https (secure connection), you're logged in **but** sent to the unsecure home page (http), so you are lead to believe you're not succesfully logged in (you still see the right hamburguer and the _login_ link on the right pane). Just edit the url and point to the https page (from _http_ to _https_), so you can see that you're logged in, indeed (the account icon on the top bar).

HTH

**Comment by Beep6581** [comment] 2022-02-21 14:17
@TechXavAL yes, and on top of that the web browser seems to do some smart-assery, as sometimes it just refuses to use the HTTP/HTTPS method I enter and changes it to the opposite. Unfortunately I don't have access to the RawPedia server, and nothing came of my requests to have it looked at.

**Comment by TechXavAL** [comment] 2022-02-21 14:31
@Beep6581 

Well, while it is fixed (if that ever happens), a workaround is using an extension/plugin:

https://www.eff.org/https-everywhere

This shouldn't be the ideal solution, but I think it doesn't hurt anyway, as it is useful in all other internet related interactions...

The only doubt a user may have is if _Encrypt All Sites Eligible_ should be turned on or not... Well, it will depend on how paranoid you are about your privacy...

**Comment by Beep6581** [comment] 2022-02-21 14:34
@TechXavAL thanks for that tip!
