### ISSUE TITLE
Add support for Panasonic DC-S5

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#5909] opened 2020-09-17 21:26 UTC
Raw files can be found [here](https://www.imaging-resource.com/PRODS/panasonic-s5/panasonic-s5A7.HTM).

The raw files currently can be loaded and worked but the colors are muted and the exposure is way off (I have to reduce it by at least 2 stops).

**Comment by Thanatomanic** [comment] 2020-09-21 10:37
@Barugon Can you indicate which sample you tried that gave a too high exposure? My randomly chosen sample looks fine.

As for the color support either one of two things need to happen: [Adobe needs to profile the camera](https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html) so that we can copy the color matrix, or somebody needs to provide the [appropriate calibration shots ](http://rawpedia.rawtherapee.com/How_to_create_DCP_color_profiles)so we can create a DCP profile to ship with RT.

**Comment by Barugon** [comment] 2020-09-21 17:31
@Thanatomanic 
All of the RW2 files do it. Here's a screenshot of `S5hSLI000100NR1.RW2` using the neutral profile.

![Screenshot from 2020-09-21 10-28-06](https://user-images.githubusercontent.com/16503728/93800512-8aa74a00-fbf5-11ea-825e-ee16a1b3f9a7.png)

**Comment by Barugon** [comment] 2020-09-21 17:33
This is with Standard Film Curve - ISO Low applied.

![Screenshot from 2020-09-21 10-32-11](https://user-images.githubusercontent.com/16503728/93800740-e376e280-fbf5-11ea-93f3-ac39634a5297.png)

**Comment by Thanatomanic** [comment] 2020-09-21 17:49
@Barugon I suppose this is a bug in 5.8 and has been fixed in the current development builds: https://github.com/Beep6581/RawTherapee/commit/b1901997a794799bda406fea385fd3d9442b16ae

The rest of my remarks stand.

**Comment by Barugon** [comment] 2020-09-21 18:18
Cool, I'll take a look.

**Comment by Entropy512** [comment] 2020-09-24 14:25
Small warning:  If you live in North America, your ability to get daylight calibration shots is currently compromised.  The California wildfire smoke has reached the stratosphere and is blowing eastwards (on the jet stream?) and is going to throw off any daylight results.  :(

**Comment by Barugon** [comment] 2020-10-19 19:17
It looks like Camera Raw now supports the Panasonic S5:
https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html

**Comment by Thanatomanic** [comment] 2020-10-19 20:03
I've update Adobe Camera Raw to version 13.0, which should support the DC-S5, however, the camera does not show up in my `ProgramData\Adobe\CameraRaw\CameraProfiles\Camera\` directory. The newly supported Sony ILCE-7SM3 does should up as a separate folder.
I am not sure what is going on. @Beep6581 do you have any idea? Could Adobe be reusing profiles from other camera's? Is there a way to find out?

**Comment by Barugon** [comment] 2020-10-19 23:46
If I edit the exif, change the model name to DC-S1 and edit the file with RawTherapee then the colors look correct.
```
exiftool -Model=DC-S1 S5hSLI000100NR1.RW2
```

**Comment by Beep6581** [comment] 2020-11-07 21:45
Closing as duplicate of #5951

**Closed as completed by Beep6581** 2020-11-07 21:45 UTC
Labels: type: feature, scope: calibration

**Comment by Beep6581** [comment] 2020-11-07 22:36
@Thanatomanic I diff'd Adobe DNG Converter 13.0 against 12.2 and confirm that 13.0 ships no DCP. Seems they just use the matrix. I also found no known aliases for the DC-S5.

**Comment by Barugon** [comment] 2020-11-08 09:33
@Beep6581 
Please see my comments [here](https://github.com/Beep6581/RawTherapee/commit/63001c41a338f5e78adee0e8a21b3af52be2626c).
