### ISSUE TITLE
Switching between images goes through blank space

### ISSUE THREAD

**Issue by strump** [Beep6581/RawTherapee#4546] opened 2018-05-11 08:02 UTC
```
Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON
```

OS: Windows 10, v.1709, x64, Russian
RawTherapee: http://rawtherapee.com/releases_head/windows/RawTherapee_5.4_WinVista_64.zip

### Steps to reproduce:*

1. Open any image in RawTherapee 5.4;
2. Switch to the next image in list (hitting F4 or double clicking).

**Actual result:** current image is hidden for a split second. Next image is displayed.
**Expected result:** Next image is displayed without any pause.

![rawtherapee_5 4_image_switch](https://user-images.githubusercontent.com/720808/39913392-5be1191a-550a-11e8-980e-b2304d80738a.gif)

Previous version RawTherapee 5.3 works as expected (no blank space between images):

![rawtherapee_5 3_image_switch](https://user-images.githubusercontent.com/720808/39913410-6827adb0-550a-11e8-9b4a-9017a91b1cdc.gif)

**Comment by Floessie** [comment] 2018-05-11 10:00
Hi @strump,

Thanks for the detailed bug report. I'm afraid, this is a duplicate of #4476. But gladly, this has already been fixed in #4523. :smile:

Best,
Flössie

**Closed as completed by Floessie** 2018-05-11 10:00 UTC
