### ISSUE TITLE
[OSX] MacOS/rawtherapee-cli not linking to bundled libraries

### ISSUE THREAD

**Issue by Benitoite** [Beep6581/RawTherapee#3924] opened 2017-06-14 04:33 UTC
I noticed rawtherapee-cli is not receiving the same linking treatment that rawtherapee-bin is getting.

```
otool -L /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli 
/Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli:
	/opt/local/lib/libcairomm-1.0.1.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/local/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.8.0)
	/opt/local/lib/libsigc-2.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libexpat.1.dylib (compatibility version 8.0.0, current version 8.2.0)
	/opt/local/lib/libgtkmacintegration-gtk3.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	/opt/local/lib/libfftw3f.3.dylib (compatibility version 9.0.0, current version 9.5.0)
	/opt/local/lib/libgiomm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/local/lib/libgio-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	/opt/local/lib/libglibmm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/local/lib/libgobject-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	/opt/local/lib/libglib-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	/opt/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/opt/local/lib/libgthread-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	/opt/local/lib/libiptcdata.0.dylib (compatibility version 4.0.0, current version 4.3.0)
	/opt/local/lib/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	/opt/local/lib/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	/opt/local/lib/libpng16.16.dylib (compatibility version 46.0.0, current version 46.0.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.6.0)
	/opt/local/lib/libomp/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

vs rawtherapee-bin

```
otool -L /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-bin 
/Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-bin:
	@rpath/libexpat.1.dylib (compatibility version 8.0.0, current version 8.2.0)
	@rpath/libgtkmacintegration-gtk3.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libfftw3f.3.dylib (compatibility version 9.0.0, current version 9.5.0)
	@rpath/libgiomm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgio-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libglibmm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgobject-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libglib-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	@rpath/libsigc-2.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgthread-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libgtkmm-3.0.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libatkmm-1.6.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libgdkmm-3.0.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libpangomm-1.4.1.dylib (compatibility version 2.0.0, current version 2.30.0)
	@rpath/libgtk-3.0.dylib (compatibility version 2201.0.0, current version 2201.11.0)
	@rpath/libgdk-3.0.dylib (compatibility version 2201.0.0, current version 2201.11.0)
	@rpath/libpangocairo-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.5.0)
	@rpath/libpango-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.5.0)
	@rpath/libatk-1.0.0.dylib (compatibility version 22210.0.0, current version 22210.1.0)
	@rpath/libcairo-gobject.2.dylib (compatibility version 11403.0.0, current version 11403.8.0)
	@rpath/libcairomm-1.0.1.dylib (compatibility version 6.0.0, current version 6.0.0)
	@rpath/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.8.0)
	@rpath/libgdk_pixbuf-2.0.0.dylib (compatibility version 3601.0.0, current version 3601.5.0)
	@rpath/libiptcdata.0.dylib (compatibility version 4.0.0, current version 4.3.0)
	@rpath/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	@rpath/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libpng16.16.dylib (compatibility version 46.0.0, current version 46.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/libtiff.5.dylib (compatibility version 8.0.0, current version 8.6.0)
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

AboutThisBuild.txt:
```
Version: 5.1-60-g2fcb7d96
Branch: dev
Commit: 2fcb7d96
Commit date: 2017-06-13
Compiler: clang-mp-3 3.9.1
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.16.0
Build type: release
Build flags: -arch x86_64 -O3 -std=c++11 -mtune=generic -Werror=unused-label -mmacosx-version-min=10.9 -flto -fopenmp=libomp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON

```

**Comment by Benitoite** [comment] 2017-06-14 04:55
forgot to tag you @partha1b and @ion12

**Comment by Benitoite** [comment] 2017-06-16 08:28
Manually doing install_name_tool on the rawtherapee-cli executable for each dependency does work, and I guess I could insert that into macosx_bundle.sh, but I wonder if there is an elegant portable solution, maybe duplicate something being done to fix the install names in rawtherapee-bin to fix -cli?

I got a working zipped dmg by putting this into tools/osx/macosx_bundle.sh right before the dmg gets created.

```
install_name_tool -change /opt/local/lib/libcairomm-1.0.1.dylib @rpath/libcairomm-1.0.1.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /usr/local/lib/libcairo.2.dylib @rpath/libcairo.2.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libsigc-2.0.0.dylib @rpath/libsigc-2.0.0.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libexpat.1.dylib @rpath/libexpat.1.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libgtkmacintegration-gtk3.2.dylib @rpath/libgtkmacintegration-gtk3.2.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libfftw3f.3.dylib @rpath/libfftw3f.3.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libgiomm-2.4.1.dylib @rpath/libgiomm-2.4.1.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libgio-2.0.0.dylib @rpath/libgio-2.0.0.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libglibmm-2.4.1.dylib @rpath/libglibmm-2.4.1.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libgobject-2.0.0.dylib @rpath/libgobject-2.0.0.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libglib-2.0.0.dylib @rpath/libglib-2.0.0.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libintl.8.dylib @rpath/libintl.8.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libgthread-2.0.0.dylib @rpath/libgthread-2.0.0.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libiptcdata.0.dylib @rpath/libiptcdata.0.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libjpeg.9.dylib @rpath/libjpeg.9.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/liblcms2.2.dylib @rpath/liblcms2.2.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libpng16.16.dylib @rpath/libpng16.16.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libz.1.dylib @rpath/libz.1.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libtiff.5.dylib @rpath/libtiff.5.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -change /opt/local/lib/libomp/libomp.dylib @rpath/libomp.dylib /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
install_name_tool -add_rpath @executable_path/../Frameworks /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
```

```
otool -L /Applications/RawTherapee.app/Contents/MacOS/rawtherapee-cli 
/Applications/RawTherapee.app/Contents/MacOS/rawtherapee-cli:
	@rpath/libcairomm-1.0.1.dylib (compatibility version 6.0.0, current version 6.0.0)
	@rpath/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.8.0)
	@rpath/libsigc-2.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libexpat.1.dylib (compatibility version 8.0.0, current version 8.2.0)
	@rpath/libgtkmacintegration-gtk3.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libfftw3f.3.dylib (compatibility version 9.0.0, current version 9.5.0)
	@rpath/libgiomm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgio-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libglibmm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgobject-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libglib-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	@rpath/libgthread-2.0.0.dylib (compatibility version 5001.0.0, current version 5001.3.0)
	@rpath/libiptcdata.0.dylib (compatibility version 4.0.0, current version 4.3.0)
	@rpath/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	@rpath/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libpng16.16.dylib (compatibility version 46.0.0, current version 46.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/libtiff.5.dylib (compatibility version 8.0.0, current version 8.6.0)
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

**Comment by Beep6581** [comment] 2017-07-15 21:40
@Hombre57 is this a cmake issue?

**Comment by Hombre57** [comment] 2017-07-16 00:49
Considering [this](https://cmake.org/cmake/help/v3.9/prop_tgt/MACOSX_RPATH.html) and [this cmake policy](https://cmake.org/cmake/help/v3.9/policy/CMP0042.html#policy:CMP0042), the default is to use `@rpath/` everywhere unless `INSTALL_NAME_DIR` or `CMAKE_INSTALL_NAME_DIR` is set.

Since we do not set those parameters, I don't understand what can happen here. What is your _cmake_ version ? If the cmakelists are working fine with gcc, perhaps that the problem lye between cmake and clang ?

In `rtgui/CMakeLists.txt`, try to swap the last two lines and see if the result is the same ?

**Comment by Hombre57** [comment] 2017-07-16 00:57
@Benitoite Forget the last comment, the problem is in `tools/osx/macosx_bundle.sh`, see line 165. I guess that the fix is to update the regex at line 158. Something for @Beep6581 ? :)

**Comment by Beep6581** [comment] 2017-07-16 14:45
I can't test any of that code, can't even open a DMG file, so I don't know what this script expects to find and what it's supposed to do with what it finds but fails at doing. It's a job for someone with macOS.

Having said that, this might be enough:
```diff
diff --git a/tools/osx/macosx_bundle.sh b/tools/osx/macosx_bundle.sh
index 59e8d48f..4d92192f 100644
--- a/tools/osx/macosx_bundle.sh
+++ b/tools/osx/macosx_bundle.sh
@@ -155,7 +155,7 @@ ditto {"${GTK_PREFIX}","${RESOURCES}"}/share/icons/Adwaita/index.theme
 # fi
 
 # Install names
-find -E "${CONTENTS}" -type f -regex '.*/(rawtherapee|.*\.(dylib|so))' | while read x; do
+find -E "${CONTENTS}" -type f -regex '.*/(rawtherapee-cli|rawtherapee|.*\.(dylib|so))' | while read x; do
     msg "Modifying install names: ${x}"
     {
         # id

```

Please test it @Benitoite

**Comment by Benitoite** [comment] 2017-07-16 15:38
Thanks @beep6581!
 Will test.

**Comment by Beep6581** [comment] 2017-07-16 15:48
The exact purpose of this Bash script, what it should output with what input, is not clear to me, as it mangles a whole bunch of things, uses external languages (awk) and commands. I'm quite sure it could do most of these things while staying only in Bash and being more explicit.

For example this:
```bash
# Install names
find -E "${CONTENTS}" -type f -regex '.*/(rawtherapee-cli|rawtherapee|.*\.(dylib|so))' | while read x; do
    msg "Modifying install names: ${x}"
    {
        # id
        case ${x} in *.dylib) echo "   install_name_tool -id '@rpath/$(basename "${x}")' '${x}'";; esac
        # names
        GetDependencies "${x}" | while read y; do
            echo "   install_name_tool -change '${y}' '@rpath/$(basename "${y}")' '${x}'"
        done
    } | bash -v
done
```
Could be written like this:
```bash
while read -r -d '' f; do
    msg "Modifying install names: ${f}"
    if [[ $f = *.dylib ]]; then
        install_name_tool -id "@rpath/$(basename "$f")" "$f"
    fi
    GetDependencies "$f" | while read -r y; do
        install_name_tool -change "$y" "@rpath/$(basename "$y")" "$f"
    done
done < <(find "${CONTENTS}" -type f \( -ipath "*/rawtherapee" -or -ipath "*/rawtherapee-cli" -or -ipath "*.dylib" -or -ipath "*.so" \) -print0)
```

I don't vouch that my example works since I can't test it, but to me it's much more clear what's going on, and it's safer. The `GetDependencies` part could be further simplified. In fact the whole "Manually doing install_name_tool" comment https://github.com/Beep6581/RawTherapee/issues/3924#issuecomment-308966301 suggests that what needs to be done is much simpler than the way it's currently being done, but you get the picture.

This is a job for a macOS user though, and I'm happy enough with the one-liner in the previous comment if it works.

**Comment by Partha1b** [comment] 2017-07-16 21:28
@Beep6581 & @Benitoite 

I am not sure what role a command line interface plays on a Mac and how or why it is even executed.

However, whatever app you launch you just have to make sure that it's able to find all its dependencies that are not part of the system.

Hope that makes sense or helps.

**Comment by Benitoite** [comment] 2017-07-16 21:52
@Beep6581 Your one-line patch worked fine; both executables properly install_name'd.

```
otool -L /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-bin 
/Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-bin:
	@rpath/libexpat.1.dylib (compatibility version 8.0.0, current version 8.3.0)
	@rpath/libgtkmacintegration-gtk3.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libfftw3f.3.dylib (compatibility version 9.0.0, current version 9.5.0)
	@rpath/libgiomm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgio-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libglibmm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgobject-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libglib-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	@rpath/libsigc-2.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgthread-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libgtkmm-3.0.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libatkmm-1.6.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libgdkmm-3.0.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libpangomm-1.4.1.dylib (compatibility version 2.0.0, current version 2.30.0)
	@rpath/libgtk-3.0.dylib (compatibility version 2201.0.0, current version 2201.16.0)
	@rpath/libgdk-3.0.dylib (compatibility version 2201.0.0, current version 2201.16.0)
	@rpath/libpangocairo-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.6.0)
	@rpath/libpango-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.6.0)
	@rpath/libatk-1.0.0.dylib (compatibility version 22410.0.0, current version 22410.1.0)
	@rpath/libcairo-gobject.2.dylib (compatibility version 11403.0.0, current version 11403.10.0)
	@rpath/libcairomm-1.0.1.dylib (compatibility version 6.0.0, current version 6.0.0)
	@rpath/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.10.0)
	@rpath/libgdk_pixbuf-2.0.0.dylib (compatibility version 3601.0.0, current version 3601.6.0)
	@rpath/libiptcdata.0.dylib (compatibility version 4.0.0, current version 4.3.0)
	@rpath/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	@rpath/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libpng16.16.dylib (compatibility version 47.0.0, current version 47.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/libtiff.5.dylib (compatibility version 8.0.0, current version 8.6.0)
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
imac:build tune$ otool -L /Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli
/Users/tune/repo-rt/build/RawTherapee.app/Contents/MacOS/rawtherapee-cli:
	@rpath/libcairomm-1.0.1.dylib (compatibility version 6.0.0, current version 6.0.0)
	@rpath/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.10.0)
	@rpath/libsigc-2.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libexpat.1.dylib (compatibility version 8.0.0, current version 8.3.0)
	@rpath/libgtkmacintegration-gtk3.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libfftw3f.3.dylib (compatibility version 9.0.0, current version 9.5.0)
	@rpath/libgiomm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgio-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libglibmm-2.4.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgobject-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libglib-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	@rpath/libgthread-2.0.0.dylib (compatibility version 5304.0.0, current version 5304.0.0)
	@rpath/libiptcdata.0.dylib (compatibility version 4.0.0, current version 4.3.0)
	@rpath/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
	@rpath/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	@rpath/libpng16.16.dylib (compatibility version 47.0.0, current version 47.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	@rpath/libtiff.5.dylib (compatibility version 8.0.0, current version 8.6.0)
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)

```

**Comment by Beep6581** [comment] 2017-07-16 22:23
@Benitoite I committed the change along with some safety fixes, can you check that they're not safety breakages? :) i.e. the script from `dev` should work.

**Comment by Benitoite** [comment] 2017-07-17 02:14
@Beep6581 Your fixes work for me. Thanks.

**Closed as completed** 2017-07-17 07:46 UTC
