### ISSUE TITLE
Add support of EXR images 

### ISSUE THREAD

**Issue by Nicknroll** [Beep6581/RawTherapee#6040] opened 2021-01-01 18:06 UTC
Hello, thank you for great app!
I'd wish if RawTherapee has support of Open EXR images cause it is the only way to get 32bit images from Blender3D.

-Nick

**Comment by Thanatomanic** [comment] 2021-01-01 19:17
Duplicate of https://github.com/Beep6581/RawTherapee/issues/1895

**Closed as completed by Thanatomanic** 2021-01-01 19:17 UTC
