### ISSUE TITLE
HUAWEI WAS-LX1A Open Camera (app) DNG

### ISSUE THREAD

**Issue by falket** [Beep6581/RawTherapee#4511] opened 2018-04-17 09:12 UTC
I'm trying to open a dng created with open camera app and taken with a Huawei p10 lite

Colors are really off (bayer filter rotated?)

https://we.tl/7ZTPw32MRl

(it's not mine, as soon as i'll get it i'll upload an horizontal file to raw.pixls.us)

Thank you,

**Comment by Beep6581** [comment] 2018-04-17 09:55
Another smartphone camera with a broken-by-design DNG. Though this is not the cause of the wrong colors, the illuminants are in the wrong order, and you should report this to Open Camera.

**Comment by falket** [comment] 2018-04-17 14:02
Done -> https://sourceforge.net/p/opencamera/tickets/431/

A raw will soon be avaible to raw.pixls.us.

Why "a broken-by-design DNG"?

Thank you.

**Comment by Beep6581** [comment] 2018-04-17 17:36
In the sense that it wasn't broken by the software which downloads photos from the smartphone nor by some downstream DNG converter, but by the program which created it.

**Comment by SimonSegerblomRex** [comment] 2021-08-30 18:13
This issue can be closed. (It's just the wrong CFA pattern specified in the file. [Apparently](https://sourceforge.net/p/opencamera/tickets/431/#918a) it's been fixed by the phone manufacturer.)

**Closed as completed** 2021-08-31 08:08 UTC
Labels: scope: file format
