### ISSUE TITLE
Repeated Crash with One Photo (out of 29)

### ISSUE THREAD

**Issue by buddhaauthor** [Beep6581/RawTherapee#3323] opened 2016-06-01 03:31 UTC
Hi All,

RT is repeatedly crashing with one photo in my queue. I have no idea why except that it is the only photo in the queue that I cropped. I wonder if sending this bug report is useful, since I have the crash report from my Mac. In the hope that it is, I attach it.

Cheers!

[RT Crash.txt](https://github.com/Beep6581/RawTherapee/files/292614/RT.Crash.txt)

**Comment by buddhaauthor** [comment] 2016-06-01 03:45
Oh, don't know why the version of RT is not appearing. In any case, it was many months old so I just upgraded to version 4.2.753 and had the same crash.

**Comment by NextTherapist** [comment] 2016-06-01 15:11
Try to use the newest builds which you can find here (but for Windows): https://discuss.pixls.us/t/new-windows-builds/615
Older builds had among other things this bug: https://github.com/Beep6581/RawTherapee/issues/3084
They crashed with only one image file without exif metadata in the folder.
I do not know if this is the reason for your crash, but they really do a lot of bug correction every week...

**Comment by Beep6581** [comment] 2016-06-02 18:52
@buddhaauthor hey, unfortunately all our current OS X builds are old, but luckily ion12 is working on a new one. Once a new one becomes available, test it and open a new issue with a stack backtrace + raw file + PP3, if you can reproduce the crash there. I will close this issue so it doesn't hang open when it refers to an old build.

The new build will be on our website, hopefully soon, but you can also keep an eye on this issue:
https://github.com/Beep6581/RawTherapee/issues/3324

**Closed by Beep6581** 2016-06-02 18:52 UTC

**Comment by buddhaauthor** [comment] 2016-06-02 19:25
Okay, thanks for the course of action. I’ll followup when the new build is out.

Cheers,

Franz
