### ISSUE TITLE
HiDPI scaling issues

### ISSUE THREAD

**Issue by hyphone** [Beep6581/RawTherapee#3187] opened 2016-02-29 22:06 UTC
I just tried the GTK3 version on my HiDPI display that is scaled 2x in Gnome 3.18 (font is scaled at 0,75).

The thumbnails and the navigator window are half the size:
http://oi68.tinypic.com/8zg29d.jpg
http://oi66.tinypic.com/28tb95c.jpg

**Comment by Hombre57** [comment] 2016-02-29 23:22
TODO: taking car of `Gtk::Widget::get_scale_factor ()` , and update by listening to `configure`events.

**Comment by Hombre57** [comment] 2016-03-01 11:04
There's also another way to solve this issue : set the display scale factor to 1 (possible on a per application basis) and provide an iconset dedicated to HiDPI display. Not sure if Gtk provides a secondary iconset (i.e. unscaled) though.

**Comment by Beep6581** [comment] 2016-03-01 11:55
Can't we use SVG directly?

**Comment by Hombre57** [comment] 2016-03-01 16:12
Probably, but I don't know for Gtk's stock icons.

**Comment by TurkeyMan** [comment] 2016-04-20 00:08
I just tried tried the latest build from the Arch community repo, I think it's current (4.2.448).
Scaling is not great. Looks like some scaling has been performed, but icons are tiny, some text is still too small to see. In the settings dialog for instance, it looks like text has been scaled, but the layout ( positioning, gaps between the text) have not been scaled, and everything feels really bunched up.
Needs work. Running 4k should look exactly like running 1920x1080, except with clearer text/icons.

On: Linux, Cinnamon, 4k (ie, 2x scaling).

**Comment by hyphone** [comment] 2016-04-20 10:02
current version in the Marcin Bajor-repo (arch homepage -> downloads -> arch) is 4.2.795

scaling works fine

**Comment by diethardsteiner** [comment] 2017-01-01 16:22
Has this been resolved yet? I compiled the current gtk3 branch, on a Dell XPS 13 with a QHD+ display, using latest Fedora with Gnome Desktop (Wayland), the thumbnails are half the size (as shown by @hyphone). @heckflosse @Beep6581

**Comment by Beep6581** [comment] 2017-01-01 16:59
Closing as duplicate of #3547

**Closed by Beep6581** 2017-01-01 16:59 UTC
Labels: enhancement
