### ISSUE TITLE
Rw2 file lense distortion

### ISSUE THREAD

**Issue by BennyNielsen** [Beep6581/RawTherapee#3155] opened 2016-02-17 16:58 UTC
Hi RawTherapee

I run the 4.2.447 on a Windows 10.
I have a Panasonic DMC-FZ1000 camera.
When I load my Rw2 files into RawTherapee it looks like the lense distortion is wrong.
To my knowledge the information about lense distiortion is a part of the Rw2 file.
I have uploaded som files here:
http://filebin.net/8u4lqnwtns

Rw2 file from the camera.
Jpg _Camera_Save from the camera.
jpg _RT_Save is the Rw2 file converted by RawTherapee
jpg _SP_Save is the Rw2 file converted by SilkyPix(software with the camera)

I hope you can help me.

Thanks for a great program
Benny Nielsen

**Comment by Beep6581** [comment] 2016-02-17 20:06
Duplicate of #3150.

**Closed by Beep6581** 2016-02-17 20:06 UTC

**Comment by BennyNielsen** [comment] 2016-02-18 05:51
I am very disappointed in Beep6581.
He just closes my issue, without taking me seriously.
I am trying to help you make RawTherapee usable for Panasonc users.
The answer is just Issue closed :(

**Comment by heckflosse** [comment] 2016-02-18 11:37
@BennyNielsen [try Auto Distortion Correction](http://50.87.144.65/~rt/w/index.php?title=Lens/Geometry#Distortion_Correction) and [crop the image](http://50.87.144.65/~rt/w/index.php?title=Crop) to remove the ugly dark corners

**Comment by BennyNielsen** [comment] 2016-02-18 13:26
@heckflosse
I tryed that. but the picture is still distorted.

**Comment by Beep6581** [comment] 2016-02-18 22:13
@BennyNielsen you reported what you thought was a bug, I responded that it's a normal aspect of raw files and not a bug and I pointed you to the documentation. In response, you spammed this bug tracker with duplicate reports and duplicate replies and then claimed that doing so makes RawTherapee more usable for Panasonic users. That's nonsense. Please read the documentation I sent you, and look for the LCP yourself or make one yourself.

**Comment by BennyNielsen** [comment] 2016-02-19 05:56
@Beep6581 Ok I had given up, but let us try again.
The SilkyPix program I like because it loads my raw files and they look fine immediately. Everything else is horrible.
RawTherapee: I like everything. But it does not load my raw files like SilkyPix. It would be fantastic if it worked like that.
I do not find any .LCP files on my hard drive. So I guess SilkyPix does not have one. 
I have searched the internet, asked in facebook groups but not found a .LCP file for my camera. I was hoping that you had expertise in places where I can look for them.
I don’t know how to make a .LCP file
Can you help me?

**Comment by Beep6581** [comment] 2016-02-19 12:57
> I do not find any .LCP files on my hard drive. So I guess SilkyPix does not have one. 
> I have searched the internet, asked in facebook groups but not found a .LCP file for my camera.

The link Ingo and I sent you describes where to find LCPs and how to make your own one if you cannot find one.

RawTherapee shows you the raw file as it is. That's the core principle of RawTherapee. You can optionally have some tools turned on by default, e.g. lens distortion correction. The method of operating those tools and the procedure for creating a new processing profile (PP3) which is to be used as a new default processing profile for your photos is described in RawPedia: http://rawpedia.rawtherapee.com/

GitHub is a bug tracker, but the thing you are reporting is not a bug, it is user support. For user support use the forum, after you have read the links.
http://rawpedia.rawtherapee.com/Forum
