### ISSUE TITLE
Error building using msys an Win64

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3101] opened 2016-01-16 22:24 UTC
I followed the instructions from rawpedia step by step to build using msys/gcc 5.3 on Win64.
All worked fine but the build of RT which fails with:

$ make -j8
[  0%] Creating the about file
-- git command found: C:/msys64/usr/bin/git.exe
-- CACHE_NAME_SUFFIX is "4"
[  0%] Built target AboutFile
Scanning dependencies of target rtexif
make[2]: **\* Keine Regel vorhanden, um das Ziel „/mingw64/include/pthread.h“,
  benötigt von „rtexif/CMakeFiles/rtexif.dir/rtexif.cc.obj“, zu erstellen.  Schluss.
CMakeFiles/Makefile2:122: die Regel für Ziel „rtexif/CMakeFiles/rtexif.dir/all“ scheiterte
make[1]: **\* [rtexif/CMakeFiles/rtexif.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: **\* [all] Fehler 2

@adamreichold Can you help please?

Ingo

**Comment by Desmis** [comment] 2016-01-17 12:32
Hello Ingo
I have had the same problem 2 weeks ago...
Probably you always have "Windows Environement variables" activated!

You must suppress these reference PATH, and GTKMM

:)

**Comment by heckflosse** [comment] 2016-01-17 14:16
Hi Jacques, thanks for your help:) Finally I got it working. 
Maybe we should mention in rawpedia, that if rt folder is inside a folder structure which contains blanks, the build fails. In my case 'username' was part of the directory structure and username was : 'firstname{blank}lastname" and in that case the build failes with:

gcc: error: Weyrich/rt_default/build/rtgui: No such file or directory
gcc: error: Weyrich/rt_default/rtgui/-lws2_32\: No such file or directory

Probably fixing this is possible too.

**Comment by adamreichold** [comment] 2016-01-17 15:34
@heckflosse Do you have write access to the article in RawPedia? If so, could you add there what you think describes the necessary precautions best to close this? If you don't have write access, could you give me a hint of what should be written there?

**Comment by Beep6581** [comment] 2016-01-17 16:34
I cloned to ~/test test/repo-rt and compiled, could not reproduce the problem with blanks in the parent folder.

Isn't the problem with just missing quotation marks somewhere in CMakeLists.txt? If so, it would be better to add them than to document workarounds.
Maybe line 85 (in master)?

**Comment by Beep6581** [comment] 2016-01-25 09:42
Status?

**Comment by heckflosse** [comment] 2016-02-13 12:52
When I remove myicon.rc in [this line](https://github.com/Beep6581/RawTherapee/blob/gtk3/rtgui/CMakeLists.txt#L44) it builds fine. Any idea what this is good for?
@Hombre57 @adamreichold @michaelezra

**Comment by Hombre57** [comment] 2016-02-13 15:09
I think it is necessary to define the executable's icon on Windows, but someone should confirm or elaborate.

**Comment by Hombre57** [comment] 2016-02-13 15:59
I must add that it's not a problem here (Win7/64 using MSYS2), so the problem may be elsewhere.

Which Windows OS are you using ? Win10 ?

**Comment by heckflosse** [comment] 2016-02-13 16:07
Win7/64
mkdir "test 1"
cd "test 1"
clone ........

**Comment by heckflosse** [comment] 2016-02-13 16:12
@Hombre57 For me that's no problem. I simply don't use folders with a blank ;)

**Comment by Hombre57** [comment] 2016-02-13 16:13
I was referring to the myicon problem. I don't have blank char neither, so it should work seamlessly on your PC.

**Comment by heckflosse** [comment] 2016-02-13 16:22
Of course it works fine here without blanks. But if someone wants to build on Windows he could run into the 'blank' problem too.

**Comment by Hombre57** [comment] 2016-02-13 16:53
> When I remove myicon.rc in this line it builds fine. Any idea what this is good for?

I think we have some communication problem today :) By saying this :

> I must add that it's not a problem here (Win7/64 using MSYS2), so the problem may be elsewhere.

... I'm only saying that you shouldn't have to remove myicon.rc, as it works fine here. So I don't understand where the problem is. Without myicon.rc, do your executable have the proper icon ? Normally not.

**Comment by heckflosse** [comment] 2016-02-13 17:02
No, it does not have an icon then :(

**Comment by Hombre57** [comment] 2016-02-13 17:20
I found this links interesting :
  - http://stackoverflow.com/questions/708238/how-do-i-add-an-icon-to-a-mingw-gcc-compiled-executable
  - https://msdn.microsoft.com/en-us/library/aa381058.aspx

Maybe we could update the info file properly for Windows?

For the crash on myicon.rc, do you have this file: `msys64/mingw64/bin/windres.exe`, and do you have blank char in its full path ?

**Comment by heckflosse** [comment] 2016-02-13 17:49
@Hombre57 I'll read tat later. Have to go now.

**Comment by adamreichold** [comment] 2016-03-27 13:23
Ping?

**Comment by heckflosse** [comment] 2016-04-02 20:43
Sorry, completely forgot and have been away too. I'll try again next week

**Closed** 2018-11-23 21:50 UTC
Labels: compilation
