### ISSUE TITLE
LA: New activated modules are not restored when loading a previous pp3 profile.

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#6136] opened 2021-02-25 16:32 UTC
When restoring a pp3 profile, later activated modules in Local Adjustments are not restored:
I have the first 4 modules, of which I have activated the first 2:
![1_Los2primerosModulosActivados](https://user-images.githubusercontent.com/55624244/109184397-406f5980-778f-11eb-9b56-bc77d5f352d7.JPG)

I save this profile with name: TheFirst2ModulesActivated.pp3
Next, I activate the third module and take 2 more:
![2_Con5Modulos](https://user-images.githubusercontent.com/55624244/109184430-49f8c180-778f-11eb-890a-6d1e5e24a4d7.JPG)

Now I load the previous profile: TheFirst2ModulesActivated.pp3
And the result is that the last 2 modules are still activated.  They should not be or be off.
![3_Resultado](https://user-images.githubusercontent.com/55624244/109184463-511fcf80-778f-11eb-9a9f-210a719ee109.JPG)

Greetings, Arturo.
Version: 5.8-2776-gf72747771 win64.zip

**Comment by Thanatomanic** [comment] 2021-02-25 16:59
@arturoisilvia I assume you have 'partial filling' enabled? I can replicate your behavior. 
![image](https://user-images.githubusercontent.com/6567747/109187956-b2956d80-7792-11eb-8f86-ddcbc69fd7f7.png)

There is something far worse though: if you enable 'full mode' _nothing_ is applied. Try to create a few spots, save the pp3, apply Neutral profile and then load the pp3. LA is activated, but no spots are created!
![image](https://user-images.githubusercontent.com/6567747/109188014-c214b680-7792-11eb-99ed-3464c8e738f6.png)

@Desmis @Pandagrapher Can either of you take a look? This seem quite problematic...

**Comment by Pandagrapher** [comment] 2021-02-25 17:31
@Thanatomanic @arturoisilvia 
For me the case reported by arturoisilvia is not a bug. When loading a profile with "partial filling" enabled, a merge is performed between your profile and the actual parameters (like all other tools). In the given example, all module activation/added state is kept except for the third module which is deactivated to match the loaded profile.

But the fact, that loaded profile does not erase completely when "full mode" is selected is more annoying... I am investigating...

**Comment by arturoisilvia** [comment] 2021-02-25 17:35
@Thanatomanic 
Yes, the profile processing mode is partial.

**Comment by Pandagrapher** [comment] 2021-02-27 16:41
@Thanatomanic 
This patch solves the issue when loading a profile when "full mode" is activated:

```diff
diff --git a/rtgui/profilepanel.cc b/rtgui/profilepanel.cc
index c7e889b..a13c642 100644
--- a/rtgui/profilepanel.cc
+++ b/rtgui/profilepanel.cc
@@ -531,6 +531,9 @@
 
                 if (!fillMode->get_active()) {
                     *custom->pedited = pe;
+                } else {
+                    // Resize custom->pedited to be compliant with pe spot size
+                    custom->pedited->locallab.spots.resize(pe.locallab.spots.size(), LocallabParamsEdited::LocallabSpotEdited(true));
                 }
             }
```

Pierre

**Comment by Thanatomanic** [comment] 2021-02-28 10:26
Thanks @Pandagrapher! This is now fixed: https://github.com/Beep6581/RawTherapee/commit/09441c7e545c86dd8967dd741251db9f67fc1d4f

As for the initial report, I believe you are right: this is how the partial profile mode works. It only applies those values that are present in the profile (the tooltip says so too). The difficulty is that most tools in RT are not 'dynamic', i.e. they have fixed set of sliders and settings. That makes it easy to understand what to expect; you can update sliders independently.
However, for LA you can have an expanding set of active sliders (tools). Then it is not so clear what you would expect from a partial filling mode. How fine-grained do you want to be able to set your sliders/values? Do you treat the activated modules separately? Or do you treat the _set_ of activated modules as a complete entity? I'm not sure what I would find the most logical tbh.

**Comment by Pandagrapher** [comment] 2021-02-28 16:57
@Thanatomanic 
Each LA spot is managed as an huge structure containing the settings of all tools (even if they are not activated or visible).
So, when partial filling mode is selected, I just merge those spot structures based on the spot order/number is actual profile and loaded profile (adding new spot if loaded profile wants to merge more spot there actually are).
I think best would be to merge loaded profile by adding loaded profile spots to the already present ones (or replacing already present spots if full filling mode is chosen). But that would require to rewrite a lot of `profilepanel` code which is not maybe the right moment before RT 5.9.

**Comment by arturoisilvia** [comment] 2021-03-01 09:55
I just upgraded to Version: 5.8-2794-g02a5040a6 and now the profile processing mode 'full mode' works correctly thanks to @Pandagrapher.

But with the partial mode you have to be very, very, very careful:
If you have a spot with a normal method and apply a partial profile that has a full image method spot, the normal method will become full image.

For this reason, the best solution is the one proposed by @Pandagrapher: When applying a partial profile, let it be done on a new spot.


> @Pandagrapher: 
I think best would be to merge loaded profile by adding loaded profile spots to the already present ones (or replacing already present spots if full filling mode is chosen). But that would require to rewrite a lot of `profilepanel` code which is not maybe the right moment before RT 5.9.

**Comment by arturoisilvia** [comment] 2021-03-01 09:57
(Sorry, close by error: damn enter key)

**Closed as completed** 2022-07-18 17:03 UTC
Labels: type: question, tool: selective editing
