### ISSUE TITLE
Chromatic aberration auto correction turns images green

### ISSUE THREAD

**Issue by Barugon** [Beep6581/RawTherapee#6319] opened 2021-07-28 17:57 UTC
**Short description**
~~Auto-Matched Curve and Standard Film Curve profiles~~ chromatic aberration auto correction makes images green. 

When I first load an image, I have it use the neutral profile, which works fine:
![Screenshot from 2021-07-28 10-50-21](https://user-images.githubusercontent.com/16503728/127371776-0e589fc2-33da-4671-9c00-bce3904aa78e.png)

If I ~~switch the profile to Auto-Matched Curve or Standard Film Curve~~ turn on chromatic aberration auto correction on the Raw tab then here's what I get:
![Screenshot from 2021-07-28 10-51-49](https://user-images.githubusercontent.com/16503728/127371964-ce084e40-de86-4db0-a732-c87a3887a562.png)
I tried this with images from three different cameras (Sony ILCE-7M3, Sony ILCE-7C, Panasonic DC-S5) and I get the same result with each.

**Steps to reproduce**
Open an image and select either an Auto-Matched Curve or a Standard Film Curve profile.

**Expected behavior**
Correct colors.

**Additional information**
- Version of RawTherapee: 5.8-3014-g94b5f7232
- Version of your operating system: Fedora 34, 64-bit
- If you built from source, the contents of the `AboutThisBuild.txt` file in the installation folder:
Version: 5.8-3014-g94b5f7232
Branch: dev
Commit: 94b5f7232
Commit date: 2021-07-27
Compiler: cc 11.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.13.4-200.fc34.x86_64 x86_64
Build date: Wed, 28 Jul 2021 17:38:11 +0000 UTC
Build epoch: 1627493891
Build UUID: 3f90cf70-3d1b-4caa-8410-a1af6b9c855d

**Comment by ghost** [comment] 2021-07-29 11:49
I'm not able to reproduce this.

I've tried it using the three cameras you mentioned, using 2 RAWs each and also some other cameras (Nikons).

Are you sure you start with a neutral profile?

---

* RawTherapee version : 5.8-3052-g4bf5fd78
* OS                : Linux (kernel 5.9.15-1 x86_64 amd64)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1

**Build flags:**

    -DNDEBUG
    -O3
    -Wall
    -Wcast-qual
    -Werror=delete-incomplete
    -Werror=unknown-pragmas
    -Werror=unused-label
    -Wno-attributes
    -Wno-deprecated-declarations
    -Wno-unused-result
    -Wuninitialized
    -Wunused-macros
    -flto
    -fno-math-errno
    -fopenmp
    -ftree-vectorize
    -march=native
    -std=c++11

**Comment by Floessie** [comment] 2021-07-29 13:12
Cannot reproduce on Debian Experimental AMD64 with GCC 11.1, 11.2 with and without LTO. :disappointed:

**Comment by Barugon** [comment] 2021-07-29 15:06
> Are you sure you start with a neutral profile?

![Screenshot from 2021-07-29 07-56-41](https://user-images.githubusercontent.com/16503728/127515264-bc617e30-16df-4546-b169-ce16c5b365e4.png)

Attempting to switch to either of the low-ISO versions of those profiles now results in a crash. I'll make a debug build later and get a stack trace.

[edit] Specifically, capture sharpening is causing a segfault.

**Comment by Barugon** [comment] 2021-07-29 15:23
Chromatic aberration from the Raw tab is causing the color cast and it can also cause a segfault.

**Comment by Thanatomanic** [comment] 2021-07-31 09:02
@Barugon Could you share an affected raw file?

**Comment by Barugon** [comment] 2021-08-02 14:53
It won't let me attach a raw file but [this raw file from dpreview](https://www.dpreview.com/reviews/image-comparison/download-image?s3Key=e52951ab1daa430b9bc7dbeb0bfc2c2e.arw) shows the issue.

Using a default profile of neutral, open the file, switch to the Raw tab, expand Chromatic Aberration Correction, check Auto-correction. the image either turns green or I get a segfault (turning on capture sharpening can also sometimes result in a segfault, but it doesn't screw up the colors). **I built a debug version of rawtherapee but that doesn't show the issue, only release does.**

**Comment by Barugon** [comment] 2021-08-02 15:26
This older build works fine:

Version: 5.8-2980-g2e6e52f33
Branch: dev
Commit: 2e6e52f33
Commit date: 2021-05-31
Compiler: cc 11.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O2 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.12.8-300.fc34.x86_64 x86_64
Build date: Thu, 03 Jun 2021 19:32:02 +0000 UTC
Build epoch: 1622748722
Build UUID: d9bbbad5-4a42-4390-be53-54f2b495f2d2

**Comment by Thanatomanic** [comment] 2021-08-12 07:47
@Barugon I cannot reproduce on Fedora 34 in VM

```
Version: 5.8-3023-g1c4e1216d
Branch: dev
Commit: 1c4e1216d
Commit date: 2021-08-10
Compiler: cc 11.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.11.12-300.fc34.x86_64 x86_64
Build date: Thu, 12 Aug 2021 07:33:54 +0000 UTC
Build epoch: 1628753634
Build UUID: 533c52c0-639d-4031-b5a6-e8a4813c83c9
```

The only immediate difference between our builds seems to be the compiler version. You should be able to get cc 11.2.1 on Fedora 34. Can you update your system and check whether this solves the problem?

**Comment by Barugon** [comment] 2021-08-12 14:19
I tried building the dev branch yesterday and still got the same results. Here's the output from `cc --version`:
```
cc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Barugon** [comment] 2021-08-12 15:11
I just built the dev branch. Now it simply crashes when I turn on CA auto correction. As I said before, I'm not able to see the problem with a debug build but here's what is output from `gdb` using a release build:
```
Thread 189 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd9088640 (LWP 24498)]
0x0000000000c678cd in rtengine::ImProcFunctions::rgbProc(rtengine::Imagefloat*, rtengine::LabImage*, rtengine::PipetteBuffer*, LUT<float> const&, LUT<float> const&, LUT<float> const&, int, LUT<float> const&, LUT<float> const&, LUT<float> const&, float, float, rtengine::ColorGradientCurve const&, rtengine::OpacityCurve const&, bool, LUT<float> const&, LUT<float> const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, double&, double&, double&, float&, float&, float&, double, int, int, rtengine::DCPProfile*, rtengine::DCPProfileApplyState const&, LUT<unsigned int>&, unsigned long, bool) [clone ._omp_fn.0] ()
```
And the output of `backtrace`:
```
#0  0x0000000000c678cd in rtengine::ImProcFunctions::rgbProc(rtengine::Imagefloat*, rtengine::LabImage*, rtengine::PipetteBuffer*, LUT<float> const&, LUT<float> const&, LUT<float> const&, int, LUT<float> const&, LUT<float> const&, LUT<float> const&, float, float, rtengine::ColorGradientCurve const&, rtengine::OpacityCurve const&, bool, LUT<float> const&, LUT<float> const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, rtengine::ToneCurve const&, double&, double&, double&, float&, float&, float&, double, int, int, rtengine::DCPProfile*, rtengine::DCPProfileApplyState const&, LUT<unsigned int>&, unsigned long, bool) [clone ._omp_fn.0] ()
#1  0x00007ffff58bac16 in gomp_thread_start () at /lib64/libgomp.so.1
#2  0x00007ffff5886299 in start_thread () at /lib64/libpthread.so.0
#3  0x00007ffff5430353 in clone () at /lib64/libc.so.6
```

**Comment by heckflosse** [comment] 2021-08-12 16:13
Does it work with gcc <11.x ?

We had such issues some time ago, where new gcc compilers were buggy...

**Comment by Barugon** [comment] 2021-08-12 16:28
I added debug info to the release build. Here's a backtrace:
```
#0  0x0000000000c678cd in LUT<float>::operator[]<float, float, void>(float) const (this=<optimized out>, index=-nan(0x400000))
    at /home/Barugon/programs/code-rawtherapee/rtengine/LUT.h:481
#1  rtengine::ImProcFunctions::_ZN8rtengine15ImProcFunctions7rgbProcEPNS_10ImagefloatEPNS_8LabImageEPNS_13PipetteBufferERK3LUTIfESA_SA_iSA_SA_SA_ffRKNS_18ColorGradientCurveERKNS_12OpacityCurveEbSA_SA_RKNS_9ToneCurveESJ_SJ_SJ_RdSK_SK_RfSL_SL_diiPNS_10DCPProfileERKNS_20DCPProfileApplyStateERS7_IjEmb._omp_fn.0(void) ()
    at /home/Barugon/programs/code-rawtherapee/rtengine/improcfun.cc:2462
#2  0x00007ffff58bac16 in gomp_thread_start () at /lib64/libgomp.so.1
#3  0x00007ffff5886299 in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff5430353 in clone () at /lib64/libc.so.6
```
After some investigation, the float value being passed into the LUT index operator is, in fact, NaN.

**Comment by Barugon** [comment] 2021-08-12 16:45
> Does it work with gcc <11.x ?
> 
> We had such issues some time ago, where new gcc compilers were buggy...

Built it with clang and everything works fine.
```
Version: 5.8-3023-g1c4e1216d
Branch: dev
Commit: 1c4e1216d
Commit date: 2021-08-10
Compiler: clang 12.0.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -g -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp=libomp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.13.8-200.fc34.x86_64 x86_64
Build date: Thu, 12 Aug 2021 16:41:15 +0000 UTC
Build epoch: 1628786475
Build UUID: 4025d647-fd56-49c8-bba6-611725441077
```

**Comment by TheSquirrelMafia** [comment] 2021-11-20 19:52
I have this same issue with the recent build of RawTherapee (5.8-3055-ga1bbede06). It happens when I use CA correction & I check on the Avoid color shift. The image turns green or RawTherapee crashes.

Version: 5.8-3055-ga1bbede06
Branch: dev
Commit: a1bbede06
Commit date: 2021-11-12
Compiler: cc 11.2.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.5
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: MINGW64_NT-10.0-22000 3.2.0-340.x86_64 x86_64
Build date: Sat, 20 Nov 2021 19:16:14 +0000 UTC
Build epoch: 1637435774
Build UUID: cb1a9421-f89c-45e3-a3e2-7b5e4d3abfb8

The funny thing is that it only does it on my Windows 11 64bit AMD Ryzen 5 3600 machine, but not on the older Intel i5 & i7 machines that I have. Those have no issues with the CA correction, so I don't know if it's a Windows 11 and/or AMD Ryzen thing.

However, I have no issues on the same Windows 11 AMD Ryzen machine when running the older 5.8-3024-g22f89bc75 version. It works perfectly. Weirdness.

**Comment by heckflosse** [comment] 2021-11-20 23:15
> Compiler: cc 11.2.0

gcc 11.2 builds of RT are not stable unfortunately :-(

**Comment by Barugon** [comment] 2021-11-20 23:25
@TheSquirrelMafia 
I found that the solution was to build using clang.

**Comment by ghost** [comment] 2021-11-21 10:27
@Barugon (and slightly off-topic):

Are you able to build using clang with WITH_LTO set to ON? I'm not and I have no problems when I set it to OFF.

The speed increase by setting it to ON is probably negligible, but I'm just curious.

**Comment by heckflosse** [comment] 2021-11-21 11:19
@TheSquirrelMafia 

On msys2 I downgraded to gcc 10.3.0.
That works fine

```
$ pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-10.3.0-8-any.pkg.tar.zst /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-fortran-10.3.0-8-any.pkg.tar.zst /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-libs-10.3.0-8-any.pkg.tar.zst /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-libgfortran-10.3.0-8-any.pkg.tar.zst /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-ada-10.3.0-8-any.pkg.tar.zst /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-objc-10.3.0-8-any.pkg.tar.zst
```

**Comment by TheSquirrelMafia** [comment] 2021-11-22 02:59
^ Thanks a lot! I didn't have gcc & gcc-libs 10.3.0-8, but had gcc & gcc-libs10.3.0-7. That did the trick! Also ignored in pacman.conf.

**Comment by Barugon** [comment] 2021-12-14 05:14
> Are you able to build using clang with WITH_LTO set to ON?

Just tried this and it seems to work fine. Just a couple of warnings about not being able to vectorize a couple loops.

**Comment by ghost** [comment] 2021-12-14 08:44
@Barugon : Thanks for checking.

I'll have to do some more testing and checking to figure out why it doesn't  build using clang when I set WITH_LTO  to ON.

**Comment by Thanatomanic** [comment] 2022-04-10 09:05
This is most likely due to https://github.com/Beep6581/RawTherapee/issues/6384. Closing this for now.

**Closed as completed by Thanatomanic** 2022-04-10 09:05 UTC
