### ISSUE TITLE
Histogram/RGB, Hsv, Lab values do not respond to output profile changes

### ISSUE THREAD

**Issue by iliasg** [Beep6581/RawTherapee#3565] opened 2016-12-30 14:22 UTC
When the histogram/navigator is set to display the output values (which is the default setting) the output values/histogram should change with every change in output profile. 
This was working correctly until recent changes in output color management (tested with 4.2.1000)
With the recent builds histogram/RGB,Hsv,Lab values stay same as with RT_sRGB.icc even if we change output profile .. except if the choosen output profile is rec2020 !!
I checked the values reported and looks like they are correct for RTsRGB. 
Tested with .. 
Branch: master
Version: 4.2.1224
Changeset: cc8dae26ff6b81d810fd954828b65ff380652fff
Compiler: gcc 6.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -m64 -mwin32 -mthreads -std=gnu++11 -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by iliasg** [comment] 2016-12-30 16:06
labels ..

**Comment by iliasg** [comment] 2016-12-31 14:44
Dublicate ..
https://github.com/Beep6581/RawTherapee/issues/3506

**Comment by Beep6581** [comment] 2016-12-31 16:54
Closing as duplicate of #3506.

**Closed by Beep6581** 2016-12-31 16:54 UTC
Labels: bug, color management
