### ISSUE TITLE
Darek frame substraction ui

### ISSUE THREAD

**Issue by PiotrekKa** [Beep6581/RawTherapee#3931] opened 2017-06-15 20:02 UTC
Maybe it is not the bug itself but if one wants to select dark frames for DFS manually one can choose only one file which means the funcionality od this tool is limited, while it seems possible to use average od multiplex files from dark frame directory when picked up automatically.

**Comment by heckflosse** [comment] 2017-06-15 20:18
Can you please rephrase your suggestion/question in clear words?

**Comment by PiotrekKa** [comment] 2017-06-16 06:31
When selecting Dark frames manually it is not possible to use more than one frame.

**Comment by Beep6581** [comment] 2017-06-19 17:23
Duplicate of #2473

**Closed as completed by Beep6581** 2017-06-19 17:23 UTC
