### ISSUE TITLE
Feature request: command line option to avoid .pp3 files creation

### ISSUE THREAD

**Issue by fsenore** [Beep6581/RawTherapee#4685] opened 2018-07-13 17:32 UTC
For my workflow a command line option to avoid the creation of .pp3 files would be very useful.

I store my raw files in a separate folders structure, and I copy them to another location when I edit them: I only edit a small number of files.

I use a Panasonic camera: the jpeg preview embedded in the raw file is not full-size but it much smaller. For this reason I often open raw files just to check if they are sharp, and sometimes to try some quick adjustments just to see what happens. These are not intended as read edits, just quick looks.
If I use RawTherapee for this task the folders are filled with .pp3 files that have no use for me, since they do not contain useful info.

With the requested command line option I could create a desktop shortcut to look at images without filling the disk with unwanted .pp3 files, and this would be very useful to me.

Thank you in advance.

Fulvio Senore

**Comment by Beep6581** [comment] 2018-07-13 18:26
Duplicate of #2857

To avoid having PP3 files saved alongside your photos, have them stored only in the cache.
http://rawpedia.rawtherapee.com/Preferences#Processing_Profile_Handling

**Closed as completed by Beep6581** 2018-07-13 18:26 UTC

**Comment by fsenore** [comment] 2018-07-13 20:02
I noticed #2885 and in my humble opinion this is not a duplicate. #2885 asks for not writing a .pp3 file unless something has changed, which BTW looks like a very reasonable request.
I agree that #2885 would solve my problem, but since it has not been solved for years I created a different request.  My request is much simpler since adding a flag to inhibit .pp3 creation should be a rather simple change.

The Processing Profile Handling suggestion does not solve my problem because it is a global setting. I would like to have the .pp3 files in the same location as the input file when I edit, and I would like to have a shortcut to start RT without .pp3 saving when I only want to look at the files.

**Comment by Beep6581** [comment] 2018-07-13 21:46
@fsenore I agree that it is not the same, but considering how few developers there are, how hacky this request is and that issue #2885 is the "proper way" of doing it and progress has already been made, it makes sense to mark this as a duplicate and not have it perpetually dangling in open state.

Another solution to your problem is to have a script which does two things:
1. Sets in the options file that RT should save PP3s only to the cache,
2. Launches RT with your photo.

Then you have another script which does the same two things but sets the option file to save the PP3 alongside the photo.

In Linux it's as simple as having a Bash script which does something like this:
```bash
sed -i s/SaveParamsWithFile=true/SaveParamsWithFile=false/ ~/.config/RawTherapee/options
rawtherapee $1
```
And the other script which does the opposite.

**Comment by fsenore** [comment] 2018-07-14 12:39
Thank you for your suggestion, it should solve my problem.
