### ISSUE TITLE
Windows 10: Raw therapee window located out of screen

### ISSUE THREAD

**Issue by gaaned92** [Beep6581/RawTherapee#6233] opened 2021-05-09 21:11 UTC
System: windows 10

RawTherapee versions: all recent versions for all builds, stable, official nightly, my own nightly builds

reference: https://discuss.pixls.us/t/cant-start-the-latest-dev-version-of-rawtherapee-for-win64/24746/27

Description : from time to time, it can happen that in the option file/ GUI section, the two variables WindowX and WindowY are overwritten with garbage (-32768).
The RawTherapee window is then located out of the screen and not displayed.
Users are very puzzled.
Workaround: stop RT, reset the two variables to 0? RESTART rt

How to reproduce: although I tried, I never succeeded to find some configuration permitting to trigger  the bug.

**Comment by Thanatomanic** [comment] 2021-05-10 11:49
I guess we need some logic here to make sure the windows will render in actually available, visible screen space:
https://github.com/Beep6581/RawTherapee/blob/3ad786745cf11fade334ff41aad0573dfcd7c04e/rtgui/rtwindow.cc#L522-L533

For reference: https://developer.gnome.org/gdk3/stable/GdkMonitor.html#gdk-monitor-get-geometry

**Comment by Pandagrapher** [comment] 2021-05-11 08:56
Application position is also retrieve before being saved in `option` file when RT is closed:
https://github.com/Beep6581/RawTherapee/blob/3ad786745cf11fade334ff41aad0573dfcd7c04e/rtgui/rtwindow.cc#L856-L872

However here, we don't check if application is visible before getting (and saving) position. I am wondering if weird position cannot be retrieved if application was minimized before being closed, for instance (cannot test on MacOS because windows manager still retrieves the position before app was minimized).

Other idea to solve this issue : We saturate `windowX` and `windowY` by 0, like that, in case of unusual negative position value, RT will be automatically located in screen at next opening.

**Comment by Thanatomanic** [comment] 2021-05-11 09:02
Even on a dual monitor setup negative values mean that you have the top left corner of the window outside of the visible screen area. I was curious to see whether maybe my secondary monitor to the left of my main monitor would result in negative values _relative to the main screen_, but that is not the case.

No clue about how other OSes do things, but for Windows it would make sense to simply disallow negative values and clamp to 0.

**Comment by simohno** [comment] 2021-05-11 16:20
I found just here that I was experiencing the same very annoying issue: from time to time, apparently the RT main window stopped loading at all, and the sole solution for me was to delete the _options_ file and have it regenerated to all the defaults by RT (annoying because I lost all the customizations!). A non-experienced user (not knowing even the AppData\Local\RawTherapee... folder) would have been in serious trouble, because a reinstallation does not make changes to the _options_ file nor on anything else in the AppData folder, if I am right.

Now I have entered the old, problematic _options_ file with Notepad++ and I found
WindowX = 32000
WindowY = 32000
(not -32768 as @gaaned92 reported, but a positive huge value; therefore @Thanatomanic a second type of constraint should be necessary). Changing those values to 0 perfectly solved the issue. Tested on the last development version available (n. 2826 of 2021/03/22, now removed from nightly builds page as per #6139).
Many thanks
Simone

**Comment by Pandagrapher** [comment] 2021-05-12 10:54
Just made some test on a Windows 10 PC:
- When RT is fullscreen, `WindowX/Y` can be negative (-8, -8). I guess it's because there is no application border in fullscreen mode (8px border?)
- When RT is minimized and closed while being minimized, `WindowX/Y` is systematically saved at (-32000, -32000)!

I gonna try to see if I can improve the code to be more robust.

**Comment by Pandagrapher** [comment] 2021-05-12 17:07
I worked on a fix in the following branch:
https://github.com/Pandagrapher/RawTherapee/tree/window_position_fix

I have made the following changes:
- When, in code, RT window is moved to a specific position, is toggled fullscreen or not, is maximized or not, window position is not anymore updated in `options`. This will reduce the risk of having incoherent position value because of asynchronous GUI events.
- Same is done when user maximizes, minimizes (I have added event detection) or toggles fullscreen. Like this, when user closes RT, last "nominal" position will be saved in `options`.
- Add more robustness to `get_position` function: position is saturated between 0 and monitor pixel size in both directions.

I have made some tests in Windows 10 and MacOS Big Sur but I haven't tested all the cases (dual screen configuration, for instance).

I have detected the following limitations (already present before patch):
- ~~Windows 10: If RT is maximized at launch (because of saved state in `options`), position is retrieved at (0, 0) instead of keeping the last saved one.~~ Fixed.
- ~~MacOS: When window is maximized, moving RT window keeps it in maximized states and so user chosen app position isn't saved.~~ Fixed.
- ~~Both: Apparently, reading code, there is the same kind of issue with RT multiple windows mode. Need to work on it...~~ Fixed.
- ~~Both: I have seen some Gtk deprecated functions used in the code dealing with window position. Gonna word to replace them in the same time.~~ Fixed.

Please don't hesitate to test and give some returns.
Pierre

**Comment by Pandagrapher** [comment] 2021-05-23 16:17
@Thanatomanic @gaaned92 
I finalized the Pull Request fixing the last item. It is now ready for the last review before merging it.

Pierre

**Comment by chaimav** [comment] 2021-05-25 12:19
I am not sure if it was this fix or not, but I am now having the same issue with the nightlies. The main window is nowhere to be found. Opening the Options file, I see no reference to window position?

Edit: I found the user specific options file and I can confirm deleting it solves the problem 👍

**Comment by Pandagrapher** [comment] 2021-05-25 13:54
@chaimav The fix of this issue is still in review and still not has been merged to `dev` branch. So this issue can still happen in the nightly builds.

Waiting for it, as a workaround, it's not mandatory to delete the options file: you just have to edit the `WindowX/Y` fields in it and set them to `0`.

**Closed as completed** 2021-06-21 19:22 UTC
Labels: type: bug, type: enhancement, scope: GUI
