### ISSUE TITLE
Bug when edit current image in external editor

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#4291] opened 2018-01-10 16:20 UTC
When you open an image, and when you pressed on button "left bottom of preview" : "Edit current image in external editor", (in my case Photoshop) the ouput is very very bad, as a very noisy image.

**Comment by agriggio** [comment] 2018-01-10 16:40
@Desmis Jacques, can you share a problematic file and its associated pp3? Everything seems to be working fine here (when using GIMP, I don't have Photoshop)

**Comment by Desmis** [comment] 2018-01-10 16:44
@agriggio 

**For all files, for all settings**, wen I save to Photoshop, image is not an image, it's uggly :)

jacques

**Comment by agriggio** [comment] 2018-01-10 16:45
@Desmis I assume you are testing the `dev` branch, right? Could you try with GIMP?

**Comment by Desmis** [comment] 2018-01-10 16:48
I have tried yesterday when merging with "newlocallab", I try another time, with "dev" branch (just compiled)
Same problem

I have not Gimp installed :)

**Comment by heckflosse** [comment] 2018-01-10 16:55
@Desmis Jacques, can you post screenshots showing the 100% view of the same region in photoshop and rt?

**Comment by agriggio** [comment] 2018-01-10 16:57
Hmmm.... I just tried again, this time RT crashed with this:

```text
Output profile_: "RT_sRGB"
Using "RT_sRGB" output profile
/tmp/IMG_1076-4.tif: Error writing TIFF header.
Segmentation fault
```

@Hombre57, might this be related to your recent changes to the TIFF metadata code?

**Comment by Hombre57** [comment] 2018-01-10 17:04
@agriggio I suppose, but I need more info on this bug, especially the byte order of your test image and the output bit depth.

**Comment by Desmis** [comment] 2018-01-10 17:05
Here a link with imgur, I hope it works

**Comment by agriggio** [comment] 2018-01-10 17:06
@Hombre57 the output depth should be 16, I just pressed "edit with external editor". If I tried to save as TIFF in the normal way, I get no crash (though this doesn't mean much).
The test image I was using is this:
https://discuss.pixls.us/t/playraw-the-rail-bridge-north-queensferry/6243

**Comment by Desmis** [comment] 2018-01-10 17:08
Here the link

The original image is "amsterdam_moving_boat_1"

https://imgur.com/W4oc4S3

**Comment by heckflosse** [comment] 2018-01-10 17:13
Issue confirmed using a D800 file and exporting to gimp 2.8

![grafik](https://user-images.githubusercontent.com/13733487/34785580-d94edc30-f631-11e7-9e52-c1737620a96e.png)

**Comment by Hombre57** [comment] 2018-01-10 17:13
@Desmis Les grands esprits se rencontrent... I came across with this issue on my own just 20mn ago. I'm pushing a fix. The problem was that the edited image was "MM" (Big endian), and you saved as Tiff/16 bits. We do the byte swapping, while libtiff does it on its own.

@agriggio The fix will also include the fix for the ICC output reference image that was lacking metadata (it will be set now, in Tunneling mode), or should I make a separate commit (it's a one liner, really) ?

**Comment by agriggio** [comment] 2018-01-10 17:17
@Hombre57 a single commit is fine for me (but 2 don't hurt if you prefer :-)

**Comment by Hombre57** [comment] 2018-01-10 17:23
Done.

**Comment by Desmis** [comment] 2018-01-10 17:23
I just install Gimp, same results :)

**Comment by Hombre57** [comment] 2018-01-10 17:40
@Desmis "install Gimp" ? En français ? Mon patch a été appliqué à dev, et a corrigé ce que l'on voit dans l'image ci-dessus.

**Comment by Desmis** [comment] 2018-01-10 17:48
@Hombre57 

Jean Christophe, je viens de tester, compiler... avec Photoshop tout fonctionne correctement

Merci
jacques

**Comment by Hombre57** [comment] 2018-01-10 17:55
@Desmis de rien :)

Closing.

**Closed as completed by Hombre57** 2018-01-10 17:55 UTC
