### ISSUE TITLE
rawtherapee bug v5.9.0

### ISSUE THREAD

**Issue by dhrugg** [Beep6581/RawTherapee#6819] opened 2023-08-09 07:01 UTC
Hi

Unable to open ratherapee on MacOS Monterey V12.6.6

Application reports has 'quit unexpectedly'. Full system report below for reference

Thanks

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rawtherapee [729]
Path:                  /Volumes/VOLUME/RawTherapee.app/Contents/MacOS/rawtherapee
Identifier:            com.rawtherapee.RawTherapee
Version:               5.9.0 (5.9.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-09 16:58:45.4009 +1000
OS Version:            macOS 12.6.6 (21G646)
Report Version:        12
Anonymous UUID:        A0F24D7D-2D85-8026-50A0-95DDDCFB1998

Time Awake Since Boot: 620 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/Applications/RawTherapee.app/Contents/Frameworks/libomp.dylib'
Referenced from: '/Volumes/VOLUME/RawTherapee.app/Contents/MacOS/rawtherapee'
Reason: tried: '/Applications/RawTherapee.app/Contents/Frameworks/libomp.dylib' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x110ba098e __abort_with_payload + 10
1   dyld                          	       0x110bb6a72 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x110bb6aa4 abort_with_payload + 9
3   dyld                          	       0x110b64699 dyld4::halt(char const*) + 615
4   dyld                          	       0x110b605b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x110b5f4e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b78f11b8  rdx: 0x00007ff7b78f1620
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b78f1200  rsp: 0x00007ff7b78f11b8
   r8: 0x00007ff7b78f1220   r9: 0x0000000000000000  r10: 0x00000000000000ac  r11: 0x0000000000000246
  r12: 0x00000000000000ac  r13: 0x00007ff7b78f1620  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x0000000110ba098e  rfl: 0x0000000000000246  cr2: 0x0000000110b66da4
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x110b5a000 -        0x110bc5fff dyld (*) <2517e9fe-884a-3855-8532-92bffba3f81c> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=13.7M resident=0K(0%) swapped_out_or_unallocated=13.7M(100%)
Writable regions: Total=9268K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9268K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                              80K        3 
__DATA_CONST                      1088K        2 
__LINKEDIT                        2048K        4 
__TEXT                            11.7M        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             79.8M       17 

-----------
Full Report
-----------

{"app_name":"rawtherapee","timestamp":"2023-08-09 16:58:45.00 +1000","app_version":"5.9.0","slice_uuid":"ef39bbf0-8356-3e01-a569-e00c6d4ff14e","build_version":"5.9.0","platform":1,"bundleID":"com.rawtherapee.RawTherapee","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.6 (21G646)","incident_id":"69141261-51EB-4FAE-9993-60BAAC60D6DD","name":"rawtherapee"}
{
  "uptime" : 620,
  "procLaunch" : "2023-08-09 16:58:45.3804 +1000",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro12,1",
  "procStartAbsTime" : 622558394658,
  "coalitionID" : 772,
  "osVersion" : {
    "train" : "macOS 12.6.6",
    "build" : "21G646",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-09 16:58:45.4009 +1000",
  "incident" : "69141261-51EB-4FAE-9993-60BAAC60D6DD",
  "bug_type" : "309",
  "pid" : 729,
  "procExitAbsTime" : 622569440492,
  "cpuType" : "X86-64",
  "procName" : "rawtherapee",
  "procPath" : "\/Volumes\/VOLUME\/RawTherapee.app\/Contents\/MacOS\/rawtherapee",
  "bundleInfo" : {"CFBundleShortVersionString":"5.9.0","CFBundleVersion":"5.9.0","CFBundleIdentifier":"com.rawtherapee.RawTherapee"},
  "storeInfo" : {"deviceIdentifierForVendor":"A1F737D2-81F9-5E6E-82F2-C547CD0FEA94","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.rawtherapee.RawTherapee",
  "crashReporterKey" : "A0F24D7D-2D85-8026-50A0-95DDDCFB1998",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libomp.dylib'","Referenced from: '\/Volumes\/VOLUME\/RawTherapee.app\/Contents\/MacOS\/rawtherapee'","Reason: tried: '\/Applications\/RawTherapee.app\/Contents\/Frameworks\/libomp.dylib' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10240,"threadState":{"r13":{"value":140701913257504},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701913256480},"cr2":{"value":4575358372},"rdx":{"value":140701913257504},"r10":{"value":172},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4575594894,"matchesCrashFrame":1},"rbp":{"value":140701913256448},"rsp":{"value":140701913256376},"r12":{"value":172},"rcx":{"value":140701913256376},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4575305728,
    "size" : 442368,
    "uuid" : "2517e9fe-884a-3855-8532-92bffba3f81c",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703563112448,
  "size" : 19331678208,
  "uuid" : "f2ce8b0d-f2e7-3c14-88fa-430ab7913380"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=13.7M resident=0K(0%) swapped_out_or_unallocated=13.7M(100%)\nWritable regions: Total=9268K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9268K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                              80K        3 \n__DATA_CONST                      1088K        2 \n__LINKEDIT                        2048K        4 \n__TEXT                            11.7M        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             79.8M       17 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000055
    },
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro12,1, BootROM 481.0.0.0.0, 2 processors, Dual-Core Intel Core i7, 3.1 GHz, 16 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB30Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by Benitoite** [comment] 2023-08-09 21:19
Dulpicate of https://github.com/Beep6581/RawTherapee/issues/6045
*and*
Duplicate of https://github.com/Beep6581/RawTherapee/issues/5686

**Comment by dhrugg** [comment] 2023-08-10 00:29
Thanks

**Closed as completed** 2023-08-10 00:29 UTC
