### ISSUE TITLE
Give out an error message when a file couldn't be loaded

### ISSUE THREAD

**Issue by 10110111** [Beep6581/RawTherapee#5538] opened 2019-11-24 10:03 UTC
Currently, when RawTherapee is started with a filename on a commandline, which it can't open (e.g. it doesn't exist), it silently opens a directory and simply waits for the user to guess what's just happened. Similarly, if I open a corrupt DNG file (e.g. samples per pixel being 8 instead of correct 4), I see it simply show "0%" in the progress bar with no other indication of activity (no CPU usage, the GUI still responsive), and this seems to go forever (until I close RT), which is also bad UX.

It'd be much more user-friendly if instead RawTherapee told the user what happened: e.g. failure to open file (with corresponding `strerror` message), or failure to decode it (e.g. file corrupt or format unsupported) etc., and after this message reset to some usable state so that it's possible to open another file.

The behavior described above can be seen with RawTherapee 5.3 on Ubuntu 18.04.

**Comment by Beep6581** [comment] 2019-11-27 09:48
Duplicate of #3583

**Closed as completed by Beep6581** 2019-11-27 09:48 UTC
Labels: type: enhancement
