### ISSUE TITLE
Nikon Z6iii raw files are not read correctly

### ISSUE THREAD

**Issue by purew** [Beep6581/RawTherapee#7256] opened 2024-11-19 01:07 UTC
I just got some files from a Nikon Z6iii and the NEF files don't seem to be read correctly by Rawherapee. The camera body is configured with `RAW recording` set to `High efficiency*`

The [link the Issue template describes as required reading does not seem to load currently](https://rawpedia.rawtherapee.com/Adding_Support_for_New_Raw_Formats) but I'm attaching 2 sample images (saved as both jpeg and NEF by the camera). The jpegs are correctly in in monochrome as that was what the picture control was set to.

I'm using the following version of rawtherapee
```
$ rawtherapee -v
RawTherapee, version 5.11-70-gbce20bbd0
```
and OS is Archlinux with 
```
$ uname -a
Linux falcon 6.11.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 17:57:56 +0000 x86_64 GNU/Linux
```

[2024-11-09_nikon z6_3_dsc_0213.zip](https://github.com/user-attachments/files/17807839/2024-11-09_nikon.z6_3_dsc_0213.zip)
[2024-11-09_nikon z6_3_dsc_0215.zip](https://github.com/user-attachments/files/17807849/2024-11-09_nikon.z6_3_dsc_0215.zip)
![2024-11-09_nikon z6_3_dsc_0215](https://github.com/user-attachments/assets/82442c26-97d7-4bfb-9c11-dbc7b855e48e)
![2024-11-09_nikon z6_3_dsc_0213](https://github.com/user-attachments/assets/1d053ddc-6011-41b9-a630-d763de755a25)

**Comment by Lawrence37** [comment] 2024-11-19 07:26
Closing as a duplicate of #6408 (high efficiency encoding support).

**Closed as not planned by Lawrence37** 2024-11-19 07:26 UTC
Labels: scope: file format
