### ISSUE TITLE
Zoom 50% actually zooms to 500%

### ISSUE THREAD

**Issue by Jim91961** [Beep6581/RawTherapee#3400] opened 2016-08-23 04:03 UTC
Version:
4.2.1148 for Windows Vista/7/8/10 64 bit

Downloaded from:
http://rawtherapee.com/downloads

Operating System:
Windows 10 64 bit

Bug:
Using scroll wheel on mouse to change zoom percent works fine except for the 50% level. the 50% zoom level goes to 500%, not 50%. I noticed this in RT 4.1 as well.

GUI issue:
System Default (sRGB Color Space Profile)
The wording is too long and it displays across button and across navigation buttons to the right of the color space button

**Comment by Beep6581** [comment] 2016-08-24 08:15
Works fine here in Linux. Are you using LCP? Can you reproduce with a photo when the neutral profile is applied?

**Comment by Jim91961** [comment] 2016-08-24 16:12
What is LCP?I will test tonight with a neutral profile and no lens correction profile, then report back.

**Comment by Beep6581** [comment] 2016-08-24 18:53
LCP http://rawpedia.rawtherapee.com/Lens/Geometry#Lens_Correction_Profile

**Comment by Jim91961** [comment] 2016-08-26 00:37
It definitely has something to do with the LCP. I removed the LCP from a shot and moved it back to neutral and zoom worked well. I played with several variations including my edits without LCP, auto without LCP and it worked fine. I removed LCP and it worked fine. I applied LCP at the end of the stack and sometimes it worked fine, sometimes it 50% would zoom to 200% instead of 500%. Sometimes it would work fine. The LCP is from Canon for EPS 17 - 85 F4 - 5.6 IS USM lens on Canon 50D body.  I may just have to alter my workflow to add LCP at the end.

**Comment by Floessie** [comment] 2016-08-26 05:33
@Jim91961 Edited your comment above, because it included your e-mail address.

**Comment by Jim91961** [comment] 2016-08-26 05:35
Thank you

**Comment by Beep6581** [comment] 2017-02-17 21:04
No updates, closing.

**Closed by Beep6581** 2017-02-17 21:04 UTC
