### ISSUE TITLE
Inspector window does not update from within the editor / filmstrip

### ISSUE THREAD

**Issue by marter001** [Beep6581/RawTherapee#6111] opened 2021-02-13 13:57 UTC
i am confused by inspector... it should show the full view of the hovered pic, right?
pls, have a look at my pics: while editing a landscape i was hovering another landscape in the previews. What i expected, was, that one of those two files would get opened by inspector. But instead another pic, earlier edited and stored in the same folder, was shown.
And: The right side of the inspector-frame is transparent and doesnt show the whole pic.
![inspector_1](https://user-images.githubusercontent.com/78749513/107851493-b4624700-6e0a-11eb-8f8c-9bb09bf11c0d.jpg)
![inspector_2](https://user-images.githubusercontent.com/78749513/107851512-d8258d00-6e0a-11eb-8192-ee6419699a78.jpg)
This is shown, using shift-f in file browser
![inspector_3](https://user-images.githubusercontent.com/78749513/107851519-e96e9980-6e0a-11eb-91c9-12c03073e75d.jpg)

Im am using Win10 64bit, RT Version: 5.8-2751-gd369efb04 on a 4k-monitor at 3840x2160px
I was able to reproduce this in other folders too. Inspector showed pictures which had been edited earlier.

**Comment by Thanatomanic** [comment] 2021-02-13 17:27
So, the behavior in the editor mode is bugged, but I'm completely unsure what the expected behavior should be. To be honest, I had never noticed the 'Inspect' option in the context menu before and I can't seem to find an explanation in RawPedia about it.

The inspector window that opens can be panned and zoomed, but it is completely unrelated to either the selected picture in the filmstrip or the opened picture in the editor. When you go to the file browser, it does behave as expected from the inspect window: hovering over thumbnails updates the inspector.
Maybe @rfranke can take a look at what's going on? Could this introduced by your changes?

**Comment by Thanatomanic** [comment] 2021-02-13 17:28
@marter001 I have not been able to reproduce your partially transparent inspector.

**Comment by marter001** [comment] 2021-02-13 18:38
> 
> 
> @marter001 I have not been able to reproduce your partially transparent inspector.
@Thanatomanic : just scroll the mousewheel front:

![inspector_4](https://user-images.githubusercontent.com/78749513/107858148-f56e5180-6e32-11eb-8695-1aabc73c0e83.jpg)

**Comment by Thanatomanic** [comment] 2021-02-13 19:00
I'm sorry to say that scrolling and zooming still never gives me a transparent inspector window. At extreme zoom levels I can get some visible border, but otherwise the window behaves okay.

What is weird, is that if you open the inspector window from the filmstrip first, you get a small resizable window which can show you a different image than the one you've opened. If you then open the inspector from the File Browser you get a full-screen inspector window. If you then go back to the filmstrip, you will _also_ get a full screen preview that can only be exited with 'Esc', but _does_ show the correct image, although with some visual problems.

![image](https://user-images.githubusercontent.com/6567747/107858737-1c7a5280-6e36-11eb-96e4-fa647fc3ee71.png)

There is a lot going on here that shouldn't be happening...

**Comment by marter001** [comment] 2021-02-13 19:18
> I'm sorry to say that scrolling and zooming still never gives me a transparent inspector window. At extreme zoom levels I can get some visible border, but otherwise the window behaves okay.

@Thanatomanic i estimate, this could depend of the monitor-resolution. in middle-position of the mouse-wheel the window is filled, but scrolling in or out leads to strange results here ...
![inspector_5](https://user-images.githubusercontent.com/78749513/107859256-7aa83500-6e38-11eb-9ba9-e063b13286a0.jpg)

**Comment by Beep6581** [comment] 2021-02-15 13:16
Maybe related to RawTherapee/RawTherapee#5946 ?

I tested in `5.8-2767-g`137f78f01 and `5.8-2759-g`a1f3edbea and don't get that "Inspect" entry in the context menu.

**Comment by Thanatomanic** [comment] 2021-02-15 13:18
@Beep6581 Please make sure you have this enabled in Preferences:
![image](https://user-images.githubusercontent.com/6567747/107951421-99bdd880-6f98-11eb-8531-f9eee600e10c.png)

(and yes, this is completely undocumented as you already know)

**Comment by Lawrence37** [comment] 2021-02-27 20:48
I don't think the inspector window was intended to be used in the film strip. The quick fix would be to remove the Inspect item from the menu in the film strip. Supporting the inspector in the film strip is a reasonable long term solution.

**Comment by Lawrence37** [comment] 2021-06-13 18:56
@marter001 Is this issue still present in the latest version?

**Comment by marter001** [comment] 2021-06-14 16:45
@Lawrence37 thanks for your effort. The issue as described seems to be solved. I didnt realize, that the name of "Inspector" was changed to "prüfen" in the german version, so i thought, the inspector was taken out......
Now by checking this issue, i wonder, there is no window or frames at all, just a grey screen with the pic laid over. No explanation to the user, how to close this or how tho handle it, scrolling a.s.o. I felt a little uncomfortable with this.

**Comment by Lawrence37** [comment] 2021-06-15 01:15
Thanks for testing. I am closing this issue now.

The inspector window was meant to be full-screen. I see how it can be confusing because there are no buttons, text, or any other visual cues to indicate what's going on (and documentation is [not complete](https://github.com/Beep6581/RawTherapee/issues/6115)). If you have any suggestions on how to improve the intuitiveness or show helpful information in the inspector, feel free to leave them here or in a new issue. The inspector will probably be reworked following the release of 5.9. Feedback from users like you will be helpful.

**Closed as completed by Lawrence37** 2021-06-15 01:15 UTC
Labels: type: bug, scope: GUI
