### ISSUE TITLE
rawtherapee-cli Does Not Support 32-bit Tiff Output

### ISSUE THREAD

**Issue by jedypod** [Beep6581/RawTherapee#4641] opened 2018-06-25 21:03 UTC
I am interested in the 32 bit float tiff output that was added in RawTherapee v5.4. It is working well in the GUI, but it appears that the ability to export 32 bit tiff files from the rawtherapee-cli commandline version of the program is unavailable.

Is this something that could be added?

I am using `RawTherapee 5.4, released on 2018-03-20.` and have also tried compiling the latest nightly which has the same issue.
When running a command like this: 
`rawtherapee-cli -o _MG_8032_32bpp_aces_cli.tif -q -p linear_aces.pp3 -b32 -tz -c _MG_8032.dng`

I get an error like this:
```RawTherapee, version 5.4, command line
Error: specify -b8 for 8-bit or -b16 for 16-bit output.```

Thanks for your help!

**Comment by Beep6581** [comment] 2018-06-25 21:21
There is ongoing work in issue 2357, see from https://github.com/Beep6581/RawTherapee/issues/2357#issuecomment-345558426

Closing as duplicate of #2357

**Closed as completed by Beep6581** 2018-06-25 21:21 UTC

**Comment by jedypod** [comment] 2018-06-26 00:35
Okay! 

I did not read through the other issue thread carefully enough. I see the 32 bit cli mentioned now.

Thanks for your help!

If you guys can successfully implement 16bit half float exr output with color management, you would have the best raw debayer software in the open source realm :)

Keep up the good work!
