### ISSUE TITLE
Curves not drawn completely

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3973] opened 2017-07-17 15:12 UTC
To reproduce:
1) collapse all tools
2) open an image
3) apply neutral profile
4) close rt
5) start rt
6) open the same image again
7) expand the defringe tool
8) open the curve in defringe tool

looks like this:
![defringe00](https://user-images.githubusercontent.com/13733487/28274900-9c95c06a-6b12-11e7-91ae-752b7c3608bf.png)

when I minimize/maximize rt the curve is shown correctly:
![defringe01](https://user-images.githubusercontent.com/13733487/28274958-c1ab483e-6b12-11e7-923d-afd56e9e5fe2.png)

Reproducible on Windows7 and Linux with SETM, METM and MEOW

```
Version: 5.1-159-gaab3a603
Branch: dev
Commit: aab3a603
Commit date: 2017-07-17
Compiler: gcc 7.1.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: Release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

```
Version: 5.1-159-gaab3a603
Branch: dev
Commit: aab3a603
Commit date: 2017-07-17
Compiler: cc 7.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.1
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment] 2017-07-17 16:57
Please see #3525 it's probably the same cause.

Same problem with L\*a\*b\* and the RGB curves. If I hover my mouse over the curve drop-down combobox thingy ![imgur-2017_07_17-18 57 12](https://user-images.githubusercontent.com/5844619/28279742-c492d508-6b21-11e7-94fb-c893f3b7eaa0.png) then the UI fixes itself - true for every curve this bug happens with.

**Comment by heckflosse** [comment] 2017-07-17 17:41
@Beep6581 Confirmed that the UI fixes itself, but I need to hover over the arrow. Hovering over the curve type or the label does not fix the UI.
Maybe @Hombre57 has an idea...

**Comment by Hombre57** [comment] 2017-07-17 21:43
@Beep6581  @heckflosse Yes, that's a bug that we all experience since Gtk3.20. I searched for weeks, but I must either be missing something in the widget creation process or something is wrong with size computation in Gtk. My more comprehensive view on the situation is [explained here](https://github.com/Beep6581/RawTherapee/issues/3446#issuecomment-257426346). Went to the Gtk IRC, that was not really helpful.

**Comment by RawConvert** [comment] 2017-08-15 21:52
I get this behaviour also.

**Comment by Beep6581** [comment] 2018-08-19 19:16
Duplicate of #3525

**Closed as completed by Beep6581** 2018-08-19 19:16 UTC
