### ISSUE TITLE
LH curve loads at 100% and does not end

### ISSUE THREAD

**Issue by StefanGyuzelev** [Beep6581/RawTherapee#4365] opened 2018-02-04 18:29 UTC
Version date 01.feb.2018

Version: 
Branch: master
Commit: 
Commit date: 
Compiler: cc 7.3.0
Processor: AMD\ FX(tm)-8300\ Eight-Core\ Processor
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.2
Lensfun: V0.3.2.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -march=bdver1 -pipe -std=c++11 -Werror=unused-label -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:   
OpenMP support: ON
MMAP support: ON

I tray to use LH equalizer curve ,but cpu loads at 100% and process does not end.

**Comment by Floessie** [comment] 2018-02-04 19:01
Duplicate of #4355.

**Closed as completed by Floessie** 2018-02-04 19:01 UTC
