### ISSUE TITLE
Loading bundled profiles not working under Wayland (Fedora 26)

### ISSUE THREAD

**Issue by mlaverdiere** [Beep6581/RawTherapee#3967] opened 2017-07-11 11:45 UTC
I'm on Fedora 26 with default setup, i.e. running GNOME under Wayland.  

RT (stable 5.1) seems to work fine in general, except that loading bundled profiles (let's say: pop 2) only work once, then the menu becomes unresponsive.  Same thing with RT unstable 5.1-95.

Problem does not occur when running under x.org.

**Comment by Beep6581** [comment] 2017-07-11 12:05
Probably a Wayland/GTK3 issue. Can you reproduce the problem using some other GTK3-using program?

**Comment by mlaverdiere** [comment] 2017-07-11 19:25
Nope, all other GTK3 apps run fine for me under Wayland, with no menu issue...

**Comment by mbajor** [comment] 2017-07-12 13:59
@mlaverdiere Are you using repository for Fedora 25?

**Comment by mlaverdiere** [comment] 2017-07-12 22:06
@mbajor Well, you made me realize that I was using the Fedora 24 repo...  (wouldn't it be a better idea to use the $releasever joker in the repo file to assure that users are relying on the appropriate repo after each upgrade?  That's how other reliable repo - like official Fedora and rpmfusion - are set up... )

Anyway, I changed for the Fedora 26 repo, I did the upgrade and clean up the cold confg and cache files, but the result is the same:  bundled menu not responsive after the first profile is loaded.

**Comment by Beep6581** [comment] 2017-07-12 22:23
@mlaverdiere please paste the contents of your AboutThisBuild.txt or Preferences > About > Version http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by mlaverdiere** [comment] 2017-07-13 00:39
Here it is:

Version: 5.1
Branch: 5.1
Commit: f23d70fd
Commit date: 2017-05-15
Compiler: cc 7.1.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O2 -DNDEBUG
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by gjmvervoort** [comment] 2017-07-13 16:59
Same issue here, 5.1 build from git on Fedora 25 x86-64:

git checkout 5.1
rm -f CMakeCache.txt && cmake -DCMAKE_BUILD_TYPE=Release -DPROC_FORCED_LABEL:STRING=native . && make -j9 && sudo make install

**AboutThisBuild.txt**

Version: 5.1
Branch: 5.1
Commit: f23d70f
Commit date: 2017-05-15
Compiler: cc 6.3.1
Processor: native
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O2 -DNDEBUG
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment] 2017-07-13 17:26
@gjmervoort could you try building dev branch instead of 5.1? I don't expect that it works in dev, just to be sure...

**Comment by gjmvervoort** [comment] 2017-07-13 17:34
dev branch gives same result.

After opening a photo, I can select once one of the bundled profiles and then I not access the bundled profiles menu any more. When I open another photo I can select it again once.

**AboutThisBuild.txt**

Version: 5.1-141-gded8c66
Branch: dev
Commit: ded8c66
Commit date: 2017-07-13
Compiler: cc 6.3.1
Processor: native
System: Linux
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: Release
Build flags:  -std=c++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O2 -DNDEBUG
Link flags:   
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment] 2017-07-13 17:43
@gjmvervoort Thanks for testing! Do you use Single Editor Tab Mode or Multiple Editor Tab Mode? I ask, because you wrote `When I open another photo I can select it again once.`

**Comment by gjmvervoort** [comment] 2017-07-13 18:03
Editor layout setting: Single Editor Tab Mode, Vertical Tabs

If I change it to: Multiple Editor Tab Mode, the result is the same.

**Comment by heckflosse** [comment] 2017-07-13 18:05
@gjmvervoort Very interesting that in SETM it works again once for a new photo. I will investigate

**Comment by gjmvervoort** [comment] 2017-07-13 18:08
Indeed, for each new tab I can again select a bundled profile once.
And if I got back to a tab where I previously selected a bundled profile, then I still can not select another bundled profile.

**Comment by heckflosse** [comment] 2017-07-13 18:20
@gjmvervoort 

> And if I got back to a tab where I previously selected a bundled profile...

That sounds more like Multiple Editor Tab mode than Single Editor Tab mode
Anyway, as you wrote the result is independent on the mode, that's a first info for me to search the culprit

**Comment by gjmvervoort** [comment] 2017-07-13 18:25
Initially I had the Single Editor Tab Mode, but because of your question I switched to Multiple Tab Mode to see if that change the behaviour. And indeed the result is the same for both modes.

**Comment by heckflosse** [comment] 2017-07-14 22:47
maybe related from [here](https://wiki.gnome.org/Initiatives/Wayland/GTK%2B)

```
For now, the Wayland backend is working using heuristics to use popups when appropriate, which makes menus and combo box popups mostly work.
```

**Comment by Beep6581** [comment] 2017-11-16 11:24
Closing as the problem lies upstream.

**Closed as completed by Beep6581** 2017-11-16 11:24 UTC
Labels: type: bug

**Comment by dnw3039** [comment] 2017-12-31 04:09
This is still a problem on the Linux dev branch on version Version: 5.3 and  it also affects the Film Simulation menu. 

heckflosse 15 July seems to correct 

Using the suggestion in https://fedoraproject.org/wiki/How_to_debug_Wayland_problems
I tried RT using the weston compositor and the menu problems did not occur.

The article suggests that this test indicates the problem is not with GTK3 but with Wayland and kwin. 
" Otherwise file the issue against the compositor your environment uses (mutter, kwin, etc)"

So for those using Ubuntu and find this problem a big limitation in using RT the work-arroung  is to select Xorg rather than Wayland as the window manager, details here https://askubuntu.com/questions/961304/how-do-you-switch-from-wayland-back-to-xorg-in-ubuntu-17-10

**Comment by ror6ax** [comment] 2018-04-23 09:38
@mlaverdiere  - did you follow this up with mutter/kwin developers? I am having the same issue on Fedora.

**Comment by mlaverdiere** [comment] 2018-04-24 13:39
No, I didn't and I'm not in the best position to
      follow up on this bug, as I'm not really using RT anymore.
      
       
    
      
      Marco Laverdière
    
    Le 2018-04-23 à 05:38, Gregory
      Reshetniak a écrit :
    
    
      @mlaverdiere
        - did you follow this up with mutter/kwin developers? I am
        having the same issue on Fedora.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Beep6581/RawTherapee","title":"Beep6581/RawTherapee","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Beep6581/RawTherapee"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ror6ax in #3967: @mlaverdiere  - did you follow this up with mutter/kwin developers? I am having the same issue on Fedora."}],"action":{"name":"View Issue","url":"https://github.com/Beep6581/RawTherapee/issues/3967#issuecomment-383515532"}}}

**Comment by Beep6581** [comment] 2018-04-24 14:12
I wrote a document to ease dealing with this:
http://rawpedia.rawtherapee.com/Wayland

**Comment by ror6ax** [comment] 2021-04-03 17:15
Hey @Beep6581, is there a specific Wayland/GTK bug this is linked to?
