### ISSUE TITLE
RT crashes during the work with NEF's from Nikon D40

### ISSUE THREAD

**Issue by romandocent** [Beep6581/RawTherapee#4426] opened 2018-03-03 01:34 UTC
Cough a bug during work with my old Nikon D40 NEF's. Looks like it crushes only with NEF's that I use with Adobe's Nikon D40 DCP color profiles. It allows to process one NEF, then it crushes right after I'm trying to open the next one NEF with included DCP or later, after I do any manipulation with this NEF. 
It never crushes this way with other raw files from other cameras I use.

RT version info:
Version: 5.3
Branch: releases
Commit: ec0f793
Commit date: 2017-09-30
Compiler: cc 5.4.0
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.18.0
Lensfun: V0.2.8.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

Linux Ubuntu 16.04 LTS 64bit
CPU AMD Opteron 6128x16
Memory 16Gb
Graphics GeForce GTX 1050 Ti/PCIe/SSE2

Crush log file is included
[log.txt](https://github.com/Beep6581/RawTherapee/files/1776989/log.txt)

**Comment by heckflosse** [comment] 2018-03-03 09:56
Duplicate of #4202

**Closed as completed by heckflosse** 2018-03-03 09:56 UTC

**Comment by Beep6581** [comment] 2018-03-03 16:02
@romandocent : "cr**a**sh"

**Comment by romandocent** [comment] 2018-06-18 00:16
Looks like it crAshes again since 5.4, Ubuntu 18.04. During saving (loosing changes).
