### ISSUE TITLE
GPS data lost when processing RAW (DC-GX800)

### ISSUE THREAD

**Issue by Hezer** [Beep6581/RawTherapee#4622] opened 2018-06-17 10:49 UTC
Noticed location data not getting written from raw to processed files. Also RawTherapee doesn't show GPS data in the Metadata tab for the raw files.

I'm taking photos with Panasonic DC-GX800 (DC-GX850 / DC-GF9) then transferring GPS log from phone to camera and writing the location data to images.

RawTherapee version info: 
> Version: 5.4
Branch: 5.4
Commit: a5e8eb9c8
Commit date: 2018-03-20
Compiler: gcc 7.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Lensfun: V0.3.2.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations  -DNDEBUG  -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic  -s -O3 -fno-use-linker-plugin
OpenMP support: ON
MMAP support: ON

All the files, RAW, Processed JPG, Processing settings and ExifTool txt outputs for raw and output images are available here:
https://filebin.net/rwsbdz0j9n1o8nlm

**Comment by Hezer** [comment] 2018-06-17 10:57
Managed to select wrong jpg when uploading, for which I had already copied gps information from raw files with ExifTool.

It's now updated to correct one.

**Comment by Beep6581** [comment] 2018-06-17 19:30
Duplicate of #4464

**Closed as completed by Beep6581** 2018-06-17 19:30 UTC
