### ISSUE TITLE
Window Decorations in Win10

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#3954] opened 2017-07-05 08:39 UTC
RT5.1.119, Win10(64bits)
The program behaves incorrectly when it does not have native system window decorations. Quite alien.

**1.** The program does not minimize when I click on its icon in the taskbar. It loses focus only.

**2.** Aero Snap (the Mouse Drag Window Arranging Feature). 
I drag someone window to the edge of the screen. On the other side of the screen - thumbnails of the remaining programs. If I click any program, it will fill the other half of the screen. But among the programs there is no RT!
Screenshot: [https://img-fotki.yandex.ru/get/362774/98535730.53/0_19b918_63d2b074_orig](https://img-fotki.yandex.ru/get/362774/98535730.53/0_19b918_63d2b074_orig)

**3.** Shadows near the borders of the window are impenetrable! I can not click anything under them.

**3a.** Situation: the taskbar sets to hide automatically and RT's window is maximized. I lower the cursor to the bottom edge of the screen. It is expected that the taskbar will pop up. But this does not happen : )

For example, in the OpenSUSE the program has native KDE window decorations - and there are no problems.

Return the normal native borders and a titlebar, please : )

**Comment by heckflosse** [comment] 2017-07-06 21:33
I'm on Windows 7 where all seems to work correctly. Unfortunately no dev seems to be on Windows 10...

**Comment by ghost** [comment] 2017-07-07 07:49
Hi @heckflosse,

I saw your comment with a screenshot on the forum, [https://discuss.pixls.us/t/pass-through-rt-with-only-dng-to-tif16-conversion/4569/2](https://discuss.pixls.us/t/pass-through-rt-with-only-dng-to-tif16-conversion/4569/2). Everywhere, on the main site, on the "Gaaned92 RT WIN64 nightly builds", RT has GTK-decorations. But your RT has Win-native titlebar! May I ask you where I can find a build like this? : )

Maybe it would be helpful. There is a visible difference between a native snap to a screen border ([screenshot](https://img-fotki.yandex.ru/get/249479/98535730.53/0_19bf15_8f4d6f0_orig)) and an RT-snap ([screenshot](https://img-fotki.yandex.ru/get/5413/98535730.53/0_19bf14_e011bbd4_orig)). 

I understand that these are cosmetic improvements, matters are not of paramount importance : )

**Comment by heckflosse** [comment] 2017-07-07 10:30
@chaotic-sys
The builds are not the problem, because `Gaaned92 RT WIN64 nightly builds` also have native title bar on my Windows 7

**Comment by ghost** [comment] 2017-07-07 11:13
@heckflosse 
Thanks for the answer, I will dig in this direction.
On first, "Win7" compatibility mode did not show any changes : )

**Comment by TooWaBoo** [comment] 2017-07-07 17:27
I'm on Win 10 and there is no native window on GTK3.20 or higher.

![unbenannt](https://user-images.githubusercontent.com/13800920/27969192-390e3560-634a-11e7-860a-201ac7235ae4.PNG)

**Comment by heckflosse** [comment] 2017-07-07 17:36
@TooWaBoo Great to know that you're on Win 10 :+1: That makes testing this kind of stuff a bit easier.
Can you confirm the issues from first post?

**Comment by TooWaBoo** [comment] 2017-07-07 17:57
**3. Shadows near the borders of the window are impenetrable! I can not click anything under them.**
This issue exists on every app which doesn't use a native window.

All other reported issue work fine on my machine.

**Comment by heckflosse** [comment] 2017-07-07 18:19
@TooWaBoo Thank you!

**Comment by JamesForBugReport** [comment] 2017-07-08 10:22
I am Windows 10 and also experience all the issues listed in OP.
The only one I had previously noticed by myself was number 1, but as chaotic-sys says, these are just cosmetic and do not have a big impact on the use of RT.

Version: 5.1
Branch: 5.1
Commit: f23d70fd
Commit date: 2017-05-15
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads  -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -DNDEBUG -msse2 -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by TooWaBoo** [comment] 2017-07-08 11:31
Perhaps the different behaviour depends on different compile settings.

Can anyone test this build please?
https://filebin.net/coyjef8ej0g4nlnq

Extract the zip file and run rawtherapee inside the folder.

```
Version: 5.1-131-g2ea369ae
Branch: dev
Commit: 2ea369ae
Commit date: 2017-07-08
Compiler: gcc 7.1.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by ghost** [comment] 2017-07-08 12:27
I downloaded and checked the program. It seems nothing has changed.

I can say that Silkypix DS 4.4 is also not visible with aerosnap. It does not have a snap function at all. It has no shadows : ) When it is maximized, the taskbar also does not pop up when the cursor is moved down. But Silkypix can minimized  when you click on its button in the taskbar :)

One more remark. In the browser tab in the context menu, the icons are aligned with the text. Maybe, it would be prettier if they were brought to the edge.
![capture-1](https://user-images.githubusercontent.com/29912986/27985354-e3c06d82-63f1-11e7-9548-40a2fca19628.jpg)

**Comment by TooWaBoo** [comment] 2017-07-08 22:28
@chaotic-sys 

Thanks for testing. Since the Creators update of Win10 a lot of people get trouble with older graphic cards.
I guess the culprit of the different behavior on Win10 belongs to the new window handler, incompatible graphic card or GTK.

**Comment by gaaned92** [comment] 2017-07-09 06:18
@TooWaBoo 
Even before the Creators update of W10 I noticed these issues that were present since the beginning of use of gtk3. This behaviour did not change with the W10 update. Moreover, my HW is rather recent.
I can be wrong, but I think it is a kind of incompatibility of gtk3 and W10.

**Comment by TooWaBoo** [comment] 2017-07-09 06:25
> 3a. Situation: the taskbar sets to hide automatically and RT's window is maximized. I lower the cursor to the bottom edge of the screen. It is expected that the taskbar will pop up. But this does not happen : )

I've read over this point, I can confirm this issue too.

**Comment by JamesForBugReport** [comment] 2017-07-09 10:51
I am not running Creators update.
I'm with @gaaned92 it feels like a GTK3 issue to me, not hardware.

**Comment by Beep6581** [comment] 2017-07-09 13:48
Can you get your hands on some other GTK3-using program and compare?

**Comment by gaaned92** [comment] 2017-07-09 14:13
@Beep6581 smart idea
There is a gtk3-demo in the MSYS2 system.
The gtk3-window has the same behaviours  as RT on W10.

**Comment by ghost** [comment] 2017-07-09 14:14
Synfig Studio: all the same issues : )
![capture-1](https://user-images.githubusercontent.com/29912986/27994616-0afe5188-64ca-11e7-9ab2-96957719f7a2.jpg)

**Comment by ghost** [comment] 2017-10-13 20:39
With new native windows (https://github.com/Beep6581/RawTherapee/issues/4141) everything works perfectly!
(Except for the second point - when dragging,  other thumbnails still does not appear. But this is a trifle.)

I think that the issue can be closed.

**Comment by Beep6581** [comment] 2017-10-15 18:22
Duplicate of #4141

**Closed as completed by Beep6581** 2017-10-15 18:22 UTC
