### ISSUE TITLE
Histogram missing from second tone curve

### ISSUE THREAD

**Issue by afontenot** [Beep6581/RawTherapee#5720] opened 2020-04-22 05:58 UTC
**Description**

The second tone curve doesn't show a histogram, even though the first one does:

![second_tone_curve_no_histogram](https://user-images.githubusercontent.com/3870410/79946242-67008d80-8424-11ea-9e59-664b72e272f0.png)

Also, I find it strange that the L\*a*\b* adjustments don't show a histogram unless they're enabled. Edit: actually, a\*, b\*, LC, and CL all appear not to have histograms, even with the adjustment tool enabled.

**Replication**

Open RawTherapee. Open any RAW image (I tested both DNG and CR2). Check for histograms on the second tone curve.

**Version Info**

Arch Linux 5.6.4-arch1-1

RawTherapee 5.8-1

**Additional information**

I've included a full screenshot of my RawTherapee window showing the issue with tone curve 1 vs tone curve 2: https://drive.google.com/open?id=1MqJZaABFZ_sUczx7clnbq1e5Zbwlgsx3

**Comment by Thanatomanic** [comment] 2020-05-09 15:32
> Also, I find it strange that the L*a*\b* adjustments don't show a histogram unless they're enabled. Edit: actually, a*, b*, LC, and CL all appear not to have histograms, even with the adjustment tool enabled.

I believe this is due to performances issues. Recalculating the histogram when you don't need it, can slow down the application.

**Comment by Beep6581** [comment] 2020-05-11 11:34
Duplicate of #3018

**Closed as completed by Beep6581** 2020-05-11 11:34 UTC
Labels: scope: GUI
