### ISSUE TITLE
no redraw in curves widgets in gtk3 branch

### ISSUE THREAD

**Issue by vivo75** [Beep6581/RawTherapee#3447] opened 2016-10-05 23:19 UTC
Hi, somewhere between these two commits curves stopped being redrawn, so basically every change to any curve leave a phantom which make things unusable.

6ba96a10e97aee695d2a4b272a14c8a84cb71476 working
d16d244fc572615248a8c0f741f434213f4cd548 curves problem

**Comment by heckflosse** [comment] 2016-10-06 00:05
@vivo75 Thanks for the report. 6ba96a1 is master branch and d16d244 is gtk3 branch.

**Comment by heckflosse** [comment] 2016-10-06 00:27
@vivo75 [How to write useful bug reports](http://50.87.144.65/~rt/w/index.php?title=How_to_write_useful_bug_reports)

**Comment by vivo75** [comment] 2016-10-06 00:56
my bad, I'm using a gentoo ebuild that  is using the gtk3 branch (EGIT_BRANCH="gtk3") but overriding EGIT_COMMIT override the branch, indeed.

So I can only say that the last good build was Sat Sep 24 00:02:09

rawtherapee: Sat Sep 24 00:02:09 2016: 254 seconds
rawtherapee: Tue Oct  4 21:41:09 2016: 259 seconds
rawtherapee: Wed Oct  5 23:02:11 2016: 258 seconds
rawtherapee: Thu Oct  6 00:19:55 2016: 257 seconds
rawtherapee: Thu Oct  6 00:37:52 2016: 247 seconds
rawtherapee: Thu Oct  6 00:47:12 2016: 242 seconds

**Comment by Beep6581** [comment] 2016-10-06 07:13
@vivo75 what you're describing sounds like you have no RT theme loaded in Prefereces. And "Sat Sep 24 00:02:09" is a date in an unknown timezone, not a version, i.e. useless and unreliable. Please see heckflosse's link on writing a good bug report and supply:
- screenshots
- link to the ebuild
- AboutThisBuild
etc

**Comment by heckflosse** [comment] 2016-10-06 10:40
@vivo75 please have a look [here](https://discuss.pixls.us/t/anyone-else-having-issues-with-curves-and-histogram-in-rt-4-2-896/1128)

**Comment by vivo75** [comment] 2016-10-06 19:09
@Beep6581 yeah, next time I'll write a better bug report, possibly not starting it a 4AM

Recap: it's a problem of gtk{+,mm} version >= 3.20 broke badly as described in by this forum post
[anyone-else-having-issues-with-curves-and-histogram](https://discuss.pixls.us/t/anyone-else-having-issues-with-curves-and-histogram-in-rt-4-2-896/1128/19) (thanks Ingo)

ebuild is here, I've added a dependancy on versions of gtk prior to 3.20:
[rawtherapee-9999-r1.ebuild](https://github.com/vivo75/vivovl/blob/master/media-gfx/rawtherapee/rawtherapee-9999-r1.ebuild)

RT report this as versions, notice that even if RT was built against gtkmm 3.20.1 just downgrading to version 3.18.1 (no rebuild of RT) make things work as usual.

Branch: gtk3
Version: 4.2.1234
Changeset: d16d244fc572615248a8c0f741f434213f4cd548
Compiler: x86_64-pc-linux-gnu-gcc 5.4.0
Processor: Intel(R)\ Core(TM)\ i7\ CPU\ X\ 980\ @\ 3.33GHz
System: Linux
Bit depth: 64 bits
Gtkmm: V3.20.1
Build type: Gentoo
Build flags: -O2 -ggdb3 -march=corei7 -pipe  -std=gnu++11  -Werror=unused-label -fopenmp -Werror=unknown-pragmas
Link flags:  -Wl,-O1 -Wl,--as-needed
OpenMP support: ON
MMAP support: ON

screenshot of the problem:
![screenshot_20161006_023147](https://cloud.githubusercontent.com/assets/60593/19166673/c1fb3bc6-8c08-11e6-9664-3bbedc677e27.png)

**Comment by Beep6581** [comment] 2016-10-07 12:19
RawTherapee does not yet support >=gtk+-3.20.0
Duplicate of https://github.com/Beep6581/RawTherapee/issues/3446

**Closed by Beep6581** 2016-10-07 12:19 UTC
Labels: missing info

**Comment by Hombre57** [comment] 2016-10-16 23:37
gtk3.20 still not supported, but this particular issue has been fixed in the gtk3-bugfix branch. Please test if still compatible with previous version of Gtk3 please.

**Comment by vivo75** [comment] 2016-10-17 17:10
@Hombre57 yes the "gtk3-bugfix" branch does work, there are still visual differences as it's visible in the two screenshot below, but RT is useable.

OT I've a personal opinion on libraries that require this kind of changes after a "minor" upgrade but I'll keep that for myself.

![gtk-3-18_20161017_182153](https://cloud.githubusercontent.com/assets/60593/19447103/4999d434-949c-11e6-85c0-3b8a9f5c4d84.png)
![gtk-3-20_20161017_185626](https://cloud.githubusercontent.com/assets/60593/19447102/498b8c12-949c-11e6-91ef-d7677c158fa1.png)

**Comment by Hombre57** [comment] 2016-10-17 19:58
> OT I've a personal opinion on libraries that require this kind of changes after a "minor" upgrade but I'll keep that for myself.

I think we have the same opinion.

On the second screenshot, the theme is not loaded at all.

**Comment by vivo75** [comment] 2016-10-17 21:43
maybe it's not loaded because of these warning/errors shown at startup?
```
vivo@Monfi ~/Pictures/20161015-empty_inside $ rawtherapee  raw/ & 
[1] 17619
vivo@Monfi ~/Pictures/20161015-empty_inside $ RawTherapee, version 4.2.1317

(rawtherapee:17619): Gtk-WARNING **: Theme parsing error: RawTherapee.css:112:44: The style property GtkProgressBar:min-vertical-bar-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(rawtherapee:17619): Gtk-WARNING **: Theme parsing error: RawTherapee.css:113:47: The style property GtkProgressBar:min-horizontal-bar-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(rawtherapee:17619): Gtk-WARNING **: Theme parsing error: RawTherapee.css:175:20: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(rawtherapee:17619): Gtk-WARNING **: Theme parsing error: RawTherapee.css:175:47: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(rawtherapee:17619): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee:17619): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee:17619): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee:17619): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee:17619): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee:17619): Gtk-CRITICAL **: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(rawtherapee:17619): Gtk-WARNING **: Allocating size to gtkmm__GtkVScrollbar 0x4a587b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(rawtherapee:17619): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -117878697 and height 532

(rawtherapee:17619): Gtk-WARNING **: Allocating size to gtkmm__GtkHBox 0x4a9d270 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by Hombre57** [comment] 2016-10-17 21:55
@vivo75 Gtk3.20 and beyond are now officially not suitable for RT (since 5mn ago). We'll see at next iteration of the Gtk version, and pray that it's still a usable SDK.

**Comment by vivo75** [comment] 2016-10-17 22:21
yes, yes I know, I'll take a look too if you are ok with that, let's start with the easy stuff.
RawTherapee.css would benefit from this simple patch, not tested, since the theme is not loaded but css warnings at startup disappear.
```
diff -u a/RawTherapee.css b/RawTherapee.css
--- a/RawTherapee.css   2016-10-17 23:51:00.085016555 +0200
+++ b/RawTherapee.css   2016-10-18 00:13:54.980478518 +0200
@@ -109,8 +109,12 @@
 }
 
 GtkProgressBar {
+    min-width: 10;
+    min-height: 10;
+    /* TODO: check if min-{width,height} work in gtk-3.18
     -GtkProgressBar-min-vertical-bar-width: 10;
     -GtkProgressBar-min-horizontal-bar-height: 10;
+    */
 }
 
 GtkDrawingArea {
@@ -172,7 +176,7 @@
     background-color: #262626;
 }
 
-GtkEntry:insensitive, GtkSpinButton:insensitive {
+GtkEntry:disabled, GtkSpinButton:disabled {
     background-color: #363636;
 }
```

**Comment by Hombre57** [comment] 2016-10-17 22:28
See here for my own patch that you can take your hand over if you want :
https://gist.github.com/Hombre57/fd3879890662744fd38e7b11cc87faef

**Comment by vivo75** [comment] 2016-10-17 22:30
thank you

**Comment by Hombre57** [comment] 2016-10-17 22:35
Forgot to say : the font is forced to 8pt in this patch. The thing is that you can't use what the FontSelector send you as is anymore, i.e. something like `sans 8`. We create a custom CSS code on the fly to update the font, and with Gtk3.20 and above, you have to set this in a syntaxically correct CSS string, i.e. using `font-family`, `font-size` (with a supported unit), `font-style`. The problem is that to convert from the Pango style to the CSS style, I create a `Pango::FontDescription` with `sans 8` in our example, and ask this object to give me the font family (works nice) and the font size (doesn't work !). So the font size is forced to 8pt as of now.
