### ISSUE TITLE
Profile Load/Save Dialog switches into background when a Tooltip pops up - GTK+ 3

### ISSUE THREAD

**Issue by TooWaBoo** [Beep6581/RawTherapee#3099] opened 2016-01-16 13:02 UTC
I think this belongs to issue #3075.

1. Click on "Save Profile"
2. Don't move the mouse and wait until a Tooltip appears.
-> Save Dialog switches into the background

Win 10, RT 4.2.670

**Comment by sguyader** [comment] 2016-01-16 14:43
I can reproduce it (RT 4.2.670, Windows 7). If I don't move the mouse, no tool tip appears, but if I move the mouse and put the cursor again on top of the button, indeed when the tooltip appears the Wave profile window switches to the backgraound. It does the same thing with "Load profile".

**Comment by Beep6581** [comment] 2016-01-16 19:51
Cannot reproduce in Awesome.

**Comment by adamreichold** [comment] 2016-02-06 13:44
Closing a duplicate of #3132.

**Closed by adamreichold** 2016-02-06 13:44 UTC
