### ISSUE TITLE
Add the "Scale" function

### ISSUE THREAD

**Issue by romandocent** [Beep6581/RawTherapee#3460] opened 2016-10-15 22:43 UTC
I would like to see the "scale" function for the crop and/or perspective correction. 
It's very helpful when you have a deal with architecture. But as RT cuts pictures, the third-party software is necessary for such corrections ((.
See the examples on screenshots. Is it possible to add this simple but very useful tool?

![screenshot from 2016-10-15 00-35-34](https://cloud.githubusercontent.com/assets/19542067/19413800/42b1d114-9341-11e6-87df-2c51a95a38c9.png)
![screenshot from 2016-10-15 07-32-58](https://cloud.githubusercontent.com/assets/19542067/19413801/42b5461e-9341-11e6-9cc6-111eeee6010b.png)

**Comment by Beep6581** [comment] 2016-10-16 17:01
Duplicate of #198

**Closed by Beep6581** 2016-10-16 17:01 UTC
Labels: enhancement
