### ISSUE TITLE
Support for automatic underwater color-correction

### ISSUE THREAD

**Issue by SamuelBenard** [Beep6581/RawTherapee#4557] opened 2018-05-15 11:37 UTC
I'm a diving instructor. I take lots of underwater photos. I have a paralenz camera (http://paralenz.com/) which does automatic color correction according to the depth. That's working quite good. I also found an android/iphone app : dive+ (https://play.google.com/store/apps/details?id=com.lifeplus.diveplus&hl=en_US). As a Linux user for years, I would love to see open source solutions. I can provide photos with depth informations.

**Comment by Beep6581** [comment] 2018-05-15 12:00
How to convert Paralenz raw files to DNG:
https://support.paralenz.com/hc/en-us/articles/115005795465-Converting-RAW-images-to-DNG

What remains is updating camconst.json for these DNG files.

@chagam upload some sample photos using https://filebin.net/

**Comment by Beep6581** [comment] 2018-05-15 12:02
Duplicate of #4266

**Closed as completed by Beep6581** 2018-05-15 12:02 UTC
Labels: type: enhancement

**Comment by SamuelBenard** [comment] 2018-05-15 12:05
@Beep6581 I'm sorry but it's not a duplicate. I was talking about having the same kind for color correction in rawtherapee as the one paralenz does. Have a look at the dive+ app. If you take underwater photos without filter, dive+ can do post correction. I mentioned paralenz just for information.

**Comment by Beep6581** [comment] 2018-05-15 12:16
@chagam ah, then I misunderstood the intent of the issue. Is there a standard for this color correction based on depth, and if so, do you have a link to the specification?

**Comment by SamuelBenard** [comment] 2018-05-15 12:21
Honestly, I have no idea. The thins I know is red color start disappearing below 8m and a dehaze filter would probably help. When we go diving, photographers either add a red filter in front of their camera or use extra lights. I can show you a before/after photo with dive+ so you can see the result. I'll try to search for specifications but i'm not sure they exist.

**Comment by Beep6581** [comment] 2018-05-15 12:25
@chagam please upload some sample photos, as the one we already have is very poor quality. Preferably a well-lit photo with things of various color.

**Comment by SamuelBenard** [comment] 2018-05-15 12:31
I found this : http://digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1010&context=grcsp
I think 4 filters should be used. 
1st: an average color of the photo to determine if the predominant color if more greenish or blueish 
2nd: dehaze of the average color
3rd: missing color filter to add them (usually add red)
4th: white balance correction.
As i'm not an engineer no a photographer, this are just subjections. I'll try to take some pictures this week with a camera. I only have olympus TG4 (does raw) or AW130 (no raw). Which one do you prefer ? I'll take pictures of a slate I use for courses. I'll use no extralight as more light you use, less color correction you need :)

**Comment by Beep6581** [comment] 2018-05-15 12:45
@chagam a few good quality sample photos from the Paralenz Dive Camera please.

**Comment by SamuelBenard** [comment] 2018-05-15 12:48
Ok, I'll check if i can disable the automatic color correction

**Comment by Beep6581** [comment] 2018-05-15 12:59
@chagam I doubt the automatic color correction affects the raw file. If it can be disabled, take a photo of the same view one with and one without automatic color correction.

Also please take a completely clipped (overexposed) photo, it can be taken above-water, for example point the camera at the bright sky or a lamp and quickly take a photo before it adjusts, so that everything is completely white.

**Comment by SamuelBenard** [comment] 2019-11-14 14:40
Hi,
Sorry I couldn't provide pictures as I didn't go back in the water since for various reasons. But today, I found that http://openaccess.thecvf.com/content_CVPR_2019/papers/Akkaynak_Sea-Thru_A_Method_for_Removing_Water_From_Underwater_Images_CVPR_2019_paper.pdf

Someone did better than I could ever do
