### ISSUE TITLE
Sharp mask creates artifacts

### ISSUE THREAD

**Issue by vilmantasr** [Beep6581/RawTherapee#3729] opened 2017-03-05 16:52 UTC
Sharp mask creates artifacts. Camera Pentax K-5II, RawTherapee version: 5.0-r1-gtk3-82-ga42f5f4 (compiled from git, Windows 10 64bit.)

Sharp mask on
![2017-03-05 18_41_55-rawtherapee 5 0-r1-gtk3-82-ga42f5f4 - c__users_vilma_pictures_2017_2017-03-04_im](https://cloud.githubusercontent.com/assets/8343756/23589327/954fe3ba-01d3-11e7-9783-a9c690afb6df.png)

Sharp mask off
![2017-03-05 18_42_21-rawtherapee 5 0-r1-gtk3-82-ga42f5f4 - c__users_vilma_pictures_2017_2017-03-04_im](https://cloud.githubusercontent.com/assets/8343756/23589332/b60f26a6-01d3-11e7-905b-fd3d1f3bc83d.png)

DNG and PPT: https://drive.google.com/file/d/0Bz2Ge9UibPI4VWZnUFJfTExwSVE/view?usp=sharing

**Comment by Beep6581** [comment] 2017-03-05 17:43
Duplicate of #837

**Closed as completed by Beep6581** 2017-03-05 17:43 UTC
