### ISSUE TITLE
Freezes while browsing/viewing .NEF files

### ISSUE THREAD

**Issue by ghost** [Beep6581/RawTherapee#3881] opened 2017-05-18 23:55 UTC
```Version: 5.1
Branch: 5.1
Commit: f23d70f
Commit date: 2017-05-15
Compiler: gcc 5.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.18.0
Build type: release
Build flags: -mwin32 -m64 -mthreads -msse2 -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -Wno-aggressive-loop-optimizations -DNDEBUG -O3
Link flags: -m64 -mthreads -static-libgcc -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

While browsing images in a folder with 300 RAW files (.NEF), the application freezes with no error messages. It won't crash and exit by itself. Literally everything freezes and the GUI won't process any further clicking. Need to open Task Manager and kill the executable in order to exit the application.

I am running Windows 7 64-bit.

Thank you for the help.

**Comment by heckflosse** [comment] 2017-05-19 11:43
I tried to reproduce in a folder with 512 .NEF. Works fine here (Win7/64).

**Comment by agriggio** [comment] 2017-05-19 12:00
hi @bisherbas, what happens if you try only with a subset of the pictures?

**Comment by ghost** [comment] 2017-05-19 12:49
@heckflosse Files stored on SSD or HD? Mine is HD.

**Comment by ghost** [comment] 2017-05-19 12:50
@agriggio I copied 100 something files into another folder and the application worked fine. Never crashed.

I noticed that if everything works properly the application uses about 800MB memory. Whenever the application freezes, Task Manager always shows ~2,000MB memory for RawTherapee. I am not sure if this is relevant but I thought it might help troubleshoot the issue.

**Comment by heckflosse** [comment] 2017-05-19 13:11
@bisherbas Files are stored on HD (RAID-0 of three HDs)

**Comment by heckflosse** [comment] 2017-05-19 13:14
@bisherbas Can you try with the win64 build from [here](https://discuss.pixls.us/t/rawtherapee-5-1-released/4201/6)? It uses a newer gtk+ version. Just to exclude gtk3.18 causing the freeze

**Comment by ghost** [comment] 2017-05-19 20:47
@heckflosse Issue persists. What other information I can provide to better troubleshoot it?

```Version: 5.1-13-gedc6fa91
Branch: dev
Commit: edc6fa91
Commit date: 2017-05-15
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads  -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -DNDEBUG -msse2 -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

**Comment by heckflosse** [comment] 2017-05-19 21:00
@bisherbas Let's clarify what you mean by `browsing images in a folder with 300 RAW files`.

Is that?

1. Opening a folder with 300 files the first time ?
2. Opening files in a folder with 300 files where the thumbs of that folder are already built?
3. anything else?

Please provide as much details as possible to allow us to reproduce.

Ingo

**Comment by ghost** [comment] 2017-05-19 21:11
@heckflosse 2.

I should indicate that the issue presents itself less frequently on the latest nightly I installed. Significant improvement.

**Comment by Beep6581** [comment] 2017-05-20 14:18
@bisherbas which is the latest nightly you installed? Has anything else on your system changed in the meanwhile? Do these freezes happen if your web browser is closed while running RT?

**Comment by ghost** [comment] 2017-05-20 16:50
@Beep6581 

```Version: 5.1-13-gedc6fa91
Branch: dev
Commit: edc6fa91
Commit date: 2017-05-15
Compiler: gcc 6.3.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -m64 -mwin32 -mthreads  -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=c++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -mwindows -DNDEBUG -msse2 -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON
```

File name: RawTherapee_5.1_WinVista_64.zip

Nothing changed in between the installed. Freeze happens regardless of the browser (Chrome) or any other programs.

**Comment by Beep6581** [comment] 2017-05-20 16:53
@bisherbas there is no relevant difference between `edc6fa91` and the 5.1 release. But you are using a GTK+ 3.22 build, while the 5.1 on our website uses 3.18.

**Comment by ghost** [comment] 2017-05-20 16:54
@Beep6581 OP was about f23d70f. As I indicated edc6fa91's performance is much better. GTK is different per @heckflosse. I think I am all set now. edc6fa91 is workable. Thank you for your time.

**Comment by Beep6581** [comment] 2017-05-20 16:57
`f23d70f` is 5.1, `edc6fa91` is identical to `f23d70f` except for a splash screen and RELEASE_NOTES change. GTK+ seems to be the main difference.

> performance is much better

Performance or stability?

**Comment by ghost** [comment] 2017-05-20 16:57
@Beep6581 stability :) thanks for the correction. Not sure why but the newer GTK appears to have resolved my problem.

**Comment by Beep6581** [comment] 2017-05-20 17:08
Then we should update the build on our website too.

I'll let @heckflosse and the rest decide whether to close this issue.

**Comment by heckflosse** [comment] 2017-05-20 17:50
I think we can close the issue soon. I will update my windows builds system now also (have been on gtk 3.18 all the time).

Ingo

**Comment by Beep6581** [comment] 2017-05-22 14:48
Build updated.

**Closed as completed** 2017-06-05 20:24 UTC
