### ISSUE TITLE
Strange behaviour from RAW CA correction

### ISSUE THREAD

**Issue by edco** [Beep6581/RawTherapee#3224] opened 2016-03-17 11:45 UTC
When RAW CA correction is enabled, it creates this strange pattern, with substantial changes in brightness. I've ramped up the contrast and isolated the red channel in the attached images to highlight the issue, but it is visible when I process the image normally, and affects all channels. For the examples I used auto correction - manual correction has similar issues, but the artefacts appear in a regular square grid.

Camera is a Sony a7R. Original RAW file is 37MB, but I'm happy to attach it if necessary.

RawTherapee 4.2.753 running on OS X 10.11.3.

![dsc02303-no-ca](https://cloud.githubusercontent.com/assets/5522594/13844747/c75c40ec-ec8f-11e5-9d19-987b0d6ba5ad.jpg)

![dsc02303-ca](https://cloud.githubusercontent.com/assets/5522594/13844748/c761d638-ec8f-11e5-9fdb-29103ed35f92.jpg)

[pp3.zip](https://github.com/Beep6581/RawTherapee/files/177742/pp3.zip)

**Comment by heckflosse** [comment] 2016-03-17 13:16
@edco Please upload the raw file to filebin.net and post the link here

**Comment by edco** [comment] 2016-03-17 22:36
Here's the RAW: http://filebin.net/l6el5jkd6i

**Comment by heckflosse** [comment] 2016-03-17 22:47
@edco I can reproduce the issue with your raw and pp3. Looking...

**Comment by heckflosse** [comment] 2016-03-17 23:13
Hmm, raw ca correction basically works by shifting the red and blue values of bayer array a bit. Maybe it doesn't work well on images without CA shot with noisy high iso?

**Comment by edco** [comment] 2016-03-18 03:21
No interpolation in raw CA correction? Even so, it seems a really dramatic shift in intensity for an offset of a couple of pixels.

I was wondering if it could be something specific to Sony's lossy raw format, though I have no understanding of RawTherapee's processing pipeline to back that up with.

**Comment by heckflosse** [comment] 2016-03-18 13:20
Of course interpolation too. Still looking...

**Comment by heckflosse** [comment] 2016-03-18 19:43
@edco I think I found a solution for this issue. But I have to test a bit before I post a patch.

Ingo

**Comment by heckflosse** [comment] 2016-03-19 17:24
I created branch [cacorrectfix](https://github.com/Beep6581/RawTherapee/commits/cacorrectfix) with a fix for this Issue. Further tests are needed...

**Comment by heckflosse** [comment] 2016-04-10 18:46
I'll close this Issue **without** pushing the changes to master in about one week due to lack of interest

**Comment by edco** [comment] 2016-04-10 22:49
Lack of interest? Is there something you need me to do?

**Comment by heckflosse** [comment] 2016-04-10 23:41
@edco If you can compile rt I would like like you to test the https://github.com/Beep6581/RawTherapee/commits/cacorrectfix branch.

**Comment by edco** [comment] 2016-04-11 23:43
Okay. It's been a while since I set up a build environment for something like RawTherapee, but I should be able to get something going in the next day or two.

**Comment by Beep6581** [comment] 2016-04-22 19:58
Tested, agree with committing a new default value of 2.0, as discussed in IRC.

**Comment by heckflosse** [comment] 2016-04-22 21:17
@Beep6581 the new default value of 2.0 doesn't solve this 'bug'. The default value of 2.0 is 'good' for the cases where there's some ca to remove, which is not the case with this high ISO shot, because it doesn't suffer from ca at all. Nevertheless I would appreciate to get some tests of 'cacorrectfix' branch :)

**Closed** 2018-11-23 21:49 UTC
